### ISSUE TITLE
Feature Suggestion: Exception logging with Rails backtrace cleaner

### ISSUE THREAD

**Issue by carlosantoniodasilva** [sidekiq/sidekiq#5589]
We have been running a small extension in our app that swaps the previous [Sidekiq::ExceptionHandler::Logger](https://github.com/mperham/sidekiq/blob/fc7b7d8532549553673d4e510894b10a063792b3/lib/sidekiq/exception_handler.rb#L7) with our own, so that we can apply the [Rails backtrace cleaner](https://api.rubyonrails.org/classes/ActiveSupport/BacktraceCleaner.html) to it and only log app specific lines.

This changed with Sidekiq v6.5.0 where [the default error handler was moved to a method in Sidekiq](https://github.com/mperham/sidekiq/commit/67daa7a408b214d593100f782271ed108686c147#diff-2eecd3565b38823c09513903afa6686627d3ba8d883d520d3a83db61375e5ddeR63-R68), as part of the preparation for changes to Sidekiq 7. We can still wrap that method and apply the cleaner on our side, but I wanted to reach out and ask if this is maybe something that'd be interesting to have implemented in Sidekiq directly?

My thinking is that Sidekiq could provide some sort of hook / config for backtrace cleaning (e.g. `config[:backtrace_cleaner]`, a proc that receives the backtrace), that could be applied to this exception logging, and perhaps also to the backtraces stored within the jobs (similar to https://github.com/mperham/sidekiq/issues/4451) if that'd be interesting too, and that within the [Rails context](https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/rails.rb#L7) it could be set to the default `Rails.backtrace_cleaner` cleaner.

Would that be something of interest to have in Sidekiq itself? And I imagine this is something that'd be included only in the upcoming v7?

I'm happy to get a draft going, just wanted to start with some questions to gather initial interested and direction.

Thanks,
Carlos

**Comment by mperham** [comment]
I'd love something which gracefully integrates Rails's backtrace cleaner. You can target just main/7.0 or you can additionally backport to the 6-x branch and I'll get it into 6.5.8 coming soon.

**Comment by mperham** [comment]
Yeah, stick to main. I'm considering 6.x closed to new features.

**Comment by fatkodima** [comment]
@carlosantoniodasilva Had you started working on this feature? I can help with it or implement it.

**Comment by carlosantoniodasilva** [comment]
@fatkodima sorry about the delay getting back to you here, this was a bit of a weird week.

I actually had started but hit some weird test issue at the time, and didn't circle back on it for a number of reasons, my bad. I was about to start looking into it again, got that test fixed, but I see you've implemented it already, that's awesome, thank you!
