### ISSUE TITLE
Feature Request: More predictable behavior with empty batches

### ISSUE THREAD

**Issue by sobrinho** [sidekiq/sidekiq#5678]
Ruby version: 2.7.6
Rails version: 6.0.3.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.5.8 / Pro 5.5.5 / Ent 2.5.3

Hi there!

The [documentation](https://github.com/mperham/sidekiq/wiki/Batches) says:
> A Batch with zero jobs is invalid, its behavior is undefined. Every batch must contain a job.

This scenario is detectable and Sidekiq could be smart about it (not sure about rabbit holes, let me know if I'm not seeing something here).

A contrived example:

```ruby
Step1.perform_async(SecureRandom.uuid)

class Step1
  include Sidekiq::Job

  def perform(uuid)
    batch = Sidekiq::Batch.new
    batch.on(:success, self.class, { "uuid" => uuid })
    batch.jobs do
      MyModel.in_batches(of: 1000) do |relation|
        args = relation.pluck(:id).zip
        Sidekiq::Client.push_bulk("class" => OtherJob, "args" => args)
      end
    end
  end

  def on_success(status, options)
    Step2.perform_async(options.fetch("uuid"))
  end
end

class Step2
  include Sidekiq::Job

  def perform(uuid)
    batch = Sidekiq::Batch.new
    batch.on(:success, self.class, { "uuid" => uuid })
    batch.jobs do
      AnotherModel.active.in_batches(of: 1000) do |relation|
        args = relation.pluck(:id).zip
        Sidekiq::Client.push_bulk("class" => AnotherJob, "args" => args)
      end
    end
  end

  def on_success(status, options)
    Step3.perform_async(options.fetch("uuid"))
  end
end
```

Issues:

1. When `MyModel` doesn't have records, `Step1#on_success` is not triggered.
2. When `AnotherModel` doesn't have records, `Step2#on_success` is not triggered either.

One way to workaround is to check if there are jobs to be enqueued and short-circuit if not:

```ruby
Step1.perform_async(SecureRandom.uuid)

class Step1
  include Sidekiq::Job

  def perform(uuid)
    if MyModel.none?
      on_success(nil, { "uuid" => uuid })
      return
    end

    batch = Sidekiq::Batch.new
    batch.on(:success, self.class, { "uuid" => uuid })
    batch.jobs do
      MyModel.in_batches(of: 1000) do |relation|
        args = relation.pluck(:id).zip
        Sidekiq::Client.push_bulk("class" => OtherJob, "args" => args)
      end
    end
  end

  def on_success(status, options)
    Step2.perform_async(options.fetch("uuid"))
  end
end

class Step2
  include Sidekiq::Job

  def perform(uuid)
    if AnotherModel.active.none?
      on_success(nil, { "uuid" => uuid })
      return
    end

    batch = Sidekiq::Batch.new
    batch.on(:success, self.class, { "uuid" => uuid })
    batch.jobs do
      AnotherModel.active.in_batches(of: 1000) do |relation|
        args = relation.pluck(:id).zip
        Sidekiq::Client.push_bulk("class" => AnotherJob, "args" => args)
      end
    end
  end

  def on_success(status, options)
    Step3.perform_async(options.fetch("uuid"))
  end
end
```

Although: 

1. This spreads across the codebase
2. It is very easy to forget to check
3. In some places we have more than a model to inside a batch, increasing complexity

```ruby
  def perform(uuid)
   klasses = [ModelA, ModelB, ModelC]

    if klasses.all? { |klass| klass.none? }
      on_success(nil, { "uuid" => uuid })
      return
    end

    batch = Sidekiq::Batch.new
    batch.on(:success, self.class, { "uuid" => uuid })
    batch.jobs do
      klasses.each do |klass|
        klass.in_batches(of: 1000) do |relation|
          args = relation.pluck(:id).zip
          Sidekiq::Client.push_bulk("class" => AnotherJob, "args" => args)
        end
      end
    end
  end
```

Another approach is to have a dummy job:

```ruby
class MyJob
  include Sidekiq::Job

  def perform(uuid)
    klasses = [ModelA, ModelB, ModelC]

    batch = Sidekiq::Batch.new
    batch.on(:success, self.class, { "uuid" => uuid })
    batch.jobs do
      DummyJob.perform_async

      klasses.each do |klass|
        klass.in_batches(of: 1000) do |relation|
          args = relation.pluck(:id).zip
          Sidekiq::Client.push_bulk("class" => AnotherJob, "args" => args)
        end
      end
    end
  end
end

class DummyJob
  include Sidekiq::Job

  def perform_async
    # Intentionally no-op due to Sidekiq behavior on empty batches
  end
end
```

That way, callbacks are called regardless of having jobs or not.

_Be aware that short-circuit examples are contrived, `on_complete` suffers from the same issue and it would require more machinery to emulate it._

The idea here is to have an internal noop job on Sidekiq that could be enqueued to trigger callbacks when batch.jobs == 0.

How do you feel about this?

**Comment by mperham** [comment]
The idea of adding a `Sidekiq::Batch::EmptyJob` to an empty batch is a seemingly simple solution however this is a HUGE change to the batch semantics. If we make this change, I'm not clear if this needs to wait for Pro 8.0 or Pro 7.1.

**Comment by sobrinho** [comment]
Yeah, we can add a feature flag though where it is off by default on 7.1 and on by default on 8.0 (or even remove the feature flag entirely to enforce it).

**Comment by sobrinho** [comment]
If you get me access to the private repo, I can submit a PR there implementing it! :)

**Comment by mperham** [comment]
The implementation is relatively easy, I've already done it, but there are several broken tests. The test suite pretty extensively probes batch semantics to ensure no regressions so I've got to go through each failure.

**Comment by sobrinho** [comment]
Awesome, you are the best! ❤️

**Comment by Parad0X** [comment]
Very excited about this change 🙏

**Comment by mperham** [comment]
The plan is for this change to be part of Sidekiq Pro 7.1.

Right now the implementation creates a empty job if the jobs block finishes without adding any jobs. If you have inline job execution enabled in your test suite, any batch callbacks should fire immediately after an empty jobs block.

Because empty batch behavior has long been documented as undefined, I don't have a problem changing the behavior outside of a major release. Speak up if you feel differently.

**Comment by raybaxter** [comment]
+1 for creating an empty job in 7.1. It currently I'm putting in an empty job in multiple places in my code and it would be nice to clean that up.

**Comment by mperham** [comment]
Coming soon...
