### ISSUE TITLE
Tools for tracking deprecations more programmatically

### ISSUE THREAD

**Issue by technicalpickles** [sidekiq/sidekiq#5743]
Currently, there are a few different ways that deprecations have been communicated through logs and code comments. In a large and ~old~ mature enough application, it can be really easy to miss during development, CI, and production because they are often just log messages in a see of other log messages

We are still on Sidekiq 6.x, and I know there are some notable change we still need to tackle for 7.0, which will be risky if we can't be sure we've addressed the deprecations.

I think ideally, we'd like a way to be notified of deprecations, and handle it ourselves: either raise an error (like in dev and CI), or log a message (in production). This is basically what you can do with [ActiveSupport::Deprecation](https://api.rubyonrails.org/classes/ActiveSupport/Deprecation.html), which we've had a lot of success with during big upgrades.

I assume a dependency on `active_suppor` would be out of the question? 😅 

I could imagine a `deprecation_handler` similar to how `error_handlers` work currently for hooking into them.

## Deprecation examples

On main:

https://github.com/mperham/sidekiq/blob/9feefc2d3653fc4c187ca3e46155d2736f2f3c62/lib/sidekiq/client.rb#L47

On 6.x:

https://github.com/mperham/sidekiq/blob/ad0f13cac5138b891d54ef2f2df3460d5151e34c/lib/sidekiq.rb#L97

https://github.com/mperham/sidekiq/blob/ad0f13cac5138b891d54ef2f2df3460d5151e34c/lib/sidekiq.rb#L225

https://github.com/mperham/sidekiq/blob/ad0f13cac5138b891d54ef2f2df3460d5151e34c/lib/sidekiq/redis_connection.rb#L14

https://github.com/mperham/sidekiq/blob/ad0f13cac5138b891d54ef2f2df3460d5151e34c/lib/sidekiq/rails.rb#L51-L56

https://github.com/mperham/sidekiq/blob/ad0f13cac5138b891d54ef2f2df3460d5151e34c/lib/sidekiq/job_util.rb#L27-L31

There are also some in sidekiq-ent and sidekiq-pro that are similar.

**Comment by mperham** [comment]
Does Ruby have a solution for deprecations? Seems like this is a bigger API question for the community. I don't want a dependency on activesupport but if they are willing to extract the API into a separate gem which is intended to be a community-wide standard, I would consider that dependency.

**Comment by technicalpickles** [comment]
`ActiveSupport::Deprecation` is the best I've seen, and I've used that in libraries that already has it.

The next best thing would be [Kernel#warn](https://docs.ruby-lang.org/en/master/Kernel.html#method-i-warn) that is part of stdlib. It does have a `deprecated` option too. The downside would be that it seems to go to $stderr by default:

```
❯ ruby -e 'warn "aiii"'
aiii
❯ ruby -e 'warn "aiii"' >/dev/null
aiii
❯ ruby -e 'warn "aiii"' 2>/dev/null
```

That wouldn't show up logs unless an app is explicitly handling that somehow. It would work for our use case though, because we already process that.

---

Regardless of how, having a `deprecation_handler` gives users the flexibility to choose how they want to see things. If there is a community-standard, the default handler can use that. I started a draft for it over at https://github.com/mperham/sidekiq/pull/5745 if you want to check it out.

**Comment by technicalpickles** [comment]
Collecting feedback from the two drafts I started. I'll post a followup comment about next recommendations and next steps.

## https://github.com/sidekiq/sidekiq/pull/5745 Add Sidekiq::Config#handle_deprecation


> I'm not yet convinced. Any gem can have deprecations over time. I would rather see something which could work with any gem rather than something specific to Sidekiq.
> -- <cite>@mperham</cite>

---

> I think I addressed this in [#5743 (comment)](https://github.com/sidekiq/sidekiq/issues/5743#issuecomment-1402472062) .
> 
> `warn` is closest to the standard (adding `category: :deprecation`), with `ActiveSupport::Deprecation` following it. I don't think the ergonomics are great though, because it doesn't include things like caller information, leaving gems to implement it themself. I could make a gem for it, but that would lead to the [xkcd standards](https://xkcd.com/927/) problem.
> 
> My opinion is that just because there isn't a standard for gems to deprecate, it doesn't mean that sidekiq shouldn't try to make it easier to understand and fix deprecations in preparation for upgrades. Using an abstracted `deprecation_handler` enables adopting something better if/when it comes along.
> -- <cite>@technicalpickles</cite>

---

> 
I like what AS::Deprecation does in terms of documenting, in code, how the API should change so that log messages can be auto-generated with the calling site. Like you showed, we have 4-5 different usecases for deprecation. If we can build an API which supports those changes, I think we'll have something we can ship as Sidekiq::Deprecated in 7.1 and possibly extract it as a gem in 7.2. I have no problems borrowing liberally from AS::Deprecation's API to keep compatibility as much as possible and retain the MIT license.


## https://github.com/sidekiq/sidekiq/pull/5745 Introduce Sidekiq::Deprecation as a way to mark deprecations

> I don't like the notion of deprecations as a fancy logger. `S::D.warn` isn't valuable enough to continue down that path.
> 
> I like the notion of creating a Deprecation object for each change. There's a lot of functionality we can codify: explanations, timeframe, routing old style calls automatically to the new style API, usage metrics, etc.
> 
> ```ruby
> dep = ActiveSupport::Deprecation.new("7.0", "Sidekiq")
> dep.deprecate_methods(Sidekiq.singleton_class,
>         default_worker_options: :default_job_options,
>         "default_worker_options=": :default_job_options=)
> ```
> -- <cite>@mperham</cite>

---

> > I like the notion of creating a Deprecation object for each change. There's a lot of functionality we can codify: explanations, timeframe, routing old style calls automatically to the new style API, usage metrics, etc.
> 
> It is appealing, for sure. I'm not familiar enough with sidekiq to know what those usages are going to be in the existing code base.
> 
> Could import ActiveSupport::Deprecation whole sale and rename to Sidekiq::Deprecation? It still does offer a `Sidekiq::Deprecation.warn`, but there are more nuanced usages.
> 
> I'm not sure it's better to do that, or to directly use `ActiveSupport::Deprecation` through an active_support though, because there is a modest amount of complexity (I am still learning some of them as I put this together).
> -- <cite>@technicalpickles</cite>

---

> I'm sorry if "fancy logger" was disrespectful or unfair.
> 
> The issue is that I really don't want to pull in a dependency on activesupport. That's a lot of code which some teams don't want in their app. I'd prefer to work with other gem authors to standardize some community-led API rather than bless ActiveSupport.
> 
> In other words, I don't see how to get what you want without more interest from the community. Should we start our own gem project and see if other gem makers want to sign onto an de facto community API for deprecations? Maybe we could provide a "compatibility" mode which plugs into AS::Deprecated (e.g. remove "AS::" to get our shim).
> 
> https://github.com/contribsys/deprecatedrb
> 
> What do you think? Do you want to help flesh out this project and gem?
> -- <cite>@mperham</cite>

---

> > I don't see how to get what you want without more interest from the community
> 
> I think the original PR would be a middle ground. It doesn't do anything fancy, while providing an extension point with a default behavior out of the box. I could do a gem which hooks it up to ActiveSupport::Behavior.warn. It'd also be a chance to experiment with those more elaborate deprecation patterns it offers.
> 
> > Should we start our own gem project and see if other gem makers want to sign onto an de facto community API for deprecations? Maybe we could provide a "compatibility" mode which plugs into AS::Deprecated (e.g. remove "AS::" to get our shim).
> > https://github.com/contribsys/deprecatedrb
> > What do you think? Do you want to help flesh out this project and gem?
> 
> Sure 👍🏻
> 
> I was chatting with @shageman about this, and we found https://github.com/cbeer/deprecation . Hilariously, it depends on active-support 😮‍💨
> 
> This morning looking for other options, and found:
> 
> * [Gem::Deprecate](https://github.com/ruby/ruby/blob/master/lib/rubygems/deprecate.rb): rubygems' internal way of marking things deprecated. It is year based for some reason, rather than version. It's a module that can be extended, and can create method wrappers to mark something deprecated with a replacement
> * [ruby-deprecate_public: Warn when calling private methods via public interface](https://github.com/jeremyevans/ruby-deprecate_public) by @jeremyevans. More narrowly defined for making public methods private over time
> -- <cite>@technicalpickles</cite>

**Comment by technicalpickles** [comment]
To summarize all that... 😅 

I'm looking for a standard interface from Sidekiq about how deprecations are logged. Currently, it is done primarily through `Sidekiq.logger.warning`, but there isn't a consistent pattern to detect. My ideal would be to be able to have something simple like a proc/lambda where I can configuration what happens with it. The default could be to call `Sidekiq.logger.warning`.

ActiveSupport::Deprecation has some compelling uses, like defining methods that are deprecated, and the horizon for when they will be removed. Using it directly would be too big of a dependency to bring in though. There aren't any other libraries for deprecating out there, so one would need to be written.

I am a little concerned about starting a library just to do this. It feels like a big ask to design a community driven deprecation framework just to have the ability to do it in sidekiq 😬 

---

If I were to implement it, I would want to do it in a way to make the smallest set of changes possible, and I'd want to be able to integrate with Sidekiq sooner than later.

The simplest way I can imagine so far is as thus:

- revisit https://github.com/sidekiq/sidekiq/pull/5745 Add `Sidekiq::Config#handle_deprecation
- start work on deprecaterb, focus on the simpest use case of just warning that there is a deprecation with caller information
- package integrating it as `sidekiq-deprecaterb`, which can pull in the dependency, and define it's own `Sidekiq::Config#handle_deprecation`
- add a railtie for `deprecaterb` (or standalone gem?) to pass through to `ActiveSupport::Deprecation`
- iterate on deprecaterb to make APIs for code-as-documentation of methods being deprecated
- when/if it makes sense, sidekiq-deprecaterb can be folded into sidekiq proper (or not)

**Comment by mperham** [comment]
I agree with your synopsis. I'm not willing to develop a new API for this and there's no standard gem out there for deprecations except ActiveSupport, which I'm not willing to pull in at this time.

I don't see a way forward right now. I'm happy if someone wants to take over `contribsys/deprecatedrb`, it could make for a nice summer internship project for a CS student.

**Comment by technicalpickles** [comment]
> I don't see a way forward right now

That is to say, that iterative path of adding a deprecation hook, then integrating a gem to be written, doesn't work for you?

>  I'm happy if someone wants to take over contribsys/deprecatedrb

No offense, but if I'm doing most of the work to build something out, I'm more likely do it in a repo I manage and hopefully with a better name 😅

**Comment by mperham** [comment]
> That is to say, that iterative path of adding a deprecation hook, then integrating a gem to be written, doesn't work for you?

Sorry, I didn't want to assume you were going to do all the work so it wasn't clear who was going to do the work for those bullet points. Your plan looks good. For now, assume no shim gem ("sidekiq-deprecatedrb"). We'll include the shim directly in Sidekiq.

> No offense, but if I'm doing most of the work to build something out, I'm more likely do it in a repo I manage and hopefully with a better name 😅

Of course. You can start from scratch or I'm happy to turn over or move that repo to you and you can do with it as you wish. I wanted to reserve the name on rubygems ASAP but I'm not tied to the name.

**Comment by mperham** [comment]
Closing for now since I don't want this open for months without progress but any PRs are welcome.
