### ISSUE TITLE
The Sidekiq repository is MOVING

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#5772]
I just took possession of the @sidekiq organization on GitHub. I plan to transfer this repository to this organization on Monday, Feb 13th.

According to the [documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), all links should redirect for an indefinite period of time.

The new URL will be https://github.com/sidekiq/sidekiq. Questions or concerns?

**Comment by frederikspang** [comment]
How long does GH keep old redirects? I'm thinking, there may be some users using git sources in Gemfile? If so, they'll probably notice when it's not working, but I'm not sure if Bundler throws a warning at redirect?

Also - nice with the @sidekiq org 🎉

**Comment by hakusaro** [comment]
> How long does GH keep old redirects?

This is anecdotal, but as long as @mperham doesn't create a new repo called sidekiq, indefinitely. I have redirects that have been going strong for at least 7 years now.

**Comment by frederikspang** [comment]
> This is anecdotal, but as long as @mperham doesn't create a new repo called sidekiq, indefinitely. I have redirects that have been going strong for at least 7 years now.


All my worries have disappeared. Go for it!
