### ISSUE TITLE
Clear Duplicates across Queues

### ISSUE THREAD

**Issue by OskarEichler** [sidekiq/sidekiq#5776]
Hey guys, we are looking to clear duplicate jobs across queues, as it might so happen that different parts of our code base schedule the same job with the same arguments independently from each other. We looked at the gem [sidekiq-unique-jobs](https://github.com/mhenrixon/sidekiq-unique-jobs) but found that it can create a lot of overhead in Redis performance, and potential dead locks.

Instead we are now thinking to simply run a scheduled job every hour or so that runs through all of the queues and checks for duplicates and clears them out like so:

```
        queues = Sidekiq::Queue.all
        jobs = []
        queues.each do |queue| 
          jobs += queue.to_a
          puts "Fetched #{queue.name}"
        end
    
        job_groups = jobs.group_by{ |job| job.klass }
        puts "Grouped Jobs"
    
        job_groups.each do |klass, jobs|
          unique_jobs = jobs.uniq{ |job| job.args }
          duped_jobs = jobs - unique_jobs
          duped_jobs_count = duped_jobs.count
          duped_jobs.each(&:delete)
          puts "Cleared #{duped_jobs_count} #{klass}'s"
        end
    
        puts "Done"
```

Turns out this can take a while... does anyone know of a better way of doing this / a different solution to prevent dupes?

**Comment by mperham** [comment]
Enterprise has a Unique jobs feature.  https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs

**Comment by nateberkopec** [comment]
>does anyone know of a better way of doing this / a different solution to prevent dupes?

The best solution is for duplicates to not be a problem. If your jobs are idempotent, you don't care how many times they are executed.

**Comment by mperham** [comment]
There is no way to do this efficiently. Idempotency is the recommendation but the unique jobs feature is there for people who need it.
