### ISSUE TITLE
Queue is pilled up

### ISSUE THREAD

**Issue by sunil-edcast** [sidekiq/sidekiq#5777]
Hi 
Due to some buggy code, Queue is pilled up with 14 million jobs. There are duplicate jobs.
I want to delete duplicate jobs. I can not iterate over 14 million jobs.
is there any method/way to remove duplicate jobs from queue?. Any help will be appreciated.

Thanks in Advance.

**Comment by maxwang096** [comment]
@sunil-edcast, please see [#5776](https://github.com/mperham/sidekiq/issues/5776)

**Comment by nateberkopec** [comment]
Re: my comment of #5776, it may be easier to _change the job code_ to be idempotent rather than to try to fix the Redis state. So that fix is still possible in your case.
