### ISSUE TITLE
Breaking change in 7.0.4 and JSON validity checks

### ISSUE THREAD

**Issue by BobbyMcWho** [sidekiq/sidekiq#5784]
Ruby version: 3.0
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s): 7.0.4

After deploying 7.0.4, we noticed that one of our controllers started returning an ArgumentError when enqueuing a job that had a   string-keyed hash with a DateTime value parameter. I believe this is due to the changes in #5768 that only look at certain value classes. 

I wanted to report this as it is a breaking change in a patch version, though I understand that the best course of action is probably for us to to_s the value ourselves prior to passing it to the perform_async.

**Comment by mperham** [comment]
It sounds like your test code was depending on DateTime round tripping to/from JSON successfully. The new JSON check is faster but stringent; it doesn't allow you to rely on implementation-specific behavior. That DateTime value might not deserialize correctly with another language's JSON impl, for instance.

**Comment by 97jaz** [comment]
Oh, I just saw this after submitting a related one #5785

**Comment by ryanb** [comment]
I ran into this error as well. In my case I had `ActiveSupport::HashWithIndifferentAccess` in the arguments.

It would be nice if the error showed the class name and value that tripped the JSON safe check since it can be tricky to know what is allowed.

**Comment by mperham** [comment]
Cc @fatkodima 

yeah, it would be nice to show more context so debugging is quick and easy.

**Comment by fatkodima** [comment]
I apologize for the breaking change. 
@mperham So improving the raised error message with the details would be enough?

**Comment by mperham** [comment]
Yes. I don’t want to special case or whitelist specific classes as JSON safe, e.g. HWIA, but let’s make the error as useful as possible.

**Comment by mperham** [comment]
7.0.6 is now available with better error messaging.
