### ISSUE TITLE
Breaking change in Sidekiq 7.0.4 (`json_safe?`)

### ISSUE THREAD

**Issue by 97jaz** [sidekiq/sidekiq#5785]
Ruby version: 3.1.2
Rails version: 7.0.4.2
Sidekiq / Pro / Enterprise version(s): 7.0.4/7.0.6/7.0.3

The new (faster) safe json check, unlike the previous one, performs a strict check on the classes in the payload. There are a couple of cases where we have instances of `ActiveSupport::SafeBuffer`, which is a subclass of `String`, in the payload. (I'm looking at a case where we use `ActionView::Helpers::NumberHelper#number_with_delimter`, which returns a `SafeBuffer`.)

So we're now getting the error:
```
     ArgumentError:
       Job arguments to SlackNotificationWorker must be native JSON types, see https://github.com/sidekiq/sidekiq/wiki/Best-Practices.
       To disable this error, add `Sidekiq.strict_args!(false)` to your initializer.
```
... where we did not previously get it. I'm sure the strict equality check is faster than an ~`#instance_of`~ `#is_a?` check, but it is a breaking change.

**Comment by mockdeep** [comment]
We ran into the same issue when sanitizing an email body before sending it in a background job. `sanitize` returns an `ActiveSupport::SafeBuffer`, which is a subclass of string. We can workaround this by adding `.to_str` to the result, but `SafeBuffer` is safe to serialize as json, so kind of seems like it ought to be allowed.
