### ISSUE TITLE
Migrate away from deprecated Redis commands

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#5788]
Redis 6.2 introduces a lot of deprecations. These are the deprecated commands I can find which Sidekiq possibly uses.

- [x] RPOPLPUSH https://redis.io/commands/rpoplpush/
- [x] ZRANGEBYSCORE
- [x] ZREVRANGE
- [x] ZREVRANGEBYSCORE
- [x] GETSET
- [x] HMSET
- [x] SETEX
- [x] SETNX

Visit https://redis.io/commands.json and search for "deprecated_since".

**Comment by zerocool4u2** [comment]
The error you get with older versions of redis (6.0.9) is not intuitive at all

```log
RedisClient::CommandError: 
    ERR value is not an integer or out of range
```

In retrospective, after seen this was related to a redis version upgrade, I should looked up immediately for my server's version. 
Leaving these in here, since there aren't results on google linking this error and sidekiq

**Comment by vpanmand-mdsol** [comment]
> The error you get with older versions of redis (6.0.9) is not intuitive at all
> 
> ```
> RedisClient::CommandError: 
>     ERR value is not an integer or out of range
> ```
> 
> In retrospective, after seen this was related to a redis version upgrade, I should looked up immediately for my server's version. Leaving these in here, since there aren't results on google linking this error and sidekiq

Are able to figure out the resolution of this issue?

**Comment by zerocool4u2** [comment]
oh, sorry I should have been more explicit, the solution is upgrading to a version of redis greater than 6.2, but prior to that version(at least 6.0.9) you get that error `ERR value is not an integer or out of range` which is really cryptic

**Comment by d-wierdsma** [comment]
Hey @mperham !

Would it be possible to reflect the changes from this issue in the documentation?

I was just reading some docs of Super Fetch and it gave me a bit of confusion that it mentions [here](https://github.com/sidekiq/sidekiq/wiki/Reliability#using-super_fetch) that RPOPLPUSH is used, when based on my understanding of this issue it is no longer used as it is deprecated.

> Sidekiq Pro offers an alternative fetch strategy, super_fetch, for job processing using Redis' [RPOPLPUSH](http://redis.io/commands/rpoplpush) command which keeps jobs in Redis. 

If I've misunderstood in some way please let me know!

**Comment by mperham** [comment]
@d-wierdsma You've got to remember that the vast bulk of my customer base aren't running the latest. The wiki documentation needs to help both old and new versions as much as possible. It's not terribly interesting that RPOPLPUSH has been replaced, people can figure out that Sidekiq has migrated to use the newer LMOVE.

**Comment by d-wierdsma** [comment]
No worries! Thanks for the explanation :D
