### ISSUE TITLE
Unsafe JSON arguments appear to be rebroken in 7.0.5

### ISSUE THREAD

**Issue by geoffharcourt** [sidekiq/sidekiq#5789]
Ruby version: 3.2.1
Rails version: 7.0.4.2
Sidekiq / Pro / Enterprise version(s): 7.0.5 / 7.0.6 / 7.0.3

We are seeing jobs in CI fail in 7.0.5 that didn't fail in 7.0.3 (but did fail in 7.0.4) for flagged unsafe JSON arguments. Our job takes arguments like this:

```
perform_async(1, 2, {"description"=>"fun", "max_points"=>"50"})
```

Calling `Hash#stringify_keys` on the hash above produces an equivalent hash. In 7.0.4 we saw unexpected failures, but the 7.0.5 failure now says something new about `nil`:

```
ArgumentError:

Job arguments to GoogleClassroomWorkers::CreateLessonWorker must be native JSON types, but nil is a NilClass.
--
  | See https://github.com/sidekiq/sidekiq/wiki/Best-Practices.
  | To disable this error, add `Sidekiq.strict_args!(false)` to your initializer.
  | # /bundle/ruby/3.2.0/gems/sidekiq-7.0.5/lib/sidekiq/job_util.rb:33:in `verify_json'
  | # /bundle/ruby/3.2.0/gems/sidekiq-7.0.5/lib/sidekiq/client.rb:91:in `push'
  | # /bundle/ruby/3.2.0/gems/sidekiq-7.0.5/lib/sidekiq/job.rb:365:in `client_push'
  | # /bundle/ruby/3.2.0/gems/sidekiq-7.0.5/lib/sidekiq/job.rb:198:in `perform_async'
  | # /bundle/ruby/3.2.0/gems/sidekiq-7.0.5/lib/sidekiq/job.rb:290:in `perform_async'
  | # ./app/controllers/api/v1/google_classrooms/lessons_controller.rb:12:in `block in create'
```

The same failure in 7.0.4 looked liked this:

```
ArgumentError:
--
  | Job arguments to GoogleClassroomWorkers::CreateLessonWorker must be native JSON types, see https://github.com/sidekiq/sidekiq/wiki/Best-Practices.
  | To disable this error, add `Sidekiq.strict_args!(false)` to your initializer.
```

**Comment by mperham** [comment]
cc @fatkodima

**Comment by mperham** [comment]
Can you supply an actual snippet which triggers the behavior? I can't repro.

```
> HardJob.perform_async(1, 2, {"description"=>"fun", "max_points"=>"50"})
2023-02-15T21:48:06.442Z pid=34187 tid=utj INFO: Sidekiq 7.0.5 connecting to Redis with options {:size=>2, :pool_name=>"internal", :url=>nil}                                                     
=> "5726fe4b36d8c1ba1e381d47"
```

**Comment by fatkodima** [comment]
That is a problem with a HWIA. I reproduced, PR is almost ready.

**Comment by mperham** [comment]
Can you try main?

**Comment by geoffharcourt** [comment]
I'm now getting a warning about the hash being a `HashWithIndifferentAccess` and it's still failing. Going forward, should we be calling `to_hash`? (We're already calling `#to_h` on the params we receive.)

**Comment by mperham** [comment]
HWIA is not a legal JSON type so it must be converted. SafeBuffer is not a legal type so it must be converted.

I know it’s not ergonomic but I want the caller to trust that the args that go into perform_async are what they will get in perform. Otherwise your code can have subtle bugs.

**Comment by geoffharcourt** [comment]
@mperham that makes sense! Getting an exception here at least now makes this easy to find in tests.

**Comment by mperham** [comment]
7.0.6 is now out.
