### ISSUE TITLE
RESP2 support

### ISSUE THREAD

**Issue by timcraft** [sidekiq/sidekiq#5791]
Hi! Whilst upgrading to v7 I ran into the same problem as #5550. Redis Enterprise Cloud is redis 6.2 but doesn't support the HELLO command which causes redis-client to raise `RedisClient::UnsupportedServer` exceptions.

I added `protocol: 2` to my sidekiq config which seems to mostly be okay, but there are some errors. For example: the "Busy" tab in the web ui is broken because the hgetall command returns a hash using RESP3 but an array using RESP2, and Sidekiq::WorkSet#each calls #each_pair which works for hashes but not arrays. You can see the difference in the redis-client return values like this:

    $ irb -r redis-client
    irb(main):001:0> RedisClient.config(protocol: 2).new_client.call('HGETALL', 'FOO')
    => []
    irb(main):002:0> RedisClient.config(protocol: 3).new_client.call('HGETALL', 'FOO')
    => {}

Is the redis-client `protocol: 2` option officially supported here in sidekiq?

If so, is it the responsibility of sidekiq or redis-client to handle the differences between RESP2 and RESP3? For example should redis-client be returning hashes from hgetall commands using RESP2, or should Sidekiq::WorkSet#each be converting arrays to hashes before calling #each_pair?

***

Ruby version: 3.0.5
Rails version: 6.1.7.2
Sidekiq / Pro / Enterprise version(s): 7.0.5

Using the following initializer:

`Sidekiq.default_configuration.redis = {protocol: 2}`

**Comment by mperham** [comment]
My initial feeling is that APIs shouldn't change their return types. @byroot ?

Sidekiq 7 only supports RESP3 because redis-client was initially RESP3 only. If r-c can provide transparent RESP2 support then it's possible Sidekiq 7 can support both RESP2 and 3.

**Comment by byroot** [comment]
> APIs shouldn't change their return types.

Well, it's not so much that it changes the type, it's that RESP2 doesn't has many types as RESP3.

So in RESP2, a `{ "foo" => "bar" }` is serialized as `["foo", "bar"]` and the client has to know what command was called, and that a Hash is expected.

So no, Sidekiq 7 doesn't support RESP2, and it would be hard to do so, and the `redis-client` `protocol: 2` configuration was mostly added for the `redis-rb` gem.

**Comment by timcraft** [comment]
> So no, Sidekiq 7 doesn't support RESP2, and it would be hard to do so, and the `redis-client` `protocol: 2` configuration was mostly added for the `redis-rb` gem.

Makes sense, thanks for clarifying.
