### ISSUE TITLE
Sidekiq-Ent 7.0.4 requires Redis 7.0 feature

### ISSUE THREAD

**Issue by leifg** [sidekiq/sidekiq#5793]
Ruby version: 3.2.1
Rails version: 7.0.4.2
Sidekiq / Pro / Enterprise version(s): 7.0.5 / 7.0.7 / 7.0.4

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

With the recent upgrade to Sidekiq Enterprise 7.0.4 we are seeing errors when enqueuing unique jobs:

```
RedisClient::CommandError

/usr/local/bundle/gems/redis-client-0.12.1/lib/redis_client/connection_mixin.rb:22:in `call'
/usr/local/bundle/gems/redis-client-0.12.1/lib/redis_client.rb:210:in `block (2 levels) in call'
/usr/local/bundle/gems/redis-client-0.12.1/lib/redis_client/middlewares.rb:16:in `call'
/usr/local/bundle/gems/redis-client-0.12.1/lib/redis_client.rb:209:in `block in call'
/usr/local/bundle/gems/redis-client-0.12.1/lib/redis_client.rb:626:in `ensure_connected'
/usr/local/bundle/gems/redis-client-0.12.1/lib/redis_client.rb:208:in `call'
/usr/local/bundle/gems/sidekiq-7.0.5/lib/sidekiq/redis_client_adapter.rb:27:in `method_missing'
/usr/local/bundle/gems/sidekiq-ent-7.0.4/lib/sidekiq-ent/unique.rb:141:in `block in call'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/usr/local/bundle/gems/sidekiq-ent-7.0.4/lib/sidekiq-ent/unique.rb:140:in `call'
```

I think I isolated the error in the sidekiq-ent source code (in `lib/sidekiq-ent/unique.rb:141`).

With the recent change the call to redis was updated to pass in the parameters `get` in addition to `nx`. Only one of those parameters is allowed in redis versions prior to 7.0 ([official doc](https://redis.io/commands/set/) last paragraph).

In fact I was able to reproduce the issue with a redis 6.2 instance via: 

```ruby
Sidekiq.redis{|c | c.set("a", "b", nx: true, get: true)  }
```

I am not sure what the solution is but implicitly updating the redis requirement on a patch update was most likely unintentional.

**Comment by mperham** [comment]
Ugh, what a footgun from Redis. The docs only note the limitation at the very bottom of the page. https://redis.io/commands/set/

**Comment by hernanat** [comment]
hey @mperham we're getting this too -- I tried to run an update but only `redis-client` updated but I am unsure if that will fix this. If it doesn't, are you planning a release or should we downgrade?

Thanks!

**Comment by mperham** [comment]
You can expect a patch release on Monday morning.

**Comment by hernanat** [comment]
cool thanks -- what version should we revert to in the meantime?

**Comment by mperham** [comment]
The previous patch version should work fine.

**Comment by hernanat** [comment]
thanks Mike ! 🚀
