### ISSUE TITLE
Memory leak in perform_bulk

### ISSUE THREAD

**Issue by costi** [sidekiq/sidekiq#5795]
Ruby version: ruby 3.0.2p107
Rails version: none
Sidekiq / Pro / Enterprise version(s): 6.5.8

After `perform_bulk` we are leaking memory. This is reproduced in a simple script, without rails or any other gems.
I'm enqueuing 900k jobs with perform bulk and the memory increases from 148MB to 418MB.

`Gemfile`
```ruby
source 'https://rubygems.org'
gem 'sidekiq', '< 7'
gem 'get_process_mem'
```

`bulk.rb`
```ruby
require 'sidekiq'

class EasyJob
  include Sidekiq::Job

  def perform(*args)
    # Do nothing for now
  end
end

require 'get_process_mem'

puts "Memory used: #{GetProcessMem.new.mb}"
puts 'generating job arguments...'
jobs = (1..900_000).map { |i| [i, i.to_s]  }
puts 'Done.'
puts "Memory used: #{GetProcessMem.new.mb}"

puts "sending a job with perform_async"
EasyJob.perform_async(jobs[0])
puts "Memory used: #{GetProcessMem.new.mb}"

puts "sending a 100 jobs with perform_bulk"
EasyJob.perform_bulk(jobs.first(100))
puts "Memory used: #{GetProcessMem.new.mb}"

puts 'enqueueing jobs to sidekiq'
EasyJob.perform_bulk(jobs)
puts "done enqueuing #{jobs.size} jobs to sidekiq"
puts "Memory used: #{GetProcessMem.new.mb}"

puts "Running GC"
GC.start
puts "Memory used: #{GetProcessMem.new.mb}"

puts 'clearing redis memory'
Redis.new.flushall
puts "Memory used: #{GetProcessMem.new.mb}"

puts 'Running in batches with perform_bulk'
jobs.each_slice(10000) do |smaller_jobs|
  EasyJob.perform_bulk(smaller_jobs)
end
GC.start
puts 'Done.'
puts "Memory used: #{GetProcessMem.new.mb}"

puts 'clearing redis memory'
Redis.new.flushall
puts "Memory used: #{GetProcessMem.new.mb}"
```

```bash
Memory used: 35.0390625
generating job arguments...
Done.
Memory used: 147.703125
sending a job with perform_async
Memory used: 147.703125
sending a 100 jobs with perform_bulk
Memory used: 148.53125
enqueueing jobs to sidekiq
done enqueuing 900000 jobs to sidekiq
Memory used: 418.7890625
Running GC
Memory used: 412.08984375
clearing redis memory
Memory used: 412.08984375
Running in batches with perform_bulk
Done.
Memory used: 421.8828125
clearing redis memory
Memory used: 421.8828125
```

**Comment by fatkodima** [comment]
That's not a memory leak. Not an expert, but from my knowledge, ruby only allocates additional memory from the operating system (for the pages holding ruby objects, for example), but frees very rarely in case it will need more memory in future. And even if it frees, the `malloc` function under the hood does not return memory to the OS immediately for the same reason. 

`get_process_mem` probably uses some unix cli tool to get the process memory, but this memory is the memory allocated by the ruby process, not the memory actually used. I advise to use `memory_profiler` gem and see if there are any unexpectedly high number of retained objects.

**Comment by costi** [comment]
@fatkodima I think you're right

After perform_bulk and `GC.start` I did `ObjectSpace.count_objects` and the growth was all  in `:FREE` which was free slots for objects. There is no memory leak.
