### ISSUE TITLE
Cleaning up batch jobs from deleted batch

### ISSUE THREAD

**Issue by SemmyTan** [sidekiq/sidekiq#5797]
Hello,

I am using Sidekiq Pro and incorrectly deleted a batch job and am wondering if there is any way to clean up the orphaned(?) batch jobs.

Last week, I somehow ended up with a hanging batch job for sending emails due to Sidekiq getting shut down in the middle of running the batch job. This batch job would then get rerun each time Sidekiq was restarted the next few days, likely due to the `super_fetch` setting that I have enabled. I am not sure what caused this situation, but I am unable to look further into it at this point and this is not the main issue.

I knew that specific batch job was no longer needed so I did a quick search on google and ran the command to delete the batch without really thinking about it.
```
batch = Sidekiq::Batch::Status.new(bid)
batch.delete
```

It wasn't until today that I read the full Sidekiq batch documentation and saw the warning for `Deleting a batch will break Sidekiq if there are still jobs associated with that batch in Redis`. I did not run `batch.invalidate_all` before running `batch.delete`. Some of the deleted batch jobs still seem to be running each time Sidekiq is restarted. I set up the Sidekiq Web UI and also checked the Sidekiq API through the rails console and there are no pending jobs or batches displayed, so I think the batch jobs got orphaned somehow and now my Sidekiq is "broken" per the warning.

Is there any way to manually search for and delete these orphaned/ghost jobs directly through Redis? I think completely clearing out all data in Redis should fix this, but I wanted to see if there was any other way to find and delete these jobs before going with the nuclear option.

Thank you

**Comment by mperham** [comment]
You'll need to dip into the API. https://www.mikeperham.com/2021/04/20/a-tour-of-the-sidekiq-api/
