### ISSUE TITLE
The new verify_json logic is not compatible with ActiveJob Serializers

### ISSUE THREAD

**Issue by stefano-sarioli** [sidekiq/sidekiq#5799]
Ruby version: ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [arm64-darwin22]
Rails version: Rails 6.1.7.2
Sidekiq version(s): sidekiq-7.0.5

Thanks for all the fantastic job you all poured into making Sidekiq awesome. I'm here to report an issue with our code related to the latest bug fix release.

We are using a custom ActiveJob serialiser, and with the new logic introduced the in PR #5768 (that is impressing), we are drifting away from the serialiser supported by ActiveJob.
As you can see here https://github.com/rails/rails/blob/main/activejob/lib/active_job/serializers.rb, there is a list of default serialiser supported by ActiveJob that is richer that he now present in the `RECURSIVE_JSON_SAFE` list.
Also, as you can see here https://github.com/rails/rails/blob/f6b386d1822607601253c1df7e5d819425538a05/activejob/lib/active_job/railtie.rb, by default, it's possible to add custom serialiser to ActiveJob, and that will now always raise an error in Sidekiq because there is no way to add a serialiser to the `RECURSIVE_JSON_SAFE` list.

It's possible to ignore the Sidekiq check with `Sidekiq.strict_args!(false)`, but I'm not sure that this was an intentional behaviour, and for sure is not a bug fix change. 

I think we have a couple of options:

- We officially state that if you enable the Sidekiq `strict_args` check, you are limited to a subset of the serialiser supported byt ActiveJob.
- We update the implementation to consider all the serialiser supported by ActiveJob.
- We rollback the original PR.

I'm okay with any of these solutions as long as we document them. 
WDYT?

**Comment by fatkodima** [comment]
Active Job's serializer should already serialize all the arguments to json acceptable types before that check is made. 
Can you provide a reproducible example?

**Comment by stefano-sarioli** [comment]
@fatkodima Sure, I'll work on it and get back to you.

**Comment by mperham** [comment]
Maybe for 6.1? It's working fine for Rails 7.0:

```ruby
    hsh = HashWithIndifferentAccess.new
    hsh[:range] = 3..9
    hsh[:time] = Time.now
    aj.perform_later("mike", 123, :foo, hsh)
```

```
[{"job_class"=>nil, "job_id"=>"e63339ae-9196-4ac4-935e-ec6becd51d05", "provider_job_id"=>nil, "queue_name"=>"bar", "priority"=>nil, "arguments"=>["mike", 123, {"_aj_serialized"=>"ActiveJob::Serializers::SymbolSerializer", "value"=>"foo"}, {"range"=>{"_aj_serialized"=>"ActiveJob::Serializers::RangeSerializer", "begin"=>3, "end"=>9, "exclude_end"=>false}, "time"=>{"_aj_serialized"=>"ActiveJob::Serializers::TimeSerializer", "value"=>"2023-02-20T10:23:40.213889000-08:00"}, "_aj_hash_with_indifferent_access"=>true}], "executions"=>0, "exception_executions"=>{}, "locale"=>"en", "timezone"=>"UTC", "enqueued_at"=>"2023-02-20T18:23:40Z"}]
```

It's a big payload but everything is serialized correctly to plain JSON.

**Comment by ZilvinasKucinskas** [comment]
I likely ran into the same issue.

This is the payload generated with `noticed` gem that started failing when I tried to update from Sidekiq 7.0.3 to 7.0.5:

```ruby
{"retry"=>true,                                                                   
 "queue"=>"default",                                                              
 "class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",                 
 "wrapped"=>Noticed::DeliveryMethods::ActionCable,                                
 "args"=>                                                                         
  [{"job_class"=>"Noticed::DeliveryMethods::ActionCable",                         
    "job_id"=>"e2230a91-2ae3-493b-8b09-bfe8d675f004",                             
    "provider_job_id"=>nil,                                                       
    "queue_name"=>"default",                                                      
    "priority"=>nil,                                                              
    "arguments"=>                                                                 
     [{"notification_class"=>"Account::OwnershipNotification",                    
       "options"=>                                                                
        {"format"=>{"_aj_serialized"=>"ActiveJob::Serializers::SymbolSerializer", "value"=>"to_websocket"},
         "channel"=>"NotificationChannel",
         "_aj_symbol_keys"=>["format", "channel"]},
       "params"=>
        {"account"=>{"_aj_globalid"=>"gid://test-app/Account/264178000"},
         "previous_owner"=>"User One",
         "_aj_symbol_keys"=>["account", "previous_owner"]},
       "recipient"=>{"_aj_globalid"=>"gid://test-app/User/298486374"},
       "record"=>{"_aj_globalid"=>"gid://test-app/Notification/980190963"},
       "_aj_symbol_keys"=>["notification_class", "options", "params", "recipient", "record"]}],
    "executions"=>0,
    "exception_executions"=>{},
    "locale"=>"en",
    "timezone"=>"UTC",
    "enqueued_at"=>"2023-02-21T06:10:15Z"}],
 "jid"=>"68a598c9db71cefe34821fbb",
 "created_at"=>1676959815.829025}
 ```
 
 Calling `verify_json(payload)` throws `Job arguments to Noticed::DeliveryMethods::ActionCable must be native JSON types, but nil is a NilClass. (ArgumentError)`.

**Comment by fatkodima** [comment]
> Calling verify_json(payload) throws Job arguments to Noticed::DeliveryMethods::ActionCable must be native JSON types, but nil is a NilClass. (ArgumentError)

Can you try running sidekiq `main`? That would show a more helpful error message after https://github.com/sidekiq/sidekiq/pull/5790.

I think, you should call `.to_s` on the `NameOfPerson::PersonName` instance.
