### ISSUE TITLE
 Sidekiq::Pro::Web.with doesn't work with connection_pool, string or Redis objects

### ISSUE THREAD

**Issue by pkmuldoon** [sidekiq/sidekiq#5805]
Ruby version:

Ruby 3.2.0

Rails version:

Rails 7.0.4.1

Sidekiq / Pro / Enterprise version(s):

sidekiq (7.0.5)
sidekiq-pro (7.0.7)

Sidekiq/Pro 7 doesn't accept connection_pools any more as it has its own internal connection_pool. However, the `Sidekiq::Pro::Web.with` method still expects a connection_pool with the key argument `redis_pool:`

Here are some more details.

We mount our Sidekiq web with these two lines in config/routes.rb

```
 mount Sidekiq::Pro::Web.with(redis_pool: CacheConfig.Redis.connection), at: "/sidekiq-other", as: "other" if CacheConfig::Redis.available?
 mount Sidekiq::Web => "/sidekiq"
 ```
 
 So two web UIs, serving two separate Sidekiq services, each with its own Redis instance served by the same Rails monolith.

As noted earlier, Sidekiq 7 has moved to use its own connection_pool, but the `.with` command still expects a connection_pool with the `redis_pool:` key argument, even though it appears not to work with said connection_pool. This all worked ok in Sidekiq 6.
 
I've tried returning a string URL there, i.e.  "redis://127.0.0.1:6379/1" as well as a plain old Redis client object but neither works. The issue I get if I return a  connection_pool object  to the `redis_pool:` argument key is this:

```
NoMethodError - private method `select' called for "# Server\r\nredis_version:7.0.8\r\nredis_git_sha1:00000000\r\nredis_git_dirty:0\r\nredis_build_id:73fe4a3beb619f6\r\nredis_mode:standalone\r\nos:Darwin 22.3.0 arm64\r\narch_bits:64\r\nmonotonic_clock:POSIX clock_gettime\r\nmultiplexing_api:kqueue\r
```
With a string argument to the `redis_pool` key argument: “undefined method `with' for "redis://127.0.0.1:6379/1"

And the same with a plain old Redis object

**Comment by mperham** [comment]
Did you see that the Pro Web UI sharding documentation has a separate snippet for Sidekiq 7.x?

https://github.com/sidekiq/sidekiq/wiki/Pro-Web-UI#sharding

```ruby
# Sidekiq Pro 7.x
POOL1 = Sidekiq::RedisConnection.create(url: "redis://localhost:6379/1")
POOL2 = Sidekiq::RedisConnection.create(url: "redis://localhost:6379/2")

Myapp::Application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  mount Sidekiq::Pro::Web.with(redis_pool: POOL2), at: "/sidekiq2", as: "sidekiq2"
```

You need to use Sidekiq's API to create the connection pool. Try that and let me know if you have further issues.

**Comment by pkmuldoon** [comment]
We're not sharding Redis. Outside of development, we're actually using two entirely separate redis cloud URLs to different redis DB's. I'll look into this though!

**Comment by pkmuldoon** [comment]
That all works, thanks!
