### ISSUE TITLE
Return values for sidekiq_retry_in must now be integers not 

### ISSUE THREAD

**Issue by RobsonKing** [sidekiq/sidekiq#5806]
During our upgrade from sidekiq 5.2.9 (pro 5.0.0) to sidekiq 6.5.8 (pro 5.5.8)

We encountered a problem where our jobs using sidekiq_retry_in were no longer respecting their custom interval. 

Example job
```
  class RetryDelay < ApplicationSidekiqWorker

    sidekiq_retry_in { 1.day }
    def perform
      raise "boom"
    end
  end
```

after digging around I believe that the change:
https://github.com/sidekiq/sidekiq/pull/5432/files

resulted in only integers being accepted as valid return values from sidekiq_retry_in.  We fixed our code by changing

`sidekiq_retry_in { 1.day }`
 to 
`sidekiq_retry_in { 1.day.to_i }`

If this change was intentional, may I suggest logging a message to the console if a non integer is returned from sidekiq_retry_in?  This might save someone else a bunch of time debugging.

Thanks for the great work!

**Comment by mperham** [comment]
Thanks, I don't think this is severe enough to warrant backporting to 6.x but it's fixed on main.
