### ISSUE TITLE
error_handlers not executed until retries are exhausted (after upgrading to Rails 7)

### ISSUE THREAD

**Issue by betesh-at-data-axle** [sidekiq/sidekiq#5807]
Ruby version: 3.1.2, 3.2.1
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): sidekiq 6.5.8, sidekiq-pro 5.5.8

Prior to upgrading to Rails 7, sidekiq would [notify honeybadger](https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/plugins/sidekiq.rb#L27-L65) when an error occurred, containing information about the error coming from our code.  Once we upgraded to Rails 7, the error notification changed to be a `Sidekiq::JobRetry::Skip`, coming from [this line](https://github.com/sidekiq/sidekiq/blob/0c1e466fdb995b67ab14ae08aa23e02a55f28593/lib/sidekiq/job_retry.rb#L132).

Once we've exhausted retries, we'll get a honeybadger notification describing the error being raised by our application code, not a sidekiq `Skip`, but we don't want to wait that long--Honeybadger provides a `sidekiq.attempt_threshold` option so we can configure how many failures before sidekiq reports the error to honeybadger, but since `handle_exception` isn't called until retries are exhausted, honeybadger's error handler is never called.

https://github.com/sidekiq/sidekiq/blob/0c1e466fdb995b67ab14ae08aa23e02a55f28593/lib/sidekiq/job_retry.rb#L128

I would have expected something more like:

```
if msg["retry"]
  handle_exception(e)
else
  raise e
end 
```

so that error_handlers are triggered even before retries are exhausted.  Maybe that's not the purpose of error_handlers, but from [the wiki page](https://github.com/sidekiq/sidekiq/wiki/Error-Handling#error-handlers) ("Gems can attach to Sidekiq's global error handlers so they will be informed any time there is an error inside Sidekiq"), it sounds like error handlers should be triggered on every failure, not just once retries are exhausted.

The oddest part is that this worked until we upgraded Rails from 6.1.7 to 7.0.4, even though we did not change the version of honeybadger, sidekiq, or sidekiq-pro as part of that upgrade.  So I'm not sure which gem is to blame here, but I'm opening the issue on sidekiq because, based on the code I linked above, the new behavior seems to be expected, but based on the wiki, it does not.

**Comment by mperham** [comment]
Are you using active job? Is your Honeybadger gem up-to-date?

**Comment by betesh-at-data-axle** [comment]
Honeybadger is up-to-date--I've seen this happen with both 5.0.2 and 5.1.0.

Some of our jobs use good old-fashioned `include Sidekiq::Job`, but others inherit from `ActiveJob::Base`.  I looked through a handful of the `Skip`s on honeybadger and they are all coming from classes that `< ActiveJob::Base`.

**Comment by betesh-at-data-axle** [comment]
I was mistaken.  We only observed this on honeybadger 5.0.2, and after upgrading honeybadger to 5.1.0, the unwrapped errors are being reported.

We were configuring honeybadger with `ignore_only`, so we weren't ignoring their default ignore list.  If we had been using it, the `Skip`s would never have been reported and we never would have noticed anything was wrong, so bizarrely enough it worked out better this way.

Even without the default ignore list, the `Skip`s are no longer getting reported.
