### ISSUE TITLE
Dispatch one time job from Periodic tab

### ISSUE THREAD

**Issue by rainerborene** [sidekiq/sidekiq#5808]
I think it would be useful to have a button `Queue` on the Periodic tab to enqueue a job right from the Sidekiq Web admin panel. Say you have a worker that refreshes a cache storage. You would be able to refresh it immediately. No wait until the next run. Do you think it is a good feature @mperham?

**Comment by adamzapasnik** [comment]
Noticed this issue was closed, but it could be a useful feature when devs don't have a direct access to the production server and UI comes in handy.
