### ISSUE TITLE
Potential PR: Order UI Queues Tab by Priority Instead of Alphabetical

### ISSUE THREAD

**Issue by pmichaeljones** [sidekiq/sidekiq#5809]
When using a procfile, the UI BUSY tab shows the queues in order of importance/weight/priority. 

<img width="1199" alt="Screen Shot 2023-03-02 at 1 13 58 PM" src="https://user-images.githubusercontent.com/6728265/222425806-b12ef991-4d2c-412b-b5a2-44a3373e7748.png">

The UI QUEUES tab, however, shows them alphabetically.

<img width="1209" alt="Screen Shot 2023-03-02 at 1 18 58 PM" src="https://user-images.githubusercontent.com/6728265/222426891-3c91faad-8179-4888-b2cf-ca058f6d8e39.png">

Any interest in a PR that sorts the queues tab by priority instead of alphabetical? I'd happily work on it.

**Comment by mperham** [comment]
Sure, that would be fine.

**Comment by pmichaeljones** [comment]
Sounds good!
