### ISSUE TITLE
Feature Request: Emit statsd metrics when enqueuing jobs

### ISSUE THREAD

**Issue by jordan-brough** [sidekiq/sidekiq#5811]
Sidekiq Pro emits metrics when processing jobs. It'd be helpful if it also emitted metrics when enqueuing jobs.

For example, if a queue is very backed up (say hundreds of thousands of jobs), I could look at a history of job enqueue metrics to get a better feel for what's been happening in terms of items feeding into the queue.

**Comment by mperham** [comment]
Sidekiq Enterprise's historical metrics do emit the queue sizes regularly. https://github.com/sidekiq/sidekiq/wiki/Ent-Historical-Metrics#metrics

**Comment by jordan-brough** [comment]
In case it's helpful, this is approximately what we've added to our code now to accomplish this:
```ruby
class SidekiqClientMetrics
  def call(worker_class, _job, queue, _redis_pool)
    yield.tap do
      statsd.increment("sidekiq.enqueue", tags: ["worker:#{worker_class.name}", "queue:#{queue}", "result:success"]
    end
  rescue => e
    statsd.increment("sidekiq.enqueue", tags: ["worker:#{worker_class.name}", "queue:#{queue}", "result:error", "error:#{e.class.name}"]
  end
end
```
(I translated that a bit from our implementation so I'm not 100% sure the code is correct.)

and we add that as a `client_middleware` in both `configure_client` and `configure_server`.

**Comment by mperham** [comment]
> Would I be able to use those metrics to, say, create a graph showing job enqueue counts over time, split by worker class name and queue?

You'd be able to see queue size over time.

> How are sidekiq.scheduled and sidekiq.enqueued recorded?

Integer gauge of the size of the corresponding Redis structures.

> Do those inspect queue sizes or do they emit metrics when jobs are enqueued?

Queue sizes. You don't have visibility into the job classes within the queues but you'll get that upon execution in the `job.perform` metric.

With your implementation, a million enqueues will generate a million metrics. With Sidekiq Enterprise, a million enqueues will generate no metrics but within N seconds, the historic metrics will scan the queue size and push one metric with value 1_000_000.

**Comment by jordan-brough** [comment]
Thanks, that makes sense.

Since it's hard to inspect the contents of a Sidekiq queue, I think it's very helpful to have the metric-per-enqueue.

Same thing as what Sidekiq Pro does in `Sidekiq::Middleware::Server::Statsd`, but on the opposite end of the pipe — during enqueue instead of dequeue.

I find that very helpful in situations where a queue that services multiple types of jobs suddenly has a high number of jobs and you're not sure why or what's in the queue.  We had this happen just recently and it would've been very helpful to break down enqueues by worker class name and queue name. Seeing the queue size is helpful, but being able to break things down by job type is sometimes very revealing.  It'd probably be just as good (or maybe better) if the periodic queue size check could break things down by worker class, but my understanding is that's not feasible w/ how Sidekiq works currently. Lmk if I'm wrong.

Is metrics-on-enqueue something you'd consider adding to Sidekiq/Sidekiq Pro?

**Comment by mperham** [comment]
If a queue is stalled, it's due to the contents of the Busy tab, not due to the contents of the Queues tab. I've never considered the metric you describe as worth the network traffic and CPU cost.

You could add this metric yourself with a client middleware if you wanted to try it out. Most of the code is already there in Pro's statsd server middleware.

**Comment by jordan-brough** [comment]
I'm not talking about a queue being stalled necessarily due to slow jobs. I'm talking about e.g. scenarios where an unexpectedly large number of jobs are in a queue. E.g. it could be because some jobs are processing very slowly, or it could be because something is dumping a lot more jobs than expected into the queue (which is e.g. what happened in our case).  In that case it's very helpful to be able to quickly see what is (likely) in the queue, which is currently quite difficult w/ Sidekiq.

We are doing it w/ a client middleware now (see code snippet above), but to me it seems like something that could be nice to have in Sidekiq itself.  It'd be 2x the statsd traffic Sidekiq is currently sending. That's not a huge increase and statsd systems should be good at handling/aggregating that sort of thing.  But if you don't agree on the value then I can understand not wanting to add more.

Do you have other suggestions on how to handle the "what's in my queue right now" question? I seem to have that question not too infrequently, and if the queue has serious volume it seems like a hard one to answer currently.

**Comment by mperham** [comment]
I understand your scenario. The Web UI does allow you to see the contents of a queue, 25 items at a time, but yeah there's no way to get a count of job types. 

Like I said, I think it's something relatively easy for you to add yourself. If you'd like me to build a prototype for you to try, I'm happy to do so but I'm not convinced its worth the overhead to add it for everyone.

**Comment by jordan-brough** [comment]
> If you'd like me to build a prototype for you to try, I'm happy to do so

Sure, it'd be great to see how you'd recommend implementing it. It sounds like you'd do something different than [what I pasted above](https://github.com/sidekiq/sidekiq/issues/5811#issuecomment-1456403202)?
