### ISSUE TITLE
Sidekiq::Client.push_bulk should work in batches

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#5814]
Sidekiq::Job.perform_bulk allows the `batch_size` parameter but `push_bulk` does not. Add support for a default batch_size of 1000.

NB: the term "batch_size" has nothing to do with Sidekiq Pro's Batches feature and is an unfortunate overlap in terminology. We could also call it "group size", "window size", "bulk size" or other?

**Comment by mperham** [comment]
Allowing an unlimited number of elements in the bulk push means performance will suffer beyond a certain point. This was seen in the wild when mastodon.social was pushing 1000s of jobs at a time for its fanout logic. Implicitly breaking those payloads into batches of 1000 should improve performance.

**Comment by fatkodima** [comment]
I can try to implement this, if you are not going to do it yourself.
I remember, there was a discussion regarding a similar config, but do not remember if it was in the `sidekiq`s repository, or if it was related to the sidekiq. But I remember the answer was kinda like that "it is very easy to do it manually".

But yeah, better to fix the inconsistencies between the two. I vote for the `batch_size` name - it is more familiar for ruby/rails developers, and personally, I know about sidekiq "batches" feature, but it does not resonate with it for me.

**Comment by mperham** [comment]
I have it done but it is rather tricky with kwargs and backwards compatibility. Go ahead if you want, let’s see what your solution looks like.

One other thing I wanted to see if it’s possible: to lazy generate and push bulk jobs in those batches; you might push one million jobs but you only need enough memory for the 1000 job window because “args” is a lazy Generator.

**Comment by ClearlyClaire** [comment]
> Allowing an unlimited number of elements in the bulk push means performance will suffer beyond a certain point. This was seen in the wild when mastodon.social was pushing 1000s of jobs at a time for its fanout logic. Implicitly breaking those payloads into batches of 1000 should improve performance.

Hi! We are actually not using `Sidekiq::Client.push_bulk` directly but the `sidekiq-bulk` that does [something very similar](https://github.com/aprescott/sidekiq-bulk/blob/master/lib/sidekiq/bulk.rb) to `perform_bulk`, including slicing the jobs into batches. However, the `sidekiq-bulk`'s default limit is 10,000 jobs, while with `perform_bulk` the default is 1,000.

> One other thing I wanted to see if it’s possible: to lazy generate and push bulk jobs in those batches; you might push one million jobs but you only need enough memory for the 1000 job window because “args” is a lazy Generator.

That is actually the one reason I have right now to prefer `sidekiq-bulk` over `perform_bulk`.

**Comment by mperham** [comment]
@ClearlyClaire Would you mind giving this PR a quick review to see if it seems like it will handle Mastodon's needs? ^^^^^

**Comment by ClearlyClaire** [comment]
That PR looks sensible, but what we use right now is almost equivalent to `Sidekiq::Job.perform_bulk` (even though it's called `push_bulk`, it's not `Sidekiq::Client.push_bulk`), except for the fact that it accepts a block that it runs on the slices to get the actual job arguments. In my limited testing, this is more efficient than going through a lazy enumerator.

**Comment by mperham** [comment]
Coming in 7.1
