### ISSUE TITLE
Restore dumping config when `sidekiq -v` (verbose) is used

### ISSUE THREAD

**Issue by davetron5000** [sidekiq/sidekiq#5822]
Ruby version: 3.2.1
Rails version: N/A
Sidekiq / Pro / Enterprise version(s): 7.0.6 open source

See https://stackoverflow.com/questions/75642616/programmatically-access-sidekiq-config-what-config-options-are-there-and-where-d for some context

Previously, you could do `sidekiq -v` and it would dump the config it had parsed.  This isn't there, likely lost during the refactor of config for V7.

It appears that the server's config is available via `Sidekiq::CLI.instance.config` *after* `Sidekiq::CLI.instance.parse` has been called.

* Is there interest in restoring this feature? ( I would like it for reasons stated below :)
* Is accessing `Sidekiq::CLI.instance.config` the right place to do that if I were to dump it?

If Yes to either, I'm happy to take a shot at adding this since I'm requesting it.

## Reasons Why This is Useful

Sidekiq has several places you can specify configuration and also has reasonable defaults, so it can be easy to e.g. mis-spell a name or env var and have Sidekiq start up and work, but not with the config you specified.  Being able to dump out exactly what config Sidekiq is going to use would be really handy when making changes to the config.

**Comment by mperham** [comment]
1. Yeah, bring it back!
2. Yes, exactly.

**Comment by mperham** [comment]
I went ahead and fixed this since I wanted to get it into today's patch release.
