### ISSUE TITLE
Failed count doesn't hyperlink to the Failures page

### ISSUE THREAD

**Issue by nmolinossb** [sidekiq/sidekiq#5826]
Ruby version:
Rails version:
Sidekiq / Pro / Enterprise version(s): 7.0.7

In the banner at the top of every page, why doesn't the "Failed" count link to the "Failures" page similar to how Busy/Enqueued/etc. do?

**Comment by mperham** [comment]
There is no Failures page. Do you mean Retries?

**Comment by nmolinossb** [comment]
<img width="1616" alt="Screenshot 2023-03-16 at 3 17 05 PM" src="https://user-images.githubusercontent.com/89423082/225764951-e7d28148-4ba6-4e55-895d-c60bb5932745.png">
Sorry, I didn't see the email about your reply.  Attached is a screenshot showing the piece that doesn't link (circled in red).   Failures page is:  /sidekiq/failures

**Comment by mperham** [comment]
That failures tab is provided by the sidekiq-failures gem and isn’t built in.
