### ISSUE TITLE
Route rescued jobs to a specific queue

### ISSUE THREAD

**Issue by utay** [sidekiq/sidekiq#5831]
Ruby version: 3.2.0
Rails version: 7.0.4.1
Sidekiq / Pro / Enterprise version(s): 7.0.2 / 7.0.4 / 7.0.3

Hi there,

I'd like to revive https://github.com/sidekiq/sidekiq/issues/4594 and this comment:
> I’m torn on what to do here because a very common use case is Kubernetes deploys killing Sidekiq processes without warning thus leading to orphaned jobs, and if you rescue those jobs they should execute just fine.

We run jobs on Kubernetes and pods are configured to wait that Sidekiq processes have finished executing jobs before being terminated, and we have a few super-fetched jobs per day most of the time due to actual crashes. Our use case would be to route jobs that get super-fetched (crash or out-of-memory) in a "debug" queue with a single worker and tracing sampled at 100% so that we can easily analyze them afterwards. 

I don't think we can implement that in the current state because:
- The `config.super_fetch!` callback allows us to log the job but we can't modify it
- Super-fetched jobs don't go through Sidekiq client middlewares so we can't change their destination queue 
- We could reroute them in a Sidekiq server middleware but there's no info in the job payload which indicates that this job was super-fetched 

Ideally we would have a `superfetched: true` attribute in the metadata or an optional `queue` argument to `config.super_fetch!`. Do you think one of these could be implemented? Thank you!

**Comment by mperham** [comment]
Perhaps you could use the poison pill callback to push a copy of the job into that `debug` queue?

**Comment by utay** [comment]
We would like to avoid pushing a copy of the job because they would run in parallel and potentially conflict with each other

**Comment by utay** [comment]
Oh, right. But we would like to reroute rescued jobs that crashed and have not been classified as poison pills yet (< 3 retries). Most of the time in our case, jobs crash because they get OOM and then succeed before being moved to the dead set

**Comment by mperham** [comment]
We can't tell if a job was rescued because it's a poison pill or if it was rescued because it was running concurrently with another job which was a poison pill. Remember a Sidekiq process might be executing a dozen jobs concurrently. It's only when we see the same JID associated with multiple process crashes that we have enough data to classify it as a poison pill.

**Comment by utay** [comment]
Apologies for the delay here. Right. The idea here is to queue all rescued jobs (poison pill or not yet) to the "debug" queue. This might route non-poison-pill and non-crashing jobs to this queue as well because a Sidekiq process runs jobs concurrently but that's fine for us

**Comment by mperham** [comment]
Thank you for the suggestion but I'm going to close this as I have no plans to implement it.
