### ISSUE TITLE
6.5.8 - Redis connections being left open in sidekiq worker process

### ISSUE THREAD

**Issue by kalleth** [sidekiq/sidekiq#5839]
# Summary

We're seeing redis connections being left established and not cleaned up/reused in our app. Using `lsof`, those connections are only being left open in our `worker` (i.e. sidekiq) container, and not by our `web`, `clock` or `sneakers` container.

Using busybox `lsof`:
```
worker# lsof | grep ruby | grep socket | wc -l
845

web# lsof | grep ruby | grep socket | wc -l
38

clock# lsof | grep ruby | grep socket | wc -l
2

sneakers# lsof | grep ruby | grep socket | wc -l
37
```

Running `apk add lsof` to install a proper `lsof` gives:

```
/app # lsof | grep ruby | grep redis | wc -l
16492

/app # lsof | grep ruby | grep redis | head
ruby         1                root    9u     IPv4              20122      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51584->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   10u     IPv4              20128      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51590->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   11u     IPv4              20872      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51606->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   12u     IPv4              66695      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:35022->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   13u     IPv4              20874      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51614->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   14u     IPv4              20875      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51620->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   15u     IPv4             114578      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:58826->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   16u     IPv4              84396      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:38752->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   17u     IPv4              27065      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:45260->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   18u     IPv4              24787      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:47582->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
```

And looking at our ECS dashboard shows:

<img src="https://user-images.githubusercontent.com/615627/226414904-c72c705f-f1e6-437d-b4a7-07b66d841e86.png" width="250">

(The big drop is where our worker container ran out of available file descriptors and crashed).

# Operating environment

- ECS Fargate (docker containers)
- AWS Elasticache 6.2.6

# Versions and initializers

Ruby version: 3.1.2
Rails version: 6.1.7.3
Sidekiq / Pro / Enterprise version(s): 6.5.8

Initializer:

```ruby
if Rails.env.production? || Rails.env.staging?
  Sidekiq.configure_server do |config|
    config.logger.level = Logger::WARN
    # give a bit more leniency to redis connction on sidekiq
    config.redis = {
      url: ENV["REDIS_URL"],
      network_timeout: 5,
      reconnect_attempts: 3,
      ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
    }
  end
end
```

And, unfortunately, yes, we're doing The Bad Thing of using redis as a cache too:

```ruby
  config.cache_store = :redis_cache_store,
                       { url: ENV["REDIS_URL"], ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
```

However, I'd expect to see the `web` processes (which make extensive use of this) also leaking connections if the problem existed in the cache driver -- but I guess it's possible.

Finally, we are making use of [sidekiq-throttled](https://github.com/ixti/sidekiq-throttled). I don't see anything dramatic that stands out, although the `concurrency` strategy does some pretty low-level stuff at https://github.com/ixti/sidekiq-throttled/blob/main/lib/sidekiq/throttled/strategy/concurrency.rb#L44-L72 that I don't understand, that could impact the ability of the sidekiq process to release the redis connection.

**Comment by kalleth** [comment]
Before you spend significant time on this, I'm going to try introducing a `timeout` option to the `:redis_cache_store` - as I just noticed it doesn't have one (but sidekiq does) and see if that resolves the problem. I'll update and close if it does.

**Comment by kalleth** [comment]
It does not appear that adding a timeout to the `cache_store` use of redis has changed anything. I still don't know if this is a problem with `redis-rb` or `sidekiq`, but I do know that restarting _solely_ the sidekiq container causes connections to return to normal (see graph).

![image](https://user-images.githubusercontent.com/615627/226953831-06897986-e6d7-47a0-94b9-7240c36c824b.png)

It's possible this bug exists within `sidekiq`, `redis-rb` or `sidekiq-throttled`, but I'm not sure how to narrow this down any further, so I can raise the bug in the right repo if it's not a sidekiq issue. Any suggestions?

**Comment by mperham** [comment]
Can you post a TTIN dump so we can see where the threads are relaxing?

**Comment by kalleth** [comment]
[log-events-viewer-result.csv](https://github.com/sidekiq/sidekiq/files/11041873/log-events-viewer-result.csv)

nb this is after a recent prod deploy (which restarts all the containers), I can wait and provide a more detailed one this evening that may shed more light?

**Comment by mperham** [comment]
I think you should run a Sidekiq instance without sidekiq-throttled and see if it exhibits the same behavior.

**Comment by kalleth** [comment]
I've decided to go a different way to solve this, as I couldn't think up a method to easily rate limit our interactions with external API's without throttled and/or significant rework.

By changing `CONFIG SET timeout` from unlimited (0, the default for ElastiCache) to any value (e.g. 1000) on the server side in the parameter group for the elasticache instance, the issue is _completely_ resolved for us.

That means I won't be able to investigate further - at least in the near term - so I'm going to close this issue.

**Comment by kalleth** [comment]
@mperham I certainly haven't seen any Sentry alarms or problems processing jobs since implementing the change, so it looks like redis (or sidekiq!) is being very graceful about reconnecting, too!

Sorry I wasn't able to go deeper.

**Comment by abigoroth** [comment]
@kalleth I have a question, now in 2024 how can I execute a command into Fargate ?
