### ISSUE TITLE
Jobs rejected as not-unique after Sidekiq Enterprise upgrade

### ISSUE THREAD

**Issue by Darhazer** [sidekiq/sidekiq#5849]
Ruby version: 3.2.1
Rails version: 7.0.4.3
Sidekiq / Pro / Enterprise version(s): 7.0.7 / 7.0.8 / 7.0.6

After deploying the upgrade of sidekiq-enterprise from 2.5.3 to 7.0.6 we noticed spike of "Skipping enqueue for ..., not unique" messages. After some investigation, it looks like `unique_for:` jobs are not being unlocked due to change of the unlock code.

Previously it would send `job[LOCKED_KEY]` to the `unique_unlock` script, while the new version sends `job["jid"]`.
It looks like if the job was scheduled with the old version, but than executed by the new one, it sticks in the unique lock until the lock key itself expires, but we use very long expiration times for that.

**Comment by mperham** [comment]
Yes, there was a tweak to the unique data in 7.0.4 to enable this feature:

```
Unique middleware now prints the JID holding the lock if there is a duplicate [#5736]
```

In general I don't support running multiple versions simultaneously, especially across major versions. If your puma process is using Enterprise 2.5.3 and your Sidekiq process is running 7.0.6, the unique feature will not work.

**Comment by Darhazer** [comment]
So it doesn't support zero-downtime deployment, as you need to stop scheduling new jobs, restart sidekiq, restart puma and only then start scheduling jobs.

Meanwhile, I've created a script to remove old lock keys. Note: it doesn't account for jobs currently executed, so you need to pause all the queues, wait for all currently executing jobs to be finished, then execute, and unpause the queues afterwards. Hope it will be helpful if someone gets in the same situation:

```ruby
keys = Sidekiq.redis_pool.with { |conn| conn.keys('unique:*') }

queues = Sidekiq::Queue.all
jobs = []
queues.each do |queue|
  Sidekiq::JobSet.new(queue.name).each do |job|
    jobs << job.jid
  end
end

Sidekiq::ScheduledSet.new.each do |job|
  jobs << job.jid
end
Sidekiq::RetrySet.new.each do |job|
  jobs << job.jid
end

invalid_keys = keys.select do |key|
  jid = Sidekiq.redis_pool.with { |conn| conn.get(key) }
  !jobs.include?(jid)
end

invalid_keys.each do |key|
  Sidekiq.redis_pool.with { |conn| conn.del(key) }
end
```

**Comment by rianmcguire** [comment]
We also ran into this while planning a Sidekiq upgrade.

If anyone is looking for a zero-downtime workaround, we wrote a monkey patch:

```ruby
module Sidekiq::UniqueUpgradeCompatibility
  # sidekiq-ent 7.0.4 introduces a breaking change to unique_for that prevents the unique locks being released
  # if there's a mismatch between the client and server versions (it's incompatible both forwards and backwards)

  # < 7.0.4 identifies the locking job by timestamp
  # >= 7.0.4 identifies the locking job by jid

  # We can use this monkey patch to temporarily make Sidekiq forwards and backwards compatible when upgrading past
  # 7.0.3. Once we've been running only >= 7.0.4 for the maximum unique_for TTL, the patch can be removed.

  # This replaces the implementation of Sidekiq::Enterprise::Unique.unlock
  def unlock(job, cfg = Sidekiq.default_configuration)
    hash = job[Sidekiq::Enterprise::Unique::TOKEN_KEY]
    timestamp = job[Sidekiq::Enterprise::Unique::LOCKED_KEY] # For Sidekiq clients < 7.0.4
    code = job["jid"] # For Sidekiq clients >= 7.0.4
    return unless hash

    # Only the job which locked the hash can unlock the hash, since only it
    # should have the timestamp (enqueued by < 7.0.4) or the JID (enqueued by >= 7.0.4)
    #
    # We attempt to unlock both, since we don't know which client version enqueued this job.
    Sidekiq::Enterprise::Scripting.call(:unique_unlock, ["unique:#{hash}"], [timestamp], cfg) if timestamp
    Sidekiq::Enterprise::Scripting.call(:unique_unlock, ["unique:#{hash}"], [code], cfg) if code
  end
end

Sidekiq::Enterprise::Unique.singleton_class.prepend Sidekiq::UniqueUpgradeCompatibility
```

**Comment by javierjulio** [comment]
I'm in the process of upgrading Sidekiq (w/Enterprise) from v6 to v7. We use the `unique_for:` feature in many jobs. The windows are short, 10 minutes or less. With the incompatibility issue in Sidekiq Enterprise 7.0.4 we are concerned about deploying this and having duplicate jobs.

@mperham would you suggest using the monkey patch by @rianmcguire as a safe alternative for a zero downtime deployment, or is it best to deploy the v7 upgrade off-hours when there are no unique jobs running or scheduled? I believe the unique lock issue is for any unique job that is running during the deploy or was scheduled pre-deploy and will run post upgrade, is that right?

**Comment by mperham** [comment]
@javierjulio Please don't reopen years old issues. Open your own issue.
