### ISSUE TITLE
How to set Redis options of sidekiq worker processes?

### ISSUE THREAD

**Issue by ck2000** [sidekiq/sidekiq#5851]
I am running `sidekiq -C sidekiq.yml -e production` and sidekiq smoothly comes up. However I am trying to adjust the redis connection options to set a password to access the redis-server. I would love to pass the password parameter to the redis options from the rails credentials.

> 2023-03-26T16:22:05.534Z pid=658003 tid=e8uv INFO: Booted Rails 7.0.4.3 application in production environment          
> 2023-03-26T16:22:05.535Z pid=658003 tid=e8uv INFO: Running in ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
> 2023-03-26T16:22:05.535Z pid=658003 tid=e8uv INFO: See LICENSE and the LGPL-3.0 for licensing details.                 
> 2023-03-26T16:22:05.535Z pid=658003 tid=e8uv INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
> 2023-03-26T16:22:05.535Z pid=658003 tid=e8uv INFO: **Sidekiq 7.0.7 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil}**

I already have the following initalizer setup in Rails which works fine for the sidekiq backend. However I struggel to set this up for the worker processes.

> Sidekiq.configure_server do |config|
>   redis_host = Rails.application.credentials.dig(:redis, :host) || 'localhost'
>   redis_port = Rails.application.credentials.dig(:redis, :port) || 6379
>   redis_password = Rails.application.credentials.dig(:redis, :password) || ""
>   config.redis = { host: redis_host, port: redis_port.to_i, password: redis_password }
> end
> 
> Sidekiq.configure_client do |config|
>   redis_host = Rails.application.credentials.dig(:redis, :host) || 'localhost'
>   redis_port = Rails.application.credentials.dig(:redis, :port) || 6379
>   redis_password = Rails.application.credentials.dig(:redis, :password) || ""
>   config.redis = { host: redis_host, port: redis_port.to_i, password: redis_password }
> end

**Comment by mperham** [comment]
That's exactly right. I don't know why it's not working for you.

**Comment by ck2000** [comment]
Thank you for your quick response. How can we further debug this?

**Comment by mperham** [comment]
Puts? Use a debugger?

**Comment by ck2000** [comment]
Found the issue within my systemctl script ... incorrect path. Thx
