### ISSUE TITLE
Improve documentation for Batch callback_queue

### ISSUE THREAD

**Issue by tiagotex** [sidekiq/sidekiq#5852]
The current documentation for Batch callback_queue mentions:

> Batch callbacks run in their own job. If there are errors in the batch callback, it will retry like any other job. You can specify a different queue for the callback jobs so they have a higher priority:

https://github.com/sidekiq/sidekiq/wiki/Batches#callback-details

This caused some confusion because it was not clear that batch callbacks would be set in the same queue used by the final job. Instead, I expected it to be set in the same queue as the batch creator job. I found this by looking at the previous issues:

> A batch is not a job so it would never appear in a queue. The batch callbacks are jobs and will go into whatever queue was used by the final job in the batch to execute unless you set the callback_queue attribute when creating the batch, i.e. batch.callback_queue = "critical"

https://github.com/sidekiq/sidekiq/issues/2876#issuecomment-229253630

Are you open to changing the Wiki to:

> Batch callbacks run in their own job, they are enqueued in the queue used by the final job in the batch to execute. If there are errors in the batch callback, it will retry like any other job. You can specify a different queue for the callback jobs so they have a higher priority:

**Comment by mperham** [comment]
You don't need to ask permission to edit the wiki. Just do it.
