### ISSUE TITLE
How to create a single capsule inside a Sidekiq cluster?

### ISSUE THREAD

**Issue by sos4nt** [sidekiq/sidekiq#5861]
One use case for capsules are processing concurrency sensitive jobs using a single-threaded capsule. This works just fine when running a single Sidekiq process. Inside a larger Sidekiq cluster however, you can have multiple machines, each running multiple Sidekiq processes. When defining a capsule as shown in [`docs/capsule.md`](https://github.com/sidekiq/sidekiq/blob/main/docs/capsule.md#sidekiqcapsule), each process on each of the machines would have its own single-threaded capsule. The capsule(s) would prevent concurrency on a thread level, but not on a process or machine level.

Is there an (easy) way to create a single capsule across a whole Sidekiq cluster? How would I set up a Sidekiq cluster to process my "concurrency sensitive" queue one job at a time? (I'm using Sidekiq Enterprise)

**Comment by mperham** [comment]
Enterprise does have a concurrent rate limiter, but it sounds like you want to start a special Sidekiq process to access a special queue, separate from all other Sidekiq processes in your cluster. That's as simple as `sidekiq -q solo`.
