### ISSUE TITLE
Metrics: Job execution vs counts tooltip ordered improperly

### ISSUE THREAD

**Issue by lloydwatkin** [sidekiq/sidekiq#5865]
Sidekiq: 7.0.7

Job execution counts/time tooltip looks like the times are sorted alphabetically rather than numerically..

![Screenshot from 2023-04-05 13-58-37](https://user-images.githubusercontent.com/271622/230088533-e0580773-233d-4fd8-9aa7-c651bc716a28.png)

**Comment by adamlogic** [comment]
Is the issue that these items should be in the opposite order so they match the bubbles? Or am I misunderstanding?

![CleanShot 2023-04-07 at 08 03 41@2x](https://user-images.githubusercontent.com/372/230605698-97acfa1d-edc0-4a76-840c-963eff94351f.png)
