### ISSUE TITLE
Sidekiq can't connect to Heroku Redis

### ISSUE THREAD

**Issue by harmoney-reaksmey** [sidekiq/sidekiq#5873]
**Ruby version:** 2.6.0
**Rails version:** 4.2.11
**Sidekiq:** 3.4.1
**Redis Client:** 4.0.2
**Heroku Redis Version :** 7.0

**Initializer**

> Sidekiq.configure_client do |config|
>   config.redis = { :size => 1, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
> end
> 
> Sidekiq.configure_server do |config|
>   config.redis = { :size => 1, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
> end

I have upgraded Heroku Redis to version 7.0 and trying to connect with Sidekiq. But I received this error when running

`Sidekiq.redis { |c| p c.client.location }`

> Traceback (most recent call last):
>        16: from /app/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/commands/console.rb:9:in `start'
>        15: from /app/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/commands/console.rb:110:in `start'
>        14: from (irb):1
>        13: from /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-3.4.1/lib/sidekiq.rb:81:in `redis'
>        12: from /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `with'
>        11: from /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `handle_interrupt'
>        10: from /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `block in with'
>         9: from /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `handle_interrupt'
>         8: from /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:107:in `block (2 levels) in with'
>         7: from (irb):1:in `block in irb_binding'
>         6: from /app/vendor/bundle/ruby/2.6.0/gems/redis-4.0.3/lib/redis.rb:214:in `client'
>         5: from /app/vendor/bundle/ruby/2.6.0/gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
>         4: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
>         3: from /app/vendor/bundle/ruby/2.6.0/gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize'
>         2: from /app/vendor/bundle/ruby/2.6.0/gems/redis-4.0.3/lib/redis.rb:215:in `block in client'
>         1: from /app/vendor/bundle/ruby/2.6.0/gems/redis-4.0.3/lib/redis/client.rb:124:in `call'
> Redis::CommandError (ERR unknown subcommand ''. Try CLIENT HELP.)

**However, it seems to be successful if I run**

```
redis_info = Sidekiq.redis { |conn| conn.info }
redis_info['connected_clients']
```
> "1"

`Sidekiq.redis { |conn| p conn.connection[:location] }`

> "ec2-3-221-157-55.compute-1.amazonaws.com:31389"

**My Redis client seems to be able to connect with Heroku Redis**

`redis = Redis.new(url: ENV['REDIS_URL'], ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE })`

> #<Redis client v4.0.3 for redis://ec2-3-221-157-55.compute-1.amazonaws.com:31389/0>

`redis.ping`

> pong

Could you please advise is there any thing wrong ?

Really appreciated for your help

**Comment by runephilosof-abtion** [comment]
On https://github.com/sidekiq/sidekiq#requirements it says Redis 6.2+.
Maybe that means => 6.2, < 7

**Comment by runephilosof-abtion** [comment]
Probably part of Sidekiq 7.1 #5769, removing the deprecated commands
