### ISSUE TITLE
Sidekiq Web UI somewhere lost confirmation dialogs after upgrade

### ISSUE THREAD

**Issue by JIucToyxuu** [sidekiq/sidekiq#5878]
Ruby version: 2.7.1
Rails version: 6.0.6.1
Sidekiq version: 6.5.8

After upgrade from 5.2.7 to 6.5.8, I got next issue.

Sidekiq Web UI view, located on /sidekiq/busy, contain two buttons: 'Quiet All' and 'Stop All'.  In Sidekiq 5.2.7, both protected from randomly click with confirmation dialog. In 6.5.8 - not. After little investigation, I see what JS code was changed. Updated code works only with 'input' elements, but 'Quiet All' and 'Stop All' is buttons. Before, it was works with any element with 'data-confirm' attribute.

For better understanding look at code:
1) 5.2.7 - [JS code](https://github.com/sidekiq/sidekiq/blob/v5.2.7/web/assets/javascripts/application.js#L34-L36) works with any elements.
2) 5.2.7 - ['Quiet All' and 'Stop All' - buttons](https://github.com/sidekiq/sidekiq/blob/v5.2.7/web/views/busy.erb#L9-L10)
3) 6.5.8 - [JS code](https://github.com/sidekiq/sidekiq/blob/v6.5.8/web/assets/javascripts/application.js#L21) works only with inputs
4) 6.5.8 ['Quiet All' and 'Stop All' - buttons](https://github.com/sidekiq/sidekiq/blob/v6.5.8/web/views/busy.erb#L40-L41)

Bug?

**Comment by mperham** [comment]
Yeah that sounds like a bug. PR welcome.
