### ISSUE TITLE
perform_bulk + unique jobs N+1

### ISSUE THREAD

**Issue by mscoutermarsh** [sidekiq/sidekiq#5880]
Hello!

I believe we've found that when using `perform_bulk` with `unique`, there is an N+1 for setting the uniqueness value.

## Context
We are using `perform_bulk` on a Job with `unique` enabled. We also have `super_fetch` enabled (not sure if relevant).

```ruby
sidekiq_options queue: :example, unique_for: 1.hour, unique_until: :success
```

I noticed today when looking at job performance that while `perform_bulk` is bulk queueing the jobs. The uniqueness locks are all being added 1-1.

<img width="896" alt="CleanShot 2023-04-17 at 08 54 17@2x" src="https://user-images.githubusercontent.com/155044/232490215-f5d4698d-5b6b-4e80-adf8-6eec8e14d801.png">

Note: we were enqueuing 1901 jobs, in batches of 50 (because we apply different `wait` periods to each).

Each of the set commands looks like this:
```
SET unique:35d4068877af361b7eaaf35934ed64cea570f268 f008654579ed631bcee18101 nx px 3635999
```

## Sidekiq versions
```
sidekiq (7.0.6)
sidekiq-ent (7.0.5)
sidekiq-pro (7.0.7)
```

**Comment by mperham** [comment]
Yep, expected. There's no way to batch up middleware invocations.

**Comment by mscoutermarsh** [comment]
Thanks @mperham! We'll look at removing unique for the jobs that are more time sensitive here.

**Comment by mperham** [comment]
There's nothing the user can do to fix it. The bulk operation is still cutting down on Redis round trips, it just can't get rid of all of them in this case.

**Comment by mperham** [comment]
If you are pushing 2000 unique jobs, you'll have 2001 round trips instead of 4000.
