### ISSUE TITLE
Add latency to Pro Metrics

### ISSUE THREAD

**Issue by sobrinho** [sidekiq/sidekiq#5888]
Ruby version: 2.7.6p219
Rails version: 6.0.3.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.5.8 / Pro 5.5.5 / Ent 2.5.3

Hey!

We enabled the dogstatsd monitoring but we don't have the latency being reported.

What do you think about tracking it there as well?

We currently have a manual instrumentation that runs in a Sidekiq Component every 30 seconds to report the latency, would be nice to have it natively.

**Comment by mperham** [comment]
Any commercial functionality which requires a cluster leader goes into Enterprise. That includes historical metrics like latency.

**Comment by sobrinho** [comment]
Ops, bad title! We are on Enterprise! ;)

**Comment by sobrinho** [comment]
Currently enterprise is tracking the queue size of every queue but the latency only from the default queue.

**Comment by sobrinho** [comment]
Our instrumentation looks like this right now for reference:

```ruby
Sidekiq::Queue.all.each do |queue|
  next if if queue.name == 'default' # already instrumented by ent
  dogstatsd.gauge('sidekiq.queue.latency', queue.latency.to_i, tags: ["queue:#{queue.name}"])
end
```

**Comment by mperham** [comment]
This is As Designed. Latency is expensive to collect so you must opt into it. 

https://github.com/sidekiq/sidekiq/wiki/Ent-Historical-Metrics#custom

**Comment by sobrinho** [comment]
Nice, didn't read that page before, thanks! ❤️
