### ISSUE TITLE
Sidekiq process may be CPU-saturated

### ISSUE THREAD

**Issue by amolbudkhe** [sidekiq/sidekiq#5893]
Ruby version: ruby 2.7.4p191
Rails version: 6.1.7.3
Sidekiq / Pro / Enterprise version(s): 6.5.3

initializer/Sidekiq.rb
```ruby
require 'sidekiq'

Sidekiq.default_job_options = { backtrace: true }

Sidekiq.configure_server do |config|
  config[:concurrency] = ENV['SIDEKIQ_CONCURRENCY'].to_i
  config.redis = { url: ENV['SIDEKIQ_SERVER_REDIS_URL'] }

  Rails.logger = Sidekiq.logger
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['SIDEKIQ_SERVER_REDIS_URL'] }
end
```

sidekiq.yml
```
:queues:
  - verify
  - reports
  - default
:limits:
  verify: 1 # Tasks for the verify will be run by at most 1 worker at the same time
  reports: 1
```

production.sidekiq.log
```
2023-04-24T13:34:07.282Z pid=8 tid=62lo WARN: Your Redis network connection is performing extremely poorly.
Last RTT readings were [99783, 100355, 100326, 99421, 100300], ideally these should be < 1000.
Ensure Redis is running in the same AZ or datacenter as Sidekiq.
If these values are close to 100,000, that means your Sidekiq process may be
CPU-saturated; reduce your concurrency and/or see https://github.com/mperham/sidekiq/discussions/5039
```
We are facing some weird issues with the sidekiq jobs. There is a job that does some procession and that job triggers some events after the completion of a particular amount of tasks. Those events are sent to the pusher library and that library sends those events to the browser and then the browser reloads the page to show the status of the job. But now we are facing some intermittent issues with this process. browser is not getting reloaded and in the logs, we are able to see the warning that I have mentioned above.

Can you please help us with this issue?

**Comment by amolbudkhe** [comment]
@mperham Sorry Didn't get you

**Comment by amolbudkhe** [comment]
Current concurrency is 1

**Comment by mperham** [comment]
It sounds like you have a job which is pegging the CPU for quite a while. Profile and tune it to run faster or split it up into smaller jobs.

**Comment by amolbudkhe** [comment]
But earlier we didn't face this issue.

**Comment by mperham** [comment]
I don't know what that means.

**Comment by mperham** [comment]
This warning was added in 6.2.0. What version did you upgrade from?

**Comment by amolbudkhe** [comment]
5.2.8

**Comment by mperham** [comment]
That version didn’t have this Redis health check. Ignorance does not mean your old system was healthy.

**Comment by nateberkopec** [comment]
Linking #5025
