### ISSUE TITLE
Sentineled redis with credentials for redis hosts

### ISSUE THREAD

**Issue by d3mash** [sidekiq/sidekiq#5896]
Hey, first of all thank you for all your work on Sidekiq 🙏 

I have the following issue with the gem:

When I use three redis sentinels like this:

```ruby
Sidekiq.configure_client do |config|    # and repeat this inside a Sidekiq.configure_server
  config.redis = {
    db: 0,
    name: "name",
    sentinels: [
      "sentinel://sentinel01.example.com:26379",
      "sentinel://sentinel02.example.com:26379",
      "sentinel://sentinel03.example.com:26379",
    ]
  }
end
```

I can't figure out how to add username/password credentials to the URL that the sentinel returns to the process. Is there a way for me to add connection options to the resulting URL?

**Comment by mperham** [comment]
This is a question for redis-client. https://github.com/redis-rb/redis-client#sentinel-support Usually password goes directly into the URL: `"sentinel://user:pwd@sentinel03.example.com:26379"
