### ISSUE TITLE
Configure sidekiq logs in test environment

### ISSUE THREAD

**Issue by paul-mesnilgrente** [sidekiq/sidekiq#5898]
Ruby version: 3.2.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.9

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```ruby
binding.pry
Sidekiq.configure_server do |config|
  binding.pry
  config.logger = Sidekiq::Logger.new($stdout)
end
```

The first `binding.pry` is called but not the second one in test environment. How do I customize the logger in tests to avoid noisy logging in rspec prompts?

**Comment by mperham** [comment]
Use configure_client.
