### ISSUE TITLE
Sidekiq-pro batch join hangs indefinitely on empty batch

### ISSUE THREAD

**Issue by sjahu** [sidekiq/sidekiq#5913]
Ruby version: 3.2.1
Rails version: 7.0.4.2
Sidekiq / Pro / Enterprise version(s): 7.1.0 / 7.1.1 / 7.1.0

Since #5678 was delivered in sidekiq-pro 7.1.1, trying to `join` on an empty batch causes Sidekiq to hang indefinitely.

```ruby
batch = Sidekiq::Batch.new
batch.jobs do
  # nothing
end
Sidekiq::Batch::Status.new(batch.bid).join

exit

# halts with sidekiq-pro 7.1.0; hangs indefinitely with sidekiq-pro 7.1.1
```

Prior to 7.1.1, this worked fine. Was this change intentional? If the goal is to make the behaviour of empty batches more predictable, I think joining on an empty batch should behave as before, especially if the addition of the "empty job" now allows callbacks to work with empty batches.

Or is there a better way to handle this situation?

Thank you!

---

I acknowledge relying on the previous undefined behaviour was risky due to the documented pitfalls 🙂

> Do not create a batch with no jobs as it will never fire callbacks or finish. Your code should explicitly handle that empty case to avoid creating a Batch unnecessarily. ([wiki](https://github.com/sidekiq/sidekiq/wiki/Batches#callbacks))

> Because empty batch behavior has long been documented as undefined, I don't have a problem changing the behavior outside of a major release. ([comment](https://github.com/sidekiq/sidekiq/issues/5678#issuecomment-1416506376))

**Comment by sjahu** [comment]
More details: from what I can tell, the way the new "empty job" functionality works is that an empty job is created which is actually processed by a Sidekiq worker, and not marked as complete until it's been processed.

So, you can still join on an empty batch, but you actually have to have a worker running for it to work, since the batch isn't _actually_ empty.

**Comment by mperham** [comment]
> So, you can still join on an empty batch, but you actually have to have a worker running for it to work, since the batch isn't actually empty.

That is correct and is the new behavior in 7.1.
