### ISSUE TITLE
Use configured default queue name for enqueuing Sidekiq::Batch::Empty

### ISSUE THREAD

**Issue by taylorthurlow** [sidekiq/sidekiq#5914]
In the situation where a default queue has been specified using the `default_job_options` method:

```ruby
Sidekiq.default_job_options = { queue: :my_queue_name }
```

Would you consider using this queue, if defined, to be the fallback queue that `Sidekiq::Batch::Empty` jobs are placed in? Currently the selected queue would be the batch's callback queue, and then defaulting back to `"default"`. I don't specify callback queues directly when setting up my batch callbacks so it looks like the callback queue is not explicit and therefore the empty batch job is queued in `default`. In my case this causes a small problem because I do not have a worker process running which processes the `default` queue.

**Comment by mperham** [comment]
Yeah, that seems reasonable.

**Comment by taylorthurlow** [comment]
@mperham I can see the changed code in sidekiq-pro (currently running 7.1.3) but I don't think its having the intended effect on my end. When determining the queue for the blank callback job, the code currently uses:

```ruby
Sidekiq.default_configuration[:queue]
```

This returns `nil` for me (as does the same with a string key accessor), where:

```ruby
Sidekiq.default_job_options["queue"]
```

Returns the correct queue name (which I set as a symbol not a string, which has not been a problem so far).

Unless I'm missing something else code-wise I don't see where `:queue` would return a non-nil value when called/accessed on a `Sidekiq::Config` instance.

**Comment by raybaxter** [comment]
I set that value in my initializer:
```
# Set queue for Sidekiq::Batch::Empty jobs
Sidekiq.default_configuration[:queue] = "my_queue"
```

I clarified this behavior in the [wiki](https://github.com/sidekiq/sidekiq/wiki/Batches#notes).

**Comment by mperham** [comment]
@taylorthurlow You're absolutely right. I mixed up the top-level Sidekiq::Config options hash for the default job options hash. Thank you for double checking my work!

```diff
           if @added.size == 0
-            cbq = callback_queue || Sidekiq.default_configuration[:queue] || "default"
+            cbq = callback_queue || Sidekiq.default_job_options["queue"] || "default"
```

**Comment by taylorthurlow** [comment]
Just happy to be able to help and give back in any way I can. 👍

**Comment by raybaxter** [comment]
Updated wiki to use string. @mperham That change will be in 7.1.4?

**Comment by mperham** [comment]
@raybaxter please leave this out of the wiki. Minor bugs like this don’t need to be cataloged.

**Comment by raybaxter** [comment]
@mperham I'm not sure what you mean. I think that in aggregate I'm documenting the desired behavior. https://github.com/sidekiq/sidekiq/wiki/Batches/_compare/eef2bc7d28a873588e349d9b936db189cce7068f...7a4de4f01f603b2a5b2200b275cf5299f20976ed

The intermediate change documented the short-lived symbol version, but there are no traces left of that.

**Comment by mperham** [comment]
@raybaxter I don't think S::Batch::Empty needs to be documented at all. I would say as of Pro 7.1, empty batches will fire callbacks immediately.

**Comment by raybaxter** [comment]
They don't fire callbacks if you don't have a `default` queue or specify an alternate queue. I'd been doing that via ``Sidekiq.default_configuration[:queue]`. 

Is some other mechanism preferred?

**Comment by mperham** [comment]
> They don't fire callbacks if you don't have a `default` queue or specify an alternate queue.

Sure, that's the bug. We don't need to document anything about it; the wiki documents features and their expected behavior. Set `callback_queue` for now until the next release to workaround the bug.

**Comment by raybaxter** [comment]
Got it. I was thinking that the bug was string versus symbol use of `queue` in the configuration.

**Comment by raybaxter** [comment]
This is not working in 7.1.4.

I am having `Sidekiq::Batch::Empty` jobs wind up in the `default` queue.

**Comment by mperham** [comment]
What do you see for `Sidekiq.default_job_options["queue"]`?

**Comment by raybaxter** [comment]
I have two services; both return "default". I had the relevant queues in "default_configuration."

**Comment by mperham** [comment]
Well, you need to change that value to your default queue or set callback_queue.
