### ISSUE TITLE
Deleting jobs not releasing uniqueness lock

### ISSUE THREAD

**Issue by gaffney** [sidekiq/sidekiq#5917]
Locks for uniqueness are being held on deleted jobs indefinitely.

As far as I can tell, I cannot re-enqueue these jobs without manually deleting `unique:` keys in Redis.

-----

Ruby version: 3.0.4
Rails version: 6.1.6
Sidekiq / Pro / Enterprise version(s): Enterprise 7.0.5

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

`initializers/sidekiq.rb`

```ruby
# frozen_string_literal: true

require "sidekiq/web"

Sidekiq::Enterprise.unique! unless Luna.env.test?

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
  config.redis = { url: ENV.fetch("REDIS_JOBS_URL", "redis://127.0.0.1:6379") }

  require "periodic_jobs"

  config.periodic(&PERIODIC_JOBS)
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch("REDIS_JOBS_URL", "redis://127.0.0.1:6379") }
end

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  Rack::Utils.secure_compare(
    ::Digest::SHA256.hexdigest(user),
    ::Digest::SHA256.hexdigest(ENV.fetch("SIDEKIQ_WEB_USER"))
  ) &
  Rack::Utils.secure_compare(
    ::Digest::SHA256.hexdigest(password),
    ::Digest::SHA256.hexdigest(ENV.fetch("SIDEKIQ_WEB_PASSWORD"))
  )
end

Sidekiq.strict_args!
```

`config/sidekiq.yml`:

```yml
---
concurrency: <%= ENV["SIDEKIQ_MAX_THREADS"] || 10 %>
queues:
  - default
  - mailers
  - push_notifications
  - active_storage_purge
  - active_storage_analysis
```

```ruby
class MyWorker < ApplicationWorker
  sidekiq_options retry: 4, unique_for: 10.minutes, unique_until: :start

  def perform
    puts("Did something")
  end
end
```

```ruby
[1] pry(main)> MyWorker.perform_at(1.hour.from_now)
2023-05-14T05:40:12.357Z pid=99296 tid=2bxo INFO: Sidekiq 7.0.6 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://127.0.0.1:6379"}
=> "cc6482c8f158653a16413e79"
[2] pry(main)> Sidekiq::ScheduledSet.new.find_job("cc6482c8f158653a16413e79")
=> #<Sidekiq::SortedEntry:0x00007f7bc50adcd0
 @args=nil,
 @item=
  {"retry"=>4,
   "queue"=>"default",
   "unique_for"=>"600",
   "unique_until"=>"start",
   "class"=>"MyWorker",
   "args"=>[],
   "jid"=>"cc6482c8f158653a16413e79",
   "created_at"=>1684042812.357878,
   "unique_token"=>"8d982f8f933f3f2544ab75fdaed6b9293ff3f6da",
   "unlocks_at"=>"1684047012.357109"},
 @parent=#<Sidekiq::ScheduledSet:0x00007f7bc50af148 @_size=1, @name="schedule">,
 @queue="default",
 @score=1684046412.357109,
 @value=
  "{\"retry\":4,\"queue\":\"default\",\"unique_for\":\"600\",\"unique_until\":\"start\",\"class\":\"MyWorker\",\"args\":[],\"jid\":\"cc6482c8f158653a16413e79\",\"created_at\":1684042812.357878,\"unique_token\":\"8d982f8f933f3f2544ab75fdaed6b9293ff3f6da\",\"unlocks_at\":\"1684047012.357109\"}">
[3] pry(main)> Sidekiq::ScheduledSet.new.each { |j| j.delete if j.klass == "MyWorker" }
=> nil
[4] pry(main)> Sidekiq::ScheduledSet.new.find_job("cc6482c8f158653a16413e79")
=> nil
[5] pry(main)> MyWorker.perform_at(1.hour.from_now)
2023-05-14T05:40:56.239Z pid=99296 tid=2bxo INFO: Skipping enqueue for MyWorker, not unique (lock held by JID cc6482c8f158653a16413e79)
=> nil
```

> **2023-05-14T05:40:56.239Z pid=99296 tid=2bxo INFO: Skipping enqueue for MyWorker, not unique (lock held by JID cc6482c8f158653a16413e79)**

```
gaffney backend % redis-cli
127.0.0.1:6379> KEYS *
1) "unique:8d982f8f933f3f2544ab75fdaed6b9293ff3f6da"
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

No fix in the changelog as far as I can tell.

**Comment by gaffney** [comment]
To be clear, even after the `unique_for` time, the issue persists. I am running into this issue with jobs I enqueued a week ago.

**Comment by mperham** [comment]
Can you give me a script which reproduces the behavior?

**Comment by gaffney** [comment]
Does the above not reproduce for you? I provided a minimal reproduction with the worker class and the pry.

Unless you are saying that the behavior in my repro is expected, but the "even after the `unique_for` time, the issue persists" is not?

**Comment by gaffney** [comment]
Something around my actions for this pushed our Redis CPU to 100% and caused a production outage, so clearly my idea of "manually deleting `unique:` keys in Redis" was not a very good idea. That or it was caused by simply deleting the unique jobs; unsure which. The last time this happened it was because Sidekiq was doing some `scan` operation continually looking for keys that do not exist... I am guessing that is the same issue here.

<img width="682" alt="image" src="https://github.com/sidekiq/sidekiq/assets/1113620/c42201ac-8390-4923-9dcd-7831b7e244c6">

_The last downspike is because we restarted Redis to mitigate._

**Comment by mperham** [comment]
Your console script is expected behavior. You didn't show the console waiting 10 minutes plus the unique_for time *includes* the scheduled delay, so it would be 70 minutes.

**Comment by gaffney** [comment]
> waiting 10 minutes plus the unique_for time _includes_ the scheduled delay, so it would be 70 minutes.

Oh... this may be what I was experiencing then. Just to make sure I am understanding:

- Job is enqueued to run in a week from now, has 10 minute uniqueness
- Job is deleted manually after, say, 10 minutes, e.g. `Sidekiq::ScheduledSet.new.each { |j| j.delete if j.klass == "MyWorker" }`

Is it expected behavior that we have to wait 1 week before we can enqueue that job again? If so what is your recommended workaround?

**Comment by mperham** [comment]
Well, the unique jobs feature adds a death_handler to remove locks for any job which has uniqueness and is killed. Oh, and I think your code needs to call `kill` rather than `delete`.

**Comment by gaffney** [comment]
Perfect, thank you!

That's a gotcha IMO but glad I know to use `kill` going forward.

Closing as it appears this is expected behavior.

_P.S. Deleted the ElastiCache metrics graph comment above as it turns out the cause was misattributed. The production issue was related to our usage of `scan`, which overwhelmed Redis when `Sidekiq::ScheduledSet` became large... not anything directly related to `unique_for` or `job.delete`._
