### ISSUE TITLE
Test helper to verify periodic job registration block doesn't seem to work

### ISSUE THREAD

**Issue by aliismayilov** [sidekiq/sidekiq#5918]
Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
Rails version:  7.0.4.3
Sidekiq / Pro / Enterprise version(s): 7.1.0 / 7.1.1 / 7.1.0

The new [test helper](https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md#710) to verify periodic jobs doesn't seem to work:
```ruby
require "sidekiq-ent/periodic/testing"
require "sidekiq-ent/periodic/config" # without this `Sidekiq::Periodic::ConfigTester.new` fails

VALID_CRON_BLOCK = ->(mgr) { mgr.register("0 0 * * *", "SomeJob") }
ct = Sidekiq::Periodic::ConfigTester.new
ct.verify(VALID_CRON_BLOCK)
/ruby/gems/3.2.0/gems/sidekiq-ent-7.1.0/lib/sidekiq-ent/periodic/testing.rb:17:in `verify': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

I believe the method signature of `Sidekiq::Periodic::ConfigTester#verify` should be `def verify(block)` instead of `def verify(&block)`.

Bonus point: would be nice if `sidekiq-ent/periodic/testing` would also require `sidekiq-ent/periodic/config`, so, we don't have to require 2 files to be able to instantiate `Sidekiq::Periodic::ConfigTester`.

**Comment by mperham** [comment]
Thanks for this. Of course my test suite required all of this stuff beforehand so I didn't catch any of it. The next release should work the way you wish.
