### ISSUE TITLE
Figure out if retries are exhausted in middleware

### ISSUE THREAD

**Issue by Linuus** [sidekiq/sidekiq#5919]
We have a server middleware which logs some information about jobs that run. We would like to add info about whether or not the retries are exhausted, but it's hard from the middleware. We need to check the job payload config, JobRetry defaults etc. to try and figure it out. And, at the end we can't be 100% sure because the job might have a `sidekiq_retry_in` block defined.

We could implement a death handler (they are always called, regardless of if they are sent to the dead set, right?), but then we'd get two different log lines. First we'd log information about the job in the middleware and then once in the death handler, which is not ideal for us.

So, I'm just wondering if there is any reliable way of knowing in the middleware if retries are exhausted or not?
If not, we'll just have to cope with one of the options above.

**Comment by mperham** [comment]
Save the retry count yourself in a custom client middleware. Compare it to the retry_count in a custom server middleware.

**Comment by Linuus** [comment]
> Save the expected retry count yourself in a custom client middleware. Compare it to the retry_count in a custom server middleware.

I don’t understand 🤔 How can we figure out the retries in a custom client middleware? It’s either the JobRetry default max, the globally configured max, retry config in job or decided by the `sidekiq_retry_in`. It doesn’t help to use a client middleware?

I guess it’s not really possible to know until you call the death handler really since the `sidekiq_retry_in` must be called.

**Comment by mperham** [comment]
Yeah I don't know if it's possible if `sidekiq_retry_in` usage must be allowed. You could restrict usage of that feature in your app, undef it as a monkeypatch, for instance.

**Comment by Linuus** [comment]
Ok thanks. Yeah I guess it's either accepting not to use `sidekiq_retry_in` or try to use the death handler instead.

Death handlers are always called, right? Even if the job won't be sent to the dead set?

**Comment by mperham** [comment]
Correct.
