### ISSUE TITLE
Shutdown signal and cleanup

### ISSUE THREAD

**Issue by dorongutman** [sidekiq/sidekiq#5921]
Ruby version: 2.7.8
Rails version: 6.0.6.1
Sidekiq / Pro / Enterprise version(s): 6.5.8 / 5.5.5 / 2.5.3

Let's assume the following sidekiq initialization portion:
```ruby
Sidekiq.configure_server do |config|
  config.on(:shutdown) do
    Rails.logger.debug("Received shutdown event")
    MyDatabaseDriver.disconnect_client_connections
  end
end
```

And the following worker:
```ruby
class MyJob
  include Sidekiq::Job

  def perform(*args)
    500.times do |i|
      puts "Iteration #{i}"
      do_some_db_work
      sleep 0.1
    end
  end
end
```

Once enqueued, the above job will run for about 50 seconds. If during these 50 seconds the sidekiq (server) worker process will receive a TERM signal, the `:shutdown` event will trigger immediately, causing the db connections to disconnect, but the running job will continue running code, including db queries for example, until it finishes running or we reach the timeout.

The above is just to prove a point and you might be saying that I should check on every iteration of the loop, but it could also be just a slow hard working job, that runs calculation and multiple queries with the database. 

It does seem that sidekiq "knows" when it's actually shutting down (after all running jobs completed) because there are logs lines once the timeout is reached, for example.

A real example of the above would be using sdk's like [Statsig](https://docs.statsig.com/server/rubySDK#initializing-statsig-when-using-unicorn-puma-passenger-or-sidekiq) or [Split.io](https://help.split.io/hc/en-us/articles/360020673251-Ruby-SDK#shutdown) or various others that require some kind of flushing or gracefully shutting down of background threads or closing connections for example.

**Comment by mperham** [comment]
Right, the shutdown callback is called when TERM is received. It's not guaranteed to run after all executing threads go quiet. You want to use `at_exit`.
