### ISSUE TITLE
Sidekiq PRO: Pause/Unpause buttons does not appear

### ISSUE THREAD

**Issue by guizaols** [sidekiq/sidekiq#5922]
Ruby version: **3.0.3**
Rails version: **7.0.4.2**
Sidekiq / Pro / Enterprise version(s): **PRO**

I've installed a Sidekiq PRO today but the `pause/unpause` button does not appear in the UI.
I added  the following and nothing works:
```
require "sidekiq-pro"
require "sidekiq/pro/api"
require "sidekiq/pro/web"
```

Here is my **sidekiq.yaml**
```yml
:scheduler:
  :dynamic: true
:verbose: false
:concurrency: 10
:logfile: ./log/sidekiq.log
:queues:
  - analytics
  - facebook
  - default
```

**Comment by mperham** [comment]
it should be there with that require. Screenshot?

require "sidekiq/pro/web"

**Comment by guizaols** [comment]
Here's the screenshot of `sidekiq.rb`

![Screenshot 2023-05-16 at 14 08 38](https://github.com/sidekiq/sidekiq/assets/1687999/096b5b3a-661e-4baf-96c1-4953a44f4a12)

**Comment by guizaols** [comment]
Sorry, my bad!

Here's the Web UI.
![Screenshot 2023-05-16 at 14 26 33](https://github.com/sidekiq/sidekiq/assets/1687999/10258433-1a51-4aa4-b683-cb3c0c09a316)

**Comment by guizaols** [comment]
I set a queue as `paused` via console and it showed the tag properly
![Screenshot 2023-05-16 at 14 56 03](https://github.com/sidekiq/sidekiq/assets/1687999/6d1eb903-2e79-4ef9-abde-a37f5a4f56e8)

**Comment by mperham** [comment]
What does `Sidekiq::Web.settings.views` return?

**Comment by guizaols** [comment]
> 

`/Users/guizaols/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/web/views`

**Comment by guizaols** [comment]
> If you open a Rails console, what does `Sidekiq.pro?` return?

`undefined method `pro?' for Sidekiq:Module (NoMethodError)`

**Comment by mperham** [comment]
You aren't requiring Sidekiq Pro. `require "sidekiq-pro"` or `bundle exec rails c`.

**Comment by guizaols** [comment]
It's not indeed! But there's a require in the initializer. I can create `batches` and look them at the UI. Any idea what could be?

**Comment by mperham** [comment]
Oh wait, you're using an old version which does not have the Pause button in the UI. That was added in v6.0.4. https://github.com/sidekiq/sidekiq/blob/main/Changes.md#604

**Comment by guizaols** [comment]
Thanks to reply @mperham
