### ISSUE TITLE
Job Metrics Histogram Values Appear to be Multiplied by 200.0

### ISSUE THREAD

**Issue by Aesthetikx** [sidekiq/sidekiq#5928]
Ruby version: 3.1.3
Rails version: 6.1.7.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.0.9

It appears that the histogram on the web ui job metrics page is not reflecting the bubble chart below. In my example, it appears that the job durations are multiplied by exactly 200. For example, hovering over the 'quickest' bubble indicates a single job finishing in 0.065 seconds. However, the 'quickest' histogram bar reports 1 job finishing in 13 seconds, which is 200.0 times higher.

![Screenshot 2023-05-19 at 11-34-09 Sidekiq](https://github.com/sidekiq/sidekiq/assets/1302406/80758587-445d-4b96-9d9a-0bcd95eadde0)

```
irb
irb(main):001:0> 13 / 0.065
=> 200.0
irb(main):002:0> 150 / 0.75
=> 200.0
irb(main):003:0> 100 / 0.5
=> 200.0
irb(main):004:0> 20 / 0.1
=> 200.0
```

I can dig in more if needed. I have not had time to review the code, beyond it presumably stemming from data coming from this line https://github.com/sidekiq/sidekiq/blob/0175cdbe03c3a9edf908a155ae6f006061b5c224/web/views/metrics_for_job.erb#LL8C2-L8C2.

**Comment by mperham** [comment]
Fixed in 710.
