### ISSUE TITLE
Gem Update issue when upgrading sidekiq and redis for Heroku setup.

### ISSUE THREAD

**Issue by yesh4gvm** [sidekiq/sidekiq#5934]
Ruby version: 2.6.6
Rails version: 4.2.8
Sidekiq / Pro / Enterprise version(s): 5.1.3

Issue when upgrading sidekiq to 5.2.8 version.

I have been noticed from Heroku as they are depricating there older version so upgrading Heroku Data for Redis version is done successfully but it says we need to upgrade redis gem (current-version: 4.0.3) . But for upgrading redis gem version to (4.8.1) it shows error in one of my specs which is been created for sidekiq jobs.

Although in same file of that specs there are various test case which falls or run though that worker but it works for them but only few them it get fails. (We are using Circle Ci jobs which automatically triggers after code push to particular branch)

Also one more thing after upgrading sidekiq to newer version 5.2.8 its shows redis-pipelined command logs which is kind of annoying.

Attachement of my gemfile and gemfile lock as this is files are now currently in working condition with older version which is currently working on my production app.

Thanks in advance.
[gemfile.docx](https://github.com/sidekiq/sidekiq/files/11583898/gemfile.docx)
[gemfile.lock.docx](https://github.com/sidekiq/sidekiq/files/11583899/gemfile.lock.docx)

**Comment by mperham** [comment]
I don't support Sidekiq 5 anymore.

If you choose to defer maintenance and not upgrade app dependencies for many years, you choose to accumulate technical debt which makes it more and more difficult to upgrade as time passes. After a few years, that upgrade process becomes painful for even maintainers like me to navigate. This is why we drop support for older versions. Good luck.
