### ISSUE TITLE
Sidekiq asset cache headers can cause cookie leaking via CDN

### ISSUE THREAD

**Issue by bessey** [sidekiq/sidekiq#5936]
Ruby version: 3.1
Rails version: 6.1
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.1

We recently ran into an issue where a Rails application served via CloudFront was leaking sessions between internal users 😬. After some triage I identified that Sidekiq's Web UI's assets were being cached, and these responses included the Rails session's Set-Cookie header.

The cause seems to be that the Web UI sets `Cache-Control: public, max-age=86400` on its asset headers, which as IIUC tells the browser **and CDNs** that they are good to cache the response. Admittedly, the fact these cookies are not in the CDN cache **key** is not Sidekiq's fault, but that is the default setting for AWS CloudFront's built in "CachingOptimized" policy:

<img width="1062" alt="Screenshot 2023-06-01 at 12 06 52" src="https://github.com/sidekiq/sidekiq/assets/708200/73b33c20-ce07-406c-8a39-c31dce98814f">

I am concerned that the way Sidekiq is configured right now is an unsafe default behaviour for common use cases. If you mount Sidekiq Web UI into a Rails app's router which, Web UI assets will respond with a session identifier and CDN friendly cache headers:

![image](https://github.com/sidekiq/sidekiq/assets/708200/a49445f2-68e9-417a-bf82-e7ee7783e765)

Unless you can prevent Rails sending Set-Cookie headers, I think this is an unsafe default? I don't know if its possible to suppress those this far down the stack in a way that is not tightly coupled to Rails. Another option might be to set `Cache-Control: no-cache="Set-Cookie"` which as I understand it is a [standards-based way to tell CDNs to exclude Set-Cookie from the cached response](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Cookies.html).

**Comment by mperham** [comment]
Thanks for discovering this and bringing it up. [This line](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/web.rb#L140) was initially borrowed from the Rack::Static documentation, here:

https://github.com/rack/rack/blob/main/lib/rack/static.rb#L85

I wonder if they would consider this an insecure suggestion. You might contact [Rack security](https://github.com/rack/rack/blob/main/SECURITY.md#reporting-a-security-issue) and ask their opinion.

**Comment by mperham** [comment]
In the future, please look for a security policy before opening a public issue. These issues can be sensitive.

https://github.com/sidekiq/sidekiq/blob/main/SECURITY.md#reporting-a-vulnerability

**Comment by bessey** [comment]
Hey @mperham, apologies for the less than responsible disclosure. I figured since its only Sidekiq + CloudFront + app with sensitive cookies it didn't merit a private disclosing, but that was not my judgement to make.

I'll reach out to Aaron for thoughts on this, per the Rack Security docs.

**Comment by mperham** [comment]
@tenderlove I certainly have no desire to send the Cookie header with static assets but that request handling is outsourced to Rack::Static [here](https://github.com/sidekiq/sidekiq/blob/726b58a7f6427a393d16acb9e5cbc95b550efc42/lib/sidekiq/web.rb#L143-L146). Should Rack::Static have an option to return "sanitized" responses which can be safely cached?

**Comment by tenderlove** [comment]
Who is setting the session cookie header?  Certainly not `Rack::Static`.  If a middleware above Rack::Static is the one setting the cookie, I'm not sure how Rack::Static could have any impact on it (or business messing with it).  If it's a middleware below Rack::Static, I could see Rack::Static removing the `Set-Cookie` header on the way out, but I suspect that isn't the case.

I think finding who is actually setting the Cookie header, and when, would be instructive.

**Comment by mperham** [comment]
Yeah, that's a good question. When I mount `Sidekiq::Web` in routes.rb and request a static asset, I see this:

```
% curl -I http://localhost:3000/sidekiq/images/logo.png
HTTP/1.1 200 OK
Last-Modified: Tue, 21 Feb 2023 16:23:56 GMT
Content-Type: image/png
Cache-Control: no-cache
X-Request-Id: 95f5a36e-e300-4752-b29c-307e4133bb60
X-Runtime: 0.019034
Server-Timing: sql.active_record;dur=1.56
Content-Length: 4143
```

When I run `Sidekiq::Web` via rackup with a simple `Rack::Session::Cookie` middleware, I get this:

```
% curl -I http://localhost:9292/images/logo.png        
HTTP/1.1 200 OK
Last-Modified: Tue, 21 Feb 2023 16:23:56 GMT
Content-Type: image/png
Cache-Control: public, max-age=86400, no-cache="Set-Cookie"
Content-Length: 4143
```

@bessey Can you supply a way to reproduce the response with Cookie header or tell us more detail about your Sidekiq::Web setup?

**Comment by pbstriker38** [comment]
I noticed that our sidekiq assets also have `public, max-age=86400` and I ran across this in another gem that we use.

https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/432

**Comment by bessey** [comment]
I knocked together an MVP reproduction https://github.com/bessey/sidekiq-devise-cdn-sec

To repro you need

- stock Rails 
- stock Devise
- stock Sidekiq
- a Devise constraint around the Sidekiq mount, [as shown in the Sidekiq Wiki](https://github.com/sidekiq/sidekiq/wiki/Monitoring#devise)

That's it. I couldn't repro with a different Rails routing constraint that writes to the session cookie, which surprised me. I haven't gone too deep though as its the end of my work day.
