### ISSUE TITLE
Backport additional `strict_args!` mode updates to v6.x

### ISSUE THREAD

**Issue by javierjulio** [sidekiq/sidekiq#5938]
There seems to have been several updates to the validations in the `strict_args!` mode in v7 that when addressed report no warnings but if running v6 with those corrections, in some cases the warnings are still reported. 

The `strict_args!` mode is very helpful but migrating to v7 isn't easy due to requirements outside of just Sidekiq (e.g. updating Redis version, also [recent stack error issue](https://github.com/sidekiq/sidekiq/issues/5920#issuecomment-1570546516)). It would be helpful to backport any `strict_args!` mode related changes to v6 to make it easier to migrate to v7 where it is required.

Using Sidekiq v6 with a job that takes a hash argument and expected corrections, still outputs a warning:

```
Loading development environment (Rails 7.0.5)
Ruby 3.0.5p211
>> Sidekiq::VERSION
=> "6.5.8"
>> class SampleWorker
  include Sidekiq::Worker
  def perform(params)
  end
end
SampleWorker.perform_async({ id: 1, type: "Sample", created_at: Time.now.utc.to_f }.stringify_keys)
{"ts":"2023-06-01T23:00:42.637Z","pid":79790,"tid":"1ju","lvl":"WARN","msg":"Job arguments to SampleWorker do not serialize to JSON safely. This will raise an error in\nSidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today\nby calling `Sidekiq.strict_args!` during Sidekiq initialization.\n"}
=> "a18422c18aae75b41f339fcf"
```

The same worker though on Sidekiq v7 does not report any warning, or since I didn't modify the default, no error is raised:

```
Loading development environment (Rails 7.0.5)
Ruby 3.0.5p211
>> Sidekiq::VERSION
=> "7.1.1"
>> class SampleWorker
  include Sidekiq::Worker
  def perform(params)
  end
end
SampleWorker.perform_async({ id: 1, type: "Sample", created_at: Time.now.utc.to_f }.stringify_keys)
{"ts":"2023-06-01T23:01:54.930Z","pid":79964,"tid":"1q8","lvl":"INFO","msg":"Sidekiq 7.1.1 connecting to Redis with options {:size=>10, :pool_name=>\"internal\", :driver=>:hiredis, :url=>\"redis://localhost:6379\", :network_timeout=>5, :id=>nil}"}
=> "bcf6ffc15ef9341bb293e316"
```

**Comment by javierjulio** [comment]
For more background, with all job corrections in place for `strict_args!` mode, we still get warnings in v6.5.8 for only two jobs. One job has a hash argument, and the other a time argument. Both were corrected with the same changes shown in the samples posted. No warnings are reported with all the same corrections on v7.1.1.

We know that some corrections on v6.5.8 are addressing warnings. We had one job that had a symbol argument that when converted to a string, it no longer reported a warning on that version.

The repeated warnings on v6 once corrected seems to only be caused by certain types is my guess.

**Comment by mperham** [comment]
I can't reproduce the issue:

```
irb(main):006:0> SampleWorker.perform_async({ id: 1, type: "Sample", created_at:
 Time.now.utc.to_f }.stringify_keys)
=> "1018d015ecabea7322a2c35d"
irb(main):007:0> Sidekiq::VERSION
=> "6.5.9"
irb(main):008:0> Sidekiq.strict_args!
=> :raise
irb(main):009:0> Sidekiq.strict_args!(:warn)
=> :warn
irb(main):010:0> SampleWorker.perform_async({ id: 1, type: "Sample", created_at: Time.now.utc.to_f }.stringify_ke
ys)
=> "7d1499607f83c494c902cf86"
irb(main):011:0> 
```

**Comment by javierjulio** [comment]
I noticed it didn't always appear. Based on other recent issues (linked in description) it seems to do with Oj. 😔 I cannot replicate the issue on Sidekiq v6 but if we use this Oj initializer the warning appears once but on repeated attempts it does not.

With a `config/initializers/oj.rb` file:
```
Oj.optimize_rails
Oj.default_options = { mode: :rails }
```

In a rails console on another project with Sidekiq v6 and Oj:
```
Loading development environment (Rails 7.0.5)
Ruby 3.0.5p211
>> Sidekiq::VERSION
=> "6.5.7"
>> class SampleWorker
  include Sidekiq::Worker
  def perform(params)
  end
end
SampleWorker.perform_async({ id: 1, type: "Sample", created_at: Time.now.utc.to_f }.stringify_keys)
2023-06-02T18:26:01.761Z pid=16847 tid=n8j WARN: Job arguments to SampleWorker do not serialize to JSON safely. This will raise an error in
Sidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today
by calling `Sidekiq.strict_args!` during Sidekiq initialization.

=> "196a5c297889ac89cb080fb0"
>> class SampleWorker
  include Sidekiq::Worker
  def perform(params)
  end
end
SampleWorker.perform_async({ id: 1, type: "Sample", created_at: Time.now.utc.to_f }.stringify_keys)
=> "2862f3999d793f77f4085389"
>> class SampleWorker
  include Sidekiq::Worker
  def perform(params)
  end
end
SampleWorker.perform_async({ id: 1, type: "Sample", created_at: Time.now.utc.to_f }.stringify_keys)
=> "e84986125ceb08dd44aac894"
```

**Comment by mperham** [comment]
I understand. Oj is listed as a troublesome gem in the wiki so I'm not going to support it. I would advise you to remove it and use stdlib json.
