### ISSUE TITLE
Usability improvement for setting up Periodic Jobs

### ISSUE THREAD

**Issue by bmulholland** [sidekiq/sidekiq#5945]
I accidentally configured periodic jobs in the client config block, not the server config block. I got a warning about a missing constant, but I figured that was something else and added a manual require of `sidekiq-ent/periodic/config`. Then I ran the code and wondered why it didn't work :)

Could there be a check when using `.periodic` in `configure_client` that throws an error saying "wrong block, use server instead." ? It's a small improvement that might save others time.

**Comment by mperham** [comment]
I don't feel super strongly either way but I think the existing warnings are probably sufficient.

**Comment by bmulholland** [comment]
Sure. FWIW, the only "warning" I saw was "uninitialized constant Sidekiq::Periodic::Config"
