### ISSUE TITLE
ENT - Sidekiq periodic manager runs on wrong queue

### ISSUE THREAD

**Issue by theobarango** [sidekiq/sidekiq#5947]
Ruby version: 3.0.5
Rails version: 6.1
Sidekiq / Pro / Enterprise version(s): 6.4.1

This is more of a question. I've noticed in our logs that on a certain queue where our really critical workers are typically run, we see logs like the following `Enqueued periodic job <SomeJobClass> with JID cb4dc7a2b41eb7588939eadb for 2023-06-19 16:56:00 +0000`, and my guess is this is coming from the Sidekiq manager that we've setup in `sidekiq.rb` initializer (please correct me if i'm wrong).

My question is, why does this manager run on this queue?
The [docs](https://github.com/sidekiq/sidekiq/wiki/Ent-Periodic-Jobs) don't specify how to set the queue for the manager to run, so how does it decide? 

Thanks.

**Comment by mperham** [comment]
Each job says which queue it should go into. The manager does not decide the queue, the job metadata tells it which queue to use.

**Comment by mperham** [comment]
Some examples of how you can specify the queue for a job:

```ruby
class SomeJobClass
  sidekiq_options queue: "foo"
```

```ruby
SomeJobClass.set(queue: "foo").perform_async(...)
```

```ruby
mgr.register("* * * * *", "SomeJobClass", queue: "foo")
```

**Comment by theobarango** [comment]
Hi @mperham thanks for getting back to me, but that's not exactly what i'm asking. I'm aware of how to set the queue for a periodic job. But it would seem that the manager it self that queues these periodic jobs spits out logs into a queue that i'm not sure how it got access to.

Looking in the source code, i can see that the following log `Enqueued periodic job #{cycle.klass} with JID #{jid} for #{ts}` comes from `sidekiq-ent-2.2.3/lib/sidekiq-ent/periodic/manager.rb`. 

My question is, why am i seeing this log in a queue that i didn't give the sidekiq manager access to? Especially also as `#{cycle.klass}` (or whatever job the manager just enqueued) is not supposed to be in this particular queue. 

**Sidenote:** In `sidekiq.rb` when registering this job as a periodic job, we don't set the queue. And the job klass also doesn't have a `queue` set either. I'm thinking it _should_ go to the default queue in this case.

**Comment by mperham** [comment]
I have no idea what you mean wen you say "spits out logs into a queue". Sidekiq logs to stdout. Any redirection of log output is up to you.

**Comment by theobarango** [comment]
My fault, maybe my expression is not very clear. 

By "spits out logs into a queue" i just mean that in our datadog logs that are segmented by the sidekiq queues, i see these `Enqueued periodic job...` logs in the logs meant for a queue that it shouldn't be in. 

And since these logs are triggered from `sidekiq-ent-2.2.3/lib/sidekiq-ent/periodic/manager.rb:188`, i figured that ok maybe the manager was somehow running in this queue, which led to my question.

**Comment by mperham** [comment]
That log message is not associated with any particular queue. Maybe that's the misunderstanding/issue here.
