### ISSUE TITLE
Batches in testing mode

### ISSUE THREAD

**Issue by matteeyah** [sidekiq/sidekiq#5953]
Ruby version: 3.2.2
Rails version: 7.0.5.1
Sidekiq / Pro / Enterprise version(s): Pro

```ruby
# frozen_string_literal: true

Sidekiq.configure_server do |config|
  config.redis = {
    url: ENV.fetch('REDIS_URL', 'redis://localhost:6379'),
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
  }
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: ENV.fetch('REDIS_URL', 'redis://localhost:6379'),
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
  }
end
```

When I run a job that creates a batch inline (via Sidekiq or ActiveJob) the batch always gets persisted to Redis. If Sidekiq is in testing mode and pushing to Redis is disabled (via `.fake!` or `.inline!`), I'd expect that the batches also don't go to Redis and have some kind of in-memory implementation instead.

I don't actually even care about persisting the batch anywhere, I'm only interested in not persisting them to Redis.

**Comment by mperham** [comment]
Batches always use Redis. There is no in memory mode.

**Comment by matteeyah** [comment]
@mperham Yeah, I understand, but what I'm saying is - this makes it difficult to test code that schedules batches without polluting the environment. Having an in-memory option would exclude Redis for being a requirement for the test environment, which is a convenience bonus.

Maybe an alternative solution could be to provide an API that removes all batches from Redis - which we could call in the test teardown.

**Comment by mperham** [comment]
We have that, it's called `redis.flushdb`. 😃

**Comment by matteeyah** [comment]
Doesn't that flush the whole Redis database? (Including the keys that were set in development). The idea is to just remove the keys that were set during the tests, not everything.

Redis _does_ support multiple databases, but the general consensus (incl. an email from the Redis author - https://groups.google.com/g/redis-db/c/vS5wX8X4Cjg/m/8ounBXitG4sJ) is that multiple databases shouldn't be used at all.

This means that we'd have to set up two separate Redis instances - one for development and one for testing, which just complicates things considerably.

---

In comparison, a database is easier to clean, since we can have multiple databases on a single Postgres instance, which is not the case for Redis (see above).

**Comment by mperham** [comment]
Yes, that’s what we want here: we want to reset all sidekiq state after each test.

antirez didn’t like the feature because it makes replication and clustering much harder, but none of that matters here. We are using Redis only for local testing, so use databases.
