### ISSUE TITLE
Unpredictible Sidekiq::Batch::Immutable

### ISSUE THREAD

**Issue by GSoustradeIceberg** [sidekiq/sidekiq#5954]
Ruby version: 3.2.0
Rails version: 6.1.7.3
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.1.1 + Sidekiq Pro 7.1.3

Initializer & sidekiq service :
[sidekiq@_service.txt](https://github.com/sidekiq/sidekiq/files/11892498/sidekiq%40_service.txt)
[initializers_sidekiq_rb.txt](https://github.com/sidekiq/sidekiq/files/11892499/initializers_sidekiq_rb.txt)

Dear Sidekiq team,

Inside a multistep calculation pipeline, with each step being a separated Sidekiq::Batch, we are facing an issue with errors Sideliq::Batch::Immutable. Those errors seem to pop randomly and will retry forever. The consequence for us is that with each retry of that error, our calculation pipeline is launched another time and we end up with multiple identical calculations going at the same time.

This error seems to be fired by a job inside of the batch, it seems to be the last operation done in the batch, I guess to handle its life cycle. But I don't understand why the batch is already immutable at the moment this operation is made.
Here you will find a screenshot of a problematic batch view : 
![sidekiq_immutable_issue](https://github.com/sidekiq/sidekiq/assets/137999901/e69046a6-0980-4b2f-a9d6-fd9e301d3f16)

We always had this issue from time to time, but it became more intense as we enhanced our ressources (number of parallel servers) and the calculations load.
I looked for oom-kills, or maybe redis overload but I couldn't find anything ; our servers RAM and I/O disks for the sidekiq services and the redis service seem fine.
Please tell me if I can provide any useful information.

Thank you very much.

**Comment by mperham** [comment]
You need to show me the code that is adding jobs to the batch and the full backtrace.

**Comment by GSoustradeIceberg** [comment]
Launching a batch is done this way : 

```
def launch
  @batch = self.prepare_batch
  self.launch_batch
end
```

The above methods definitions are : 

```
      def prepare_batch
        batch = Sidekiq::Batch.new
        batch.callback_queue = 'callbacks'
        batch.description = "xxx"

        batch.on(:success, 'EntityCalculationPipeliner::CalculationSteps::GenericCallback#generic_success', self.get_callback_options)
        batch.on(:death, 'EntityCalculationPipeliner::CalculationSteps::GenericCallback#generic_death', self.get_callback_options)

        return batch
      end
```


```
      def launch_batch
        @batch.jobs do
          @eltA_list.each do |eltA|
            eltB_list.flat_map do |eltB|
              job_args = [calculation_id, eltA, eltB, @current_step]
              CalculationPipeline::ComputeResultAWorker.set(queue: 'slow').perform_async(*job_args)
            end
          end
        end
      end
```

The workers are structured like this : 


```
class ComputeResultAWorker < BaseWorker
  def perform(....)
    super(...) do
     *calculations*
    end
  end
```

And the super from the BaseWorker is : 

```
  def perform(xxx)
    return if batch.present? && !valid_within_batch?

    begin
      yield
    rescue ZeroDivisionError, Exceptions::XXXCustomError => e
      Notifier::Notification.new(message: "xxx").send
    rescue Sidekiq::Batch::Immutable => e
      Notifier::Notification.new(message: "Ignored immutable batch error for xxx : #{e.message}").send
    end
  end
```

As you can see, I already tried to rescue the Immutable batch error, but it never catches it, meaning (I think) that the error is fired from an operation inside sidekiq, and not our code. Therefor, I never succeed in finding a backtrace.. I'm all ears if you may have a way.

Thank you for your time.

**Comment by mperham** [comment]
Looks fine. Maybe your error is coming from one of the two callbacks. Can you show me that code?

**Comment by GSoustradeIceberg** [comment]
Sure.

```
      def generic_success(status, options)
        options = options.with_indifferent_access
        current_step = options[:current_step]
        computation.launch_next_step(current_step, options: options)
      end
```
launch_next_step will simply call .launch (given in the previous message) for the next calculation step


```
      def generic_death(status, options)
        * only ActiveRecord find_by queries and slack notifications sending *
      end
```


Also, I forgot something before

The BaseWorker which all workers inherit from also includes the following things : 

```
class EntityCalculationPipeline::BaseWorker
  prepend BasicWorker
  include Sidekiq::Worker
  sidekiq_options(queue: :slow, retry: 5, backtrace: true)

  def perform(xxx)
    return if batch.present? && !valid_within_batch?

    begin
      yield
    rescue ZeroDivisionError, Exceptions::XXXCustomError => e
      Notifier::Notification.new(message: "xxx").send
    rescue Sidekiq::Batch::Immutable => e
      Notifier::Notification.new(message: "Ignored immutable batch error for xxx : #{e.message}").send
    end
  end
```


And the BasicWorker (sorry it's a bit a mess..) is the following : 

```
module BasicWorker

  def perform(*args, &block)
    super(*args, &block)
    GC.start
    # Compact ruby heap page allowing better memory organisation for freeing memory
    # Ressource: https://jemma.dev/blog/gc-compaction
    GC.compact
  end

end
```

**Comment by mperham** [comment]
> As you can see, I already tried to rescue the Immutable batch error, but it never catches it, meaning (I think) that the error is fired from an operation inside sidekiq, and not our code. Therefor, I never succeed in finding a backtrace.

I don't understand. How do you know you are getting the error if you can't find an instance of the error reported somewhere?

I don't see any smoking guns here. Only a full backtrace will show us exactly where the error is triggered in your code.

**Comment by GSoustradeIceberg** [comment]
Thank you for checking our code.
The thing with this error is that it seems to be fired out of any worker and therefore I cannot catch it at any level in my code. I can only see it in the retrys but without a stacktrace. Unless there is a way to get the stacktrace from a retry with console commands or inside the sidekiq UI ? I will look into that and try my best to provide you with the stacktrace.

**Comment by mperham** [comment]
That backtrace indicates that the batch was deleted via API. It's not safe to delete a batch while its jobs still exist in the queues.

**Comment by GSoustradeIceberg** [comment]
I was able to find the code piece which deleted the batches (with an invalidate_all)

Thank you for your help !

**Comment by GSoustradeIceberg** [comment]
It's just wierd that job kept living / retrying after calling invalidate_all. I checked on redis directly and they seem to be tagged as 'orphans'.

**Comment by mperham** [comment]
Sounds like Sidekiq Pro might have rescued some orphaned jobs due to process crash?

**Comment by GSoustradeIceberg** [comment]
@mperham Indeed we have a general issue of jobs getting orphaned and thus having batches with ghost pendings, never ending. However we already use the feature config.super_fetch!, which tries to tackle this behavior if I understood well. Shall I open a new issue about this ? Or is this a known bias that we have to bear for now ? 

Thank you,

**Comment by mperham** [comment]
Orphaned jobs are almost always due to incorrect deploy code. The Deployment wiki page tells you how to correctly deploy. Make sure your scripts are following those rules.

**Comment by GSoustradeIceberg** [comment]
Alright I will check our code thank you.
