### ISSUE TITLE
Freshen up Sidekiq.org

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#5957]
The website looks a little rough on phone and tablet. Code is on the gh-pages branch. Can I pay someone for a few hours of CSS work to improve the design?

![image](https://github.com/sidekiq/sidekiq/assets/2911/d50e6bbd-9536-42cb-93c4-901c63703f2e)

![image](https://github.com/sidekiq/sidekiq/assets/2911/43d2a85a-fb7c-41be-a1c0-dd9bcd4f29d1)

**Comment by Script47** [comment]
Did you have something in mind or was it more of a general tidy up of the phone/tablet experience?

**Comment by mperham** [comment]
I’m happy with the content and general look, just wanted a better tablet/phone experience.

**Comment by Script47** [comment]
I'll reach out to you over email, if that's alright.
