### ISSUE TITLE
Documentation for sidekiq embedded with passenger

### ISSUE THREAD

**Issue by n-studio** [sidekiq/sidekiq#5959]
This article (https://www.mikeperham.com/2022/10/27/sidekiq-7.0-embedding/) states that sidekiq embedded can be used on passenger, but I was unable to find documentation to do so.

Would it be possible to add documentation on how to use sidekiq embedded with passenger?

Thank you!

**Comment by mperham** [comment]
Did you look at the Embedding wiki page?

**Comment by n-studio** [comment]
That's embarrassing...
I didn't, and it was all there: https://github.com/sidekiq/sidekiq/wiki/Embedding

Sorry for the useless issue 🥲

**Comment by mperham** [comment]
Cool, it’s a good reminder to me that I should link to the wiki page! 👍🏻
