### ISSUE TITLE
Sessions between Sinatra apps

### ISSUE THREAD

**Issue by dshorthouse** [sidekiq/sidekiq#5960]
I'm trying to figure out how to have Sidekiq::Web honour a session in a Sinatra app & kick it out if not met. My Sinatra `APP` is modular and uses `Rack::Session::Cookie` as well as `Rack::Protection::AuthenticityToken`. When I have:

```
run Rack::URLMap.new('/' => APP, '/admin/sidekiq' => Sidekiq::Web)
```
...in config.ru, it doesn't matter if there's an active session or not. `/admin/sidekiq` is accessible. How might I ensure that the session established in my `APP` is the very same one used for `/admin/sidekiq`?

As a work-around, I could forget about `/admin/sidekiq` entirely, but it's such a lovely interface that I'd hate to toss a great UI when clearly so much effort & care has gone into it.

Much appreciation for pointers.

**Comment by mperham** [comment]
You'll need to show me how you're setting up the rack app and its middlewares.

**Comment by dshorthouse** [comment]
Thanks @mperham for the prompt response. As you may have been able to surmise from my `/admin/sidekiq` path above, it really wasn't a session I was inquiring about. Rather, I was trying to figure out how to make use of the *roles* established in my Sinatra `APP`. And so, I made great use of `Sidekiq::Web.register` to register my own module and it worked like a charm. You may close this one as it had nothing to do with the functionality of Sidekiq web, just my own ineptitude.
