### ISSUE TITLE
unique_for not working as expected

### ISSUE THREAD

**Issue by sos4nt** [sidekiq/sidekiq#5962]
Ruby version: 3.0.4
Rails version: 7.0.6
Sidekiq **Enterprise** version: 7.1.1

We're running a periodic job once every 2 minutes: (that's a lot, I know)

```ruby
Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    mgr.register('*/2 * * * *', 'VeryFrequentJob')
  end
end
```

To ensure that no two jobs are running concurrently, we added `unique_for` as a safeguard with a generous value of 10 minutes:

```ruby
class VeryFrequentJob
  include Sidekiq::Job
  sidekiq_options unique_for: 10.minutes

  def perform(...)
    # ...
  end
end
```

Sometimes, the periodic jobs are not executed and pile up. I assume this is because of Sidekiq shutting down due to a deployment. When this happens, all piled up jobs are executed at once as soon as Sidekiq starts processing them. Here's an excerpt from our log, just showing the 2-minute job:

<img width="295" alt="Bildschirmfoto 2023-07-04 um 12 30 08" src="https://github.com/sidekiq/sidekiq/assets/28232/16253877-ac52-452b-840c-3ef056a8452c">

As you can see, the job is executed regularly at 08:18, 08:20, and 08:22. It's _not_ executed at :24, :26, :28, :30, :32, :34, :36, and :38 (8 times) an instead gets executed 8 times at 08:39 before continuing the usual schedule.

I don't mind the jobs piling up, that's somehow expected. I'm just surprised that `unique_for` did not stop the 8 jobs from running concurrently. Or from being scheduled in the first place.

We have implemented a global mutex now to solve this specific situation. But I'm still curious what's going on here and what `unique_for` actually does / prevents and when to use it? I'm also interested in best practices to your problem: running a periodic job in a non-overlapping way.

**Comment by mperham** [comment]
Use the Expiring Jobs feature instead.

**Comment by mperham** [comment]
I’m not sure why the uniqueness feature is acting so strange for you. If you enqueue or schedule one, it should not allow another job to enqueue within 10 minutes until that job runs.

**Comment by sos4nt** [comment]
> If you enqueue or schedule one, it should not allow another job to enqueue within 10 minutes until that job runs.

Since we don't schedule this job manually at all, I suspect a problem / bug (?) with the period job feature.

**Comment by mperham** [comment]
What does your intiializer look like?

**Comment by aria-grande** [comment]
@sos4nt specifying the unqiue_for option when you register a periodic job will work!
```
  mgr.register('*/2 * * * *', 'VeryFrequentJob', unique_for: 3.minutes)
```

**Comment by swalke16** [comment]
Watching this thread as while we are still gathering data (slowed down by the holidays) I think we may be seeing something similar.  Sidekiq enterprise 7.2.2. 

We have a job that is `unique_for: 6.hours` that is scheduled to run at a specific time on the day following the day on which it is enqueued.  At some point in that day if the scheduler job that enqueues that job runs again we see duplicates with the same args and unique token in the scheduled set. 

I'm wondering if for future scheduled jobs it's not preventing enqueuing a duplicate if the time is past the `unique_for` period of the scheduled job?  

Still digging and will provide more info as I find it, but putting this out here early in case it ends up being helpful.

**Comment by mperham** [comment]
Don’t hop into other issues. Open your own. Closing for staleness.
