### ISSUE TITLE
Can I create two sidekiq servers in a rails application

### ISSUE THREAD

**Issue by Bhumika2015** [sidekiq/sidekiq#5965]

**Comment by mperham** [comment]
You can create as many Sidekiq processes as you need, one per CPU.

**Comment by Bhumika2015** [comment]
Processes or Servers ?

**Comment by mperham** [comment]
Define server? You can have as many machines running as many processes as you want, as long as they are all talking to the same Redis.

**Comment by Bhumika2015** [comment]
Sever means different and completely independent of one another.

**Comment by Bhumika2015** [comment]
I know we can have multiple processes and they will run on a same redis server. I want to create 3 independent servers like three different instances for all the servers.

**Comment by mperham** [comment]
Yes you can.

**Comment by Bhumika2015** [comment]
okay thanks.
I am getting some initialisation error after running jobs. I am getting this error.

`{"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[{"email":"ram@yopmail.com","name":"ewdewdwe bindal","fields":{"last_name":"bindal","country":null}}],"class":"MailerLite::MailerLiteWorker","jid":"16616441701ec649fc939d29","created_at":1689062788.4682937,"enqueued_at":1689069076.0530984,"error_message":"uninitialized constant MailerLite","error_class":"NameError","failed_at":1689062788.4702806,"retry_count":7,"retried_at":1689065360.2906117},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"args\":[{\"email\":\"ram@yopmail.com\",\"name\":\"ewdewdwe bindal\",\"fields\":{\"last_name\":\"bindal\",\"country\":null}}],\"class\":\"MailerLite::MailerLiteWorker\",\"jid\":\"16616441701ec649fc939d29\",\"created_at\":1689062788.4682937,\"enqueued_at\":1689069076.0530984,\"error_message\":\"uninitialized constant MailerLite\",\"error_class\":\"NameError\",\"failed_at\":1689062788.4702806,\"retry_count\":7,\"retried_at\":1689065360.2906117}"}
2023-07-11T09:51:16.061Z pid=703023 tid=gp90sycu7 WARN: NameError: uninitialized constant MailerLite
`

**Comment by mperham** [comment]
That sounds like a standard Rails error.

**Comment by Bhumika2015** [comment]
yes sounds like the same but I am not able to get reason for this error.

**Comment by dlynam** [comment]
Make sure the MailerLite gem is installed and restart Sidekiq.
