### ISSUE TITLE
Sidekiq::Limiter when OverLimit does not handle Sidekiq::Batch jobs correctly

### ISSUE THREAD

**Issue by mcheemaa** [sidekiq/sidekiq#5971]
Ruby version: 2.7.5
Sidekiq / Pro / Enterprise version(s): 6.5.6 / 5.5.4 / 2.5.2

I have added a code snippet below for understanding as well - 

```
# where issue is happening

class MyClass
  def call(group_id, item_ids)
    sidekiq_batch = Sidekiq::Batch.new
    sidekiq_batch.description = "Performing MyTaskJob for group_id #{group_id}"
    sidekiq_batch.on(:complete, MyTaskCallback, { 'group_id' => group_id })

    sidekiq_batch.jobs do
      item_ids.each do |item_id|
        MyTaskJob.perform_async(item_id)
      end
    end
  end
end


class MyTaskJob
  include Sidekiq::Worker
  sidekiq_options queue: 'my_task_queue'

  def perform(item_id)
    item = Item.find_by(id: item_id)

    limiter_options = { wait_timeout: 15, lock_timeout: 30, ttl: 4.days }
    limiter_name = "item-process-#{item.team_id}"
    concurrency = 1
    Sidekiq::Limiter.concurrent(limiter_name, concurrency, limiter_options).within_limit do
      process_item(item)
    end
  end

  def process_item(item)
    # Perform task here
  end
end

# our in house fix for this

class MyTaskJob
  include Sidekiq::Worker
  sidekiq_options queue: 'my_task_queue'

  def perform(item_id)
    item = Item.find_by(id: item_id)

    limiter_options = { wait_timeout: 15, lock_timeout: 30, ttl: 4.days }
    limiter_name = "item-process-#{item.team_id}"
    concurrency = 1
    Sidekiq::Limiter.concurrent(limiter_name, concurrency, limiter_options).within_limit do
      process_item(item)
    end
  rescue Sidekiq::Limiter::OverLimit => e
    # keeping existing behavior of retrying
    raise e unless bid.present?

    # if batch_id is present we want to retry the job in the same batch
    sidekiq_batch = Sidekiq::Batch.new(bid)
    sidekiq_batch.jobs do
      MyTaskJob. Sends::ProcessJob.perform_in(15.seconds, item_id)
    end
  end

  def process_item(item)
    # Perform task here
  end
end
```

### Discussed in https://github.com/sidekiq/sidekiq/discussions/5970

<div type='discussions-op-text'>

<sup>Originally posted by **mcheemaa** July 12, 2023</sup>
**Background -**

We have a use case where we are creating multiple jobs per row from a csv inside a Sidekiq::Batch and triggering an action in the on_complete callback. We can not use the on_success callback as some jobs can fail with actual errors so we want all jobs to be completed before triggering the callback as the on_success callback does not get triggered even if 1 of 100 jobs fail so if 99 jobs pass and 1 actually failed we want to trigger the on_complete callback to do some action. 

**Issue -**

The issue comes when we have a` Sidekiq::Limiter.concurrent ` inside the batch job and it errors out with Sidekiq::Limiter::OverLimit and multiple workers try different jobs once the callback thinks that the job was completed at least once. 

However, I am thinking that the job to be retried if it was from a batch and errored out due to the concurrency limit should be added back to the parent batch that the job came from so in reality the on_complete will not get triggered for this Sidekiq::Limiter::OverLimit error and the job will be retried inside the batch - only triggering the callback once the job was actually performed once. 

We have thought about maybe creating a custom solution to pass the `batch_id`, rescue `Sidekiq::Limiter::OverLimit` error and re enqueue the job inside the existing batch and create an incremental delay logic on our end, but I am just wondering if there is a solution for this already that someone has already found or if sidekiq thinks this will be a possible enhancement to the batches or concurrency limiter. 

I can add more details if this above does not make sense or if anyone wants to talk about it more. 
</div>

**Comment by mcheemaa** [comment]
added more details - thanks

**Comment by mperham** [comment]
You need to verify that the S::B::Server middleware comes after the S::L::Server middleware in the server chain. It's possible the middleware are getting out of order in the chain somehow. Use "sidekiq -v" to print out the chains on startup.

**Comment by mperham** [comment]
For instance this is what it prints for me:

```
2023-07-13T05:51:04.895Z pid=10247 tid=76z DEBUG: Server Middleware: Sidekiq::Metrics::Middleware, Sidekiq::Limiter::Middleware, Sidekiq::Enterprise::Unique::Server, Sidekiq::Batch::Server, Sidekiq::Enterprise::Crypto::Server
```

**Comment by mcheemaa** [comment]
@mperham seems like it is in the correct order for us 

<img width="737" alt="Screenshot 2023-07-12 at 11 08 57 PM" src="https://github.com/sidekiq/sidekiq/assets/54610255/5a338dd9-e01d-4a19-adc9-6b570d5b62af">


i used the code below to print it through the initializer

``` 
config.on(:startup) do
    puts "Server Middleware:"
    config.server_middleware do |chain|
      chain.entries.each do |entry|
        puts "  -> #{entry.klass}"
      end
    end
    puts "Client Middleware:"
    config.client_middleware do |chain|
      chain.entries.each do |entry|
        puts "  -> #{entry.klass}"
      end
    end
  end
```

**Comment by mcheemaa** [comment]
I think the issue here is that `Sidekiq::Limiter` raises the error - `Sidekiq::Limiter::OverLimit` - to retry a job when it is over limit which makes the callback think that the code inside the job was at least executed once where as in reality the job was never completed once - if that makes sense. It should in reality not trigger the on complete callback when overlimit is hit but rather trigger the on complete callback when a job is completed once. So in our case we keep on adding the same job as a new job to the batch so the batch on_complete callback does not get triggered until the job is actually completed once. Let me know if this makes sense at all 😄

**Comment by mperham** [comment]
That's just how the system works. The job was executed and raised an error. That will trigger the complete callback ad OverLimit is not treated specially. I think your workaround is reasonable.
