### ISSUE TITLE
Sidekiq::Workers API - returning a string worker object instead of a hash

### ISSUE THREAD

**Issue by kapso** [sidekiq/sidekiq#5973]
Ruby version: 3.2.2
Rails version: 7.0.6
Sidekiq / Pro / Enterprise version(s): Sidekiq v7.1.2 / Pro v7.1.3

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
```ruby
require 'sidekiq/pro/web'
require 'sidekiq-scheduler'
require 'sidekiq-scheduler/web'

Sidekiq.configure_client do |config|
  config.redis = { url: Settings.redis.url, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
  config.logger.level = Rails.env.development? ? Logger::INFO : Logger::WARN
end

Sidekiq.configure_server do |config|
  config.redis = { url: Settings.redis.url, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
  config.logger.level = Rails.env.development? ? Logger::INFO : Logger::WARN

  # Default is 5
  config.average_scheduled_poll_interval = 2

  config.on(:startup) do
    Sidekiq.schedule = YAML.safe_load(ERB.new(Rails.root.join('config/schedule.yml').read).result)
    SidekiqScheduler::Scheduler.instance.reload_schedule!
  end
end
```

**Issue**:
I have the following code running inside a Sidekiq worker...
```ruby
Sidekiq::Workers.new.each do |_process_id, _thread_id, worker|
  count += 1 if worker && worker['queue'] == 'portfolio' && worker.dig('payload', 'args')&.first == @portfolio.id
  return true if count > 1
end
```
But intermittently I run into this error - `String does not have #dig method (TypeError)`

This worker gets retried obviously, and then the error goes away.

**Comment by hernanat** [comment]
not sure if this is related, but when I install sidekiq 7.1.2 the pegged version of the redis gem (4.5.1) has [this](https://github.com/redis/redis-rb/blob/v4.5.1/lib/redis.rb#L3647) implementation for its `Hashify` lambda:

```ruby
  Hashify = lambda { |value|
    if value.respond_to?(:each_slice)
      value.each_slice(2).to_h
    else
      value
    end
  }
```

which gets used in its [`hgetall`](https://github.com/redis/redis-rb/blob/v4.5.1/lib/redis.rb#L2530) method (which the workset's `#each` method calls).

I haven't tried to repro but that looks like it could be one possibility. What version of the redis gem do you have installed? Could you include a stack trace and maybe inspect & provide what is the value of `worker` ?

**Comment by hernanat** [comment]
can you inspect `worker` and share it?
