### ISSUE TITLE
Determining number of redis connections used by sidekiq

### ISSUE THREAD

**Issue by imanpalsingh** [sidekiq/sidekiq#5977]
My first issue here, thank you for this piece of art !

----
Ruby version: 3.1.4
Rails version: 7.0.4.3
Sidekiq / Pro / Enterprise version(s): 6.5.8

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```rb

require 'sidekiq-unique-jobs'

redis_config = { url: 'redis://localhost:6379' }

Sidekiq.configure_server do |config|
  config.redis = redis_config

  config.client_middleware do |chain|
    chain.add(SidekiqUniqueJobs::Middleware::Client)
  end
  config.server_middleware do |chain|
    chain.add(SidekiqUniqueJobs::Middleware::Server)
  end

  SidekiqUniqueJobs::Server.configure(config)
end

Sidekiq.configure_client do |config|
  config.redis = redis_config

  config.client_middleware do |chain|
    chain.add(SidekiqUniqueJobs::Middleware::Client)
  end
end
```

```yml
# sidekiq1.yml
:concurrency: 4
:max_retries: 15
:queues:
  - mailers
  - default

```

When I access the sidekiq UI without any sidekiq process running. It shows me that 3 connections are being used.
<img width="1328" alt="Screenshot 2023-07-19 at 8 04 42 PM" src="https://github.com/sidekiq/sidekiq/assets/49276301/8f49e297-c824-46de-add1-81af9d7bf568">

As soon as I start this process with `bundle exec sidekiq -C sidekiq1.yml` the number of connections rise to `9`. 
<img width="1301" alt="Screenshot 2023-07-19 at 8 06 13 PM" src="https://github.com/sidekiq/sidekiq/assets/49276301/da9e69de-fe31-4845-afaa-433237afc0cb">

So, I thought that maybe `6` connections are used by this process ( not sure about 2 extra). 

I created one more sidekiq process `sidekiq2.yml`

```yml
# sidekiq2.yml
:concurrency: 4
:max_retries: 15
:queues:
  - payment
  - default
```
and ran this process along with the first one `bundle exec sidekiq -C sidekiq2.yml`. I get total connections as `14`
<img width="1302" alt="Screenshot 2023-07-19 at 8 12 59 PM" src="https://github.com/sidekiq/sidekiq/assets/49276301/382f5096-6276-4bb5-a15e-1bec8983f456">

This time it is increased by 5. No jobs are enqueued or are running during this period or any other redis connection is being created from anywhere else.

How is the number of connections determined? and why is it that number?

**Comment by mperham** [comment]
Connection count is implementation specific and not guaranteed. You'll need to dive into the Sidekiq code if you want to understand how a given version uses connections. 

I will say that every job execution thread will reserve one connection for its own use during job execution.
