### ISSUE TITLE
Routes for ActiveStorage fields inside ActiveContent do not use config for host and port when inside a job

### ISSUE THREAD

**Issue by Benratelade** [sidekiq/sidekiq#5980]
Ruby version: 3.2.2
Rails version: 7.0.3
Sidekiq: 7.1.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
not relevant? (although if it is, maybe it's a very straightforward issue I'm dealing with...)

Hi there, 

I came across an issue recently where our application was generating PDFs (using WickedPDF) inside workers. 
These PDFs could include some rich text fields ([Rails Action Text](https://guides.rubyonrails.org/action_text_overview.html)), which in turn could have image attachments. 

What we found was that when the files were generated inside a Sidekiq job, the URLs for these attachments would always have URLs starting with http://example.org.

I was not able to find the root cause of this, or to find a config anywhere that would solve this across all workers. I know this is an issue with Mailers, and the fix is to set the `url_options`, but we couldn't find somewhere that would actually work for these PDFs. 

Is there an obvious setting we are missing? 

I put together a Rails app that shows what I mean, although it does not render any PDF. Instead, it saves the content generated inside the Sidekiq job to database, so we can check it afterwards: 

https://github.com/Benratelade/rails-workers-routing-bug

**Comment by mperham** [comment]
I don't know, this is a Rails issue. Did you check the guide for ActionMailer?

**Comment by Benratelade** [comment]
Thank you for getting back to me! 

I'll post the same question in the Rails circles. 

It seems that solutions for ActionMailer are specific to ActionMailer. I also found nothing helpful for ActiveStorage or ActionText.

Let me know if you would like me to post an update here once I find out more, in case someone finds it useful.
