### ISSUE TITLE
K8s monitoring 

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#5982]
Many customers are using k8s to run their Sidekiq clusters. Add support for liveness probing.

**Comment by lusinh** [comment]
Good to hear that

**Comment by dbussink** [comment]
@mperham I'm testing the check available in Sidekiq Enterprise 7.1.2, but I suspect I've found a bug. It looks like it binds to `127.0.0.1` by default (using `DEFAULT_HOST` from `gserver`), which means it doesn't exposed in a way that Kubernetes can access it.

Is it possible to allow configuring the host to bind to as well as the port? So this can be fixed?

**Comment by dbussink** [comment]
This is what currently gets logged even when the health check is enabled:

```
{"severity":"INFO","message":"Health now available on port 7433","@timestamp":"2023-10-18T08:46:20.948Z","@version":"1"}
```

```
Warning  Unhealthy  4m7s (x573 over 48m)  kubelet            Readiness probe failed: Get "http://10.254.183.114:7433/": dial tcp 10.254.183.114:7433: connect: connection refused
```

**Comment by dbussink** [comment]
@mperham I have this locally working with allowing a specific `host` to bind to and it solves the issue. As we're also an Enterprise customer, happy to also submit the change under the conditions at https://github.com/sidekiq/sidekiq/wiki/Commercial-collaboration. 

I assign all rights, including copyright, to any future Sidekiq work by myself to Mike Perham

**Comment by mperham** [comment]
@dbussink Of course, email me a patch at mike@contribsys.com and I'd be happy to get this fixed. I'd assumed that health checks could be done locally.

**Comment by dbussink** [comment]
> @dbussink Of course, email me a patch at [mike@contribsys.com](mailto:mike@contribsys.com) and I'd be happy to get this fixed. I'd assumed that health checks could be done locally.

The readiness probe in the above logs shows it's using the assigned pod IP and it's not an operation of the local interface, so binding just to that won't work:

```
Readiness probe failed: Get "http://10.254.183.114:7433/"
```

I'll email the patch first thing in the morning! Also happy to do a PR as described in https://github.com/sidekiq/sidekiq/wiki/Commercial-collaboration if you prefer.

**Comment by mperham** [comment]
I got your patch but I'm thinking of making the API slightly different. The (port, host) arguments feel weird.

Today: a single Integer for the bound port.
```
config.health_check(7001)
```

Patch: (port, host)
```
config.health_check(7001, "0.0.0.0")
```

Proposed: either an Integer for port or a String for interface
```
config.health_check("0.0.0.0:7001")
config.health_check(":7001") # 127.0.0.1
config.health_check(7001) # 127.0.0.1
```

```ruby
host, port = arg.split(":")
host ||= GServer::DEFAULT_HOST
port = Integer(port)
```

The String iface format seems pretty standard.

**Comment by mperham** [comment]
Should `:7001` map to `0.0.0.0:7001` or `127.0.0.1:7001`?

**Comment by dbussink** [comment]
> I got your patch but I'm thinking of making the API slightly different. The (port, host) arguments feel weird.

I don't really have strong opinions on the API, this proposal works fine for me too :smile:. 

> Should `:7001` map to `0.0.0.0:7001` or `127.0.0.1:7001`?

At least in Go and afaik in other cases as well, this maps to listening on all addresses.

**Comment by dbussink** [comment]
> ```ruby
> host, port = arg.split(":")
> ```

This will break though for IPv6 addresses, as those contain `:` already (but wrapped in `[`, `]`).

**Comment by mperham** [comment]
Great feedback, I adjusted the code to handle extra colons and bracketed form.

**Comment by dbussink** [comment]
> Great feedback, I adjusted the code to handle extra colons and bracketed form.

@mperham Do you have a rough timeline for when this could be released in enterprise?

**Comment by mperham** [comment]
@dbussink Expect {OSS,Pro,Ent} 7.2.0 on Halloween.

**Comment by dbussink** [comment]
> @dbussink Expect {OSS,Pro,Ent} 7.2.0 on Halloween.

@mperham Thanks! Upgraded and we were able to drop `sidekiq_alive` with this change :smile:. Always like fewer dependencies.
