### ISSUE TITLE
Error while downloading sidekiq-pro gem, need to understand what user credentials are expired?

### ISSUE THREAD

**Issue by pravinjadhav4** [sidekiq/sidekiq#5983]
```
An error occurred while installing sidekiq-pro (5.3.1), and Bundler cannot
       continue.
       
       In Gemfile:
         sidekiq-pro

 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```
Could we understand what credentials of sidekiq-pro are expired, this is blocking all our build jobs since yesterday, could this looked at asap? This is emeritus.org and we are running a heroku build pipeline. Please let me know if we can speak to someone who can help us reinstate these credentials and give us access. We have configured the user and pass for BUNDLE_GEMS__CONTRIBSYS__COM and the builds were working till 2 days ago.

**Comment by mperham** [comment]
Please email support@contribsys.com for commercial support.
