### ISSUE TITLE
Sidekiq installation is not working

### ISSUE THREAD

**Issue by MoinVora** [sidekiq/sidekiq#5984]

**Comment by mperham** [comment]
Please read https://github.com/mperham/sidekiq/wiki/Commercial-FAQ

**Comment by MoinVora** [comment]
cap abz_prod sidekiq:install 
#<Thread:0x000055a1784e7450@/home/lenovo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sshkit-1.21.3/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
    1: from /home/lenovo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sshkit-1.21.3/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/home/lenovo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sshkit-1.21.3/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing on host 54.112.142.120: if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi exit status: 1 (SSHKit::Runner::ExecuteError)
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stdout: Nothing written
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stderr: usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
You cannot switch to user '''' using sudo, please check the sudoers file
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 54.112.142.120: if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi exit status: 1
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stdout: Nothing written
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stderr: usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
You cannot switch to user '''' using sudo, please check the sudoers file

 


Caused by:
SSHKit::Command::Failed: if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi exit status: 1
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stdout: Nothing written
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stderr: usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
You cannot switch to user '''' using sudo, please check the sudoers file

 

Tasks: TOP => sidekiq:install
(See full trace by running task with --trace)


 

has context menu
