### ISSUE TITLE
Downcasing Rack response headers incompatible with Rack 2

### ISSUE THREAD

**Issue by skipkayhil** [sidekiq/sidekiq#5988]
Ruby version: any
Rails version: < 7.1
Sidekiq / Pro / Enterprise version(s): any including f97d16acad300f596c2ab4841553e4d8b7ff0116

See rails/rails#48815

The issue is that downcasing response headers on its own (while valid according to Rack 2 SPEC as written) is not really compatible with how people have been using Rack 2 headers in practice. In the linked issue, this leads to duplicate CSP headers (`Content-Security-Policy` and `content-security-policy`) in `Sidekiq::Web` when mounted in any released version of Rails with a CSP configured.

There's been some discussion in skipkayhil/tmp-rails#1 about the best way to support Rack 2 (in practice) and Rack 3 at the same time. The two approaches are:
- make headers conditional on Rack version
- wrap response headers in `Rack::Utils::HeaderHash`/`Rack::Headers` depending on Rack version

I'm happy to make a PR to do either of these, but figured I would make an issue to ask if you had a preference

**Comment by mperham** [comment]
Can we drop support for Rack 2 yet? Can Rack put out a 2.x patch which handles those lower headers?

**Comment by mperham** [comment]
Any time this type of incompatibility pops up, I generally step back and ask if I still need this code in question. Does S::Web have to include a CSP? Can we adjust S::Web to not need a CSP? I’m far from a CSP expert so I genuinely don’t know the answers to these questions.

I’m fine with the different Rack version codepaths. It’s just a single if statement afaict. We’ll remove it in Sidekiq 8 with Rails 8, which presumably will be Rack 3+.

**Comment by skipkayhil** [comment]
> Can we drop support for Rack 2 yet?

I think the answer is its complicated 😓 I'm not sure I know enough myself to speak on what the long term plan is

> Can Rack put out a 2.x patch which handles those lower headers?

Rack 2 has `Rack::Utils::HeaderHash`, which is what you can use to wrap Response header hashes to make them behave with either casing. So the changes would generally look something like this:

```ruby
def halt(res)
  throw :halt, [res, Headers.new({"content-type" => "text/plain"}), [res.to_s]]
end
```

where `Headers` looks like this: https://github.com/rails/rails/blob/127138c09bcf061b4d17fb02ac79b214e3e05b47/actionpack/lib/action_dispatch/http/response.rb#L37-L45

**Comment by ioquatix** [comment]
> Can we drop support for Rack 2 yet?

When Rails 7.1 comes out, you can drop support for Rack 2 if that's your preference.

> Can Rack put out a 2.x patch which handles those lower headers?

Rack has always allowed for any case headers, it's just that middleware and application code has made some serious assumptions about response headers, which are sometimes correct but not following the spec. Specifically, a lot of Rack v2 middleware assumes the response headers is a hash, but that's not codified in the spec - it only has to respond to `#each{|key, value| ...}` (https://github.com/rack/rack/blob/2-2-stable/SPEC.rdoc#the-headers-). Assuming it's a hash with specific keys is not part of the spec and thus invalid in general.

> Does S::Web have to include a CSP?

This is a totally unrelated security question, but I strongly recommend including a CSP. It prevents your application from loading unexpected/uncontrolled resources from external parties, e.g. XSS attacks.

> We’ll remove it in Sidekiq 8 with Rails 8, which presumably will be Rack 3+.

This sounds like a good path to me.
