### ISSUE TITLE
Update Sidekiq::Limiter to not use namespaced queues

### ISSUE THREAD

**Issue by Jhowden** [sidekiq/sidekiq#5990]
Sidekiq / Pro / Enterprise version(s): 6.5.8/5.5.8/2.5.3

My organization is looking to update our Sidekiq/Sidekiq-ent gems to the newest version and see that namespaced queues are no longer supported. Unfortunately, we are using namespaced queues for our Sidekiq::Limiter using a different Redis instance from our regular Sidekiq. You have an old [post](https://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/) about migrating away from redis-namespace but I am curious if this approach also works for Sidekiq::Limiter or if it is safe to just remove the namesapce from the Limiter Redis configuration? From what I can tell, the Limiter is only setting/unestting the locks so if we removed the namespace then when we encounter the Sidekiq::Limiter lock for the first time it will re-create it in Redis.

Does this seem correct or do we have to be more careful about how we handle this case and the namespaced queues in Sidekiq::Limiter?

**Comment by mperham** [comment]
> we are using namespaced queues for our Sidekiq::Limiter

I don't understand the term "namespaced queues" in this context.

But in general it's safe to clear your Sidekiq::Limiter Redis keyspace as long as you restart your workers at the same time. The workers will restart and any Limiters will be recreated within the new keyspace. You may risk some false negatives (e.g. if the user has a limit of 1000 calls per hour, used 900 and then you reset the keyspace, the new Limiter will incorrectly allow 1000 more) but generally that's not a major issue.

**Comment by Jhowden** [comment]
Sorry, I should have said namespaced redis keyspace (`sidekiq_rate_limiter:lmtr-cfree-some-key`) instead of namespaced queues for the limiter. 

Would we even need to clear the Sidekiq::Limiter Redis keyspace? We have other applications that are still using namespaces so don't want to clear those keys. In the above example, I would expect the keyspace to be `lmtr-cfree-some-key` and work just fine after we restart the workers and the Limiter code is reached again.

Thanks for your input!
