### ISSUE TITLE
Throttle using Rate Limiters

### ISSUE THREAD

**Issue by sobrinho** [sidekiq/sidekiq#5991]
As said by the wiki [Limiting is not Throttling](https://github.com/sidekiq/sidekiq/wiki/Ent-Rate-Limiting#limiting-is-not-throttling) but we could use the rate limiters to throttle jobs enqueueing.

```ruby
throttle = Sidekiq::Limiter.bucket("throttle-#{user_id}", 10, :minute)
throttle.within_limit do
  # my block of code
end
```

We know that this eventually will raise `Sidekiq::Limiter::OverLimit` when you exceed it and on a Sidekiq Job it would re-enqueue in a optimistically prediction to process again.

Why not use the same algorithm to spread jobs over time outside a Sidekiq Job as well?

Let's say:

```ruby
throttle = Sidekiq::Limiter.bucket("throttle-#{user_id}", 10, :minute)

1000.times do
  SomeWorker.perform_within_limiter(throttle, some_args)
end
```

That would be the same as:

```ruby
delay = 0

1000.times do |i|
  delay += 1.minute if i % 10 == 0
  SomeWorker.perform_in(delay, some_args)
end
```

The idea is that the limiter knows that if you try to use the limiter X times, it would exceed. We can grab that information and do some math with it to spread the jobs over time automatically.

WDYT?

**Comment by mperham** [comment]
I would prototype it and see how well it works in production for you. It does rely on exception handling for flow control, which is typically a smell.
