### ISSUE TITLE
Improve security by removing inline javascripts

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#5992]
CSP allows unsafe inline script execution today. Let’s remove this need by refactoring our JS.

**Comment by BelaBartok39** [comment]
Is this being worked on?

**Comment by mperham** [comment]
Not at the moment. PRs welcome.

**Comment by BelaBartok39** [comment]
Hello! In the file web/views/dashboard.erb, I see the following:

`<script>
    window.historyChart = new DashboardChart(
      document.getElementById("history-chart"),
      <%= Sidekiq.dump_json({
        processedLabel: t('Processed'),
        failedLabel: t('Failed'),
        processed: @processed_history.to_a.reverse,
        failed: @failed_history.to_a.reverse,
      }) %>
    )
  </script>`

Is this the type of inline JS you are referring to? If not, would you have time to point to a specific example?

**Comment by mperham** [comment]
Yes. All \<script\> tags need to be removed if possible.
