### ISSUE TITLE
Renewed Request to Hide Retry All and Delete All Buttons 

### ISSUE THREAD

**Issue by chadrschroeder** [sidekiq/sidekiq#5997]
I know this has been discussed in the past in issues like https://github.com/sidekiq/sidekiq/issues/4347 and this isn't currently a supported feature, but I want to propose this again.  Would it be possible to add an easy way to hide the Retry All and Delete All buttons?  We've had people accidentally use these instead of the Retry Now and Delete buttons.

The "All" buttons are always dangerous because you can have:

1. Job A crashes.
2. You load the Dead queue page to view what crashed.
3. While you are on the page Job B crashes.
4. You decide Job A is fine to delete and you click Delete All.

This will delete both Job A and Job B even though you never saw Job B in the list.

Also, I know that the first time I saw these buttons years ago, I checked the checkboxes for individual jobs and then proceeded to click on "Delete All" thinking that it meant "delete all that have been checked".  Its easy for someone new to this UI to not immediately perceive the difference between the options.

**Comment by chadrschroeder** [comment]
To customize the `morgue` view would require either overriding the `erb` method or copying all the standard views to a different location and altering `Sidekiq::Web.settings.views`.

Otherwise, the "all" buttons can be disabled on the server by adding this in a Rails initializer or a Rack config file depending upon where Sidekiq Web is mounted:

```ruby
module Sidekiq
  class DeadSet
    def retry_all
      raise 'Retry All is unsafe.'
    end
  end

  class RetrySet
    def retry_all
      raise 'Retry All is unsafe.'
    end

    def kill_all
      raise 'Kill All is unsafe.'
    end
  end

  class SortedSet
    def clear
      raise 'Delete All is unsafe.'
    end
  end
end
```

**Comment by mperham** [comment]
Sharp knives can cut you. The Web UI exposes Sidekiq's underlying realtime data. Any operations on that data must take into account that realtime nature. I think Chad's suggestion is a reasonable one and allows you to patch in your own guardrails if you want.
