### ISSUE TITLE
ENT - Race condition in bootstrap with points limiter (LUA script loading)

### ISSUE THREAD

**Issue by pkopac** [sidekiq/sidekiq#5998]
I see that randomly certain instances of Sidekiq get broken for their entire lifetime. Fortunately it's rare, so the jobs retry on other instances. It seems like a race condition when switching threads. I think this might be a similar problem to https://github.com/sidekiq/sidekiq/issues/3043

Sidekiq / Pro / Enterprise version(s):
Sidekiq 7.1.0
Pro 7.1.1
Enterprise 7.1.0

This happens 0.5 seconds after 'SuperFetch[default] activated':

```
can't add a new key into hash during iteration

/usr/local/bundle/gems/sidekiq-ent-7.1.0/lib/sidekiq-ent/limiter/points.rb:141:in `<class:Points>'	
/usr/local/bundle/gems/sidekiq-ent-7.1.0/lib/sidekiq-ent/limiter/points.rb:27:in `<module:Limiter>'	
/usr/local/bundle/gems/sidekiq-ent-7.1.0/lib/sidekiq-ent/limiter/points.rb:6:in `<module:Sidekiq>'	
/usr/local/bundle/gems/sidekiq-ent-7.1.0/lib/sidekiq-ent/limiter/points.rb:5:in `<top (required)>'	
/usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'	
/usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'	
/usr/local/bundle/gems/sidekiq-ent-7.1.0/lib/sidekiq-ent/limiter.rb:285:in `points'	
/app/app/workers/some_worker.rb:58:in `limiter'	
/app/app/workers/some_worker.rb:32:in `perform'	
...
```

Several jobs try to `Sidekiq::Enterprise::Scripting#bootstrap` concurrently. Then one becomes paused while iterating in favor of another that starts, and tries autoloading with the above-mentioned error.

Any job trying to use the Points limiter then fails for the whole runtime of the instance with:
```
Unsupported command argument type: NilClass

/usr/local/bundle/gems/redis-client-0.14.1/lib/redis_client/command_builder.rb:75:in `block in generate'	
/usr/local/bundle/gems/redis-client-0.14.1/lib/redis_client/command_builder.rb:68:in `map!'	
/usr/local/bundle/gems/redis-client-0.14.1/lib/redis_client/command_builder.rb:68:in `generate'	
/usr/local/bundle/gems/redis-client-0.14.1/lib/redis_client.rb:208:in `call'	
/usr/local/bundle/gems/redis-client-0.14.1/lib/redis_client/decorator.rb:26:in `call'	
/usr/local/bundle/gems/sidekiq-ent-7.1.0/lib/sidekiq-ent/scripting.rb:21:in `block in call'
...
```

Because the script wasn't in `LUA` before the the first `bootstrap` started, so later on it won't be in `SHAS` -> `nil`.

### Solution
We managed to work around it like this:
```ruby
Sidekiq.configure_server do |config|
  ...
  # This is required to prevent race condition for loading LUA scripts.
  Sidekiq::Limiter::Points
  Sidekiq::Limiter::Concurrent
  Sidekiq::Enterprise::Scripting.bootstrap(config)
end
```
However, it would be worth to prevent this either by eagerly loading by default or adding a mutex. We spotted this only now and we started using Points limiter very soon after release.

**Comment by mperham** [comment]
bundle up sidekiq-ent

**Comment by mperham** [comment]
#5908
