### ISSUE TITLE
Move to structured logging

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#6006]
More and more customers seem to be using the JSON logger. Go 1.21 adds a [new structured logging API][0]. I think the industry is at a point where structured logging seems like it should become the new default.

1. Is there a stdlib impl already? Or a widely adopted gem which would add structure APIs on top of ::Logger that we might depend on?
2. What APIs, if any, would Sidekiq need to provide?
3. We'll need to make it easy to revert to the plain text logger. Are there further backwards compatibility issues?

Other ideas and comments welcome.

[0]: https://go.dev/blog/slog

**Comment by dbussink** [comment]
Fwiw, we're using https://github.com/iMacTia/sidekiq-logstash at the moment for structured logging.

**Comment by mperham** [comment]
I'm not really seeing much functionality to add. You activate the JSON logger and it becomes structured. Is Sidekiq missing any further niceties or polish? I don't think it's worth changing the default when it's pretty easy to enable already.

**Comment by dbussink** [comment]
> I'm not really seeing much functionality to add. You activate the JSON logger and it becomes structured.

Never realized this was already available since Sidekiq 6 🤦. So moved to what is already available anyway.
