### ISSUE TITLE
job["overrated"] not reset when max reschedules is reached

### ISSUE THREAD

**Issue by lorrin** [sidekiq/sidekiq#6010]
Ruby version: 3.1.4
Rails version: 6.1.7
Sidekiq / Pro / Enterprise version(s): 7.1.0

In the Sidekiq Enterprise rate limiter middleware, when the job raises a `Sidekiq::Limiter::OverLimit` exception, `job["overrated"]` is consulted to see whether the rate limit has been exceeded too many times. If not, it is rescheduled. If yes, then the exception is re-raised and the job is failed by re-raising the `Sidekiq::Limiter::OverLimit`. That triggers the usual failed job retry behavior. What is supposed to happen during the failed job retry if `Sidekiq::Limiter::OverLimit` is raised again?

My expectation was that the same rate limiting behavior would be repeated. E.g. 20 more attempts (with the default rate limit behavior) before it is over the rate limit for too long and considered to be the second job failure. However, the behavior I'm seeing is that the first OverLimit immediately counts as being over rate limit for too long and it directly becomes a second job failure. So with 3 job failure retries, it is not 3*20 attempts, but 20+1+1 attempts. I believe this is because the middleware does not reset `job["overrated"]` back to zero before re-raising the `Sidekiq::Limiter::OverLimit` and therefore it gets copied into the subsequent execution.

Possibly relevant: my job is an ActiveJob, not a pure Sidekiq job, and I'm raising my own exception class instead of  `Sidekiq::Limiter::OverLimit`, with `Sidekiq::Limiter.errors` configured accordingly.

**Comment by mperham** [comment]
Correct, after 20 limiter retries with linear backoff, the job reverts to error retries with exponential backoff. This is by design.
