### ISSUE TITLE
How to use sidekiqmon against a SSL redis instance?

### ISSUE THREAD

**Issue by juanmanuelramallo** [sidekiq/sidekiq#6015]
## What is happening?
Heroku Redis provides redis instances with SSL enabled by default.

When using `sidekiqmon`, the REDIS_URL env var must be set to properly fetch the monitoring stats from the Sidekiq's redis instance.

However, when setting a `rediss://...` URL I get the following error:
```
.gem/ruby/3.2.2/gems/redis-client-0.16.0/lib/redis_client/ruby_connection.rb:131:in `connect_nonblock': SSL_connect SYSCALL returned=5 errno=0 peeraddr=54.236.129.15:29139 state=error: certificate verify failed (RedisClient::CannotConnectError)
```

## How to fix?
Heroku's documentation suggests passing the ssl_params hash to configure the redis client (https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-from-sidekiq).

But I haven't found a way to pass that `ssl_params` configuration to the `sidekiqmon` binary currently.

## Proposals

1. Allow redis options to be passed as a JSON environment variable (after this https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/redis_connection.rb#L12)
```ruby
symbolized_options[:ssl_params] ||= begin
  JSON.parse(ENV["REDIS_SSL_PARAMS"])
rescue JSON::ParserError
  {}
end
```

2. Update sidekiqmon to use the app's redis configuration (might be via initializer, env vars, or yaml)

I think the 1) is easier to add than 2) but I'm not too familiar with the gem's source code in general. 

I appreciate any feedback or suggestions, thanks.

**Comment by mperham** [comment]
I don't know how to get this working.

AFAIK Heroku Redis does not provide verifiable TLS certificates. I have no idea why this is but it seems like a major failing and limitation in their service. Email support and ask them to migrate to Let's Encrypt?

And honestly I'm not really enthusiastic about adding workarounds for braindead platform-specific limitations. They've had this issue for many, many years now. If they give you a `rediss` URL, it should verify. Anything less is crippled TLS.

**Comment by juanmanuelramallo** [comment]
Fair point. 

We were using Heroku Redis in our non-production environments, our production environment is using the managed redis offering from redis.com, so we don't have an issue there. We'll end up moving everything to redis.com eventually.

Thanks for the quick answer!
