### ISSUE TITLE
Sidekiq web issue

### ISSUE THREAD

**Issue by nmindia** [sidekiq/sidekiq#6025]
I am getting the error 'undefined method `sum' for nil:NilClass ' when opening web url for sidekiq. Please refer to this screenshot URL: https://prnt.sc/GO3UEa4B4_2h

**Comment by mperham** [comment]
Please fill out the issue template with version info.

**Comment by nmindia** [comment]
Sidekiq  "6.1.0"
Redis '7.2.0'
Ruby '2.6.5'
Rails 6.0.3.6

**Comment by mperham** [comment]
I'm almost positive that bug has been fixed in a newer version. Please upgrade your Ruby and Sidekiq versions.
