### ISSUE TITLE
Parent on_complete callback is not called in complex batch

### ISSUE THREAD

**Issue by codaksh001** [sidekiq/sidekiq#6026]
Ruby version: 2.7.6
Rails version: 5.2.8.1
Sidekiq / Pro / Enterprise version(s): 4.0.4

Currently, I am facing an issue related to a complex batch 

below is my TestWorker code

```
class TestWorker < ApplicationJob
  sidekiq_options queue: :abc_queue, unique: true

  def perform(args)
    batch.jobs do 
      batch1 = Sidekiq::Batch.new
      batch1.description = "child Test test"
      batch1.callback_queue = 'abc_queue'.freeze
      batch1.on(:complete, "TestWorker", text: "TestWorker worker", id: 1)
      batch1.jobs do
        TestWorker.perform_async({msg: "last job"})
      end
    end
      
  end

  def on_complete(_status,options)
    nil.x
    puts "TestWorker args ======================> on_complete called"
  end
end
```

below is my Test2Worker code

```
class Test2Worker < ApplicationJob
  sidekiq_options queue: :xyz_queue, unique: true

  def perform(args)
    puts "Test2Worker args ======================> perform called"
  end

  def on_complete(_status,options)
    puts "Test2Worker args ======================> on_complete called"
  end
end
```

I am calling like below
```
batch = Sidekiq::Batch.new
batch.description = "Test test"
batch.callback_queue = 'xyz_queue'.freeze
batch.on(:complete, "Test2Worker", text: "Test2Worker worker", id: 1)
batch.jobs do
  TestWorker.perform_async({msg: "TestWorker1"})
end
```

As you can see above I am creating a child batch by opening parent `batch.jobs` in TestWorker
Also, I am calling on_complete  for TestWorker which has added some code and will break the on_complete callback for the child batch
When I am running the above code and the child batch callback breaks it does not call the parent batch on_complete callback

So what does it mean,
If somehow the child batch callback failed or broke then it does not call the parent batch on_complete callback?

**Comment by mperham** [comment]
Those versions are no longer supported. Please upgrade.

**Comment by codaksh001** [comment]
Hey @mperham,
Thanks for your response, I totally agree with your suggestion that we need an upgrade and also it is in process which will take some time.
But at least can I get an answer till we upgrade
**_If somehow the child batch callback(on_complete) failed or broke then the parent batch on_complete callback will execute or not?_**

**Comment by mperham** [comment]
I think you are right. If the child batch callback fails, the parent callback will not fire until it finishes successfully.
