### ISSUE TITLE
Unable to see sidekiq scheduled jobs on sidekiq webpage after adding newrelic_rpm gem to my rails application

### ISSUE THREAD

**Issue by Himani391** [sidekiq/sidekiq#6027]
I have added newrelic_rpm gem to my rails application, after adding the gem I am unable to see sidekiq jobs under scheduled tab in sidekiq webpage.
I have created newrelic.yml using the command and updated key and app name.
No other config has been added updated so far. 
Am I missing any specific configuration related to sidekig in newrelic.yml?
Note: Job is running after scheduled time of 1 minute but it is not visible on sidekiq webpage as it was showing earlier before adding the newrelic_rpm gem.
 Ruby version: 3.1.2 
Rails version: 6.1.4.2 
newrelic_rpm gem version: 9.4.2 
sidekiq gem version: 6.5.5

**Comment by mperham** [comment]
No clue what the problem might be. Try updating to 6.5.9.

**Comment by Himani391** [comment]
> No clue what the problem might be. Try updating to 6.5.9.

Tried with sidekiq 6.5.9 as well as 7.1.2, but still facing the same. 
Also tried reverting newrelic_rpm gem addition and I could see the job in sidekiq webpage. Couldn't figure out the issue.

**Comment by mperham** [comment]
Sounds like an issue with newrelic then.
