### ISSUE TITLE
idea: retry_until

### ISSUE THREAD

**Issue by jjb** [sidekiq/sidekiq#6029]
idea:

```ruby
retry_until: X.hours # retry_for? max_retry_time?
```

as an alternative to

```ruby
retries: Y
```

so i don't have to find [this table](https://github.com/sidekiq/sidekiq/wiki/Error-Handling#automatic-job-retry) (which is not on google because github wiki isn't indexed) every time :sweat_smile:.

in most cases i don't care that much about number of times, i'm happy with "give the external service this much time to come back online" or whatever, and trust the default exponential backoff pattern over that span.

potential user confusion drawback: there might be an assumption that there will be 1 more retry around the X hour mark, but that might actually be hours wrong. (e.g. someone uses 24.hours, which results in the final one at 17).

**Comment by mperham** [comment]
Great idea. 👑

What do you think about using the pattern `retry_for: 24.hours` and the Sidekiq::Client will convert that element into `retry_until: <timestamp>` when it pushes the job to Redis? The Retry subsystem will just return early if retry_until is in the past.

**Comment by jjb** [comment]
> What do you think about using the pattern

that sounds fine to me - is the implication that it also creates another feature, `retry_until` can be specified when queueing a job? `MyJob.perform_async(foo, bar, retry_until: 10.hours.from_now)`

**Comment by mperham** [comment]
Well, I think that would be considered an implementation detail and not documented as an element you can rely on or pre-calculate yourself.

**Comment by jjb** [comment]
gotcha - in which case I don't have much opinion!
