### ISSUE TITLE
Rails `CurrentAttributes` not set correctly when inheriting from `ActiveJob::Base` and testing inline

### ISSUE THREAD

**Issue by Earlopain** [sidekiq/sidekiq#6032]
Ruby version: 3.2.2
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): 7.1.3

I have the following testcase:

```rb
require "test_helper"

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

class Dummy
  def enqueue
    DummyJob.perform_later
  end
end

class DummyJob < ActiveJob::Base
  def perform(*args)
  end
end

class CurrentAttributeTest < ActiveSupport::TestCase
  test "CurrentAttributes" do
    Current.user = "test"

    Sidekiq::Testing.inline! do
      assert_equal("test", Current.user, "FIRST")
      Dummy.new.enqueue
      assert_equal("test", Current.user, "SECOND")
      Dummy.new.enqueue
    end
  end
end
```

CurrentAttributes are reset after the first job is executed, the second assert fails. This works fine if the job includes sidekiq instead of inheriting from activejob or if the jobs are not executed inline.

I tried making a self-contained repro script but couldn't manage without a full-blown rails app. I created a test rails app here https://github.com/Earlopain/sidekiq-current-attributes where you can just run rake test to see the failure.

**Comment by mperham** [comment]
I think you need to add the current attributes server middleware to S::Testing.server_middleware. This is not done automatically.

**Comment by Earlopain** [comment]
Thank you for the swift response. I'm having trouble doing what you suggested.

```rb
# initializers/sidekiq.rb
Sidekiq::Testing.server_middleware do |chain|
  chain.add Sidekiq::CurrentAttributes::Load
end
```

This isn't right in some way, can you advise? I'm also not using the current attributes middleware at the moment, so would that even do something?

**Comment by mperham** [comment]
Put it in your test_helper.rb, not the initializer. It should only run in testing.

**Comment by Earlopain** [comment]
Makes sense about moving to test_helper, yeah.

I looked more into it and this seems to be behaviour specific to executing jobs inline and has nothing to do with sidekiq. I found this issue on rails in regards to this https://github.com/rails/rails/issues/37526. Sorry about opening the issue here.
