### ISSUE TITLE
Periodic jobs registration with multiple Redis pools

### ISSUE THREAD

**Issue by odedgottes** [sidekiq/sidekiq#6033]
Hey,

I have a Ruby on Rails app that is using Sidekiq Enterprise. There are multiple Redis pools for Sidekiq queues in the environment, and there are use cases of periodic jobs and scheduled jobs. In order to enable a process to push jobs to queues in different Redis pools, Sidekiq::Client.push method is overriden - the Redis pool to push the job to is dynamically chosen according to the job's queue.

When registering periodic jobs in the configure_server block, because of the env having multiple Redis pools and the patch described above, there is a problem - if the registration code runs in all of the Sidekiq processes, duplicate jobs will be created because there will be multiple Sidekiq leaders, one per each Redis pool, all of them will create the same periodic jobs. So currently there is a patch there that avoids this, which I would like to change, and I would appreciate your opinion on what would be the best approach here.

Currently what I have in mind is to decide on only one Redis pool that only the Sidekiqs that are connected to it will run the periodic jobs registration, with a simple condition that checks the connected Redis pool against the chosen one, and thus avoid running the registration of periodic jobs in any Sidekiq process that is connected to another Redis pool (regardless of the pools that the jobs themselves might go to, which may vary). This way only one leader, of the chosen Redis pool, will create all of the periodic jobs. Does this make sense? Is there a better approach for this situation?

Thanks

**Comment by mperham** [comment]
That would work. You do have a very complex deployment and wonder if you can simplify but I recognize that it's all highly contextual.

**Comment by oded-gottesman** [comment]
> That would work. You do have a very complex deployment and wonder if you can simplify but I recognize that it's all highly contextual.

Thanks @mperham, appreciate your answer 🙏🏼

**Comment by odedgottes** [comment]
> That would work. You do have a very complex deployment and wonder if you can simplify but I recognize that it's all highly contextual.

Thanks @mperham, appreciate your answer 🙏🏼
