### ISSUE TITLE
Improve the Documentation

### ISSUE THREAD

**Issue by zaeem** [sidekiq/sidekiq#6034]
Hey,
I am writing to inquire about the new feature capsules in Sidekiq 7. I have already read the documentation on the new feature capsules, but I have a few questions. How can I prioritize my queues using the capsules? I am using the sidekiq enterprise version and found no better recommendations on the internet regarding prioritizing the queues with capsules.
Please answer my questions as soon as possible. I am excited about the new feature capsules' potential and would like to start using them as soon as possible.

Thanks

**Comment by mperham** [comment]
Strict priority:
```
cap.queues = %w[high default low]
```

Weighted:
```
cap.queues = %w[high,3 default,2 low,1]
```

Random:
```
cap.queues = %w[high,1 default,1 low,1]
```

**Comment by zaeem** [comment]
Thanks for the response. One more thing I want to ask, I have 11 process of Sidekiq and want to apply capsules individually for each process. How can i achieve this using capsules?

**Comment by mperham** [comment]
Can you be more specific about why you want to do this? My initial thought is "that's a really bad idea".

**Comment by zaeem** [comment]
I have 11 different process of Sidekiq and I want that each process have its own capsule configurations.

**Comment by mperham** [comment]
Yeah, I understand that. But WHY? What are you trying to achieve by doing so?

**Comment by mperham** [comment]
Do you just need to configure the default capsule for each process? You can configure the processes differently for different queues:

1. bundle exec sidekiq -q some_queue -c 3
2. bundle exec sidekiq -q foobar -c 2

**Comment by zaeem** [comment]
So let me explain, I have a process which handles only report jobs and i have another process which handles only email jobs. Each process have different queues with different concurrences and i want to apply capsules individually for each process as both process are independent from each other. When i applied capsule functionality it configured under the **leader** process which i don't wanna do that.

**Comment by zaeem** [comment]
So let me explain, I have a process which handles only report jobs and i have another process which handles only email jobs. Each process have different queues with different concurrences and i want to apply capsules individually for each process as both process are independent from each other. When i applied capsule functionality it configured under the **leader** process which i don't wanna do that.
