### ISSUE TITLE
`Sidekiq::Client.push_bulk` repeats `at` array values after `batch_size` items, ignoring the rest

### ISSUE THREAD

**Issue by aprescott** [sidekiq/sidekiq#6040]
Ruby version: 3.2.2
Rails version: 7.0.8, since that's what `bundle exec rake` in the Sidekiq repo seems to use for me
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.1.4 (and confirmed on `main` as of 1ba89bbb22d2fd574b11702d8b6ed63ae59e2256)

(I have reproduced problem on the current `main` branch, using the `client_test.rb` test below, it does not seem to be mentioned in CHANGELOG.)

## Summary

`Sidekiq::Client.push_bulk` with an `at` array argument will start repeating `at` values after `batch_size` items, instead of using all `at` values given.

This breaks an expectation when trying to enqueue N jobs (with N in excess of `batch_size`) each with distinct `at` times, since the first `batch_size` values in `at` will start to repeat, ignoring the remaining given `at` values.

## Example

For example:

```ruby
Sidekiq::Client.push_bulk(
  "class" => FooJob,
  "args" => [[1], [2], [3]],
  "at" => 3.times.map { |i| Time.new(2019, 1, i + 1).to_f }
  :batch_size => 2
)
```

Based on the way [`push_bulk` checks `args.size` and `at.size`](https://github.com/sidekiq/sidekiq/blob/1ba89bbb22d2fd574b11702d8b6ed63ae59e2256/lib/sidekiq/client.rb#L121), I think the expectation with the above code is that the `args` and `at` values are paired:

- `[1]` and `Time.new(2019, 1, 1)`
- `[2]` and `Time.new(2019, 1, 2)`
- `[3]` and `Time.new(2019, 1, 3)`

In reality, the index value loops through `0..(batch_size-1)` [because of the way the `with_index` is applied](https://github.com/sidekiq/sidekiq/blob/1ba89bbb22d2fd574b11702d8b6ed63ae59e2256/lib/sidekiq/client.rb#L131). The inner index is used, which resets for each batch, resulting in the following unexpected pairing:

- `[1]` and `Time.new(2019, 1, 1)`
- `[2]` and `Time.new(2019, 1, 2)`
- `[3]` and `Time.new(2019, 1, 1)` (resets back to the first `at` value)

This seems to have been introduced as part of 1b2c3e8d0ba77447f12a4fb5035cf238ced2d23c included in v7.1.0, which made `push_bulk` batch-aware (later affecting `perform_bulk` in c1607198815d68f60d138010907dd3426d6521bb).

## Failing test case

On `main` as of 1ba89bbb22d2fd574b11702d8b6ed63ae59e2256, this test I added locally to `client_test.rb` fails:

```ruby
# in client_test.rb

it "can specify different times when there are more jobs than the batch size" do
  times = job_count.times.map { |i| Time.new(2019, 1, i + 1) }
  args = job_count.times.map { |i| [i] }
  # When there are 3 jobs, we want to use `times[2]` for the final job.
  batch_size = 2

  jids = Sidekiq::Client.push_bulk("class" => QueuedJob, "args" => args, "at" => times.map(&:to_f), :batch_size => batch_size)

  assert_equal job_count, jids.size
  assert_equal times, jids.map { |jid| Sidekiq::ScheduledSet.new.find_job(jid).at }
end
```

Test output:

```
Failure:
Sidekiq::Client::bulk#test_0009_can specify different times when there are more jobs than the batch size [/private/tmp/sidekiq/test/client_test.rb:376]:
--- expected
+++ actual
@@ -1 +1 @@
-[2019-01-01 00:00:00 -0500, 2019-01-02 00:00:00 -0500, 2019-01-03 00:00:00 -0500]
+[2019-01-01 05:00:00 UTC, 2019-01-02 05:00:00 UTC, 2019-01-01 05:00:00 UTC]
```

A corresponding diff, just for completeness:

```diff
diff --git a/test/client_test.rb b/test/client_test.rb
index 8d6ecd27..37f49ea2 100644
--- a/test/client_test.rb
+++ b/test/client_test.rb
@@ -363,6 +363,18 @@ describe Sidekiq::Client do
         assert_equal job_count, jids.size
         assert_equal times, jids.map { |jid| Sidekiq::ScheduledSet.new.find_job(jid).at }
       end
+
+      it "pairs all `at` values with each `args` value when there are more jobs than the batch size" do
+        times = job_count.times.map { |i| Time.new(2019, 1, i + 1) }
+        args = job_count.times.map { |i| [i] }
+        # When there are 3 jobs, we want to use `times[2]` for the final job.
+        batch_size = 2
+
+        jids = Sidekiq::Client.push_bulk("class" => QueuedJob, "args" => args, "at" => times.map(&:to_f), :batch_size => batch_size)
+
+        assert_equal job_count, jids.size
+        assert_equal times, jids.map { |jid| Sidekiq::ScheduledSet.new.find_job(jid).at }
+      end
     end
 
     it "can push jobs scheduled using ActiveSupport::Duration" do
```

**Comment by mperham** [comment]
Man, fixing bugs is so easy when I have rockstar users like you providing failing test cases. ❤️

**Comment by aprescott** [comment]
Thanks for such a quick fix!
