### ISSUE TITLE
NameError:   uninitialized constant RedisClient::Error

### ISSUE THREAD

**Issue by crystal-williams-brown** [sidekiq/sidekiq#6044]
Ruby version: Ruby 3.1.3p185
Rails version: Rails 7.0.7.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.1.4

sidekiq.rb
```
# on production, use a separate Sidekiq DB from the cache configured with no eviction
uri = ENV["REDISCLOUD_SIDEKIQ_URL"] || ENV["REDISCLOUD_URL"] || "redis://127.0.0.1:6379"

sidekiq_redis_config = {url: uri}

Sidekiq.configure_server do |config|
  config.redis = sidekiq_redis_config
end

Sidekiq.configure_client do |config|
  config.redis = sidekiq_redis_config
end
```
sidekiq.yml
```
--
:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
:queues:
  - critical
  - default
  - mailers
  - low

:scheduler:
  :schedule:
```
Note: left out the workers

full backtrace
[Terminal Saved Output-Sidekiq Error.txt](https://github.com/sidekiq/sidekiq/files/12664865/Terminal.Saved.Output-Sidekiq.Error.txt)

When I run my test suite it errors before running any tests because of Sidekiq. This started with upgrading from Sidekiq 6 to 7. The line it errors on is from the Sidekiq codebase.
```
Failure/Error: require File.expand_path("../../config/environment", __FILE__)

NameError:
  uninitialized constant RedisClient::Error

      BaseError = RedisClient::Error
                             ^^^^^^^
  Did you mean?  IOError
                 Errno
```

**Comment by mperham** [comment]
It's working for me.

```
$ bundle exec rails c
> RedisClient::Error
=> RedisClient::Error
> Sidekiq::VERSION
=> "7.1.4"
> RedisClient::VERSION
=> "0.17.0"
```

**Comment by crystal-williams-brown** [comment]
It works in the console for me but not in tests. It's weird

**Comment by crystal-williams-brown** [comment]
We decided to ignore the audit alert rather than upgrade for now. This is because there was going to be an issue with Heroku and Redis. So I won't be looking into this error for now. Not sure if I should close out this issue or leave it open in case others have the same problem.

Note: the app is using fakeredis for tests
