### ISSUE TITLE
Jobs never entering the retry queue

### ISSUE THREAD

**Issue by iHiD** [sidekiq/sidekiq#6049]
Hello. Firstly thanks for Sidekiq. We rely on it heavily at Exercism, run about 500,000 jobs per day, and just processed our 200 millionth job last week 💙 

<img width="273" alt="Screenshot 2023-09-25 at 00 40 35" src="https://github.com/sidekiq/sidekiq/assets/286476/28f8e79e-6ef5-414b-b8bb-d751cf9195ac">

---

I upgraded to the latest version of Sidekiq and Redis 7 this week. Since then, I've noticed that we have no jobs in the retry queue. Normally there are a few hundreds jobs in there with various retries (bouncing emails, deadlocks, etc). But since the upgrade, there's been nothing.

I just checked the dead queue and the jobs seem to be there but with zero retries (ie the created time is the same as the last retry time). I did notice under "extras" that `{"retry_for"=>0}` is present, and that this is a new addition to the codebase. I wondered if that's causing some issues?

<img width="1205" alt="Screenshot 2023-09-25 at 00 35 41" src="https://github.com/sidekiq/sidekiq/assets/286476/133e5e26-8ed1-4d51-b24f-0ff3a0055b1d">

I'm not sure what other information to give upfront. Our setup is an extremely vanilla Rails setup, with once exception, which is a some [rescue code in application job](https://github.com/exercism/website/blob/main/app/jobs/application_job.rb#L11-L42) but I don't think that'll be contributing here. If I can give any more debugging information, please let me know.

Thanks!

**Comment by mperham** [comment]
Sounds like you are on 7.1.3 and you want 7.1.4.

**Comment by iHiD** [comment]
Thanks. Deploying an update now :)

**Comment by vitalinfo** [comment]
@mperham Hi
looks like we have the same problem on 7.1.4

<img width="450" alt="image" src="https://github.com/sidekiq/sidekiq/assets/7523182/8b6f5747-7089-4c88-aadf-72c9d3fb2d7e">

**Comment by vitalinfo** [comment]
looks like it happened after

<img width="994" alt="image" src="https://github.com/sidekiq/sidekiq/assets/7523182/0a8c89b6-d1b0-44df-a8fd-9ac53bfb5875">

I'm investigating why we have a problem with memory quota, but I think job should return to "Enqueued"

**Comment by iHiD** [comment]
@mperham I've installed 7.1.4. I ran 5.4M jobs on it yesterday but **none** ended up in retries or failed. That's possible, but I normally have like ~2,000 jobs sitting in retry, so it feels very unusual for me to be in this situation. Looking in dead jobs for the previous day before upgrading to 7.1.4, I have a dozen or so jobs there, but none anywhere since installing 7.1.4.

I think maybe this needs to be reopened.

**Comment by iHiD** [comment]
Just to be clear - that post has nothing to do with the original issue. We're still not getting any jobs entering our retries or dead queue after upgrading to Sidekiq 7. I'm tempted to downgrade to 7.0.3 and see if that fixes things. Are there any more data points I can provide, @mperham?

**Comment by mperham** [comment]
@iHiD Downgrade to 7.1.2 and see if that fixes things.

**Comment by iHiD** [comment]
Done. I'll report back in a couple of hours. Thanks for the help.

**Comment by iHiD** [comment]
@mperham OK - I've tried 7.1.2 and 7.1.4 by creating failing jobs and both are working fine. I just seem to have had no failing jobs in the last 24hrs, which is very unusual, but it what it is. Thanks for your help.
