### ISSUE TITLE
Add support for `EXTEND_TIMEOUT_USEC` in systemd notify support

### ISSUE THREAD

**Issue by behrmann** [sidekiq/sidekiq#6055]
Ruby version: 3.1.4p223
Rails version: 7.0.6
Sidekiq version(s): 6.5.7

Using sidekiq in GitLab 16.3 and 16.4 I on a self-installed instance with sidekiq running as a systemd service I recently ran into an issue where sidekiq was too slow to start so that systemd killed it before it could notify systemd of its startup.

This was easily worked around by giving sidekiq more leeway to start, i.e. increasing `TimeoutStartSec=`, but it would be great if sidekiq could do this by itself by and write `EXTEND_TIMEOUT_USEC=` followed by some integer value to the notification socket regularly until the startup event is fired.

**Comment by mperham** [comment]
Interesting. Seems like GitLab needs to extend `TimeoutStartSec` too.

**Comment by behrmann** [comment]
I've got [an MR](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132627) open to work around this. This issue is rather around dynamically extending the timeout until startup is finished.

**Comment by mperham** [comment]
No plan to implement. There's not an easy, obvious way to implement this and frankly this is quite a rare issue. The default is 90 or 120 seconds and it's a very rare app that takes more than that to start up. Adjusting TimeoutStartSec is the easy, obvious fix.
