### ISSUE TITLE
Confusing behavior when testing batches

### ISSUE THREAD

**Issue by tonybruess** [sidekiq/sidekiq#6057]
Ruby version: 3.2.2
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): 7.1.4

When running tests with the batch middleware enabled, the `on_complete` callback is called immediately and does not wait for all jobs to process.

Example code:

```ruby
require 'rails_helper'

Sidekiq::Testing.inline!

Sidekiq::Testing.server_middleware do |chain|
  chain.add Sidekiq::Batch::Server
end

describe "batches bug" do
  it "reproduces" do
    batch = Sidekiq::Batch.new
    batch.description = "Test"
    batch.on(:complete, Callback)
    batch.jobs do
      TestWorker.perform_async
      TestWorker.perform_async
    end
  end
end

class TestWorker
  include Sidekiq::Worker

  def perform
    puts "TestWorker"
  end
end

class Callback
  def on_complete(status, options)
    puts "Callback"
  end
end
```

Output:
```
TestWorker
Callback
TestWorker
```

**Comment by mperham** [comment]
Looks like there's a little bit of a clash between the two features. It works if I require them in the opposite order, so inline prepends first:

```ruby
require 'sidekiq/testing/inline'
require 'sidekiq/batch/client'
require 'helper'
```

Using multiple module prepends on the same API (`Sidekiq::Client#raw_push`) can be tricky and brittle. I need to determine a better way to do so.

**Comment by mperham** [comment]
Belay that last comment (deleted).

**Comment by tonybruess** [comment]
I blinked and you fixed it! Thanks so much!

**Comment by ggalmazor** [comment]
Hi there! We are currently testing the Sidekiq 7.1.4 > 7.1.5 update in our codebase, and we suspect this change might have something to do with an issue we see when applying the update. In our case, a workflow needs to run a `done` callback on _success_. 

We have a test for this that will test that the `done` method on the expected class will be called (using RSpec mock verifications) which used to work correctly before and now it's failing.

I can't share the actual code here, but this is something very similar to what we're running:

```ruby
it "tests the worker sequence triggered by the workflow" do
  Sidekiq::Testing.inline! do
    expect(WorkerA).to receive(:perform_async).with(date).once.ordered
    expect(WorkerB).to receive(:perform_async).with(date).once.ordered
    expect(WorkerC).to receive(:perform_async).with(date).once.ordered
    # etc.
    expect_any_instance_of(described_class).to receive(:done) # This is the assertion that's failing with 7.1.5

    described_class.perform_async(date)
  end
end
```

Do you think it could be related to the change on this PR?

**Comment by ggalmazor** [comment]
The following example reproduces the same implementation structure we have in the workflow, where we will create a workflow and then batches to run each worker:

```ruby
require 'rails_helper'

Sidekiq::Testing.inline!

Sidekiq::Testing.server_middleware do |chain|
  chain.add Sidekiq::Batch::Server
end

class Workflow
  include Sidekiq::Worker

  def perform
    start
  end

  def start
    workflow = Sidekiq::Batch.new
    workflow.on(:success, 'Workflow#done')
    workflow.jobs do
      step = Sidekiq::Batch.new
      step.jobs do
        WorkflowWorker.perform_async
      end
    end
  end

  def done(_status, _options)
    puts "Workflow#done"
  end
end

class WorkflowWorker
  include Sidekiq::Worker

  def perform
    puts "WorkflowWorker#perform"
  end
end

RSpec.describe Workflow do
  describe "#perform" do
    it "aggregates the data for the given date dqw" do
      described_class.perform_async
    end
  end
end
```

The spec at the bottom launches the workflow and it reproduces the issue I was talking about in my previous comment, where the `WorkflowWorker#done` callback is never called.

**Comment by mperham** [comment]
Looks like it's the nesting that's the issue. A callback directly on the `step` batch seems to work fine.

**Comment by mperham** [comment]
I think the net result of my investigation is that you can't use inline mode to execute nested batches. It doesn't work because the batch code requires the creating code to finish the `jobs` block before callbacks can be safely created, but that doesn't happen because the jobs execute immediately, before the `jobs` block finishes.

**Comment by mperham** [comment]
...and it turns out I think I can fix this by sending the parent data to Redis before executing the child jobs.

**Comment by ggalmazor** [comment]
Hi @mperham! We've seen that 7.1.6 has been rolled out recently, but we still see the same issue [mentioned here](https://github.com/sidekiq/sidekiq/issues/6057#issuecomment-1748886574). Is this something that you're planning on fixing in an upcoming version?

**Comment by mperham** [comment]
@ggalmazor Pro 7.1.6 is now available.

**Comment by ggalmazor** [comment]
Thanks, @mperham. That one did the trick! 🙇

**Comment by phantomwhale** [comment]
Guessing this one isn't getting backported to 5.x?

(guessing it's about time we upgraded our sidekiq library version !)

**Comment by shadydealer** [comment]
@mperham is there any chance of this getting backported to  Sidekiq Pro 3.7.1?

**Comment by mperham** [comment]
3.7.1 is out of support. Y'all need to upgrade.

**Comment by sensorsasha** [comment]
> 3.7.1 is out of support. Y'all need to upgrade.

@mperham what about backporting to sidekiq-pro 5.5.8?

**Comment by mperham** [comment]
Only critical fixes are backported.
