### ISSUE TITLE
Log workers re-enqueued on a hard shutdown

### ISSUE THREAD

**Issue by bdurand** [sidekiq/sidekiq#6058]
There is no visibility into what workers need to be re-enqueued when  a process is hard shutdown after the shutdown timeout is reached unless you are running with debug logging. This can make it difficult to identify stuck workers or know that a job was potentially run twice due to being re-enqueued.

Troubleshooting instances of hard shutdowns would be easier if each job that was re-enqueued was logged as a separate log entry that included the class name, job arguments, and how long it was running for.

**Comment by mperham** [comment]
Sidekiq Pro provides the notification block where you can do whatever you want with a rescued job. It also does log at WARN level.

https://github.com/sidekiq/sidekiq/wiki/Reliability#notification
