### ISSUE TITLE
error_handler breaking change

### ISSUE THREAD

**Issue by mikebaldry** [sidekiq/sidekiq#6065]
Sidekiq / Pro / Enterprise version(s): sidekiq (7.1.5)

Last week this was added to `config.rb`
```
if handler.arity == 2
  # TODO Remove in 8.0
  logger.info { "DEPRECATION: Sidekiq exception handlers now take three arguments, see #{handler}" }
  handler.call(ex, {_config: self}.merge(ctx))
else
  handler.call(ex, ctx, self)
end
```

A gem we're using `sentry-sidekiq` implements the handler as a class instance with a `call` method. This fails because `handler` doesn't have an `arity` method as it isn't a `Proc`.

The documentation states:
>You can create your own error handler by providing something which responds to call(exception, context_hash)

Sidekiq change: https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/config.rb#L267
Sentry sidekiq: https://github.com/getsentry/sentry-ruby/blob/master/sentry-sidekiq/lib/sentry/sidekiq/error_handler.rb#L8

Thanks

**Comment by mperham** [comment]
I'm not sure what to do then. I can't gracefully change APIs if I can't detect old vs new.

**Comment by mperham** [comment]
```diff
-        if handler.arity == 2
+        if (handler.respond_to?(:arity) && handler.arity == 2) ||
+          (handler.method(:call).arity == 2)
```

I'm trying to figure out the rat's nest of logic needed for this. The above ain't quite right.

**Comment by mikebaldry** [comment]
I was just doing the same on a branch, but something along those lines! I was thinking about adding this method and using that in place of `handler.arity` for the check
```ruby
def arity(handler)
  return handler.arity if handler.is_a?(Proc)
  handler.method(:call).arity
end
```

**Comment by mperham** [comment]
Well dang @mikebaldry, you're a smart guy. Fixed.

**Comment by sl0thentr0py** [comment]
@mperham can you release this as a patch?

**Comment by mperham** [comment]
7.1.6 is now available.

**Comment by mikebaldry** [comment]
@mperham thanks for the speedy fix!
