### ISSUE TITLE
Revise Sharding docs based on Capsules

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [sidekiq/sidekiq#6068]
The [Sharding](https://github.com/sidekiq/sidekiq/wiki/Sharding) docs discuss limitations, in particular lack of support for sharding within `sidekiq/api`.

AFAICT, with the introduction of [Capsules](https://github.com/sidekiq/sidekiq/blob/main/docs/capsule.md) in Sidekiq 7, this limitation no longer exists.

- `Sidekiq::Client.via` sets `Thread.current[:sidekiq_redis_pool]`
- `sidekiq/api` calls `Sidekiq.redis`
- `Sidekiq.redis` calls `Sidekiq::Capsule.redis`
- `Sidekiq::Capsule.redis` uses `Thread.current[:sidekiq_redis_pool]`

Conclusion: `Sidekiq::Client.via` now also works with `sidekiq/api`, and potentially the Web UI.

If true, it'd be great to document, as it makes sharding viable for applications that rely on `sidekiq/api`.

**Comment by mperham** [comment]
The documentation is meant to call out lack of explicit support in `sidekiq/api` for shards.

Capsules are a server-side thing (only in the Sidekiq process) while `via` and associated plumbing work in any ruby process as they are client-side. You can do this in IRB:

```ruby
> Sidekiq::Queue.all
=> [#<Sidekiq::Queue:0x0000000108597af0 @name="default", @rname="queue:default">]
> Sidekiq::Client.via(POOL) { Sidekiq::Queue.all }
=> []
```

That's what I mean by implicit: you have to call the API within the context of an active `via` setup.
This is how multi-sharding support in the Web UI works. I will tweak the Sharding page to make this clearer.
