### ISSUE TITLE
Make test mode threadsafe

### ISSUE THREAD

**Issue by esposito** [sidekiq/sidekiq#6069]
Ruby version: 2.7.7
Rails version: 7.0.7.2
Sidekiq / Pro / Enterprise version(s): 7.1.4/7.1.1/7.1.3

Currently changing the Sidekiq test mode in RSpec by using for instance `around { |example| Sidekiq::Testing.inline!(&example) }` or `around { |example| Sidekiq::Testing.disable!(&example) }` is not threadsafe. When using the `parallel_tests` gem to run a test suite with multiple processes, tests running in different processes will use the same test mode als a test that for instance disables Sidekiq testing mode.

In our test setup we added this monkey patch to keep the test mode from leaking to other test processes:

```ruby
# Make sidekiq test modes threadsafe
module Sidekiq
  module MultiThreadedOverrides
    def __test_mode
      Thread.current[:__sidekiq_test_mode]
    end

    def __test_mode=(mode)
      Thread.current[:__sidekiq_test_mode] = mode
    end

    def __set_test_mode(mode)
      if block_given?
        current_mode = __test_mode
        begin
          __test_mode = mode
          yield
        ensure
          __test_mode = current_mode
        end
      else
        __test_mode = mode
      end
    end
  end

  class Testing
    prepend MultiThreadedOverrides
  end
end
```

Would it be possible to fix this issue directly in the Sidekiq gem?

**Comment by mperham** [comment]
The issue is that `Sidekiq::Testing.inline!` is global: it affects every thread. Your patch would lose that, no? Should we have two layers: class variable and thread-local? Blocks use thread-local, no block means class variable.

**Comment by esposito** [comment]
That makes sense! And maybe `Thread.main` can be used for the global test mode? The code might look like this:

```ruby
def __current_test_mode
  Thread.current[:__sidekiq_test_mode] || Thread.main[:__sidekiq_test_mode]
end

def __global_test_mode=(mode)
  Thread.main[:__sidekiq_test_mode] = mode
end

def __thread_test_mode=(mode)
  Thread.current[:__sidekiq_test_mode] = mode
end

def __set_test_mode(mode)
  if block_given?
    current_mode = __current_test_mode
    begin
      __thread_test_mode = mode
      yield
    ensure
      __thread_test_mode = current_mode
    end
  else
    __global_test_mode = mode
  end
end

def disable!(&block)
  __set_test_mode(:disable, &block)
end

def fake!(&block)
  __set_test_mode(:fake, &block)
end

def inline!(&block)
  __set_test_mode(:inline, &block)
end

def enabled?
  __current_test_mode != :disable
end

def disabled?
  __current_test_mode == :disable
end

def fake?
  __current_test_mode == :fake
end

def inline?
  __current_test_mode == :inline
end
```

**Comment by mperham** [comment]
Available in 7.1.6. Thank you.

**Comment by andersonkrs** [comment]
Hey all, FYI I suspect this change broke our capybara specs that yield jobs, we have couple tests that we pass a block to `inline!` like this

```rb
Sidekiq::Testing.inline! do
  # my capybara commands here that produce jobs
end
```

And the jobs don't run anymore, I think because we have different threads here right? The test thread is different from the capybara thread that runs the rails server.

That's not a big deal since we can do `Sidekiq::Testing.inline!` before the commands without a block, could you please confirm that this is correct? 🙏

**Comment by esposito** [comment]
`Sidekiq::Testing.inline!` without a block should do the trick

**Comment by kranzky** [comment]
Is it a problem that we use fiber-local variables instead of thread-local variables for this? I note that all other other sidekiq code uses fiber-local variables as well. I believe that if a Fiber is created within a thread then these FIber-local variables will be unavailable. Ref: https://ruby-doc.org/3.2.2/Thread.html#class-Thread-label-Fiber-local+vs.+Thread-local

**Comment by Adverbly** [comment]
> Hey all, FYI I suspect this change broke our capybara specs that yield jobs, we have couple tests that we pass a block to `inline!` like this

I was late to my Sidekiq 7 upgrade so just ran into this now.

Can we consider an update to the [testing wiki](https://github.com/sidekiq/sidekiq/wiki/Testing) which warns about the block usage? The block usage is shown multiple times on that page without mention of this.

Perhaps particularly in the [section which describes capybara rspecs](https://github.com/sidekiq/sidekiq/wiki/Testing#capybara-feature-tests-with-backend-running-in-parallel)(which is where I encountered this)?

**Comment by mperham** [comment]
Yep, I'll update the wiki to note that the block form is Thread-local.
