### ISSUE TITLE
Sidekiq::Testing mode methods using blocks revert mode to nil

### ISSUE THREAD

**Issue by pkopac** [sidekiq/sidekiq#6072]
Ruby version: 3.2.2
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): 7.1.6

[This change](https://github.com/sidekiq/sidekiq/commit/e9f212902185591831af514df6313f8ae2cce31a#diff-8360e8f6436eec9d748f97a72a62912bf00588fd427672d5b1e65f03e401a456R19) breaks a scenario like this:

```ruby
Sidekiq::Testing.inline! do
  Job1.perform_async # mode is inline

  Job2.perform_async # mode is now fake (it's nil, and fake is default)
end

class Job1
  def perform
    Rails.env.test? ? Sidekiq::Testing.fake! { reschedule_in_the_future } : reschedule_in_the_future
  end
end
```

It's (simplified) what we use to avoid infinite loops with `perform_in` with inline testing. Perhaps a mention in the changelog would be good, because blocks don't work as they used to now, unless you can reconcile it with thread-safety. I'll be adapting tests to avoid this (use global mode `inline` instead of the first block).

Update: Also, jobs pushed in `Sidekiq::Batch` now execute after the jobs block, even in inline mode, which again breaks some mocking.

**Comment by mperham** [comment]
Sometimes fixes in a popular system like Sidekiq will change underlying semantics.

> what we use to avoid infinite loops

I don't want to support recursive testing modes, that's a hack and leads to spaghetti code like your example. If there's an infinite loop to fix, open that as an issue.

> execute after the jobs block

The jobs block is documented as atomic. Jobs should not start executing until the jobs block has completed.

**Comment by tristanoneil** [comment]
Wanted to note that we had something like:

```ruby
RSpec.configure do |config|
  config.around do |example|
    if example.metadata[:type] == :system
      Sidekiq::Testing.inline!(&example)
    else
      Sidekiq::Testing.fake!(&example)
    end
  end
end
```

because of this change we had to swap to this:

```ruby
RSpec.configure do |config|
  config.before { Sidekiq::Worker.clear_all }

  config.around do |example|
    if example.metadata[:type] == :system
      Sidekiq::Testing.inline!
    else
      Sidekiq::Testing.fake!
    end
    example.run
  end
end
```

Not an issue, just noting for anyone else that comes across this.

**Comment by aurels** [comment]
👋 

I'm note 100% sure it is related but the following does not work anymore for us in `7.1.6` (both `sidekiq` and `sidekiq-pro`): 

* `spec_helper` : `Sidekiq::Testing.fake!` (as a default)
* `inside tests` : `Sidekiq::Testing.inline! do` (never nested)

The jobs are never run inline and `Worker.jobs.size` is increased just like if it was in *fake* mode.
If I replace the `fake!` by `inline!` in `spec_helper`, all my tests pass again.

This works as expected on `7.1.5`.

**Comment by kalashnikovisme** [comment]
Looks like @tristanoneil your Sidekiq Jobs in tests run in a different thread, so, now you must use global test modes.

**Comment by aurels** [comment]
Mmmm, interesting. But what is the purpose of the bloc version then ?

From the changelog (7.1.6) :
> The block forms of testing modes (inline, fake) are now thread-safe so you can have a multithreaded test suite which uses different modes for different tests. [#6069]

**Comment by aurels** [comment]
> The block version allows you to use a mode different from the global mode.

Yes. That's what we use it for. Am I doing something wrong (in what I describe) then ? That's what we've been doing for years.
Thanks !

**Comment by mperham** [comment]
@aurels You might have found a bug. It happens. If you have a problem or found a bug, please open a **new** issue. Adding a comment to a closed issue is not helpful.

**Comment by mperham** [comment]
@aurels And I just verified that this appears to work as expected:

```ruby
% more foo_test.rb 
require "sidekiq"
require "sidekiq/testing"
require "minitest/autorun"

class Foo
  include Sidekiq::Job
  def perform
    puts "hi"
  end
end

class FooTest < Minitest::Test
  def test_foo
    Foo.perform_async
    assert_equal 1, Foo.jobs.size

    Sidekiq::Testing.inline! do
      Foo.perform_async
    end
    assert_equal 1, Foo.jobs.size
  end
end
```

```
> bundle exec ruby foo_test.rb
```

**Comment by tvdeyen** [comment]
> 👋
> 
> I'm note 100% sure it is related but the following does not work anymore for us in `7.1.6` (both `sidekiq` and `sidekiq-pro`):
> 
> * `spec_helper` : `Sidekiq::Testing.fake!` (as a default)
> * `inside tests` : `Sidekiq::Testing.inline! do` (never nested)
> 
> The jobs are never run inline and `Worker.jobs.size` is increased just like if it was in _fake_ mode. If I replace the `fake!` by `inline!` in `spec_helper`, all my tests pass again.
> 
> This works as expected on `7.1.5`.

Having the exact same problem. Jobs never run in `Sidekiq::Testing.inline!` with a block. They do run if the test mode is toggled globally as noted by @tristanoneil in https://github.com/sidekiq/sidekiq/issues/6072#issuecomment-1760256668

So we ended up with this rspec config

```rb
```

**Comment by tvdeyen** [comment]
> @aurels And I just verified that this appears to work as expected:
> 
> ```ruby
> % more foo_test.rb 
> require "sidekiq"
> require "sidekiq/testing"
> require "minitest/autorun"
> 
> class Foo
>   include Sidekiq::Job
>   def perform
>     puts "hi"
>   end
> end
> 
> class FooTest < Minitest::Test
>   def test_foo
>     Foo.perform_async
>     assert_equal 1, Foo.jobs.size
> 
>     Sidekiq::Testing.inline! do
>       Foo.perform_async
>     end
>     assert_equal 1, Foo.jobs.size
>   end
> end
> ```
> 
>  ```
> > bundle exec ruby foo_test.rb
> ```

Maybe I missing something, but shouldnt this be the expected behavior?

```rb
% more foo_test.rb 
require "sidekiq"
require "sidekiq/testing"
require "minitest/autorun"

class Foo
  include Sidekiq::Job
  def perform
    puts "hi"
  end
end

class FooTest < Minitest::Test
  def test_foo
    Foo.perform_async
    assert_equal 1, Foo.jobs.size

    Sidekiq::Testing.inline! do
      Foo.perform_async
    end
    assert_equal 0, Foo.jobs.size
  end
end
```

```diff
- assert_equal 1, Foo.jobs.size
+ assert_equal 0, Foo.jobs.size
```

**Comment by mperham** [comment]
@tvdeyen Inline's block wouldn't consume a job which is already in fake's in-memory queue (Foo.jobs).
