### ISSUE TITLE
Sidekiq::Queues[queue_name].clear causes surprising behavior

### ISSUE THREAD

**Issue by tiendo1011** [sidekiq/sidekiq#6075]
Ruby version: 3.2.2
Rails version: 7.0.4.2
Sidekiq / Pro / Enterprise version(s): No

In the testing guide, section [Queue API](https://github.com/sidekiq/sidekiq/wiki/Testing#queue-api), there is this guide to clear the queue:
```
# Clear an individual queue
Sidekiq::Queues["other"].clear
```
However, if we look at the [implementation](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/testing.rb#L172), following the guide will lead to only `jobs_by_queue` being cleared, not `jobs_by_class`, so when we query the queue using class style (SomeJob.jobs), the job is still there. I find this behavior very surprising.

**Comment by mperham** [comment]
Doc bug, that documentation wasn't written by me. There is a `Sidekiq::Queues.clear_for(queue, klass)` API to clear in a more complete manner:

https://github.com/sidekiq/sidekiq/blob/31bceff64e10d501323bc06ac0552652a47c082e/lib/sidekiq/testing.rb#L200
