### ISSUE TITLE
RedisClient::CannotConnectError: getaddrinfo_a: All requests done

### ISSUE THREAD

**Issue by PhilippeChab** [sidekiq/sidekiq#6094]
## Description

We recently bumped our sidekiq version to 7, and we have a weird exception being raised during our deployments. It happens intermittently and does not affect sidekiq's stability, it is however a bit strange and mysterious and we wondered if you had any idea of why it might happen. The exception is: `RedisClient::CannotConnectError: getaddrinfo_a: All requests done`.

I have not been able to pinpoint the exact cause, it does seem to have something to do with sidekiq closing its redis connections while initializing new connection pools. 

Ruby version: 2.7.4 (Also tested on 2.7.8)
Rails version: 7.0.6
Sidekiq version: 7.1.4

Backtrace:
```
RedisClient::CannotConnectError: getaddrinfo_a: All requests done
/usr/local/lib/ruby/2.7.0/socket.rb:227 getaddrinfo
/usr/local/lib/ruby/2.7.0/socket.rb:227 foreach
/usr/local/lib/ruby/2.7.0/socket.rb:632 tcp
lib/redis_client/ruby_connection.rb:117 connect
lib/redis_client/ruby_connection.rb:49 initialize
lib/redis_client.rb:688 new
lib/redis_client.rb:688 block in connect
lib/redis_client/middlewares.rb:12 connect
lib/redis_client.rb:687 connect
lib/redis_client.rb:674 raw_connection
lib/redis_client.rb:641 ensure_connected
lib/redis_client.rb:283 blocking_call
lib/redis_client/decorator.rb:26 blocking_call
lib/sidekiq/fetch.rb:47 block in retrieve_work
lib/sidekiq/capsule.rb:102 block in redis
lib/connection_pool.rb:110 block (2 levels) in with
lib/connection_pool.rb:109 handle_interrupt
lib/connection_pool.rb:109 block in with
lib/connection_pool.rb:106 handle_interrupt
lib/connection_pool.rb:106 with
lib/sidekiq/capsule.rb:99 redis
lib/sidekiq/component.rb:28 redis
lib/sidekiq/fetch.rb:47 retrieve_work
lib/sidekiq/processor.rb:87 get_one
lib/sidekiq/processor.rb:99 fetch
lib/sidekiq/processor.rb:81 process_one
lib/sidekiq/processor.rb:72 run
lib/sidekiq/component.rb:10 watchdog
lib/sidekiq/component.rb:19 block in safe_thread
```

Our initializer looks like this:
```ruby
# typed: true

require "sidekiq/middleware/i18n"
require "sidekiq/web"

require Rails.root.join("lib/sidekiq/middlewares.rb").to_s

Sidekiq.strict_args!(:warn)

Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch("REDIS_URL", nil) }
  config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new if !Rails.env.development?

  config.client_middleware do |chain|
       ...
  end

  config.server_middleware do |chain|
       ...
  end

  config.on(:startup) do
    ApplicationVersionJob.perform_async(ApplicationVersion.fetch)
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch("REDIS_URL", nil) }

  config.client_middleware do |chain|
       ...
  end
end
```

Also, we are still using the `redis-rb` gem internally.

Thanks.

**Comment by mperham** [comment]
> config.redis = { url: ENV.fetch("REDIS_URL", nil) }

This is a noop. You can remove the line entirely as this is what Sidekiq does internally.

> require "sidekiq/web"

Should go in `config/routes.rb`, not the initializer.

> RedisClient::CannotConnectError: getaddrinfo_a: All requests done

I've never seen this error before. Ruby 2.7 is quite old, maybe upgrade to Ruby 3.2.

**Comment by PhilippeChab** [comment]
We have upgraded and the error seems to be gone.

I'm must admit I am rather surprised however that a version a bit more than 2 years old is considered "quite old".

Thanks for your help.
