### ISSUE TITLE
Web Interface frozen after upgrade to 7.2.0

### ISSUE THREAD

**Issue by OskarEichler** [sidekiq/sidekiq#6100]
Ruby version: 3.2.1
Rails version: 7.1.1
Sidekiq / Pro / Enterprise version(s): 7.2.0

Since upgrading to Rails 7.1.1 and Sidekiq 7.2.0 our Web Interface is frozen. It loads and when refreshing the 'Enqueued' Tab the latency column is changing and is going up, but none of the actual job counts are updating. In the logs we can see that the jobs are running. Any clue?

**Comment by mperham** [comment]
Not really. You've got to find an error backtrace or another clue somewhere. There are several 3rd party gems which are broken in 7.2.0 so make sure they are all updated too.

**Comment by OskarEichler** [comment]
@mperham So actually this is happening on 7.1.6 as well, so seems to have to do with the upgrade to Rails 7.1.1

**Comment by OskarEichler** [comment]
False alarm, the Rails 7.1.X upgrade forced us to switch over to credentials instead of secrets and there was some mis-configuration. Thanks for the swift help as always @mperham 🙏🏼
