### ISSUE TITLE
Jobs getting to the Scheduled queue through perform_async

### ISSUE THREAD

**Issue by jgmontoya** [sidekiq/sidekiq#6101]
Ruby version: 3.2.2
Rails version: 7.1.1
Sidekiq / Pro / Enterprise version(s): 7.2

I've got a series of jobs that run for a short duration of time and then enqueue themselves. For some reason I haven't yet figured out, some times I find a couple of them in the scheduled queue and they're not being executed (they don't seem to ever be pick up from the scheduled queue). The jobs are being enqueued with `.perform_async`.

What can cause a job that was called with `.perform_async` to end up in the Scheduled queue?

I haven't been able to consistently replicate the behaviour, but it's happening frequently enough to be a problem (I am enqueueing/processing millions of jobs a day)

**Comment by mperham** [comment]
A job ends up in the Scheduled tab if the job payload has an `at` key and the value is in the future. Are you using any 3rd party extensions?

**Comment by jgmontoya** [comment]
> A job ends up in the Scheduled tab if the job payload has an `at` key and the value is in the future.

In this case there is no `at` key on the `.perform_async` call.

> Are you using any 3rd party extensions?

I'm using [sidekiq-scheduler](https://github.com/sidekiq-scheduler/sidekiq-scheduler) but not on these jobs. No other extensions.

**Comment by mperham** [comment]
I'm not sure what's happening. 🤷🏻‍♂️

**Comment by jgmontoya** [comment]
This wouldn't be much of an issue if the jobs didn't stay at the Scheduled queue seemingly for ever, could you please point me to docs or maybe briefly explain how jobs move from the scheduled queue to their respective queue / enqueued status?

**Comment by mperham** [comment]
Scheduled jobs are stored in a Sorted Set, with the score being the timestamp when the job should be enqueued for execution. You'd want to know the score in Redis of the job which is not scheduling as expected.

https://github.com/sidekiq/sidekiq/blob/b62de5441e23bc44b0be44a41302667faf70e925/lib/sidekiq/scheduled.rb#L30-L43

**Comment by jgmontoya** [comment]
Thanks! I'll try to investigate further and see if I can get to something...

Will also try to rollback to v7.1.6 and check if the issue is also present there (I don't recall seeing it before so it seems to have been introduced in v7.2.0).

**Comment by jgmontoya** [comment]
What could cause a job scheduled with `perform_in(x.seconds, *args)` to hang indefinitely on the Scheduled queue?

**Comment by jgmontoya** [comment]
Sorry about the misleading issue 😬 it seems like the actual problem was: jobs scheduled were not being picked up. Not really that they were getting into the Scheduled queue in the first place but rather that they were not getting out.

I downgraded sidekiq to version 7.1.6 and it looks like it's working properly again.

**Comment by jgmontoya** [comment]
> I downgraded sidekiq to version 7.1.6 and it looks like it's working properly again.

Definitely not working properly on 7.1.6 btw, I'm having to manually enqueue jobs in the scheduled and retry queue as they're not getting picked up by sidekiq.

I haven't been able yet to completely figure out why this is happening. I suspect it has to do with my usage saturating the CPU or something.

**Comment by nicklozon** [comment]
Same issue here, but Sidekiq 6.5.7

What platform are you on? We're on Heroku, I was wondering if our worker instance clock is running slow...but the variance in the scheduled time is too large to be a time issue.

Our thread utilization is low - only using around 5-10 of 36 threads most of the time. All queues are empty. Thousands of jobs sitting in Scheduled which were scheduled for 35-38 minutes ago. Seems like whatever moves jobs from Scheduled to a queue is being consumed. Retries is also affected.

We process a lot of duplicate webhooks in quick succession, so to keep DB load low we impose a short delay on processing jobs by using the `at:` parameter. This means we put a lot of jobs in Scheduled, but
