### ISSUE TITLE
Sidekiq jobs running after hour

### ISSUE THREAD

**Issue by rmevada** [sidekiq/sidekiq#6111]
we have to schedule a job after specified minutes, for this we are using perform_in(minutes, args). We are running the job every 15 minutes. this is working as expected. In sidekiq scheduler we are seeing these jobs scheduled. but the after x minutes,the job will go to run state. it did not executed the job.its disappearing. 

we have two jobs 1 for x minutes schedule - PhiUploadBatchJobByMinutes
1 for executing the job - PhiUploadJob. but this job only running after 1 hour.

**Comment by mperham** [comment]
I'm not sure I even understand the issue. Please give me a set of steps to reproduce the issue.
