### ISSUE TITLE
CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by dil-atiwari** [sidekiq/sidekiq#6112]
Ruby version: 2.7.8
Rails version: 6.1.7.6
Sidekiq: 6.0.7
Sidekiq pro: 5.0.1
Redis Version - 7.0.7

I have deployed the application on AWS and using ElastiCache in Cluster Mode. Now when the sidekiq is trying to trigger any job I am getting **CROSSSLOT Keys in request don't hash to the same slot** error. Any help is appreciated

Code configuration

```ruby

Sidekiq.configure_server do |config|
  config.redis = { cluster: [ENV.fetch("REDIS_URL")], password: ENV.fetch("REDIS_PASSWORD", nil), namespace: SIDEKIQ_NAMESPACE }
  config.error_handlers << Proc.new {|ex,ctx_hash| Honeybadger.notify(ex) }
  Rails.logger = Sidekiq.logger

end

Sidekiq.configure_client do |config|
  config.redis = { cluster: [ENV.fetch("REDIS_URL")], password: ENV.fetch("REDIS_PASSWORD", nil), namespace: SIDEKIQ_NAMESPACE }
end
```

**Comment by mperham** [comment]
https://github.com/sidekiq/sidekiq/wiki/Using-Redis#architecture

**Comment by dil-atiwari** [comment]
@mperham As I have gone through the link. Could you tell me for my usecase what shall I do for clustering mode? Any workaround or alternative?

**Comment by mperham** [comment]
Turn off clustering.

**Comment by dil-atiwari** [comment]
@mperham I have successfully implemented it using the following configuration. Since you already mentioned this approach is not appropriate as sidekiq  hot keys are constantly changing.  I am bit in dilemma whether to go with this approach or not. 

Are there any plans in future to support sidekiq with multicluster?

```ruby
 config.redis = { cluster: [ENV["REDIS_URL], password: REDIS_PASS, namespace: "{#{SIDEKIQ_NAMESPACE}}" }
```

- requires an array with a cluster name
- namespace requires **{}** 

Rails 6.1.7.6
Ruby 2.7.8
Sidekiq 6.0.7
sidekiq-pro 5.0.1
redis-namespace 1.7.0
redis-client 0.18.0
redis-clustering 5.0.0.beta3

**Comment by mperham** [comment]
Sidekiq 6 only supports the redis gem, not redis-client.

You cannot use a Redis cluster with Sidekiq. It will not work. I literally cannot fix it, Sidekiq's data design is not compatible with cluster.
