### ISSUE TITLE
Unintentionally sharing `Sidekiq.logger.formatter` and `Rails.logger.formatter`

### ISSUE THREAD

**Issue by strviola** [sidekiq/sidekiq#6113]
Ruby version: 3.2.2
Rails version: 7.0.7.2
Sidekiq / Pro / Enterprise version(s): 7.2.0

We detected that `Sidekiq.logger.formatter` was changed unintentionally by the code below.

```ruby
# config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  config.logger = Sidekiq::Logger.new('log/sidekiq.log', 'daily', formatter: Sidekiq.logger.formatter)
end

Sidekiq.configure_client do |config|
  config.logger = Sidekiq::Logger.new('log/sidekiq.log', 'daily', formatter: Sidekiq.logger.formatter)
end
```

```ruby
# config/initializers/some_other_file.rb
Rails.application.config.after_initialize do
  puts Sidekiq.logger.formatter.inspect
  Rails.logger.formatter = Rails.logger.formatter.dup
  puts Sidekiq.logger.formatter.inspect
end
```

Result output:

```
#<Sidekiq::Logger::Formatters::Pretty:0x000000010f739460 @datetime_format=nil>
#<ActiveSupport::Logger::SimpleFormatter:0x000000010efdb628 @datetime_format=nil>
```

Due to this behavior, the method `print_banner` in lib/sidekiq/cli.rb is not executed. Another Gem we use in initializers implements code like this.
How can I utilize separate formatters for `Sidekiq.logger.formatter` and `Rails.logger.formatter` ?

**Comment by mperham** [comment]
I would say the real issue is that you are configuring a logger at all. Redirect stdout instead.

**Comment by strviola** [comment]
I have avoided this occurrence by overriding the affected Gem (I18n-js) configuration. I will close this issue.
