### ISSUE TITLE
Convenient way to check sidekiq health?

### ISSUE THREAD

**Issue by RinCat** [sidekiq/sidekiq#6115]
Ruby version: 3.1.4
Rails version: 7.2.1
Sidekiq / Pro / Enterprise version(s): 7.2.1

Hi, one of my Mastodon's sidekiq stuck at 100% CPU usage and seems not response anything, and I had to kill and restart it without debug as there are tens of thousand jobs in queue.
So, is there a way to check if a sidekiq is working or dead but the process still running? It could be dead lock or something but I do not have any error log.
The sidekiq seems only connected to a remote redis and not listening any port. I would like able to `curl` or somehow to check the corresponding queue size form shell scripts.

Thanks.

**Comment by taylorthurlow** [comment]
`sidekiq-ent` has a health check feature you can enable in your configuration initializer or in `sidekiq.yml`.

https://github.com/sidekiq/sidekiq/blob/cde6df1c89cdaea629a32011da2a22ec332ecfcf/Ent-Changes.md?plain=1#L15-L24

Curling will give you all the details Sidekiq offers. Otherwise for stuff like queue size and latency you would have to set up your own endpoint which serves queue data from Sidekiq's library API. This can take many forms like a standard Rails controller or API endpoint, we've chosen to run it as a separate rack application for infrastructure/network access reasons. Here's the rack file for that:

```ruby
# Rack application for serving Sidekiq queue stats entirely separate from
# Rails. DO NOT MOUNT THIS IN A RAILS APP WITHOUT AUTHENTICATION. Run with:
#
#     REDIS_URL="redis://localhost:6379" \
#     REDIS_PASSWORD="" \
#     bundle exec puma \
#       -v \
#       -p 3001 \
#       sidekiq_stats.ru
#
# This will run a separate Rack app with no authentication, so it is important
# that it is only run in a container context which is not publicly accessible
# on the internet.

require "sidekiq"
require "sidekiq-pro"
require "sidekiq-ent"
require "sidekiq/api"

use Rack::ContentLength
use Rack::ContentType, "application/json"

redis_config = {
  url: "#{ENV.fetch("REDIS_URL")}/2",
  password: ENV.fetch("REDIS_PASSWORD", nil),
}

redis_config.delete(:password) if redis_config[:password].nil? || redis_config[:password].empty?

Sidekiq.configure_client do |config|
  config.redis = redis_config
end

run ->(env) do
  [
    200,
    {},
    [
      Sidekiq::Queue
        .all
        .to_h { |queue|
          [
            queue.name,
            {
              size: queue.size,
              paused: queue.paused?,
              latency_sec: queue.latency.round(2)
            }
          ]
        }
        .to_json
    ]
  ]
end
```

**Comment by mperham** [comment]
@taylorthurlow Alas, building your own Rack endpoint does not tell you about the health of a Sidekiq process. Side note: the Sidekiq Web UI responds to `/stats` and `/stats/queues` with a simple JSON payload which can be used for simple monitoring instead of rolling your own:

```
% curl http://localhost:3000/sidekiq/stats 
{"sidekiq":{"processed":21,"failed":16,"busy":0,"processes":2,"enqueued":0,"scheduled":0,"retries":0,"dead":2,"default_latency":0},"redis":{"redis_version":"6.2.10","uptime_in_days":"3","connected_clients":"8","used_memory_human":"1.21M","used_memory_peak_human":"10.70M"},"server_utc_time":"20:10:39 UTC"}
% curl http://localhost:3000/sidekiq/stats/queues
{"default":0}
```

**Comment by taylorthurlow** [comment]
> @taylorthurlow Alas, building your own Rack endpoint does not tell you about the health of a Sidekiq process. Side note: the Sidekiq Web UI responds to `/stats` and `/stats/queues` with a simple JSON payload which can be used for simple monitoring instead of rolling your own:
> 
> ```
> % curl http://localhost:3000/sidekiq/stats 
> {"sidekiq":{"processed":21,"failed":16,"busy":0,"processes":2,"enqueued":0,"scheduled":0,"retries":0,"dead":2,"default_latency":0},"redis":{"redis_version":"6.2.10","uptime_in_days":"3","connected_clients":"8","used_memory_human":"1.21M","used_memory_peak_human":"10.70M"},"server_utc_time":"20:10:39 UTC"}
> % curl http://localhost:3000/sidekiq/stats/queues
> {"default":0}
> ```

Good to know about `/stats` and `/stats/queues`, thanks. We're definitely using the provided health check option to do the actual health check but I hadn't realized there was a simpler way to get queue metrics, so I appreciate the heads up.
