### ISSUE TITLE
Namespacing for statsd metrics is inconsistent

### ISSUE THREAD

**Issue by asok** [sidekiq/sidekiq#6117]
Ruby version: 3.2.2
Rails version: 6.0.1
Sidekiq / Pro / Enterprise version(s): 6.5.2 / 5.5.2 / 2.5.3

I'm using the enterprise version Datadog. According to Datadog's documentation I've specified `dogstatsd` object when initializing Sidekiq: https://docs.datadoghq.com/integrations/sidekiq/

I've also specified the enterprise `retain_history` via `Sidekiq.retain_history(30)`.

I see that:
* the metrics sent by the statsd middleware are arriving just fine (for example `jobs.perform` arrives as `sidekiq.jobs.perform`)
* the metrics sent by `Enterprise::History` object are having the namespace duplicated (for example `queue.size` arrives as `sidekiq.sidekiq.queue.size`) 

By reading the code I see that the history object specifies the namespace when it sends the metric. So for it the statsd client would need to be instantiated without the namespace argument.

**Comment by mperham** [comment]
Ah, that's because "sidekiq" is meant to be part of the name for those metrics. Your namespace should be the name of your app. So if you have an app named "batcave", you might have a metric "batcave.sidekiq.busy" which tells you how many Sidekiq threads are executing batcave jobs. That metric wouldn't make as much sense if it was just "batcave.busy" and you wouldn't be able to easily share a DataDog account across apps if you only used "sidekiq.busy".

**Comment by asok** [comment]
> That metric wouldn't make as much sense if it was just "batcave.busy" and you wouldn't be able to easily share a DataDog account across apps if you only used "sidekiq.busy"

We pass an additional tag `app_name:` with each metric in order to distinguish between the apps. But in fact passing it in the name of the metric as a prefix seems like a more explicit solution.

So if I do:
```rb
 Sidekiq::Pro.dogstatsd = ->{ Datadog::Statsd.new('localhost', 8125, namespace:'batcave') }

     Sidekiq.configure_server do |config|
       config.server_middleware do |chain|
         require 'sidekiq/middleware/server/statsd'

         chain.add Sidekiq::Middleware::Server::Statsd
       end

       config.retain_history(30)
     end
```
Now I will receive:
* `batcave.jobs.count` from the middleware
* `batcave.sidekiq.busy` from the retain history thread

I guees it makes sense. I'll try write to Datadog to update their documentation.
