### ISSUE TITLE
Sidekiq Jobset does not respect Sidekiq::Client.via

### ISSUE THREAD

**Issue by taylorchu** [sidekiq/sidekiq#6124]
Ruby version: 3.2.2
Rails version: 6.1.7.4
Sidekiq / Pro / Enterprise version(s): 6.5.12 / 5.5.8 (pro)

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
```
[
  {:url=>"redis1:6379"},
  {:url=>"redis2:6379"},
].each do |config|
  pool = ConnectionPool.new { Redis.new(config) }
  Sidekiq::Client.via(pool) do
    Sidekiq.redis do |conn|
      puts conn.info["run_id"]
    end
  end
end

```
Sidekiq::Client.via should allow us to configure sidekiq/api pool.
However, they still connect to the same redis server.

```
Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at (pry):115:in `block (2 levels) in __pry__')
31b4cff8ddf0d688c42b5151abba4c6dead8de0d
Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at (pry):115:in `block (2 levels) in __pry__')
31b4cff8ddf0d688c42b5151abba4c6dead8de0d
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version? yes

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
For the API, I think you need to use `Sidekiq.via` per #5269.
