### ISSUE TITLE
Limiter timeout retries escape the batch callbacks

### ISSUE THREAD

**Issue by yxhuvud** [sidekiq/sidekiq#6126]
Ruby version: 3.2.2
Rails version: 7.1.1
Sidekiq / Pro / Enterprise version(s): 7.2.0 / 7.2.0/ 7.2.0

We have the following setup:
A batch is spawned with a bunch of jobs. 
Every job hit an url, and we use a limiter to avoid hitting any DOS protections
When the batch is complete, we have a callback that in turn process the result of the earlier jobs. 

Lately lately we have started to get `OverLimit` errors, which eventually will be retried. However, from what we can see the batch callbacks ignore those and happen without waiting for the overlimit retries to perform. This make us lose the results of the over limit entries in the further processing. 

Is this expected behavior? I couldn't find the interaction between these two features documented anywhere.

**Comment by yxhuvud** [comment]
What should be done on our side is to adjust the wait timeouts to be a bit more reasonable so that the issue don't happen in the first place, but it is a bit surprising to get a callback when all the jobs ain't done.

**Comment by mperham** [comment]
What does `-v` log for the server middleware chain?

```
> bundle exec sidekiq -v
Server Middleware: Sidekiq::Metrics::Middleware, Sidekiq::Limiter::Middleware, Sidekiq::Enterprise::Unique::Server, Sidekiq::Batch::Server, Sidekiq::Enterprise::Crypto::Server
```

You should have Batch *after* Limiter.

**Comment by yxhuvud** [comment]
Yes, that seems to be the case. 
```
2023-12-05T13:46:15.712Z pid=40 tid=58c DEBUG: Server Middleware: Sidekiq::Metrics::Middleware, Sidekiq::Limiter::Middleware, Sidekiq::Enterprise::Unique::Server, Sidekiq::Batch::Server, Datadog::Tracing::Contrib::Sidekiq::ServerTracer, Rollbar::Sidekiq::ResetScope
```

**Comment by mperham** [comment]
If you're using a :complete callback, that's exactly the expected behavior.

**Comment by yxhuvud** [comment]
ok, if it is expected for OverLimit errors to break out of the batch then I suppose we got to deal with that by refactoring. Guess I should close this then
