### ISSUE TITLE
Sidekiq worker details even for inactive workers

### ISSUE THREAD

**Issue by pranav-dubey-cl** [sidekiq/sidekiq#6127]
Hi all,

I have a usecase wherein I want to make scheduling decisions off of the sidekiq processes and the workers(threads ) in each of them. The way I'm doing it (from elixir code) is:
```
    {:ok, workers} = Mozek.Redis.command(["SMEMBERS", "processes"])
    Enum.reduce(workers, 0, fn worker, acc ->
      {_, payload} = Mozek.Redis.command(["HGETALL", "#{worker}:workers"])
      acc + div(length(payload), 2)
    end)
```
This is working fine as long as workers are working but is not useful if workers are idle in which case the first and second queries don't give the expected result. Can someone point out what am I doing wrong or what else can I do to get the same results?

Thanks and regards,
Pranav Dubey

**Comment by mperham** [comment]
I don't understand your question. Please refer to the source code in `sidekiq/api`.

**Comment by pulkit110** [comment]
I think I stumbled on a similar issue this week. What @pranav-dubey-cl probably means is that the `processes` value can sometimes contain stale processes that are already dead. We saw that the snippet below returned ~24k processes from Redis when in reality there were only about 10 processes active. FWIW, we have ~100 workers processing jobs off the different queues and the number of workers very frequently get scaled up and down. 

It auto-cleared after a while (I don't know what triggered it - there was a deployment in between and we also had the sidekiq-web interface open). 

```rb
Sidekiq.redis do |conn|
  procs = conn.sscan("processes").to_a
end
```

Unfortunatey, I don't have a repro for this issue - we have the same app deployed on multiple environments and this happened on only one of them (all running the same version of Sidekiq and Redis). 

@mperham Do you know what might have triggered this and if there is something we can do trigger a "reset" manually?

**Comment by mperham** [comment]
Going to the Busy tab triggers the cleanup, or any use of the Sidekiq::ProcessSet API.

**Comment by mperham** [comment]
https://github.com/sidekiq/sidekiq/blob/e911f3ee7ff0275c0e9284d42fac602c0db0be2a/lib/sidekiq/api.rb#L874-L904
