### ISSUE TITLE
Google Cloud Logger not compatible with sidekiq 7.2

### ISSUE THREAD

**Issue by davebenson** [sidekiq/sidekiq#6129]
Ruby version: 3.5
Rails version: 7.1.2
Sidekiq / Pro / Enterprise version(s): 7.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

Sidekiq.configure_server do |config|
  config.redis = { url: url, id: nil }
  config.reliable!
end

23:27:02 sidekiq.1 | undefined method `broadcast_to' for #<Google::Cloud::Logging::Logger:0x0000588253116ee8 @writer=#<Google::Cloud::Logging::AsyncWriter:0x00005882531172f8 @mon_data=#<Monitor:0x0000588253117190>, @mon_data_owner_object_id=6700, @logging=#<Google::Cloud::Logging::Project:0x0000588253117988 @service=Google::Cloud::Logging::Service(******************************), @shared_async_writer=#<Google::Cloud::Logging::AsyncWriter:0x00005882531172f8 ...>>, @max_count=10000, @max_bytes=10000000, @max_queue=100, @interval=5, @threads=10, @partial_success=false, @error_callbacks=[], @cond=#<MonitorMixin::ConditionVariable:0x0000588253117028 @monitor=#<Monitor:0x0000588253117190>, @cond=#<Thread::ConditionVariable:0x0000588253116fd8>>>, @log_name="ruby_app_log", @resource=#<Google::Cloud::Logging::Resource:0x0000588253117578 @labels={:module_id=>"worker", :version_id=>"20231206t231539"}, @type="gae_app">, @labels={}, @level=1, @request_info_var=#<Concurrent::ThreadLocalVar:0x0000588253116df8 @default_block=nil, @default=nil, @index=25>, @closed=false, @formatter=#<Logger::Formatter:0x0000588253116c68 @datetime_format=nil>, @datetime_format="", @silencer=true, @project="******************************">
23:27:02 sidekiq.1 | /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.2.0/lib/sidekiq/rails.rb:62:in `block (2 levels) in <class:Rails>'
23:27:02 sidekiq.1 | /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.2.0/lib/sidekiq.rb:98:in `configure_server'
23:27:02 sidekiq.1 | /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.2.0/lib/sidekiq/rails.rb:53:in `block in <class:Rails>'
23:27:02 sidekiq.1 | /app/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:94:in `block in execute_hook'

To be honest, I'm not even sure why Rails.logger is getting set that way.  I'm not sure if there's another workaround besides reverting to sidekiq 7.1.2.

**Comment by mperham** [comment]
I'd say that Google Cloud Logger is not compatible with Rails 7.1.

**Comment by mperham** [comment]
I think it's now seen as a bad practice to completely replace `Rails.logger` with another instance.

https://github.com/googleapis/google-cloud-ruby/issues/23522
