### ISSUE TITLE
ActionMailer::MailDeliveryJob does not play nice out of the box with the `retry_for` logic

### ISSUE THREAD

**Issue by gpacuilla-st** [sidekiq/sidekiq#6130]
Ruby version: 3.0.3
Rails version: 7.0.7
Sidekiq (basic gem): 7.1.3

This is related to:
https://github.com/sidekiq/sidekiq/issues/6029
https://github.com/sidekiq/sidekiq/issues/6030

The current implementation for `retry_for` appears to be breaking retry logic for at least `ActionMailer::MailDeliveryJob` by default.

Our sidekiq config is minimal:

```
# server/config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch('REDIS_URL', nil) }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch('REDIS_URL', nil) }
end
```

Currently, these `ActionMailer::MailDeliveryJob` jobs are submitted as such by default:

```
# server/app/mailers/application_mailer.rb
class ApplicationMailer < ActionMailer::Base
  default from: "no-reply@#{URI(ENV.fetch('CLIENT_URL')).hostname}"
  layout 'mailer'
end

# server/app/mailers/test_mailer.rb
class TestMailer < ApplicationMailer
  def email(to:)
    mail(
      to: to,
      subject: 'Test Email',
      body: 'This is a test email.',
      content_type: 'text/html'
    )
  end
end

# Submitted job definition
{
  "retry": true,
  "queue": "default",
  "class": "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
  "wrapped": "ActionMailer::MailDeliveryJob",
  "args": [
    {
      "job_class": "ActionMailer::MailDeliveryJob",
      "job_id": "e390da42-b48f-4b0b-81c0-cf31526fc180",
      "provider_job_id": null,
      "queue_name": "default",
      "priority": null,
      "arguments": [
        "TestMailer",
        "email",
        "deliver_now",
        {
          "args": [
            {
              "to": "some@email.com",
              "_aj_ruby2_keywords": [
                "to"
              ]
            }
          ],
          "_aj_ruby2_keywords": [
            "args"
          ]
        }
      ],
      "executions": 0,
      "exception_executions": {},
      "locale": "en",
      "timezone": "Eastern Time (US & Canada)",
      "enqueued_at": "2023-12-07T14:52:24Z"
    }
  ],
  "jid": "fd32f63399bc781474b9eee2",
  "retry_for": 0,
  "created_at": 1701960744.040795,
  "enqueued_at": 1701960744.040907
}
```

Note that `retry: true` - the problem here is with `retry_for: 0` - the current logic at https://github.com/sidekiq/sidekiq/blob/cb2c974f3db3a7c546ac86d6e187a00ae81cd665/lib/sidekiq/job_retry.rb#L175-L176 isn't properly accounting for `retry_for: 0` it seems:

```
irb(main):011> rf = 0
=> 0
irb(main):012* if rf then
irb(main):013*   puts "test"
irb(main):014> end
test
```

And of course `failed_at + 0` _should_ always be less than the current time - so what's happening is that failed jobs here are immediately sent to `retries_exhausted` -> `send_to_morgue` and therefor no retries ever occur until you manually retry jobs from the `Sidekiq::DeadSet` (`dead` queue)

Logs after first and only attempt:

```2023-12-06T15:13:05.109Z pid=1 tid=dwl class=ActionMailer::MailDeliveryJob jid=aeb6bba6f9e74b7d7599a35a INFO: Adding dead ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper job aeb6bba6f9e74b7d7599a35a```

```2023-12-06T15:13:05.111Z pid=1 tid=dwl class=ActionMailer::MailDeliveryJob jid=aeb6bba6f9e74b7d7599a35a elapsed=0.688 INFO: fail```

```2023-12-06T15:13:05.111Z pid=1 tid=dwl WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::MailDeliveryJob",...,"executions":0,"exception_executions":{},...,"retry_for":0,...}```

The fix I've come up with right now is to override the `delivery_job` to provide a real value for `retry_for`...

```
# server/app/jobs/mail_job.rb
class MailJob < ActionMailer::MailDeliveryJob
  sidekiq_options retry_for: 48.hours
end

# server/app/mailers/test_mailer.rb
class TestMailer < ApplicationMailer
  self.delivery_job = MailJob
  def email(to:)
    mail(
      to: to,
      subject: 'Test Email', 
      body: 'This is a test email.',
      content_type: 'text/html'
    )
  end
end
```

Using that, the job does _not_ get shunted to `dead` queue immediately, and it properly retries with the default backoff logic.

Somewhere the `retry_for` is being populated with `0` for `ActionMailer::MailDeliveryJob` by default which breaks retry logic.

This seems unintentional.

**Comment by mperham** [comment]
Bugs get fixed. https://github.com/sidekiq/sidekiq/blob/main/Changes.md#714
