### ISSUE TITLE
Feature Request - Add ActiveSupport::HashWithIndifferentAccess as a safe JSON type

### ISSUE THREAD

**Issue by DimitriosLisenko** [sidekiq/sidekiq#6131]
I understand the reasoning behind not allowing arbitrary types to be passed in to the perform_async calls, but `ActiveSupport::HashWithIndifferentAccess` should be a reasonably safe type to pass in since it acts essentially the same as a Hash with string keys.

Happy to submit a PR if you think that this feature makes sense.

UPDATE: Read some previous issues/PRs where the concern is that users might try access the hash with symbol keys inside the perform method, which is fair enough. Feel free to close if your stance is still the same.

**Comment by mperham** [comment]
Exactly, that's the issue. If the arguments can't be symmetric on both client- and server-side, there's always going to be an impedance mismatch which violates the principle of least surprise.

https://en.wikipedia.org/wiki/Principle_of_least_astonishment
