### ISSUE TITLE
Report recovered jobs on logs (pro/push)

### ISSUE THREAD

**Issue by sobrinho** [sidekiq/sidekiq#6132]
Ruby version: N/A
Rails version: N/A
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.1.6 / Pro 7.1.5 / Ent 7.1.2

Hi, again! ❤️ 

Would be nice to have the number of recovered jobs (pro/push) when the connection is restored.

There's the statsd but since we don't have it running, would be nice to see on the logs! :)

**Comment by mperham** [comment]
Can you email mike@contribsys.com a patch with what you had in mind?

**Comment by sobrinho** [comment]
Yes, will do!
