### ISSUE TITLE
Bucket limiter can be timezone aware with day interval

### ISSUE THREAD

**Issue by cameronmccord2** [sidekiq/sidekiq#6134]
Ruby version: 3.2.2
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): sidekiq (6.5.12) / Sidekiq Pro 5.5.8 / Sidekiq Enterprise 2.5.3
Enterprise email(we rebranded): developer@aboutshout.com OR developer@shoutsocial.com

Use case: We use bucket limiters using the day interval but we need to have the bucket be timezone aware. User A is allowed 1000 per day for their timezone(mountain time) and user B is allowed 1000 per day for their timezone (eastern time). 

The current implementation uses `when :day then Time.now.strftime("%F")` on line `/sidekiq-ent/limiter/bucket.rb:115`. Clean and simple, uses the server's timezone(usually UTC).

Solution: 

Allow passing in an optional timezone in the options hash of the bucket initializer. The timezone is only relevant when using the interval `:day`. Then the bucket_name function's `:day` case changes to 

```ruby
when :day 
  if timezone
    Time.use_zone(timezone) { Time.current.strftime("%F") }
  else
    Time.now.strftime("%F")
  end
```

Low regression since the new `Time.use_zone` code is only ran when passing in the new timezone option.
If this is something you'd like as part of Sidekiq we can do the work, add tests, update wiki, try it for a bit, and submit a PR. Otherwise we'll stick with a monkeypatch.

I assign all rights, including copyright, to any future Sidekiq work by myself to Mike Perham.

FYI: We're still on Sidekiq 6 since we're on Heroku with Rediscloud. If we submit a PR can it be a new Enterprise 2.5.4 version?

**Comment by mperham** [comment]
I don't think it's a good idea. "Clean and simple" is a good observation and I think this violates that ethos. I'd encourage you to monkeypatch.
