### ISSUE TITLE
The incompatible args warning not generated for ActiveSupport::HashWithIndifferentAccess

### ISSUE THREAD

**Issue by thushw** [sidekiq/sidekiq#6138]
Ruby version: 3.2.2
Rails version: 7.0.4.3
Sidekiq / Pro / Enterprise version(s): 6.5.8

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```
ArgumentError: Job arguments to AccountUpdateWorker2 must be native JSON types, but {"id"=>"018c0331-b64b-d059-f7a3-d7f9ccb4196e", "user"=>"018c0330-1bd3-9798-b42c-71afb7ca31b2", "item"=>"item_000041078", "source"=>"knight", "updated_at"=>"2023-12-18T19:43:22.222406Z", "connection"=>{"status"=>"connected", "error_code"=>nil, "error_message"=>nil, "updated_at"=>"2023-11-24T21:17:49.918956Z"}} is a ActiveSupport::HashWithIndifferentAccess. See https://github.com/sidekiq/sidekiq/wiki/Best-Practices To disable this error, add `Sidekiq.strict_args!(false)` to your initializer.
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

We upgraded to sidekiq 7.0 and got errors. I was wondering why the earlier sidekiq version (6.5.8) did not throw the "do not serialize to JSON safely" warning. We were monitoring this warning and it was not triggerred.
What we are doing here is getting arguments to a controller and converting them to a `ActiveSupport::HashWithIndifferentAccess` and passing that (instead of a ruby hash).

**Comment by mperham** [comment]
Did you try 6.5.12? 6.5.8 is not the latest...

**Comment by mperham** [comment]
Ah right, it's because the warning is optional in 6.x. You have to enable the warning with `Sidekiq.strict_args!(:warn)` in your initializer with 6.x.

**Comment by thushw** [comment]
Thank you, I missed that!
