### ISSUE TITLE
[Feature request] Ability to customize `(class, args, queue)` list for unique jobs  

### ISSUE THREAD

**Issue by fatkodima** [sidekiq/sidekiq#6142]
We are currently using the Sidekiq Enterprise uniqueness feature and have database sharding in the application.
We use the `CurrentAttributes` middleware to set and restore the current database shard when running jobs.
The problem is that Sidekiq decides uniqueness based on `(class, args, queue)`, but we need to have unique jobs per shard. 
To solve this problem, we need to either monkey patch Sidekiq to also consider a shard for uniqueness or pass an additional `shard` argument to the `perform`, which is almost never used inside the job.

It would be great to be able to somehow configure or extend that `(class, args, queue)` list. I can help with the PR if this is something you want to have.

**Comment by mperham** [comment]
Please see the top of the unique.rb impl where several monkeypatch points are documented for this. I think you can implement all of this yourself without any changes to Enterprise.

**Comment by mperham** [comment]
And if you want to show your code here for people wanting to do similar, I think that would be incredibly helpful.

**Comment by mperham** [comment]
And the unique feature should already seamlessly handle sharding. You should be able to push two identical jobs to two different shards because each shard is a different Redis database with its own set of unique locks.

**Comment by fatkodima** [comment]
Wasn't able to find an answer. Do commercial clients have access to the sidekiq's Pro and Ent github repositories?

**Comment by mperham** [comment]
No, but you have access to `bundle open sidekiq-ent`.

**Comment by fatkodima** [comment]
Thank you. I see the feature is already there, implemented in v7.0.3. I missed that I have v2.5.3 at hand, so hadn't seen it.
