### ISSUE TITLE
Improve the `CurrentAttributes` module

### ISSUE THREAD

**Issue by qblanc** [sidekiq/sidekiq#6143]
Using `Current` for our project, we found that the `CurrentAttributes` module was pretty much the solution we were thinking about for a problem we were having. However, I see 2 points that could be improved. One is a must-have in my opinion (the feature looks incomplete to me without it), the other would be a nice-to-have but could be only set as an option, maybe : 
- when the jobs act themselves as clients and push new jobs to Sidekiq, the `CurrentAttributes`should also be passed along (must-have). This is a problem describred in the Sidekiq middleware doc [in the section Client middleware registered in both places](https://github.com/sidekiq/sidekiq/wiki/Middleware#client-middleware-registered-in-both-places)
- if we pass along the `cattrs`, they are "delivered" as serialized args. This is logical, but we could offer the possibility to automatically reinstatiate all the `CurrentAttributes` before the running of the job.

If you think those are good ideas (or if one of them is), i'll be happy to work on it

**Comment by mperham** [comment]
1.  Already the default. This adds the client middleware in all environments:

https://github.com/sidekiq/sidekiq/blob/73c150d0430a8394cadb5cd49218895b113613a0/lib/sidekiq/middleware/current_attributes.rb#L69-L74
2. Sounds intriguing but I'm not sure what that entails. I'd be happy to get a PR or discuss more.

**Comment by qblanc** [comment]
Thanks for the answer !
1. Sorry I got confused by the `config.client_middleware`, I didn't knew the `Sidekiq.default_configuration` was configuring both server and client side at the same time
2. Our problem is that we are using `Current` to pass along objects (for instance `Current.agent`) and the current implementation is serializing with `to_s`, thus serializing the name of the object rather than the whole object or the id at least. On the server side, the `Load` method is recreating a `Current.agent` that is not the previous `Current.agent` but only a string. Maybe it is bad practice to use `Current` with records, but the doc is actually taking such an example (`Current.user`). It would be cool if the module was able to pass along objects/records rather than just strings

**Comment by mperham** [comment]
As object hydration can often raise an error or require the database, this is something out of Sidekiq’s responsibilities IMO. I advise people to use lazy accessors which load the object on demand. Save user_id as an attribute so only the id is persisted to the job.

**Comment by qblanc** [comment]
Alright, I get the point. Thanks for the insight
