### ISSUE TITLE
[ENT] Rate Limiting Bucket w/ Points

### ISSUE THREAD

**Issue by sirwolfgang** [sidekiq/sidekiq#6146]
I have a sort of weird rate limiting issue, that's kind of like the new points system but in a bucket. Wondering if there is a way to handle this. 

The API I am hitting allows me to send 1k events a minute, but I send these events in batches that I build and sort into max request size. So each payload is made up of N number of events, of which I can only send 1,000 events a minute.

It looks like the point system would work if I could change from leaky to bucket; or bucket could work if I could pass in a value into `within_limit`. Looking at the gem, I don't see anything exposed, but maybe I am missing something?

For `within_limit` something like this could work. My production code has queue management to requeue unsent batches. 
```ruby
LIMIT = Sidekiq::Limiter.bucket('events', 1000, :minute)

batches.each do |batch|
  # Adds batch.size to the limit, blows up if (past sizes... + batch.size > limit)
  LIMIT.within_limit(batch.size) do
    send_batch(batch)
  end
end
```

**Comment by mperham** [comment]
What about the points limiter?

https://github.com/sidekiq/sidekiq/wiki/Ent-Rate-Limiting#points

**Comment by sirwolfgang** [comment]
@mperham Points uses Leaky Bucket, the API I am hitting is using Bucket. If there was a way to set the algo, points could also work.

**Comment by mperham** [comment]
Ah right, easy enough. I can add a `used` option to the window/bucket limiters so you can specify the number of points used by the call, which defaults to 1.
