### ISSUE TITLE
Either declare or remove dependency on base64 to avoid a Ruby 3.3 warning

### ISSUE THREAD

**Issue by Earlopain** [sidekiq/sidekiq#6150]
Ruby version: 3.3.0
Sidekiq / Pro / Enterprise version(s): master

Ruby 3.3 emits a warning when base64 is required without being specified in the gemspec. Ruby 3.4 will error.

There are a few places in sidekiq where base64 is being made use of. These should either be refactored to not use the gem, or it should be added to the gemspec.

You can observe this warning in CI: https://github.com/sidekiq/sidekiq/actions/runs/7358335463/job/20031428359
![image](https://github.com/sidekiq/sidekiq/assets/14981592/9541edf9-1ae6-4d10-8310-ff9db0ed47b0)
Ignore the other warnings, they originate from other gems. drb is from rails I believe.

I've gone through a few gems I use and made PRs to replace this gem with pack/unpack, since that is basically everything that it's doing. However, here the url safe variants are used which does a bit more than just calling a differently named method and inlining that here doesn't feel that great.
https://github.com/ruby/base64/blob/9669a7d3b0e3b9a739969404daf58f912c58c6b3/lib/base64.rb#L328-L333
https://github.com/ruby/base64/blob/9669a7d3b0e3b9a739969404daf58f912c58c6b3/lib/base64.rb#L351-L362

* https://github.com/rubocop/rubocop/pull/12313
* https://github.com/rack/rack/pull/2110
* https://github.com/newrelic/newrelic-ruby-agent/pull/2378
* https://github.com/lostisland/faraday/pull/1541

**Comment by mperham** [comment]
Thanks for catching this. I'm ok with a PR inlining the basic calls.
