### ISSUE TITLE
Feature Request: Callbacks/Middlewares for Handling Jobs at Risk of Loss in reliable_push

### ISSUE THREAD

**Issue by salrepe** [sidekiq/sidekiq#6154]
We've been utilizing the reliable_push functionality within Sidekiq Pro, and it has significantly improved our job processing reliability. However, while working with it, my team and I have encountered scenarios where jobs might be lost due to unexpected process exits. We acknowledge 100% reliability is not possible but we think the proposal might help to deal with that 1% of unexpected cases. 

Temporarily, to address this, we've implemented these basic methods:

```ruby
      def warn_local_queue_jobs
        jobs = jobs_from_local_queue
        log_jobs(jobs)
      rescue => e
        Sidekiq.logger.error({
          body: 'Sidekiq warn_local_queue_jobs',
          error:  { class: e.class, message: e.message, backtrace: e.backtrace }
        }.to_json)
      end
      
      private
     
      def jobs_from_local_queue
        client = ::Sidekiq::Client.new
        return [] unless client.respond_to?(:local_queue)

        jobs = pop_jobs_from_local_queue(client)
        push_jobs_to_local_queue(client, jobs)
        jobs
      end

      def pop_jobs_from_local_queue(client)
        local_queue = client.local_queue
        jobs = []
        while !local_queue.empty?
          jobs << local_queue.pop(true)
        end
        jobs
      end

      def push_jobs_to_local_queue(client, jobs)
        jobs.each do |job|
          client.local_queue << job
        end
      end

      def log_jobs(jobs)
        jobs.each do |job|
          Sidekiq.logger.warn({
            body: "[ReliablePush][SidekiqLocalQueue] process exited with jobs in the local queue.",
            job: job.last
          }.to_json)
        end
      end
```

but we believe that having callbacks or middlewares specifically for reliable_push could greatly enhance its usability and resilience in such cases.

These callbacks or middlewares could allow users to intercept and handle situations where jobs are at risk of being lost due to process exits, enabling more comprehensive error tracking and recovery mechanisms. Our current solution is logging jobs, but in next iterations we would like to introduce some storage mechanism to set alerts for later retries or analysis.

Here are some potential use cases and benefits of such a feature:

- Detailed logging, storage or notification when jobs are in danger of being lost.
- Hooks for users to implement custom recovery or requeue strategies.
- Improved visibility and diagnostics for scenarios related to unexpected process terminations.
 
We understand that adding new features involves considerations about project direction, compatibility, and maintenance. However, we believe that this enhancement could significantly benefit the Sidekiq community, enhancing its reliability and making it even more robust for diverse production environments.

Would it be possible to discuss this feature request further or provide guidance on how the community or we could contribute to making this a reality? Your insights and feedback on the feasibility and potential implementation approach would be very valuable. Thanks

**Comment by salrepe** [comment]
Hi Mike,

Thanks for your prompt response. We understand your concerns, and we appreciate your suggestion to provide additional safety with our own patches.

To address the potential loss of jobs during unexpected process exits, our proposal is inspired by the `sidekiq_retries_exhausted` hook. We don't intend for Sidekiq to rely on log output, the filesystem, or any specific storage mechanism. Instead, we envision allowing the application using Sidekiq to decide how to proceed with the unpushed jobs.

We're considering two potential methods like for example:

1. `reliable_push_limit_reached`:
   This hook would be triggered when a limit is reached, enabling users to take specific actions for individual jobs.

   ```ruby
   reliable_push_limit_reached do |job|
     # Custom actions for handling the job
   end
   ```

2. `reliable_push_jobs_on_exit`:
   This hook would be invoked when jobs are in danger of being lost due to process exits, providing an opportunity for users to implement recovery strategies.

   ```ruby
   reliable_push_jobs_on_exit do |jobs|
     # Custom actions for handling the list of jobs
   end
   ```

About contributing to a Sidekiq Pro feature, what's the best way to go about it? If you have some guidance, that would be great.

Thanks again,

**Comment by mperham** [comment]
I'm not interested in further refinement of this feature. I don't believe your suggestions would add any more real world reliability. It requires the user to provide the code, would be hard to integration test and infrequently executed.

Look into reconciliation instead: https://www.mikeperham.com/2014/05/27/the-reconciliation-step/

**Comment by salrepe** [comment]
Alright,
We are not entirely sure how distinct this would be from 'sidekiq_exhausted_retries' on the server side, as both aim to provide an alternative when Sidekiq can't do anything else with the jobs.

In any case, thanks once more. We'll figure out how to handle it on our end.
