### ISSUE TITLE
Sidekiq 7 API Change - Sidekiq[:average_scheduled_poll_interval]

### ISSUE THREAD

**Issue by hughkelsey** [sidekiq/sidekiq#6155]
Ruby version: 3.2
Rails version: 7.1.2
Sidekiq version(s): 7.2.0

Hello, I am upgrading from 6.x to 7.2 and have some internal code that uses the `average_scheduled_poll_interval`.

`Sidekiq[:average_scheduled_poll_interval]
NoMethodError: undefined method '[]' for Sidekiq:Module`

I'm happy to contribute to the wiki but have been unable to find this value. I can access `Sidekiq.default_configuration` however I'm manually setting `average_scheduled_poll_interval` and the default is nil. My fallback would be to use an ENV var to set `average_scheduled_poll_interval` and the same value where I am reading the value back.

Could I ask for a hint on how to read this value? Thank you!

**Comment by mperham** [comment]
```ruby
Sidekiq.configure_server do |cfg|
  cfg[:average_scheduled_poll_interval] = 5
end
```

**Comment by hughkelsey** [comment]
Thank you @mperham . Once this is configured (I have that working and it is well documented), how do I read it back?

`Sidekiq.configure_server do |cfg|
  cfg[:average_scheduled_poll_interval] = 5
end

Sidekiq[:average_scheduled_poll_interval] NoMethodError: undefined method '[]' for Sidekiq:Module
`

In versions previous to 7 I would get the value of `5` back.

**Comment by mperham** [comment]
Try `Sidekiq.default_configuration[:average_scheduled_poll_interval]`

**Comment by hughkelsey** [comment]
PR is here if it's helpful - thank you!

https://github.com/sidekiq/sidekiq/pull/6157
