### ISSUE TITLE
Sidekiq paused the default queue for no reason after an upgrade 6.x -> 7.x

### ISSUE THREAD

**Issue by nthx** [sidekiq/sidekiq#6161]
Hi

I have performed an upgrade of Sidekiq from version 6 to 7 today.
Everything went fine except a single incident. The default queue was paused for no reason.

Apart from somebody misclicking in the UI is there any chance there is something inside Sidekiq that could pause the queue for some reason?
I have search the source code and found some occurrences of "*pause*", however not yet deeply analysed it.

Previous gem versions:
* sidekiq (6.5.10), sidekiq-pro (5.5.8), sidekiq-ent (2.5.3)
* sidekiq (7.1.6), sidekiq-pro (7.1.5), sidekiq-ent (7.1.2)

Best - Tomasz

**Comment by mperham** [comment]
I think someone else might have mentioned a similar issue once but it's not widespread. I don't believe the pause code was touched in any way so I don't know how it might get into that state.

**Comment by nthx** [comment]
I have read some source code since.
There is only one place I could find that possibly could do it "by itself"
* basic fetch enhanced for pro and super fetch.

However I don't use "super_fetch!" in my setup.

Do you think this code can somehow pause any queue: `BasicFetch` module of `Pro` version.
(I'm not posting any more code as I'm not sure if I even can share this)

**Comment by mperham** [comment]
I don't see how. 🤷🏻‍♂️ That code responds to pausing, the code to trigger the pause is in `sidekiq/pro/api.rb`.

**Comment by nthx** [comment]
I see. That's actually good news to me. I'll try to let you know my findings. Maybe it was a user misclick.
The button to pause has no confirmation popup of any sort.
It's also a new feature for us, so the the click may went unnoticed.

Thank you for your swift response @mperham Very appreciated.
Best of luck - Tomasz
