### ISSUE TITLE
[Discussion] Handling long-running jobs that are killed by deployments

### ISSUE THREAD

**Issue by calvincchen** [sidekiq/sidekiq#6163]
Ruby version: 3.2.2
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): 7.1.0 / 7.1.0 / 7.1.0

Hi all,

We've recently had a couple incidents with long-running (zombie) jobs that don't finish between deployments. Our application deploys every 15-30 minutes, and the cycle is as follows:
1. Long-running job (>30 minutes execution time) is picked up by a worker
2. New deployment, which sends a `Sidekiq::Shutdown` to the worker and kills the long-running job
3. `Sidekiq::Shutdown` is rescued and the long-running job is pushed to the front of the queue 
  i. Note that this step does not increment `retry` counters, which is understandable as the job didn't fail - it was interrupted

This creates a cycle where, if # of zombie jobs > concurrency of a queue, we can congest a queue and effectively take down a queue. No work ever finishes executing on that queue.

I understand that it's poorly written code that leads to these zombie jobs - jobs should be small and fast for a multitude of reasons including preventing this issue. However, non-performant code is shipped on occasion and these jobs are undetected until incidents arise. In a recent case, we added performance testing (ironic) to an existing job and this caused the job performance to degrade and become a zombie job.

Would love to hear y'all's thoughts and how/if you've encountered or addressed this issue in your systems!

Two options I have in mind that would require changes to Sidekiq (as opposed to me hacking away at middleware):
1. `Sidekiq::Shutdown` is considered a job failure and increments the retry counter
  i. This will cause more noticeable behavior change with `retry: 0` jobs killed by deployments or other usages of `Sidekiq::Shutdown` - the job will not be retried
2. An additional `attempts` option that functions similar to `retry`, but is incremented when the job is popped from the queue

**Comment by mperham** [comment]
I would recommend reviewing this gem and doc:

https://github.com/Shopify/job-iteration/blob/main/guides/best-practices.md

Ultimately I don't want to add further logic to Sidekiq as a band-aid for long-running jobs. What do you think?

**Comment by fatkodima** [comment]
> I would recommend reviewing this gem and doc:

For Sidekiq specifically: https://github.com/fatkodima/sidekiq-iteration

**Comment by fatkodima** [comment]
> is there a similar event system in sidekiq-iteration? I might've missed it in the docs.

There is no currently, but I am open for this feature.
