### ISSUE TITLE
Sidekiq 

### ISSUE THREAD

**Issue by esbelf** [sidekiq/sidekiq#6165]
I am running sidekiq on an ec2 instance on AWS with RDS postgreSQL size t3.medium. There are over 200 available connections on the DB. However, when I create a few threads in my sidekiq job, I get the basic error of not having enough pooled connections. However, this does not make sense since the database connection has a lot of available connections when I check the metrics on AWS. It is a self-inflicted error by sidekiq. I tried increasing the database.yml pool size, but it doesn't have an effect.

`could not obtain a connection from the pool within 5.000 seconds (waited 5.074 seconds); all pooled connections were in use (ActiveRecord::ConnectionTimeoutError)`

Ruby version: 3.2.1
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.6

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

---
:verbose: true
:concurrency: 3
:timeout: 10

:pidfile: ./tmp/sidekiq.pid

production:
  :concurrency: 10
  :timeout: 100
staging:
  :concurrency: 5

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
Sidekiq does not use or control anything about your database. Any pool issues are between your app and Rails. Your concurrency is 10 but the Rails pools defaults to 5. Set Sidekiq’s concurrency to 5.
