### ISSUE TITLE
Is there anyway to find the total memory usage Sidekiq of Rails Application.

### ISSUE THREAD

**Issue by abdulhanan001** [sidekiq/sidekiq#6170]
Ruby version: 2.6.3
Rails version: 6.0.3 and 7
Sidekiq version: 6.0.7

**Monitoring of Sidekiq Memory Usage and Cloud Watch Logs**
Problem:Right now, whenever the Sidekiq memory usage is high, we need to add a new worker. However, we also need to identify the reasons why certain jobs are taking more time or causing latency, leading to higher Sidekiq memory usage than normal.

Assumed proposed solution: 
Source: This approach is similar to what GitLab is doing, as explained in the provided blog from ETSI https://docs.gitlab.com/ee/administration/sidekiq/sidekiq_memory_killer.html

**Comment by mperham** [comment]
I don't understand what you are asking. You can profile your jobs using a memory or CPU profiler. You can find the RSS usage of a Sidekiq process using standard tools like `ps`.

**Comment by abdulhanan001** [comment]
@mperham  Apologies for the misunderstanding. In fact, we have created a CloudWatch alarm to trigger when the usage of the Sidekiq server exceeds a specific limit. However, I also want to monitor the reasons for which jobs are causing the problem or taking more time or RSS memory.

My solution is something like this .

```
module Sidekiq::Middleware::Server
  class SidekiqMemoryMonitor
    def call(worker, job, queue)
      Rails.logger.info("SidekiqMemoryMonitor called for job: #{job}")
      begin
        yield
      ensure
        log_memory_usage(worker, job)
      end
    end
  
    private

    def log_memory_usage(worker, job)
      if memory_exceeded?
        job_details = {
          jid: job['jid'],
          worker_class: worker.class.to_s,
          rss_memory_bytes: current_rss_memory
        }

        Rails.logger.warn("Job memory usage exceeded limit: #{job_details}")
      end
    end
  
    def memory_exceeded?
      max_rss_limit = ENV['SIDEKIQ_MEMORY_KILLER_MAX_RSS'].to_i
      current_rss_memory > max_rss_limit
    end
  
    def current_rss_memory
      `ps -o rss= -p #{Process.pid}`.to_i
    end

  end
end

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'] }

  config.server_middleware do |chain|
    chain.add Sidekiq::Middleware::Server::SidekiqMemoryMonitor
  end
end
```
I have created a middleware over Sidekiq to identify the memory usage of every job. If the job's RSS memory exceeds SIDEKIQ_MEMORY_KILLER_MAX_RSS, we will push the metrics to AWS.

However, this implementation focuses on individual job's RSS memory. Is there any way to find Sidekiq container's total RSS memory usage? If the entire container's memory usage exceeds 1GB or 2GB, an alarm will trigger in AWS. The metrics for those jobs will then be pushed from the server to AWS CloudWatch. This approach will help us identify the root cause or areas for optimization in the workers' code.
Those metrics contain {class_name: '', worker_rss_memory_usage: 'xyz', skidekiq_container_rss_memory: 'xyz'}.

**Comment by mperham** [comment]
I don't know. I don't use AWS and don't know what tools are available. You'll need to get help elsewhere.

**Comment by abdulhanan001** [comment]
Thanks @mperham for your help, I use middleware and memory profiler for tracking memory taking jobs.

**Comment by freemanoid** [comment]
`ps -o rss= -p #{Process.pid}` returns total process memory. If sidekiq concurrency is more than 1, then it will be hard to understand which exact job is memory hungry. 

@abdulhanan001, did you find a way to measure a single job memory usage in a multithreaded environment?
