### ISSUE TITLE
Testing Capsules

### ISSUE THREAD

**Issue by devsheva** [sidekiq/sidekiq#6172]
Hi, i got a few moments ago into the `Capsules` feature, cause I need to configure different concurrency for some queues. As the docs say the `Sidekiq.configure_server ` is not run in Testing mode, so how can we test a Capsule ? To maybe see if it sets up the options correctly ?

**Comment by mperham** [comment]
You start a Sidekiq process and manually verify. Your automated tests are for your code, not mine.
