### ISSUE TITLE
Feature Request : Silent redis connection

### ISSUE THREAD

**Issue by kriom** [sidekiq/sidekiq#6178]
Ruby version: 3.3.0
Rails version: 7.1.3
Sidekiq version: 7.2.1

This is not a real problem, just a feature request.
I'd like Sidekiq to connect to Redis silently
It doesn't seem possible to connect Redis without output.
https://github.com/sidekiq/sidekiq/blob/2f147f6619c102ed45c280ca0a809da3b164e38b/lib/sidekiq/redis_connection.rb#L15
Would it be possible to add an option to make this connection silent ?

When I run my auto parallelized tests on 16 threads I get this message 16 times: 
```
Sidekiq 7.2.1 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://redis:6379/0"}
```
If I'm not asking in the right place, please let me know and I'm sorry.

**Comment by mperham** [comment]
Set the logger level to WARN in your spec helper.

**Comment by kriom** [comment]
Thank you very much, it works very well, with this config  :

`config/environments/test.rb`
```ruby
Rails.application.configure do
  # ...
  config.after_initialize do
    # ...
    Sidekiq.logger.level = Logger::WARN
  end
end
```
