### ISSUE TITLE
Should Sidekiq log that it is connecting to Redis in testing mode?

### ISSUE THREAD

**Issue by marcelolx** [sidekiq/sidekiq#6181]
Ruby version: 3.3.0
Rails version: 7.1.2
Sidekiq / Pro / Enterprise version(s): 7.2.0 / 7.2.0 / NA

When we run our tests with `bin/rails test`, we are getting log messages that Sidekiq is connecting to Redis

```
2024-01-31T13:45:21.791Z pid=21069 tid=evh INFO: Sidekiq 7.2.0 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>nil}
```
And based on this comment https://github.com/sidekiq/sidekiq/issues/6009#issuecomment-1792577157, it looks like Sidekiq always connects to Redis even in test mode.

My question is, should Sidekiq log such action in test mode? Mainly because when you run your test suite, it will output a lot of logs that it is connecting to Redis which isn't really relevant if it always will connect anyway (see screenshot)

![image](https://github.com/sidekiq/sidekiq/assets/20196775/2a0d63f7-6ec4-4414-9a4b-6760b68fc9c2)

Essentially [this line](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/redis_connection.rb#L15) could log only when test mode is disabled

```ruby
if Sidekiq::Testing.disabled?
  logger&.info { "Sidekiq #{Sidekiq::VERSION} connecting to Redis with options #{scrub(symbolized_options)}" }
end
```

I'm not saying it has to be this way, but before Sidekiq v7, we didn't see those logs, so I'm a bit surprised they did start showing up once we upgraded.

Also including the initializer below in case we have something misconfigured.

```ruby
# config/initializers/sidekiq.rb
unless Rails.env.test?
  Sidekiq.configure_server do |config|
    config.redis = {url: Rails.configuration.redis_sidekiq["url"]}

    if Rails.env.production?
      config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new
      config.logger.level = Logger::WARN
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = {url: Rails.configuration.redis_sidekiq["url"]}
  end

  if Rails.env.production?
    ActiveJob::Base.logger = Logger.new(IO::NULL)
  end
end
```

**PS:** We have `require "sidekiq/testing"` in our `test/test_helper.rb` file.

**Comment by mperham** [comment]
In your spec_helper.rb:
```ruby
Sidekiq.default_configuration.logger.level = Logger::WARN
```

We log that line because connecting correctly to Redis is the number one support issue with Sidekiq. The user should see when Sidekiq tries to connect and the parameters it is using to connect.

**Comment by marcelolx** [comment]
I see; that makes sense to me!

Thanks for the extra context 🙌
