### ISSUE TITLE
Sidekiq-Ent Concurrent Rate Limiter Stuck with a Size of Zero

### ISSUE THREAD

**Issue by dmorehouse** [sidekiq/sidekiq#6185]
Our Production Sidekiq cluster had an issue today where the concurrent limit somehow ended up being zero. Our code uses a concurrent limit of 1 `Sidekiq::Limiter.concurrent('other_transactions', 1, wait_timeout: 10, lock_timeout: 30)`. However a look in the Sidekiq WebUI showed the size was 0. Given that the `lmtr-cfree, lmtr-cpend, lmtr-cused` variables are stored in Redis, once a single worker got into a bad state, ALL workers got into the same bad state. Once we figured out what was going wrong, we restarted a single worker and as soon as it restarted the size went back to 1 and ALL workers started processing jobs that had been failing due to the concurrency limiter having a size (concurrency) of 1.

We were alerted to the issue by Sentry which showed that we were seeing thousands of `RedisClient::ReadTimeoutError` errors. We would have expected `Sidekiq::Limiter::OverLimit` errors.

We have only seen this issue once (today) after several years running this same job with concurrent rate limiting. We are watching for it to happen again in pre-production with the hopes that it will help us figure out a path to reproduce.

Here's a simplified version of our Job (the DEFAULT_LIMIT line is EXACTLY what we use, with a hard-coded concurrency of 1)

```
class OurJob < ApplicationJob
  DEFAULT_LIMIT = Sidekiq::Limiter.concurrent('other_transactions', 1, wait_timeout: 10, lock_timeout: 30)

  def perform
    DEFAULT_LIMIT.within_limit do
      code_that_could_fail("isn't that all code")
      ...
    end
  end
```

While we have no path to reproduce how a worker got the size into a bad state. We are assuming it was only a single worker because we run 15 workers in production and what are the odds they all would encounter the same edge case. Also, restarted a single worker fixed ALL the workers. 

However, we can easily reproduce the exception that we were seeing while the size was zero. This code reproduces the RedisTimeout. Even with a size of 0, we would expect a `Sidekiq::Limiter::OverLimit` error.
`Sidekiq::Limiter.concurrent('zero_limiter', 0, wait_timeout: 5, lock_timeout: 60).within_limit { puts "You should NOT see me" }`

Here's what our Sidekiq Limits screen looked like during the issue.
<img width="1208" alt="image" src="https://github.com/sidekiq/sidekiq/assets/2547473/71da3697-389f-49b7-a395-f44a75996984">

Versions
Sidekiq: 7.0.9
Sidekiq-Pro: 7.0.8
Sidekiq-Ent: 7.0.6
Rails: 7.0.8
Redis: 6.2.6 (AWS ElastiCache Redis)

**Comment by mperham** [comment]
Hmm, I'm getting the OverLimit error as expected. Are you configuring a low read_timeout which conflicts with your 5 sec wait_timeout?

> irb(main) $ Sidekiq::Limiter.concurrent('zero_limiter', 0, wait_timeout: 5, lock_timeout: 60).within_limit { puts "You should NOT see me" }
2024-02-02T16:47:25.423Z pid=23072 tid=fzw INFO: Sidekiq 7.2.1 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>nil}
/Users/mperham/src/ent/lib/sidekiq-ent/limiter/concurrent.rb:123:in `block in lock': zero_limiter (Sidekiq::Limiter::OverLimit)


Also, you're on an older version. An upgrade would be appropriate.

**Comment by dmorehouse** [comment]
Hmmm something strong. We have not set a read_timeout so we are using the default. I'm on a M2 Macbook Pro using a Docker image of Redis 6.2.6. When I run it locally I get
```
Sidekiq::Limiter.concurrent('zero_limiter', 0, wait_timeout: 5, lock_timeout: 60).within_limit { puts "You should NOT see me" }
2024-02-02T18:01:53.829Z pid=10333 tid=1175 INFO: Sidekiq 7.0.9 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://localhost:6377/1"}
RedisClient::ReadTimeoutError: RedisClient::ReadTimeoutError

Sidekiq::Limiter.concurrent('zero_limiter', 1, wait_timeout: 5, lock_timeout: 60).within_limit { puts "You should see me" }
You should see me
```

After doing some upgrades, I've pinpointed the change from getting a `RedisClient::ReadTimeoutError` to `Sidekiq::Limiter::OverLimit` in a change between Sidekiq-Ent 7.0.6 and 7.0.7.

We'll do the point upgrade now and test the upgrade to 7.2 soon.
