### ISSUE TITLE
Access Queue within Job

### ISSUE THREAD

**Issue by OskarEichler** [sidekiq/sidekiq#6189]
@mperham Is it possible to access the current queue within a worker? I am able to grab the default queue via the sidekiq_options_hash, but in case a job is enqueued in a different queue it will still return the default options. 

I tried Sidekiq::Context.current but that only returns the class and jid. Would be great to be able to access the queue, and potentially the current retry count as well.

Ruby version: 3.2.1
Rails version: 7.1.3

**Comment by mperham** [comment]
No, by design. Queues are typically an Ops-concern and Jobs should be orthogonal to the name of the queue used. The only state Jobs can access are their arguments. There have been other people who've documented how they got around this issue but I can't find any examples offhand.
