### ISSUE TITLE
cannot use sidekiqmon with a unix file socket path

### ISSUE THREAD

**Issue by Aubermean** [sidekiq/sidekiq#6193]
I have tried `REDIS_URL=unix:///run/redis.sock bundle exec sidekiqmon` but that doesn't work.

In my initializer, I use ` config.redis = { path: '/run/redis.sock' }` which works fine. I set it via `REDIS_PATH` in my `.env` file.

It doesn't seem possible to use a unix file socket with `sidekiqmon`?

**Comment by mperham** [comment]
That’s not a deployment mode I want to support. It limits Sidekiq to localhost only.

**Comment by Aubermean** [comment]
Hi Mike. Thanks for the fast reply.

I understand your point of view. But on baremetal - 256 AltraMax cores and 2TB RAM - Unix File Sockets are great.

In the cloud/containers/k8s/microservices world it might not make much sense. But in the deployment model I support, Unix File Sockets have an /edge/ over 'localhost'. Performance improvements of 10-20% for Redis and Postgres to boot.

Not to mention the cost, heat, and energy savings. Good old fashioned running everything on one machine, hey! This single server could obliterate most other setups, Sidekiq really shines.

I understand your decision though. I just wanted to share my perspective. I'll find another way for process monitoring. Thank you!

**Comment by mperham** [comment]
I guess if it works with Sidekiq, it should work with sidekiqmon too. But this is a redis-client limitation according to this backtrace. @byroot 

```
Invalid URL: "unix:///run/redis.sock" (ArgumentError)

        raise ArgumentError, "Invalid URL: #{url.inspect}"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.19.1/lib/redis_client/config.rb:172:in `new'
	from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.19.1/lib/redis_client/config.rb:172:in `initialize'
	from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.19.1/lib/redis_client.rb:144:in `new'
	from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.19.1/lib/redis_client.rb:144:in `config'
	from /Users/mperham/src/sidekiq/lib/sidekiq/redis_client_adapter.rb:68:in `initialize'
	from /Users/mperham/src/sidekiq/lib/sidekiq/redis_connection.rb:22:in `new'
	from /Users/mperham/src/sidekiq/lib/sidekiq/redis_connection.rb:22:in `create'
	from /Users/mperham/src/sidekiq/lib/sidekiq/config.rb:139:in `new_redis_pool'
```

**Comment by mperham** [comment]
Oh, it's pending a release. https://github.com/redis-rb/redis-client/blob/9ea5a1fd94587a08276ea9b7668ffcbc6571f4ea/CHANGELOG.md#unreleased

**Comment by byroot** [comment]
`0.20.0` is out.

**Comment by Aubermean** [comment]
My thanks to you both for the fast and professional handling of this!
