### ISSUE TITLE
Running lifecycle event right before exiting

### ISSUE THREAD

**Issue by jlambert121** [sidekiq/sidekiq#6195]
We run sidekiq in ECS and are running into an issue where we now need to shutdown a thread after all jobs have finished processing.  ECS sends a (non-configurable) `SIGTERM` when tasks need to be stopped and all of or workers properly stop and things gracefully end as they should.  

We have a gem that starts a thread with its own internal queue that flushes on a schedule which needs to be stopped as part of shutdown to ensure it has flushed its queue.  The code we're using right now is:

```ruby
Sidekiq.configure_server do |config|

  config.on(:startup) do
    MyGem.start
  end

  config.on(:shutdown) do
    MyGem.stop
  end

end
```

The problem with this seems to be that the `:shutdown` block is run immediately when a `SIGTERM` is received rather than after the last job has finished (as I had hoped).  

Solutions I've thought of:
* (would be a great solution, but I don't think is an option I've been able to find) Have ECS send a `USR1` first
* Add a `sleep` or something else in the `:shutdown` block before the `.stop` (absolutely not ideal)
* Wrap `bundle exec sidekiq` with something that captures `SIGTERM` and instead passes `USR1` on to sidekiq (also pretty hacky)

Any other options for this?  Is there any sort of `cleanup` or `last call` signal?  Maybe a way to add a wait of some kind until there are 0 jobs currently running after a `SIGTERM`?

**Comment by mperham** [comment]
Ruby provides that with at_exit. Is there some reason you can’t use that?

**Comment by jlambert121** [comment]
I didn't even think about that, that should be perfect - thank you!  I was making this much harder than it needed to be.
