### ISSUE TITLE
Sidekiq Pausing/Unpausing Queues feature doesn't work 

### ISSUE THREAD

**Issue by evgeniagusakova** [sidekiq/sidekiq#6202]
Ruby version: 2.7.1
Rails version: 6.1.7
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.0.7 / Pro 7.0.7 / Ent 7.0.5

Hello! 
We are using Sidekiq Entreprise and for some reason the feature of pausing/unpausing Queues doesn't work for us not from rails console, not from UI (please see the video):

```
2.7.1 :001 > q = Sidekiq::Queue.new('active_storage_analysis')
2.7.1 :002 > q.pause!
 => false
2.7.1 :003 > q.paused?
 => false
2.7.1 :004 >
```
We've checked log changes in Pro-Changes.md and found that for Pro 7.0.9 version was some fix related to pause/unpause queues "Fix network logic which could have resulted in pause/unpause not working", so we've updated our Pro version to 7.0.10, but this did not solve the issue.
We really need to make this feature work. Could you please let us know what could be the problem?

https://github.com/sidekiq/sidekiq/assets/18736622/c08c8f4b-ede1-4d37-b2c6-94dcc2b6b3ea

**Comment by mperham** [comment]
Issue #5834 in 7.0.9 rewrote the pause listener to use the native redis-client pubsub API, rather than the older redis.rb API.

I don't know what's wrong, no one has reported this behavior but this might happen if Bundler doesn't require `sidekiq-pro`. Are you using `bundle exec` to start? Can you show us your initializer?

**Comment by evgeniagusakova** [comment]
Hello, 
Thank you for the answer!
Our `config/initializers/sidekiq.rb` is :
```
# frozen_string_literal: true

Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') }

  config.client_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Client
  end

  config.server_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Server
  end

  SidekiqUniqueJobs::Server.configure(config)
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') }

  config.client_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Client
  end
end

SidekiqUniqueJobs.config.lock_info = true
```
>Are you using bundle exec to start?

Yes, we are using the following command in systemd unit
```
ExecStart=/home/ubuntu/.rvm/bin/rvm 2.7.1 do bundle exec sidekiq -e production --config config/sidekiq/production.yml
```

**Comment by mperham** [comment]
I don’t know what’s wrong.
