### ISSUE TITLE
Web dashboard: Metrics filtering interacts badly with live polling.

### ISSUE THREAD

**Issue by MrJoy** [sidekiq/sidekiq#6203]
Ruby version: 3.2.2
Rails version: 7.1.3.2
Sidekiq / Pro / Enterprise version(s): 7.2.2 / 7.2.0 / N/A

When filtering the Metrics page for specific classes, the result is a page that has Live Polling functionality enabled (the normal Metrics view does not).  Because the parameters for filtering are passed via POST, and the live poll refresh looks only at the URL for what to fetch, the end result is that as soon as the polling interval occurs, the URL fetched is a GET that results in a redirect to the normal metrics page.  This winds up rendering incorrectly (no chart, checkboxes not rendering/working properly).

Presumably, either the filtering request API should be GET-based so the live polling refresh can make the correct request or the filtered metrics view shouldn't have live polling.

**Comment by mperham** [comment]
Filtering should not turn on Live Poll. That's a bug if true. Is that what you are reporting?

**Comment by MrJoy** [comment]
I didn't know what the intended behavior actually _was_, so...  If the intended behavior is as you say, then yes, that's what I'm reporting.

See screenshot:

<img width="2032" alt="image" src="https://github.com/sidekiq/sidekiq/assets/113625/17f324dc-5ca7-4217-9c45-75bb255a2f66">

**Comment by mperham** [comment]
Metrics is not designed to be used with Live Polling at all. You should turn it off and I should remove the ability in a future release.

**Comment by MrJoy** [comment]
I have it turned on because I use it for other pages where doing so is supported.  It appears to be a global setting, so disabling it here is disruptive to my usual workflow.  I have never intentionally turned it on on the metrics page.

A better workaround for my organization is to not use the metrics page at all and just set up an appropriate dashboard on DataDog.
