### ISSUE TITLE
Queue order execution

### ISSUE THREAD

**Issue by Stashchenko** [sidekiq/sidekiq#6220]
We expect to execute jobs in the strong order and only when higher priority queues are empty. 
According to the [doc](https://github.com/sidekiq/sidekiq/wiki/Advanced-Options#queues):
![image](https://github.com/sidekiq/sidekiq/assets/1535772/d8b525d2-0f98-4f8f-b4e2-62be5ff41f32)

However, sidekiq pickups **default** jobs when critical jobs in progress (theoretically, the critical queue is not empty, it's processing jobs)

### Versions 
Ruby version: 3.3.0
Rails version: 7.1.3.2
Sidekiq / Pro / Enterprise version(s):
sidekiq (7.2.2)
sidekiq-ent (7.2.2)
sidekiq-pro (7.2.0)

#### sidekiq.yml
```yml
---
:concurrency: <%=  ENV['SIDEKIQ_MAX_THREADS'] || ENV['RAILS_MAX_THREADS'] || 10 %>
:timeout: 60
:queues:
  - critical
  - high
  - medium
  - low
  - default
```

#### Example 
We've created 2 simple jobs `HighJob` & `MediumJob`. 

```ruby
class HighJob
  include Sidekiq::Job
  sidekiq_options queue: :high

  def perform
    sleep = rand(10)
    sleep(sleep) # simulate some long I/O work
    puts "HighJob = #{Time.now} , sleep = #{sleep}"
  end
end

class MediumJob
  include Sidekiq::Job
  sidekiq_options queue: :medium

  def perform
    sleep(2)
    puts "MediumJob = #{Time.now}"
  end
end
```

### Reproducing 

1. Create jobs via `rails c`
```ruby
100.times {|i| MediumJob.perform_async} 
50.times {|i| HighJob.perform_async} 
```

2. Run sidekiq server: `sidekiq -C config/sidekiq.yml`

##### Output result

```ruby
HighJob = 2024-03-08 13:07:24 +0200 , sleep = 9
HighJob = 2024-03-08 13:07:24 +0200 , sleep = 0
HighJob = 2024-03-08 13:07:24 +0200 , sleep = 0
HighJob = 2024-03-08 13:07:24 +0200 , sleep = 2
HighJob = 2024-03-08 13:07:24 +0200 , sleep = 2
HighJob = 2024-03-08 13:07:24 +0200 , sleep = 4
HighJob = 2024-03-08 13:07:26 +0200 , sleep = 2
HighJob = 2024-03-08 13:07:26 +0200 , sleep = 9
HighJob = 2024-03-08 13:07:26 +0200 , sleep = 8
HighJob = 2024-03-08 13:07:26 +0200, sleep = 3
HighJob = 2024-03-08 13:07:27 +0200 , sleep = 5
HighJob = 2024-03-08 13:07:28 +0200, sleep = 1
HighJob = 2024-03-08 13:07:28 +0200 , sleep = 5
MediumJob = 2024-03-08 13:07:28 +0200
MediumJob = 2024-03-08 13:07:28 +0200
MediumJob = 2024-03-08 13:07:29 +0200
MediumJob = 2024-03-08 13:07:29 +0200
HighJob = 2024-03-08 13:07:30 +0200 , sleep = 7
MediumJob = 2024-03-08 13:07:30 +0200
MediumJob = 2024-03-08 13:07:30 +0200
MediumJob = 2024-03-08 13:07:30 +0200
HighJob = 2024-03-08 13:07:31 +0200 , sleep = 7
MediumJob = 2024-03-08 13:07:31 +0200
MediumJob = 2024-03-08 13:07:31 +0200
MediumJob = 2024-03-08 13:07:31 +0200
MediumJob = 2024-03-08 13:07:32 +0200
HighJob = 2024-03-08 13:07:32 +0200 , sleep = 8
HighJob = 2024-03-08 13:07:32 +0200 , sleep = 8
MediumJob = 2024-03-08 13:07:32 +0200
MediumJob = 2024-03-08 13:07:32 +0200
MediumJob = 2024-03-08 13:07:32 +0200
MediumJob = 2024-03-08 13:07:33 +0200
MediumJob = 2024-03-08 13:07:33 +0200
```
As we can we from the log above the `MediumJob` starts working even when `HighJob` still in progress.

Is it ok ? If yes, how to achieve strong order until higher queue is truly empty (in-progress jobs too).

#### Expected result

The medium queue should start only when the higher queue is truly empty (including in-progress jobs )

**Comment by mperham** [comment]
Sidekiq does not guarantee execution ordering or concurrency. The only actual way to guarantee execution ordering is with Sidekiq Pro's Batches and callbacks.

**Comment by Stashchenko** [comment]
> Sidekiq does not guarantee execution ordering or concurrency. The only actual way to guarantee execution ordering is with Sidekiq Pro's Batches and callbacks.

Thank you for your prompt response. We understand that Sidekiq does not guarantee strict ordering of execution or concurrency, which aligns with our expectations.

However, our concern stems from the documentation's indication that Sidekiq will prioritize low priority jobs only when high priority jobs are empty. In practice, we have observed a deviation from this behavior.

**Comment by mperham** [comment]
> Sidekiq will prioritize low priority   ~~jobs~~ _queues_ only when high priority ~~jobs~~ _queues_ are empty
