### ISSUE TITLE
Cron parser fails to update offset when calling `last` after daylight saving time change in US

### ISSUE THREAD

**Issue by bhb** [sidekiq/sidekiq#6223]
Ruby version: 3.2.2
Rails version: 7.0.8.1
Sidekiq / Pro / Enterprise version(s): 7.2.1/ 7.2.0 / 7.2.1

We recently "lost an hour" due to daylight savings time. The next day, I noticed that `Sidekiq::CronParser` reports the last time a job was run was roughly 24 hours ago, but in reality, Sidekiq ran the job 23 hours ago (which is correct).

I realize you are using a fork of [this gem](https://github.com/siebertm/parse-cron/blob/master/lib/cron_parser.rb), so if you prefer, I can file the bug on that repo.

Repro:

```ruby
parsed_schedule = Sidekiq::CronParser.new("0 1 * * *") # daily, 1AM
time = Time.zone.parse("2024-03-11 01:00:00 -0600")    # day after DST change
last_time = parsed_schedule.last(time)

(time - last_time) / 1.hour # 24 hours

# Actual UTC times from my logs (this is correct!)
x1 = Time.zone.parse("2024-03-10 01:00:00 -0700")
x2 = Time.zone.parse("2024-03-11 01:00:00 -0600")
(x2 - x1) / 1.hours # 22.9 hours (almost 23, not 24 hours)

# Note the difference between last_time and x1 (the offset is different)
last_time.to_s # "2024-03-10 01:00:00 -0600"
x1.to_s        # "2024-03-10 01:00:00 -0700"
```

**Actual:** Sidekiq behavior is correct, but `CronParser#last` incorrectly reports that the previous scheduled time is 24 hours ago.
**Expected:** Sidekiq behavior stays the same, but `CronParser#last` correctly reports the previous scheduled time was 23 hours ago.

**Comment by mperham** [comment]
I think the history records are probably more reliable for getting runtimes.

I don’t plan to ever touch the cron time handling code again. Unless there’s a bug leading to Bad Things Happening, I’m going to close as Won’t Fix. It’s impossible to reliably test all the various edge cases so I’d prefer to leave it as is.

**Comment by bhb** [comment]
I've noticed that jobs are also scheduled at the incorrect time for some period after we "spring forward" (lose an hour).

We have this entry in `config/sidekiq_schedule.yml`

```
bulk_loan_job:
  cron: "0 12 * * *"
  class: "::Billing::BulkLoanJob"
```

Looking at our logs for the message "Enqueued periodic job ::Billing::BulkLoanJob", they occur the following times

* `03/07/2025 12:00:00.012 PM -0700` (as expected, the job runs at noon)
* `03/08/2025 12:00:00.009 PM -0700` (as expected, the job runs at noon)
* `03/09/2025 1:00:01.475 PM -0600` (this not what I would expect. The time shifted at 2AM, so I would expect this to run at noon)
* `03/10/2025 12:00:00.009 PM -0600` (as expected. The time has shifted and the job runs at noon)
