### ISSUE TITLE
Process Failing Silently for Specific Queue After Upgrading from 5.x to 6.x/7.x

### ISSUE THREAD

**Issue by urbanmarcin** [sidekiq/sidekiq#6226]
Sidekiq version: Upgraded from 5.x to 6.x/7.x
Ruby version: 3.0.6p216
Rails version : 7.0.6

After upgrading Sidekiq from version 5.x to 6.x or 7.x, we have encountered an issue where the process for one of our busiest queues is failing silently. Unlike job failures, which are typically logged or retried the entire process for this particular queue stops processing jobs without logging any errors or exceptions. This issue was not present in version 5.x, where the queue operated as expected.

Additional Context:
The issue is isolated to one specific queue with a high volume of jobs.
This issue still exists for latest version sidekiq (7.2.2).
Any insights into potential breaking changes between these versions that could affect queue processing would be highly appreciated.

**Comment by mperham** [comment]
What version of Redis are you using?

**Comment by urbanmarcin** [comment]
redis: 7.0.11

**Comment by mperham** [comment]
I'm not aware of any issues which break upgrades. Can you debug further and report back any findings?

**Comment by urbanmarcin** [comment]
I'm closing it as we found root cause. Together with sidekiq we upgraded rmagick which was causing this issue.
