### ISSUE TITLE
Feature request: Ability to pause/reenqueue long running jobs during deployments

### ISSUE THREAD

**Issue by sobrinho** [sidekiq/sidekiq#6228]
Ruby version: 3.2
Rails version: 7.1
Sidekiq / Pro / Enterprise version(s): Latest

Not sure worth to have this on Sidekiq but putting here for discussion.

We have some jobs that might take days to complete (to backfilling data on heavy migrations, for instance) that might take days to complete when they start.

The problem is that Sidekiq is killed at least once a day on Heroku and after a few days (or a few deploys), Sidekiq thinks that the job is a poison pill while it's not, it's just slow.

Would be nice to have a way either to disable the poison pill check (seems dangerous) or to be able to handle a deployment/restart gracefully.

Example:

```ruby
def perform
  # From one real example we have 2_000_000_000 on that table:
  Something.where(something: false).find_each do |record|
    record.do_something!

    # I could safely pause here and re-enqueue that job to be continued by another process
    if Sidekiq.shutting_down?
      self.class.perform_async
      break
    end
  end
end
```

**Comment by mperham** [comment]
Try the [sidekiq-iteration](https://github.com/fatkodima/sidekiq-iteration) gem.

**Comment by sobrinho** [comment]
To provide more context, I don't want more than one record doing that thing at the same time meaning we can't use separate jobs for different set of records or one job per record in a batch.

A while back I did something like this but it's not exactly pretty:

```ruby
def perform(id = nil)
  Something.where(something: false).find_in_batches(start: id) do |records|
    records.each do |record|
      record.do_something!
    end

    self.class.perform_async(records.last.id)
    break
  end
end
```

**Comment by sobrinho** [comment]
Awesome, I will give it a try!
