### ISSUE TITLE
Compatibility with Elasticache serverless?

### ISSUE THREAD

**Issue by key88sf** [sidekiq/sidekiq#6229]
Hi - wondering if there are any plans to make Sidekiq compatible with the new AWS Elasticache "serverless" redis cache? I believe they are using Redis in cluster mode.  Right now when connecting sidekiq to a serverless cache, there are a few different errors like the connection timing out after a couple seconds, to a redis error: `RedisClient::CommandError: CROSSSLOT Keys in request don't hash to the same slot`

**Comment by mperham** [comment]
The key word in your issue is "cache". I imagine most of their usecases are for caching or similar. Do you know of any other job systems which support it?

Sidekiq's data model was not designed for cluster distribution. I'd need to completely redesign how most of Sidekiq's functionality works and provide an upgrade path for compatibility. OTOH it would provide basically infinite horizontal scalbility to Sidekiq.

**Comment by key88sf** [comment]
Yeah this is a pretty new feature from AWS, and I don't know of any other job systems supporting it (yet). It would definitely be awesome if Sidekiq could use it. As an aws customer it's so much easier to not have to worry about picking the right instance size, scaling it out, etc. Thank you.

**Comment by mperham** [comment]
I see the advantages but it's a big lift under the covers.

**Comment by lorrin** [comment]
I wonder if ElasticCache Serverless supports [Redis hash-tags](https://redis.io/docs/reference/cluster-spec/#hash-tags) for directing data to a shard? As [discussed before in the context of AWS MemoryDB](https://github.com/sidekiq/sidekiq/issues/5899), that would make the Sidekiq changes much less involved. That made sense in the MemoryDB context: even with all the data in a single slot, you get durability benefits from the synchronous log replication of its storage engine. Not sure if ElastiCache Serverless would play nicely with all data in a single slot.

**Comment by lorrin** [comment]
Yes, understood. My suggestion has always been to use a single hash-tag value. In the case of MemoryDB, that gets you durability other Redis implementations cannot provide.

I read a bit more about Elasticache Serverless, its scaling is [done via dynamic shard additions](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.deployment.html), so it seems highly likely that using a single hash-tag value wouldn't work out well with it.

**Comment by mperham** [comment]
Using a single hash tag boils down to forcing all of Sidekiq’s data onto a single cluster member. I don’t see how that durability is any better than a standard sentinel setup.

**Comment by lorrin** [comment]
The MemoryDB shard's primary node synchronously [writes all data to a multi-AZ transaction log](https://aws.amazon.com/memorydb/faqs/). The log is then async applied to the shard's read replicas. If the primary node were to fail, one of the replicas would fully catch up with the transaction log and then start taking traffic. Possibility of availablity interruption if the read replicas need time to catch up, but no possibility of data loss (excepting scenarios where all the AZs are lost).

The ability to replicate the transaction log to other AZs fast enough to put it in the synchronous request path is the magic sauce.

Redis Sentinel uses async replication and [does not guarantee that acknowledged writes are retained during failures](https://redis.io/docs/management/sentinel/#fundamental-things-to-know-about-sentinel-before-deploying).
