### ISSUE TITLE
An error is appearing on the Sidekiq web UI 

### ISSUE THREAD

**Issue by SelvaganapathiMani** [sidekiq/sidekiq#6230]
**Problem :**
Sometimes, when viewing the Sidekiq web page in the scheduled section, an error appears like the one below. However, after refreshing the page, the error disappears, but it reappears upon refreshing again. What is causing this issue?, and how can it be fixed?

'Undefined method 'map' for nil::NilClass'

Ruby version: 2.5.0
Rails version: 5.2.8
Sidekiq :  6.5.5
redis, '~> 5.0', '>= 5.0.1

![Screenshot from 2024-03-16 15-20-50](https://github.com/sidekiq/sidekiq/assets/46549629/b62a9479-43b2-4534-9a7e-f391cfbcc422)

![Screenshot from 2024-03-15 10-29-15](https://github.com/sidekiq/sidekiq/assets/46549629/aa9cbdbf-b4b2-4765-9d1f-704e47775b57)

```require 'sidekiq/gc_middleware'
require 'sidekiq-scheduler'
require 'sidekiq/launcher'
require 'sidekiq/extensions/launcher'

Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://' + Rails.configuration.x.redis[:server] }
  config.server_middleware do |chain|
    chain.add Sidekiq::GCMiddleware
  end

  config.on(:startup) do
    # Core Jobs
    schedule = YAML.load_file( 'sidekiq_scheduler.yml')

    # Merging environment based jobs
    yml_file_path = File.expand_path('config/sidekiq_scheduler.yml', Dir.pwd)
    schedule.merge!(YAML.load_file(yml_file_path)) if File.exists? yml_file_path
    Sidekiq.schedule = schedule
    SidekiqScheduler::Scheduler.instance.reload_schedule!
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://' + Rails.configuration.x.redis[:client] }
end

Sidekiq.default_job_options['retry'] = 5

Mail.eager_autoload!
```

**Comment by mperham** [comment]
No idea. Never seen that error before.

**Comment by mperham** [comment]
Are you sure that's not a sidekiq-scheduler bug?
