### ISSUE TITLE
Does `perform_inline` requeue/retry..?

### ISSUE THREAD

**Issue by chancancode** [sidekiq/sidekiq#6235]
Sorry this is more of a question! (Or maybe missing documentation?)

I find myself wanting to write code like this:

```rb
begin
  # Preferably we would like to do this synchronously
  NonCriticalJob.perform_inline
rescue RateLimitError
  # But if it didn't work out, no big deal, do it later
  NonCriticalJob.perform_async
end
```

...but reading the code I cannot convince myself 100% that this is ok or necessary. Specifically, I am not sure if `.perform_inline` would raise any errors at all, and whether the normal retry behavior is in force for "inline" jobs.

I would _think_ `.perform_inline` does what it sounds like, run the job synchronously and raise any errors synchronously, and then that would be it. However, looking at the code, it is still wrapped around the "middleware" code, and I cannot tell if the retry behavior is managed by one of those middleware.

Happy to help document this somewhere if I can get this answered. Not sure what would be a good place for it, perhaps in the docs for `.perform_inline`?

**Comment by mperham** [comment]
Perhaps the docs need a note but Sidekiq’s retry is baked into the server, it’s not a middleware. In-line execution will raise an error, not retry.

**Comment by chancancode** [comment]
Thanks! That's what I would have expected, but good to have confirmation!

**Comment by mperham** [comment]
PS it's been years since I last heard from you. I hope you are well!

**Comment by cpb** [comment]
Vancouver misses @chancancode too!
