### ISSUE TITLE
can't boot sidekiq on AWS (Amazon Linux 2023)

### ISSUE THREAD

**Issue by thushw** [sidekiq/sidekiq#6238]
I can't boot sidekiq on AWS EC2 on the latest two versions of sidekiq. There is an issue related to `psych` and it fails as shown on screenshot.

The only change I made was to update the sidekiq gem from 7.2.0

Ruby version: 3.2.2
Rails version: 7.1.3
Sidekiq / Pro / Enterprise version(s): 7.2.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

![sidekiq-7 2 1-error](https://github.com/sidekiq/sidekiq/assets/1197851/8c6d1e87-c664-4fee-b758-7abd948022c2)

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

I tried upgrading from 7.2.0 to 7.2.2 (the latest) and hit this error. Then I tried to move to 7.2.1

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
It sounds like you’ve got a bad Ruby install. I don’t know the fix.

**Comment by romiras** [comment]
This issue is due to bad Ruby installation. Try to do as told in a message.

**Comment by romiras** [comment]
@thushw 
are any updates on issue?
