### ISSUE TITLE
Rack version holding back updates

### ISSUE THREAD

**Issue by garytaylor** [sidekiq/sidekiq#6239]
Ruby version: 3.2.2
Rails version: 7.1.3
Sidekiq / Pro / Enterprise version(s):

Our system is unfortunately running on azure and microsoft don't seem to do open source very well.  Redis version has been stuck at 6.0.x for a long time now and there is always talk of version 7 coming along 'in the summer'.  Thats such a clever timescale because it doesn't mention the year. 

I believe it was expected last year, but I see no sign of it yet.

This is holding us back from moving to sidekiq 7.x.x - and the problem is, the 6.x.x version is now getting old and demands rack version 2 as an example.  This is preventing our entire project from moving forwards.

**Comment by mperham** [comment]
What concrete action do you expect me to take?

**Comment by garytaylor** [comment]
Sorry @mperham I missed your response

Im unsure as I dont understand the reason why 6.x holds it back ?

Maybe 6.x could just specify rack must be at least 2 - so in the gemspec

```ruby

gem.add_dependency "rack", ">= 2.2.4"

```

just like the latest master.

Im sure there are going to be many other people who will need to remain on version 6.x.x so it makes sense to update it in similar ways to 7.x.x in terms of dependencies wherever possible.

If you agree with the solution, I could put in a PR ?

**Comment by mperham** [comment]
Sidekiq 6 is locked to Rack 2. That’s by design, it will never support Rails 7.1. If you want Rack flexibility and support modern Rails, you need to upgrade to Sidekiq 7.
