### ISSUE TITLE
`unique_for` locks are not cleared when inline jobs finish

### ISSUE THREAD

**Issue by sjahu** [sidekiq/sidekiq#6246]
(re enterprise unique jobs)

When a job with `unique_for` set is executed asynchronously, the lock is cleared when the job starts or succeeds, depending on the `unique_until` setting. (And, of course, when an async job fails, it's put in the retry queue.)

When `unique_for` is set and a job is executed **inline** (`perform_inline`, `perform_sync`), however, the unique lock is not cleared when the job succeeds nor fails (nor starts, if `unique_until: :start` is set). Subsequent attempts to perform the job, either inline, again, or asynchronously, fail with a "Skipping enqueue ... not unique" message until the specified amount of time has passed.

I don't think the expected behaviour for `unique_for` + `perform_inline` is documented, but this feels like a bug to me. I'd expect locks to be cleared similarly to how they are for async jobs, though since inline jobs do not retry, an "until success" lock should probably be cleared even if the job has failed. 🤔

What do you think? Bug, or am I using it wrong? Thanks for your help.

(Setting `unique_for` on a job performed inline doesn't make a lot of sense anyway, so I'll probably change this in our app.)

---

Ruby version: 3.2.1
Rails version: 7.1.3.2
Sidekiq / Pro / Enterprise version(s): 7.2.2 / 7.2.0 / 7.2.2

**Comment by mperham** [comment]
Unique does not automatically integrate with inline. Because inline executes outside of the server process, the server middleware is not automatically configured. This is true of any Sidekiq functionality which depends on server-side middleware.

You'd need to manually add unique's server middleware:

```ruby
Sidekiq.configure_client do |cfg|
  cfg.server_middleware do |chain|
    chain.add Sidekiq::Enterprise::Unique::Server
  end
end
```

https://github.com/sidekiq/sidekiq/blob/cee6f0eb36fe71a4300ccd715c0cf5bd2ab1d9d0/lib/sidekiq/job.rb#L228

**Comment by sjahu** [comment]
Interesting, thanks for the tip!

Inline executes outside of the server process, and the middleware must be configured in order to _clear_ locks properly, but it seems like the locks are checked before executing inline even when the middleware isn't set up?

Anyway, sounds like this is behaving as expected? Feel free to close this.

Cheers

**Comment by mperham** [comment]
Correct, as expected. The client-side middleware is always configured. The server-side middleware is not required or loaded in order to minimize Sidekiq's memory overhead when running in a non-Sidekiq process. You'd need to load the server middleware manually as noted above.
