### ISSUE TITLE
Batch has a non-existent pending job that prevents it's completion.

### ISSUE THREAD

**Issue by rockwellll** [sidekiq/sidekiq#6250]
Ruby version:  3.3.0
Rails version:  7.1.3.2

Sidekiq / Pro / Enterprise version(s): 7.2.0

Hi there, we're using Batches to invoke a process in two steps. Once the first step finishes, it should invoke the second step. We've just encountered a weird case where the first step is never marked as complete because there's a pending job still to be executed, but the job cannot be found anywhere.

<img width="1376" alt="Screenshot 2024-04-12 at 3 45 48 PM" src="https://github.com/sidekiq/sidekiq/assets/38360603/197c5125-dcb8-4550-b05b-909ec97b9d11">

Normally, Sidekiq the pending jobs in the same page. But we're not seeing anything for the pending jid in this batch.

**Comment by mperham** [comment]
This is typically the type of job loss where super_fetch will recover the job. Are you using super_fetch? Have you restarted your Sidekiq processes recently to trigger job recovery?

**Comment by mperham** [comment]
Any other mysterious errors or log output associated with that JID?

**Comment by rockwellll** [comment]
> This is typically the type of job loss where super_fetch will recover the job. Are you using super_fetch? 

No, we were not using it. We've just enabled it.

> Have you restarted your Sidekiq processes recently to trigger job recovery?

Yes, but it seems that job is lost.

> Any other mysterious errors or log output associated with that JID?

We found none across the logs.

**Comment by mperham** [comment]
Definitely enable it. If the job is lost, you'll need to run your batch callback code manually or otherwise recreate a new job with that same JID and BID.

**Comment by rockwellll** [comment]
Thanks!
