### ISSUE TITLE
Sidekiq bypasses Redis proxy?

### ISSUE THREAD

**Issue by junket** [sidekiq/sidekiq#6256]
Ruby version: 3.2.3
Rails version: 7.1.3
Sidekiq / Pro / Enterprise version(s): 7.2.2

On a default and local install of Rails, only `sidekiq` and `toxiproxy` have been added to `Gemfile`. Default Redis is running and available on port `6379`. The goal is to force Sidekiq to enqueue jobs through a proxy on port `22222` that can simulate network latency/outage conditions.

However, Sidekiq does not use the proxy even when explicitly provided as the `url`. As a result, `AnyJob.perform_later` enqueues normally even when the proxy is mangled. Inspecting Sidekiq's Redis connection via console suggests it is using the default port `6379` and not `22222` as provided in the config.

Simple steps to reproduce:
1. Sidekiq:
```
# sidekiq.rb
Rails.application.config.active_job.queue_adapter = :sidekiq

Sidekiq.configure_server do |config|
  config.redis = { url: "redis://127.0.0.1:22222" }
end

Sidekiq.configure_client do |config|
  config.redis = { url: "redis://127.0.0.1:22222" }
end
```

2. Proxy:
```
# toxiproxy.rb
require 'toxiproxy'

Toxiproxy.populate([
  {
    name: "redis",
    listen: "127.0.0.1:22222",
    upstream: "127.0.0.1:6379"
  }
])
```

3. Console:
```
$ Sidekiq.redis { |conn| conn.info }['tcp_port']
=> "6379"
```

Thank you for any light you can shed. And apologies if I have done anything moronic 😬

**Comment by mperham** [comment]
Well, yeah. You asked Redis for its info and Redis is running on port 6379. Toxiproxy is running on 22222.

**Comment by mperham** [comment]
```
Sidekiq.redis { |conn| conn }
=> 
#<Sidekiq::RedisClientAdapter::CompatClient:0x0000000106ceb6f0
 @_pipeline_class=Sidekiq::RedisClientAdapter::CompatClient::Pipeline,
 @client=#<RedisClient redis://localhost:6379/0>>
```

**Comment by junket** [comment]
Thank you! So then how might I get the `RedisClient` used here inside `Sidekiq::RedisClientAdapter` to actually use the proxy as provided to the config?

**Comment by mperham** [comment]
How do you know it's not? You're not looking at the right value. Do this:

> Sidekiq.redis { |conn| conn }

**Comment by mperham** [comment]
`conn.info` is not information about the client connection. It is calling Redis and running the `INFO` command, which returns Redis server data. Redis is running on port 6379 so that's the value of the `tcp_port` element in the INFO results hash.

**Comment by junket** [comment]
Oy, got it. Thank you, you're right of course. `SidekiqClientAdapter` has `@client=#<RedisClient redis://127.0.0.1:22222/0>`. So I guess I just don't know why Sidekiq enqueues jobs successfully even when that proxy on `22222` is down ¯\_(ツ)_/¯
