### ISSUE TITLE
Feature: `attr_reader` for `LeakyBucket` config options

### ISSUE THREAD

**Issue by stevenou** [sidekiq/sidekiq#6259]
`Sidekiq::Limiter::Window` has `attr_reader :interval, :count, :bucket` and `Sidekiq::Limiter::Bucket` has `attr_reader :interval, :count`.

I propose adding `attr_reader` for the configuration options to the limiters that don't have it. I could specifically use it on `Sidekiq::Limiter::LeakyBucket`, which doesn't have any attribute readers. It would be nice to expose the `size` and `interval`. 

My use case is that I'm reading the limiter when hitting `OverLimit` error and using the limiter config details to calculate an optimal backoff time (see discussion in https://github.com/sidekiq/sidekiq/issues/6141)

**Comment by mperham** [comment]
Thanks for the suggestion, it’s a good idea. 👍🏻
