### ISSUE TITLE
Information request about redis partitioning

### ISSUE THREAD

**Issue by vvayngart1** [sidekiq/sidekiq#6261]
ruby-2.7.6
rails 6.1.7.6
Sidekiq (6.5.12)
redis_version:4.0.9
Sidekiq-pro (5.5.5)

Good afternoon

I'm looking for information on the following topic:

I'm currently running several dozens of different types of Sidekiq workers.  They all share the same instance of Redis.  1 worker out of all uses 90% of Redis Sidekiq memory.  I'd like to partition it to a separate instance of Redis and keep others on the current Redis instance

- Is it possible?
- What's the best way to go about it (e.g. config/code changes examples or link to documentation would be greatly appreciated)

NOTE1:

- I also realized that there are middleware (client and server) hooks that are available to do the preprocessing of the jobs, with an example [here](https://github.com/sidekiq/sidekiq/blob/e57a47e700978fd4e5c21cfb907409a72f18c32e/lib/sidekiq/middleware/chain.rb#L71)

Questions:
- Is it possible to change the `redis_pool` value to point to another instance of redis based on the `job_class` value?
- is it possible to modify `msg` to be enqueued to Redis by Sidekiq after executing the client middleware hook?

**Comment by mperham** [comment]
`sidekiq_options` supports a `pool` option if you wish to shard a certain subset of jobs to another Redis. More info:

https://github.com/sidekiq/sidekiq/wiki/Sharding

**Comment by vvayngart1** [comment]
From https://github.com/sidekiq/sidekiq/wiki/Sharding

`You need to spin up Sidekiq processes to execute jobs from each Redis instance. A Sidekiq process only executes jobs from a single Redis instance.`

Do u mind explaining what that means?

**Comment by mperham** [comment]
You will have a big Redis (for your big job type) and a small Redis (for others). You will need a Sidekiq process for each Redis. A Sidekiq process can only process jobs from one Redis.
