### ISSUE TITLE
failed_at field is empty for the job in the DeadSet

### ISSUE THREAD

**Issue by freemanoid** [sidekiq/sidekiq#6262]
Ruby version: 2.7.6
Rails version: 6.1.7
Sidekiq / Pro / Enterprise version(s): 7.2.3/ 7.2.0

The `failed_at` value for the [job is set when](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/job_retry.rb#L153-L159) `Sidekiq::JobRetry#process_retry` is called. Also, the job doesn't go into the `DeadSet` if `retry: false`.

However, it looks like we sometimes have jobs in the deadset that were retried but `failed_at` was never set for them.

```ruby
Sidekiq::DeadSet.new.find { |c| !c["failed_at"] }

=> #<Sidekiq::SortedEntry:0x00000000229cdc00 @args=nil, @value="{\"retry\":2,\"queue\":\"unicorns\",\"args\":[{\"tree_id\":\"42\"}],\"class\":\"UnicornProcessorJob\",\"jid\":\"fefe95a1172e5208518a11c\",\"created_at\":1713484819.898677,\"enqueued_at\":1713484819.898767}", @item={"retry"=>2, "queue"=>"unicorns", "args"=>[{"tree_id"=>"42"}], "class"=>"UnicornProcessorJob", "jid"=>"fefe95a1172e5208518a11c", "created_at"=>1713484819.898677, "enqueued_at"=>1713484819.898767}, @queue="unicorns", @score=1713864372.1318684, @parent=#<Sidekiq::DeadSet:0x0000000012319450 @name="dead", @_size=49999>>
```

Am I right that it should never happen? If yes, what could be the potential reason for that?

**Comment by mperham** [comment]
It can happen, two examples: https://github.com/sidekiq/sidekiq/blob/e57a47e700978fd4e5c21cfb907409a72f18c32e/lib/sidekiq/processor.rb#L158

https://github.com/sidekiq/sidekiq/blob/e57a47e700978fd4e5c21cfb907409a72f18c32e/lib/sidekiq/api.rb#L558

Jobs can be killed in the Web UI too.

**Comment by freemanoid** [comment]
Ok, so if we can parse the JSON like this:

```ruby
job = Sidekiq::DeadSet.new.find { |c| !c["failed_at"] }
JSON.parse(job.value)
```

Also, I couldn't find a button on the UI and we can confirm that the job was not killed through the API, are there any other obvious reasons?

**Comment by mperham** [comment]
Those are the only reasons that come to mind.

**Comment by freemanoid** [comment]
Well, here is the answer. The job was super long-running and was killed as a poison pill after multiple retries. The reason found. Thank you for the ideas. Probably in that case it's correct that there is no `failed_at` attribute set for the job.
