### ISSUE TITLE
After bumping Sidekiq from 7.1.1 to 7.2.2, the Chrome browser is not displaying the dashboard and history.

### ISSUE THREAD

**Issue by amagasu** [sidekiq/sidekiq#6265]
Ruby version: 3.1.2
Rails version: 6.0.6
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 7.2.2

After bumping Sidekiq from 7.1.1 to 7.2.2, the Chrome browser is not displaying the dashboard and history.

Safari(7.0 (19616.1.27.211.1)) is displaying the dashboard and history.
<img width="500" alt="スクリーンショット 2024-04-24 10 49 57" src="https://github.com/sidekiq/sidekiq/assets/36068058/eddf2ac1-a079-4060-b0fc-3469718531cc">

Chrome (124.0.6367.80（Official Build） （arm64）)
<img width="500" alt="スクリーンショット 2024-04-24 10 50 10" src="https://github.com/sidekiq/sidekiq/assets/36068058/72577745-f234-4640-8a0e-d55cf199b561">

**Comment by mperham** [comment]
7.2.2 has been out for months now but you are the first to report this. I suspect you might have a problem with an extension?

**Comment by mperham** [comment]
Look for errors in  the JavaScript console.

**Comment by amagasu** [comment]
Thank you!
JavaScript erros is not found!
`failedLabel: fail` is found in html.

```
{"processedLabel":"success","failedLabel":"fail","labels":["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""],"processed":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"failed":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"updateUrl":"/sidekiq/stats"}
```

<img width="500" alt="スクリーンショット 2024-04-24 11 04 58" src="https://github.com/sidekiq/sidekiq/assets/36068058/086f6c36-60cd-4ccc-a2b5-d2c7db25e0a6">
<img width="500" alt="スクリーンショット 2024-04-24 11 06 42" src="https://github.com/sidekiq/sidekiq/assets/36068058/9421f981-f53b-4eb1-94e9-2774e74e0caf">

**Comment by amagasu** [comment]
Thanks you!
I remove cache and chrome restart and displayed all
