### ISSUE TITLE
More strict CSP policy

### ISSUE THREAD

**Issue by Earlopain** [sidekiq/sidekiq#6268]
Ruby version: 3.3.1
Rails version: 7.1.3.2
Sidekiq / Pro / Enterprise version(s): main

I saw the recent XSS and was a bit surprised since I remember protection against `unsafe-eval` for `script-src` being added in 7.2.0.

The current CSP declares `http:` and `https:` for a bunch of directives. I was tempted to open a PR to remove them since the UI just continues to work but there are two problems I see with that:
* Extensions that hook into the webui might cease to function
* Assets may be hosted outside of the main app, on something like S3 (https://github.com/sidekiq/sidekiq/pull/3913#issuecomment-410318634)

For the S3 case, I feel like the user should be able to configure the CSP in some way to add their bucket url to the CSP instead of just allowing everything. Similarly for addons which may use a cdn for js/css (though vendoring like here would be prefered I think).

Apart from benefitting sidekiq, extensions would also inherit these better protections.

**Comment by mperham** [comment]
I know almost nothing about CSP. Any help or PRs would be very welcome.
