### ISSUE TITLE
Pending batches expiring in 5 months, not 30 days

### ISSUE THREAD

**Issue by kwugirl** [sidekiq/sidekiq#6277]
Ruby version: 3.0.6p216
Rails version: 6.1.7.7
Sidekiq / Pro / Enterprise version(s): 7.2.0 / 7.2.0 / 7.2.0

Hello! The wiki [says](https://github.com/sidekiq/sidekiq/wiki/Batches#linger-and-expiration) that "Pending batches will expire in Redis after 30 days" but we are seeing batches created 1 week ago showing in the admin UI has expiring in 5 months. These batches are pending because they included dead jobs that due to miscommunication with other teams, resulted in the dead jobs being deleted rather than retried. I'm confused by where the 5 months might be coming from. 

My goal is to clear out these pending batches that we know will not succeed, so that we can get the admin UI back to being useful for looking at newer batches that may be stuck for different reasons.

**Comment by mperham** [comment]
30 days is the default. The only way I know to change this value is to monkeypatch the Sidekiq::Batch::EXPIRY constant.

**Comment by raybaxter** [comment]
Batches with failures show in the UI that they expire in 5 months.

<img width="186" alt="image" src="https://github.com/sidekiq/sidekiq/assets/10649/aeb9fce6-c805-4edd-a964-625b794fec6f">

**Comment by kwugirl** [comment]
Yup, thanks @raybaxter ours looks just like that as well.

**Comment by mperham** [comment]
This will happen if a batch job dies. Sidekiq Pro extends the batch's expiry to the dead job lifetime so the batch will not expire before any dead batch jobs have been garbage collected. See `lib/sidekiq/batch/death.rb` line 75.

**Comment by stevenharman** [comment]
> Sidekiq Pro extends the batch's expiry to the dead job lifetime so the batch will not expire before any dead batch jobs have been garbage collected

Ahh, this makes sense! Maybe updating the Wiki will clear this up. 👍

**Comment by raybaxter** [comment]
> My goal is to clear out these pending batches that we know will not succeed, so that we can get the admin UI back to being useful for looking at newer batches that may be stuck for different reasons.

If you have clear criteria for deleting batches, you can delete them from the Rails console:
```ruby
Sidekiq::BatchSet.new.select {|b| b.description.match /^Full Title/ }.map(&:delete)
Sidekiq::BatchSet.new.select {|b| b.failures > 1 }.map(&:delete)
Sidekiq::BatchSet.new.detect {|b| b.bid == "S9yJ0GD2CW1TGw"}.delete
```
