### ISSUE TITLE
`Object#respond_to_missing?` redefined with too few arguments

### ISSUE THREAD

**Issue by mswain** [sidekiq/sidekiq#6281]
Ruby version: 3.2.4p170
Rails version: 7.1.3.2
Sidekiq / Pro / Enterprise version(s): 7.2.4 / 7.2.0 / 7.2.2

When running `Sidekiq::Workers.new.to_a`, Sidekiq threw the following exception (but only when workers are actively processing jobs):

```
BUNDLE_PATH/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/api.rb:1202:in `respond_to_missing?': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

On this line, `respond_to_missing?` is redefined with only one argument:

https://github.com/sidekiq/sidekiq/blob/v7.2.4/lib/sidekiq/api.rb#L1202-L1205

However, Ruby expects this method signature to look like:

```
#respond_to_missing?(symbol, include_all)
```

https://www.rubydoc.info/stdlib/core/Object:respond_to_missing%3F

Happy to provide additional initializer and configuration details if needed, but I'm guessing this won't be necessary.

Thank you!

**Comment by mperham** [comment]
Been a long time, Matt, hello from Railsconf!

Send a PR?

**Comment by mswain** [comment]
Indeed it has, sir! Hope the PNW is treating you right. PR incoming soon.
