### ISSUE TITLE
[Feature Proposal] Compressing scheduled jobs to save memory

### ISSUE THREAD

**Issue by OuYangJinTing** [sidekiq/sidekiq#6289]
### Background

![image](https://github.com/sidekiq/sidekiq/assets/33079237/e67fc3e6-25ae-423b-b057-0cde1e7c2099)
![image](https://github.com/sidekiq/sidekiq/assets/33079237/e27217fe-b3e4-4701-83be-70c4b07dd3f1)

As show in the above image, in the [Mihuahis](https://www.mihuahis.com/) project of the company I work for, there are a large number of scheduled jobs, which consume a large amount of memory, leading us to have to scale up Redis.
In order to facilitate usage, we did not directly use Sidekiq to handle asynchronous jobs, but instead used Activejob on top of it. However, in comparison, generating a simple job, Activejob requires much more memory than Sidekiq.

```ruby
class FooJob < ActiveJob::Base
  queue_as :activejob
end
FooJob.perform_later
activejobstr = Sidekiq::Queue.new('activejob').first.value

class BarJob
  include Sidekiq::Job
  sidekiq_options queue: :sidekiqjob
end
BarJob.perform_async
sidekiqjobstr = Sidekiq::Queue.new('sidekiqjob').first.value

activejobstr.bytesize.to_f / sidekiqjobstr.bytesize # => 2.706161137440758
```

### Idea

For jobs that are scheduled to be placed in the queue but require a long wait before execution (e.g. one day later), we first compress them before writing to memory. When retrieving them, we then decompress them before putting them into the queue. This way, we save a lot of memory. However, in return, we need to spend additional time and CPU resources on compression and decompression. But I believe this is acceptable for asynchronous jobs.

```ruby
Zlib::Deflate.deflate(activejobstr).bytesize.to_f / activejobstr.bytesize # => 0.6252189141856392
```

### Final

Thank you for watching. If you accept this proposal, I am willing to spend time implementing this feature.

_PS: English is not my native language; please excuse typing errors._

**Comment by mperham** [comment]
The job payload cannot be compressed because some of Sidekiq's logic requires it to look at the job in Lua. Why are your jobs so big? Can you convert your ActiveJobs to Sidekiq::Job instead and reduce the job size that way? You can also compress any large job arguments in your own code.

**Comment by OuYangJinTing** [comment]
Thank you for your response.

The scheduled jobs in our project are widely used, which has led to the continuous rapid growth of the scheduled queue， but we are currently adjusting this area.
We do not plan to convert ActiveJob to Sidekiq because many job's parameters are non-raw JSON, and ActiveJob's parameter serialization feature can reduce development work.
Our job parameters are very small, so compressing only the job parameters would not be effective.

**Comment by OuYangJinTing** [comment]
About Lua, I found that only `Sidekiq::Scheduled::Enq` uses it, and it only read the jobstr without accessing the specific data inside the jobstr. Compressing jobstr should have no impact.
Perhaps there are other places I haven't noticed that prevent compressing jobstr?

**Comment by mperham** [comment]
Sidekiq Pro's reliable scheduler has to reset `enqueued_at` in Lua. There is no compression API in Lua.

**Comment by OuYangJinTing** [comment]
Thank
