### ISSUE TITLE
Difference between capsule and concurrency=1

### ISSUE THREAD

**Issue by freesteph** [sidekiq/sidekiq#6290]
Hello,

I apologise in advance for asking such a dumb question. What is the difference between a Sidekiq Capsule and starting a sidekiq process for a given queue with `--concurrency=1`?

The wiki gives the example below:

```ruby
Sidekiq.configure_server do |config|
  config.capsule("unsafe") do |cap|
    cap.concurrency = 1
    cap.queues = %w[single]
  end
end
```

And it looks to me like:

```
# Procfile
unsafe-worker: bundle exec sidekiq -q single --concurrency=1
```

What does Capsule add? Does it enforce it at a higher layer, meaning there's no need to worry about the Procfile or process schedule?

Thank you for the clarification.

**Comment by mperham** [comment]
Capsule allows you to throttle concurrency within a single process but all threads within that Ruby process are still sharing one CPU. If you start a separate process, you can use a different CPU.

By default Sidekiq has a `default` Capsule with 5 threads. Adding that `unsafe` Capsule means you'll have 5+1 threads executing jobs, all sharing the same CPU, but only that one Thread will execute jobs from the `single` queue.

**Comment by freesteph** [comment]
Thank you. And because Capsules allow controlling concurrency within a single process alongside other capsules, this means we can do linear processing (`--concurrency=1`) without having to run a separate worker processing a single queue with one thread (1 PID -> -c 1 -> 1 thread) ?

**Comment by mperham** [comment]
Correct.
