### ISSUE TITLE
Suggestion: Raise error when calling `batch.jobs` more than once when defining the batch?

### ISSUE THREAD

**Issue by stevenou** [sidekiq/sidekiq#6293]
As clearly stated in the documentation, 

> Note that it is not safe to call `batch.jobs` more than once when defining the batch.

https://github.com/sidekiq/sidekiq/wiki/Batches

That being said, I have been bitten a few times by _accidentally_ calling `batch.jobs` more than once. I'm wondering if it's possible to raise an error when a user does this so the mistake can be caught and fixed sooner? When I accidentally do this, I end up with a batch that never finishes because there are non-existent pending jobs.

Not sure if this makes sense or not, but would like to hear your thoughts.

Thanks!

**Comment by mperham** [comment]
I've tried to do this before, it was tricky to determine whether it is safe or not. Additionally I realized it could be better to retain backwards compatibility with racy code rather than breaking people's apps and forcing them to rework their batch code.

**Comment by stevenou** [comment]
Understood on the first point. 

On the second point, I'd imagine it would be similar to `Sidekiq.strict_args!` which makes raising an exception optional/configurable.
