### ISSUE TITLE
Capsules don't observe the `-q` parameter of their process

### ISSUE THREAD

**Issue by freesteph** [sidekiq/sidekiq#6294]
Given a capsule like this:

```ruby
Sidekiq.configure_server do |config|
  config.capsule("single-threaded") do |cap|
    cap.concurrency = 1
    cap.queues = %w[payments]
  end
end
```

And a Procfile like this:

```sh
web: bundle exec puma -C config/puma.rb
workerdocuments: bundle exec sidekiq --queue documents
workerpayments: bundle exec sidekiq --queue payments
```

jobs queued on the `payments` queue will (can) be picked up by the `workerdocuments`, which makes sense because the capsule is worker-wise (well, app-wise) but doesn't make sense because the documents worker should be scoped to the `documents` queue. 

Is this expected behaviour?

**Comment by mperham** [comment]
As designed, CLI args don't affect any configured Capsules.

**Comment by freesteph** [comment]
Okay, thank you for your answers!
