### ISSUE TITLE
Update Sidekiq API with capsule data

### ISSUE THREAD

**Issue by stephenwiebe** [sidekiq/sidekiq#6295]
It appears that the Sidekiq data API doesn't expose any information about capsules. I think this would be an added attribute on the Process class? Basically I use a gem which uses the API in order to report process utilization (ie the busy/concurrency ratio), but I'm finding that I would like it to calculate this based on just the default capsule, not any other capsules.

**Comment by mperham** [comment]
Sidekiq::Process should include the capsules, as they show up on the Busy tab.

**Comment by stephenwiebe** [comment]
@mperham Can you confirm that Sidekiq::Process includes the capsules? Or can you let me know how to access the capsule data? I tried accessing it via `process['capsules']` and it doesn't seem to be valid. I also checked the code at https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/api.rb and didn't see anything on the Process class related to capsules. Nor does the documentation for the Process class at https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/api.rb#L1054 document any way to access capsule information.

**Comment by mperham** [comment]
The only place that shows capsule setup is the Busy page. Take a look at busy.erb. I will also document.

**Comment by stephenwiebe** [comment]
Ok, so in that case, it sounds like the request in this ticket still remains unimplemented? There's no way to use the Sidekiq API to access capsule information from Sidekiq::Process objects? Or am I misunderstanding?

**Comment by mperham** [comment]
Yeah, diving in more, it looks like the API doesn't explicitly provide a capsule entity. Right now launcher.rb flattens the capsule data in order to maintain backwards compatibility so there is no way to see how capsules are configured in each process. We'd need to bring that data into Redis and the API.

Let's start with use cases first. Why do you need this info? What are you looking to do with it?

**Comment by mperham** [comment]
Ah, you added your use case in the original comment.

**Comment by mperham** [comment]
Comments welcome on that PR ^^^^^
