### ISSUE TITLE
set(unique_for: ...) not working with ActiveJob

### ISSUE THREAD

**Issue by lorrin** [sidekiq/sidekiq#6296]
Ruby version: 3.1.4p223
Rails version: 6.1.7
Sidekiq / Pro / Enterprise version(s):   sidekiq= 7.1.4 / pro 7.1.4 / ent 7.1.2

https://github.com/sidekiq/sidekiq/wiki/Ent-Unique-Jobs#bypassing-or-dynamically-setting-uniqueness describes using `.set(unique_for: ...)` to dynamically set uniqueness on a specific job. This isn't working for me through ActiveJob. Is it supposed to work in ActiveJob? Would I set it the same way?

For context, I have a job that is intentionally unique, but which sometimes wants to re-enqueue a future execution of itself using e.g. `MyJob.set(wait: delay, unique_for: false).perform_later(...)`. Happy to have other suggestions. 

> If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

Checked, didn't spot anything.

**Comment by mperham** [comment]
It's possible the problem is using a Symbol instead of a String. Sidekiq stringifies everything but I don't know that ActiveJob does. Try `"unique_for" => false` instead.

**Comment by lorrin** [comment]
Hmm, no luck with `MyJob.set("unique_for" => false).perform_later(...)`. It still gives me `Skipping enqueue for MyJob, not unique`

**Comment by mperham** [comment]
I can't explain what's wrong. You'll need to step thru it with a debugger.
