### ISSUE TITLE
Batches wrapping unique_for jobs completing before jobs have run

### ISSUE THREAD

**Issue by alexfiennes** [sidekiq/sidekiq#6298]
Ruby version: ruby 3.1.4p223
Rails version: 6.1.7.7
Sidekiq / Pro / Enterprise version(s):  7.2.4 / 7.2.0 / 7.2.0

If I create a batch that is wrapping jobs which have `unique_for` _and_ there are already jobs in the queue that are duplicates of the jobs that we want to wrap in the batch then the batch doesn't wait for these jobs to complete before invoking the callbacks.  For example given the following test code:-

```
module Temp
  class UniqueJob
    include Sidekiq::Job
    sidekiq_options unique_for: 10.minutes, unique_until: :started

    def perform(message)
      Rails.logger.info "*********************** UniqueJob: #{message}"
    end
  end

  class BatchJob
    include Sidekiq::Job

    def perform(nested_jobs)
      batch = Sidekiq::Batch.new
      batch.on(:success, Temp::BatchJob)
      batch.jobs do
        nested_jobs.each do |message|
          UniqueJob.perform_async(message)
        end
      end
    end

    def on_success(_status, _options)
      Rails.logger.info '*********************** Temp::BatchJob.on_complete callback'
    end
  end

  class Test
    def self.only_batch
      BatchJob.perform_async(%w(alpha beta gamma))
    end

    def self.only_jobs
      UniqueJob.perform_in(10.seconds, 'alpha')
      UniqueJob.perform_in(10.seconds, 'beta')
      UniqueJob.perform_in(10.seconds, 'gamma')
      UniqueJob.perform_in(10.seconds, 'alpha')
      UniqueJob.perform_in(10.seconds, 'beta')
      UniqueJob.perform_in(10.seconds, 'gamma')
    end

    def self.batch_and_jobs
      UniqueJob.perform_in(10.seconds, 'alpha')
      UniqueJob.perform_in(10.seconds, 'beta')
      BatchJob.perform_async(%w(alpha beta gamma))
    end
  end
end
```

then we get the expected output for `only_batch` of 

```
*********************** UniqueJob: alpha
*********************** UniqueJob: beta
*********************** UniqueJob: gamma
*********************** Temp::BatchJob.on_complete callback
```

and for `only_jobs` (with the unique's discarded):-

```
*********************** UniqueJob: alpha
*********************** UniqueJob: beta
*********************** UniqueJob: gamma
```

but `batch_and_jobs` gives us:-

```
*********************** UniqueJob: gamma
*********************** Temp::BatchJob.on_complete callback
*********************** UniqueJob: alpha
*********************** UniqueJob: beta
```

which slightly surprises me.  I would like the callback to be run when the jobs have been run, not when it is aware that the jobs will run at some point in the future.  If it isn't possible to either attach to the duplicate jobs that are already in the queue so that the batch will complete in 10 seconds, then would it make sense to ignore the `unique_for` and run dedicated new copies of the job inside the batch?

**Comment by alexfiennes** [comment]
I've been doing more local testing and seeing what happens if we just have `perform_async` rather than `perform_in` so that the run order is more roughly the same as the enqueue order, and I have not been able to reproduce a situation where the callback is called _before_ any instance of each of the nested jobs has run.  So I suspect that the trick is to not combine `unique_for` and batches and `perform_in` and things will be more safe.

**Comment by mperham** [comment]
All of this is As Designed. Uniqueness and batches often don't play well together.

**Comment by alexfiennes** [comment]
Mike - this is kind of the conclusion that I came to as well.  How easy would it be within the current architecture to make it so that if you add a job to a batch which is declared as unique that it would raise an exception or log a warning?  I'm happy to do my best to avoid doing this, but if someone changed the behaviour of a job without realising that other people were using it in a batch then this might cause hard-to-spot errors - it would be nice if we got a nice clear warning that this was happening?

**Comment by mperham** [comment]
Uniqueness is a sharp knife, that’s why the batch wiki page warns the reader about it, but logging a warning would be useful the first time but annoying every other time.

**Comment by alexfiennes** [comment]
I am toying with recording an expiring key in REDIS each time a job completes that is unique by it's input params.  Then when a new job starts up it can check to see whether the same job has completed which started after the current job was enqueued and if so then just returning as a noop.  That way we can intermix batches and this-form-of-uniqueness without a problem.
