### ISSUE TITLE
Jobs Stuck in Enqueue state (Enqueued Actionmailer)

### ISSUE THREAD

**Issue by JezLawson** [sidekiq/sidekiq#6303]
Ruby version: 3.0.6
Rails version:  7.0.1
Sidekiq / Pro / Enterprise version(s): 7.0.2

![Screenshot 2024-05-21 at 16 08 22](https://github.com/sidekiq/sidekiq/assets/42204358/b1ed1c39-3034-43c3-982d-fb21f75fd25f)

initializer:
```
Sidekiq.configure_server do |config|
  config.redis = ...
end

Sidekiq.configure_client do |config|
  config.redis = sidekiq_config
end
```

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
yml:

```
:verbose: false
:concurrency: 10

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - default
  - mailers
  - blast_messages
  - credentialing
  - compliance
  - compliance_snapshotting

development:
  :verbose: true

production:
  :concurrency: 25
```

**Comment by mperham** [comment]
Is Sidekiq running?

**Comment by JezLawson** [comment]
Yes Mike, it is

**Comment by JezLawson** [comment]
Note: We rolled back to an earlier version of Ruby to 2.7 and this worked again.

**Comment by mperham** [comment]
And what does its logs show?

**Comment by JezLawson** [comment]
Mike, can you see the image that I've supplied? We are stuck in 'enqueued'

**Comment by mperham** [comment]
Those logs appear to be from your app server, eg puma. I’m asking about sidekiq’s log output.

and your image is in the middle of your initializer code so that’s not correct either. For instance I can’t tell what the “sidekiq_config” variable is.

**Comment by JezLawson** [comment]
Mike,, does this help?
<img width="956" alt="Screenshot 2024-05-22 at 16 05 56" src="https://github.com/sidekiq/sidekiq/assets/42204358/c47a7056-9a37-4aeb-8368-656abfebe96c">

**Comment by mperham** [comment]
It does answer that question. Now I want to see your Sidekiq logs from the same timestamps as that first log image.

**Comment by JezLawson** [comment]
Cool. So we rolled back a release early this morning.
No-one could find any sidekiq log yesterday, and if they are created on the service startup, perhaps if the start failed, this is why, leading me to suspect this is the reason the jobs stayed in the enqueued state. I've asked if the logs are now visible since we have rolled back and resolved the immediate issue.
Would this stack up with your expertise?

**Comment by mperham** [comment]
That scenario makes sense to me. The most common reason jobs pile up in a queue is because Sidekiq isn't running for some reason.

**Comment by JezLawson** [comment]
Appreciate that. We are Rails 7.1, Ruby changed from 2.7 to 3.0.6 (Just now). I'll move to 7.2.4 and see what happens.

**Comment by JezLawson** [comment]
Hi Mike
I've pushed a change out to our sidekiq.yml specifying a log file. We can't find it, and we have redeployed our failed release to a lower environment:
:verbose: true
:concurrency: 10

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - default
  - mailers
  - blast_messages
  - credentialing
  - compliance
  - compliance_snapshotting

development:
  :verbose: true
  :logfile: ./log/sidekiq_development.log

demo:
  :verbose: true
  :logfile: ./log/sidekiq_demo.log

production:
  :concurrency: 25
![Screenshot 2024-05-23 at 13 10 51](https://github.com/sidekiq/sidekiq/assets/42204358/87d74ff1-75c8-4bc8-aa2d-59dcdcd327b8)

**Comment by mperham** [comment]
If you don't know where your log files are, that tells me you're going to need a hell of a lot of help, which I can't do over github issues. Can you show up to my Office Hour in 15 minutes? https://sidekiq.org/support.html

**Comment by JezLawson** [comment]
Hi Mike

Thanks for the reply....I can't make this time I'm afraid. I'm also off tomorrow am. Can we try Tuesday am perhaps?

Jeremy

________________________________

**Comment by mperham** [comment]
I don’t provide private help to non-customers. My public Office Hour is your only option. I would strongly recommend reading through the various topics in the wiki if you’re not knowledgeable about Sidekiq.

**Comment by JezLawson** [comment]
Mike

Understood, and I empathise.
Please clarify your open office hours and it may be that I have to push this to next week.

Jeremy
________________________________

**Comment by mperham** [comment]
Office Hour: https://sidekiq.org/support.html

**Comment by JezLawson** [comment]
This issue is not closed, and I am still stuck. Please help.
