### ISSUE TITLE
Child batches with enqueued jobs don't prevent parent batches from completing

### ISSUE THREAD

**Issue by kwugirl** [sidekiq/sidekiq#6311]
Ruby version: 3.1.5p252
Rails version: 6.1.7.7
Sidekiq / Pro / Enterprise version(s): 7.2.4 / 7.2.0 / 7.2.2

Hello! We are using a overall+child batches workflow as described in [Really Complex Workflows with Batches](https://github.com/sidekiq/sidekiq/wiki/Really-Complex-Workflows-with-Batches) but are running into `Sidekiq::Batch::Immutable` errors:
1. We have an `overall` batch into which we enqueue a `StagerJob`
2. When the `StagerJob` runs, we re-open the `overall` batch to create a `step1` child batch that has jobs enqueued into it (but no further jobs are added to the `overall` batch). 
3. The `step1` batch's success callback also re-opens the `overall` batch to create a `step2` child batch that has jobs enqueued into it (and again, no further jobs are added to the `overall` batch). 
4. Then, the intent is for the `step2` batch's success callback to run, before the `overall` batch's success callback runs.

It looks like from our logs that when we create the child batches, the jobs enqueued into the child batches don't count for the `overall` batch, so a `Sidekiq::Batch::Empty` gets enqueued for that `overall` batch, and (I think?) we get a race condition between that `Sidekiq::Batch::Empty` job and ensuing callback jobs for the `overall` batch and the jobs in the child batches.

Does that seem like a reasonable diagnosis? Is there another way to achieve the complex workflow setup so that the overall batch waits on the child batches to succeed??

**Comment by mperham** [comment]
Show me the actual code. This is too complex to debug with a description.

**Comment by kwugirl** [comment]
Sure, this is what it looks like:

```ruby
# frozen_string_literal: true

class StagerJob < ApplicationJob
  sidekiq_options queue: :within_1_hour, retry_for: 24.hours, unique_for: 10.minutes

  NotWithinParentBatchError = Class.new(StandardError)

  def self.start_workflow_for(foo_id:)
    foobar_record = FooBar.find_by(foo_id: foo_id)

    overall = overall_batch(foobar_record_id: foobar_record.id)
    overall.description = "Bar workflow for Foo #{foo_id}"
    overall.jobs do
      Rails.logger.info(
        msg: 'Starting bar workflow',
        foobar_record_id: foobar_record.id,
        overall_batch_bid: overall.bid
      )
      perform_async(foo_id)
    end
  end

  def self.overall_batch(foobar_record_id:)
    batch = Sidekiq::Batch.new
    batch.on(:success, 'StagerJob#overall_batch_success', {
      'fbr_id' => foobar_record_id,
    })

    batch
  end

  def perform(foo_id)
    ensure_within_batch

    # various checks for early returns

    foobar_record = FooBar.find_by(foo_id: foo_id)
    foobar_service = FooBarService.new(foo_id)

    batch.jobs do
      step1 = Sidekiq::Batch.new

      chopping_block = foobar_service.stage

      step1.on(:success, 'StagerJob#perform_step2',
               {
                 'fbr_id' => foobar_record.id,
                 'staged' => chopping_block.rows_for_stage(2).as_json,
               })

      step1.jobs do
        chopping_block.rows_for_stage(1).each do |klass, ids|
          CleanupJob.call(klass_name: klass, instance_ids: ids.as_json) if ids.present?
        end
      end
    end

    batch
  end

  def perform_step2(status, options)
    fbr_id = options['fbr_id']
    staged = options['staged']

    overall = Sidekiq::Batch.new(status.parent_bid)
    overall.jobs do
      step2 = Sidekiq::Batch.new
      step2.on(:success, 'StagerJob#all_steps_successful',
               {
                 'fbr_id' => fbr_id,
                 'overall_batch_bid' => overall.bid
               })

      step2.jobs do
        staged.each do |klass, ids|
          CleanupJob.call(klass_name: klass, instance_ids: ids) if ids.present?
        end
      end
    end
  end

  def all_steps_successful(_status, options)
    foobar_record = FooBar.find(options['fbr_id'])

    # various logging/status field updates
  end

  def overall_batch_success(status, options)
    foobar_record = FooBar.find(options['fbr_id'])

    Rails.logger.info(
      msg: 'Bar workflow concluded',
      foobar_record_id: foobar_record.id,
      overall_batch_bid: status.bid
    )
  end

  private

    def ensure_within_batch
      raise NotWithinParentBatchError if batch.nil?
    end
end
```

As far as I can tell, it's the same structure as in the example for [Really Complex Workflows with Batches](https://github.com/sidekiq/sidekiq/wiki/Really-Complex-Workflows-with-Batches) just with fewer steps. And I believe we adhere to the given guidelines:

- jobs only open their own batch
- callbacks only open their parent batch

However we seem to be seeing instances of parent success running before child success, given the `Sidekiq::Batch::Immutable` errors in `Sidekiq::Batch::Callback` jobs that are coming up at the line `overall = Sidekiq::Batch.new(status.parent_bid)` in `StagerJob#perform_step2`.

**Comment by mperham** [comment]
Do you have the transactional client enabled? That can delay job push until the batch is no longer in context.

**Comment by kwugirl** [comment]
We _do_ have `Sidekiq.transactional_push!`! However I don't understand how that applies to this situation with batch jobs--I thought batch jobs just always push at the end of the jobs block? I don't understand what "the batch is no longer in context" means either, I'm afraid.

**Comment by mperham** [comment]
True, Sidekiq::Client should ignore transactional boundaries when inside the `jobs` block, but bugs and unexpected edge cases always exist.

**Comment by kwugirl** [comment]
I've put in a `rescue Sidekiq::Batch::Immutable` in our implementation for resetting the data to be able to start the workflow over again from the beginning.

**Comment by mperham** [comment]
Can you reduce it to a reproducible scenario? If you can, I can debug it for you.

**Comment by kwugirl** [comment]
I appreciate that, although unfortunately, probably not something that I will realistically get to in the near future. I plan to keep an eye on these batches and see how often this edge case actually comes up, mostly out of curiosity, and perhaps will try to make that reproducible scenario during a hack week at work or something.
