### ISSUE TITLE
`sidekiq-pro` gem 7.2.1 not found in the repository

### ISSUE THREAD

**Issue by gdubicki** [sidekiq/sidekiq#6312]
Ruby version: 3.3.x
Rails version: 7.x
Sidekiq / Pro / Enterprise version(s): 7.2.1

We are using Pro version. In [the changelog for Pro](https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md) there is a 7.2.1 version, but when I try to install it by setting this in my `Gemfile`:

```
source "https://<redacted>:<redacted>@gems.contribsys.com/" do
  gem "sidekiq-pro", "= 7.2.1"
end
```

...I am getting this on `bundle install`:

```
Could not find gem 'sidekiq-pro (= 7.2.1)' in rubygems repository https://<redacted>:<redacted>@gems.contribsys.com/.

The source contains the following gems matching 'sidekiq-pro':
  * sidekiq-pro-1.2.4
  * sidekiq-pro-1.5.1
  * sidekiq-pro-1.6.0
(...)
  * sidekiq-pro-7.1.5
  * sidekiq-pro-7.1.6
  * sidekiq-pro-7.2.0
```

**Comment by mperham** [comment]
It's there now.
