### ISSUE TITLE
Add splash logo on startup when using a custom log formatter

### ISSUE THREAD

**Issue by drsharp** [sidekiq/sidekiq#6314]
I know this is perhaps just a trivial issue but I've grown to love seeing the cool Sidekiq logo/kicker when I fire up Sidekiq:
```
               m,
               `$b
          .ss,  $$:         .,d$
          `$$P,d$P'    .,md$P"'
           ,$$$$$b/md$$$P^'
         .d$$$$$$/$$$P'
         $$^' `"/$$$'       ____  _     _      _    _
         $:    ',$$:       / ___|(_) __| | ___| | _(_) __ _
         `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
                $$:         ___) | | (_| |  __/   <| | (_| |
                $$         |____/|_|\__,_|\___|_|\_\_|\__, |
              .d$$                                       |_|
```

However, following [the instructions here](https://github.com/sidekiq/sidekiq/wiki/Logging#output-format) to create a custom logger (because I need to inject some extra data into the logs), I don't see that lovely logo anymore.

I've created a custom logger like this:

```
module Sidekiq
  module AddAdditionalDataToContext
    def call(item, _queue)
      Sidekiq::Context.add(:args,  item["args"])
      # ... some other context additions
    end
  end

  class Logger < ::Logger
    module Formatters
      class CustomFormatter < Base
        def call(severity, time, program_name, message)
          "#{args} => #{message}" # skipping the actual pieces as they don't matter for this Issue
        end
     end
  end
end

Sidekiq.configure_server do |config|
  Sidekiq::JobLogger.prepend(Sidekiq::AddAdditionalDataToContext)
  config.logger.formatter = Sidekiq::Logger::Formatters::CustomFormatter.new
end
```

Is there a better way to do this? A way that keeps the glorious Sidekiq logo on startup?

Just askin'

**Comment by mperham** [comment]
Send a PR if you can improve the logic:

https://github.com/sidekiq/sidekiq/blob/1c2a37d1a9d48a51739b528d8b1ad11420da2a24/lib/sidekiq/cli.rb#L44-L46

**Comment by drsharp** [comment]
I know this is closed, but for anyone else, it turns out that instead of subclassing `Base` in my custom formatter, I can just subclass `Pretty`:

```
class CustomFormatter < Pretty
```

and that works. Thanks Mike! 🙇
