### ISSUE TITLE
delete_by_class returns zero and doesn't remove any jobs

### ISSUE THREAD

**Issue by michaelfarghali-novu** [sidekiq/sidekiq#6316]
I've run into an issue where our default queue ended up with millions of duplicate jobs that we want cleared out but need to also keep certain types of jobs on the queue. 
I tried the enterprise/pro `delete_by_class`[API](https://github.com/sidekiq/sidekiq/wiki/Pro-API) as this seems like exactly what is needed but it does not clear any jobs off the queue and returns zero. 

Steps to reproduce in rails console.

queue = Sidekiq::Queue.new("default")
queue.pause!
10000.times { MyJob.perform_later }
queue.size => The expected 10k
queue.delete_by_class(MyJob) => 0

No error is raised.

Ruby 3.2.2
rails (6.1.7.2)
sidekiq-ent (7.2.0)
      einhorn (~> 1.0)
      gserver
      sidekiq (>= 7.2.0, < 8)
      sidekiq-pro (>= 7.2.0, < 8)
    sidekiq-pro (7.2.0)
      sidekiq (>= 7.2.0, < 8)

If delete_by_class has been deprecated is there a better way to delete only certain types of jobs off a queue? We are currently using the below snippet inside a job to iterate through the queue but it is taking days.
```
queue = Sidekiq::Queue.new('default')
queue.pause!
queue.each do |job|
  job.delete if JOBS_TO_REMOVE.include?(job.args.first['job_class'])
end
```

**Comment by mperham** [comment]
That method doesn’t work with ActiveJobs, only native Sidekiq::Jobs.
