### ISSUE TITLE
sidekiq-ent not found when running bin/rails on Ruby 3.3.2

### ISSUE THREAD

**Issue by dbackeus** [sidekiq/sidekiq#6317]
Ruby version: 3.3.2
Rails version: 7.1.3.3
Sidekiq Enterprise version: 7.2.2

This may well be the wrong place to report this but not sure where else to turn.

After upgrading our Rails app from ruby 3.2.0 (bundler version 2.4.6) to 3.3.2 (bundler version 2.5.11) we get `Could not find gem 'sidekiq-ent' in locally installed gems (Bundler::GemNotFound)` when running `bin/rails` (including any sub-command of `bin/rails`).

We've currently worked around this by changing the invocation to `bundle exec rails` which does work.

I'm guessing this is related to `https://enterprise.contribsys.com` being a separate authenticated external source somehow.

Full back trace:

```
/usr/local/lib/ruby/3.3.0/bundler/definition.rb:988:in `block in verify_changed_sources!': Could not find gem 'sidekiq-ent' in locally installed gems (Bundler::GemNotFound)
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:986:in `each'
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:986:in `verify_changed_sources!'
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:977:in `source_requirements'
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:569:in `resolution_packages'
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:551:in `resolver'
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:626:in `start_resolution'
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:311:in `resolve'
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:579:in `materialize'
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:203:in `specs'
	from /usr/local/lib/ruby/3.3.0/bundler/definition.rb:270:in `specs_for'
	from /usr/local/lib/ruby/3.3.0/bundler/runtime.rb:18:in `setup'
	from /usr/local/lib/ruby/3.3.0/bundler.rb:162:in `setup'
	from /usr/local/lib/ruby/3.3.0/bundler/setup.rb:26:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.3.0/bundler/ui/shell.rb:159:in `with_level'
	from /usr/local/lib/ruby/3.3.0/bundler/ui/shell.rb:111:in `silence'
	from /usr/local/lib/ruby/3.3.0/bundler/setup.rb:26:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /app/config/boot.rb:3:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
```

**Comment by mperham** [comment]
Thanks for letting me know. I would suggest you open a Bundler issue.

**Comment by wata727** [comment]
Same issue here. I know this is off-topic, but I ended up on this issue for the exact same reason, so let me share what I found here.

The Bundler version referenced by `bin/rails`  and `bundle exec` may be different. The former is loaded by `require "bundle/setup"`, while the latter is loaded by bundle(1). In my case, `/usr/local/lib/ruby/3.2.0/bundler/version.rb` was v2.4.21 and `bundle -v` was v2.5.11. This difference may be the reason why authenticated gems such as sidekiq-ent and sidekiq-pro fail to load.

**Comment by mperham** [comment]
This is almost certainly a bug in the new Bundler version.

**Comment by mensfeld** [comment]
@mperham it is bug in bundler. It also affects Karafka Pro users. This change was suppose to be unobstructive yet somehow it backfired heavily. It will affect anyone with login:password/host patterns on private gems

**Comment by OleksiiKachan** [comment]
new bundler update removes credentials from lock file. There were a few discussion in bundler repo and this change will be reverted in the next release
