### ISSUE TITLE
Dependency on the `logger` gem which will be removed in Ruby 3.5

### ISSUE THREAD

**Issue by Earlopain** [sidekiq/sidekiq#6319]
Same deal as with all the others that happened in the last few years. https://github.com/ruby/ruby/commit/d7e558e3c48c213d0e8bedca4fb547db55613f7c

https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/logger.rb

Will probably just need to be added to the gemspec

**Comment by mperham** [comment]
Great idea and thanks for the heads up! Want to send a PR with an update to the gemspec and changelog?

**Comment by Earlopain** [comment]
👍
