### ISSUE TITLE
QUESTION: Is it possible to customize UI?

### ISSUE THREAD

**Issue by nthx** [sidekiq/sidekiq#6322]
Hey @mperham
I appreciate your work 👍

Is there any news regarding the functionality of customizing UI elements, so they're available for some users and for some not?

I'm thinking about giving users with different permissions access to actionable buttons in UI

Things I'd like to have customised would be:
* ability to delete / pause a queue
* ability to delete a job from a queue
* ability to quiet / stop processes

**Comment by nthx** [comment]
I got access to the enterprise. Does it help?

**Comment by mperham** [comment]
Gems can add their own tab to the UI. We’re formalizing this in 7.3 with a new API. https://github.com/sidekiq/sidekiq/tree/main/examples/webui-ext
