### ISSUE TITLE
Error with rack 3.1.0

### ISSUE THREAD

**Issue by rus-max** [sidekiq/sidekiq#6325]
Ruby version: 3.3.2
Rails version: 7.1.3.4
Sidekiq version: 7.2.4

https://github.com/rack/rack/pull/2099

http://localhost:3000/sidekiq/scheduled

```
>> ::Rack::Utils.escape_html(text)
!! #<TypeError: no implicit conversion of nil into String>
```

**Comment by Earlopain** [comment]
I would consider this a bug in rack, I openend https://github.com/rack/rack/pull/2202

**Comment by Earlopain** [comment]
Rack 3.1.3 released which contains the above fix.

**Comment by rus-max** [comment]
Thanks!
