### ISSUE TITLE
Sidekiq Pro 7.2.0 does not support dogstatsd-ruby versions less than v5

### ISSUE THREAD

**Issue by pyueli** [sidekiq/sidekiq#6328]
Ruby version: 3.2
Rails version: 7.1
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 7.2.0

Root cause:
The host method was defined in statsd.rb of dogstatsd-ruby since v5. It doesn't exist in previous versions. This dependency isn't specified in the gem file of SidekiqPro.

Stacke trace:
NoMethodError undefined method `host' for #<Datadog::Statsd:0x00007f60b6241918 @namespace="sidekiq"
at
block in location(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-pro-7.2.0/lib/sidekiq/pro/metrics.rb:81)
Copy filepath
at
block (2 levels) in with(/usr/local/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110)
Copy filepath
at
handle_interrupt(/usr/local/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109)
Copy filepath
at
block in with(/usr/local/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109)
Copy filepath
at
handle_interrupt(/usr/local/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106)
Copy filepath
at
with(/usr/local/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106)
Copy filepath
at
location(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-pro-7.2.0/lib/sidekiq/pro/metrics.rb:81)
Copy filepath
at
start(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-ent-7.2.2/lib/sidekiq-ent/metrics.rb:39)
Copy filepath
at
block in retain_history(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-ent-7.2.2/lib/sidekiq-ent/metrics.rb:16)
Copy filepath
at
block in fire_event(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-7.2.2/lib/sidekiq/component.rb:60)
Copy filepath
at
each(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-7.2.2/lib/sidekiq/component.rb:59)
Copy filepath
at
fire_event(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-7.2.2/lib/sidekiq/component.rb:59)
Copy filepath
at
stage_coup!(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-ent-7.2.2/lib/sidekiq-ent/senate.rb:88)
Copy filepath
at
election(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-ent-7.2.2/lib/sidekiq-ent/senate.rb:135)
Copy filepath
at
cycle(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-ent-7.2.2/lib/sidekiq-ent/senate.rb:103)
Copy filepath
at
watchdog(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-7.2.2/lib/sidekiq/component.rb:10)
Copy filepath
at
block in safe_thread(/usr/local/bundle/ruby/3.2.0/gems/sidekiq-7.2.2/lib/sidekiq/component.rb:19)

**Comment by mperham** [comment]
Correct, it requires v5.

**Comment by mperham** [comment]
I can’t mandate a version if the feature is optional.
