### ISSUE TITLE
Nested batches fire in a wrong order in testing mode

### ISSUE THREAD

**Issue by freemanoid** [sidekiq/sidekiq#6330]
Ruby version: 2.7.6
Rails version: 6.1.7
Sidekiq / Pro / Enterprise version(s): 7.2.4/7.2.1

When you run nested batches in inline mode, it should wait for the end of all nested `Sidekiq::Batch#jobs` blocks before starting the inline execution.

This issue prevents us from testing sidekiq batch pipelines.

Reproducible example
```ruby
require "rails_helper"

Sidekiq::Testing.server_middleware do |chain|
  chain.add Sidekiq::Batch::Server
end

class Job1
  include ::Sidekiq::Worker

  def on_success(*)
    puts "Job1 success"
  end

  def perform
    batch1 = Sidekiq::Batch.new
    batch1.on(:success, "Job1#on_success")
    batch1.jobs do
      batch2 = Sidekiq::Batch.new
      batch2.on(:success, "Job2#on_success")
      batch2.jobs do
        Job2.perform_async
      end

      batch3 = Sidekiq::Batch.new
      batch3.on(:success, "Job3#on_success")
      batch3.jobs do
        Job3.perform_async
      end
    end
  end
end

class Job2
  include ::Sidekiq::Worker

  def on_success(*)
    puts "Job2 success"
  end

  def perform; end
end

class Job3
  include ::Sidekiq::Worker

  def on_success(*)
    puts "Job3 success"
  end

  def perform; end
end

RSpec.describe "Batch", :type => :job do
  it "works" do
    Sidekiq::Testing.inline! do
      Job1.perform_async
    end
  end
end
```

Output:
```
Job2 success
Job1 success
Job3 success
```

Expected output:
```
Job2 success
Job3 success
Job1 success
```

**Edited**: added the middleware to make the spec complete. I forgot about it since we have it enabled globally.

**Comment by freemanoid** [comment]
Hey @mperham do you have any thoughts on this? I can't contribute since it's sidekiq-pro code.

**Comment by mperham** [comment]
Unfortunately I don't see a fix here. Inline can't guarantee ordering because you are executing job2 while still defining the set of jobs in batch1. Batches can be system tested but they cannot be unit tested because they require asynchronous execution.

**Comment by freemanoid** [comment]
Can the scheduling be delayed until the latest `jobs` block using `#immediate_registration?`?

**Comment by mperham** [comment]
@freemanoid Then they aren't really inline, right?

**Comment by freemanoid** [comment]
> @freemanoid Then they aren't really inline, right?

Well, they're inline, but in the outer scope in relation to the `jobs` block. It's similar to `#perform_bulk` to some extent.
