### ISSUE TITLE
Is job.delete on a ScheduledSet job a valid way to do it now?

### ISSUE THREAD

**Issue by eddygarcas** [sidekiq/sidekiq#6338]
Ruby version: 3.3.1
Rails version: 7.1.3
Sidekiq / Pro / Enterprise version(s): 7.2.1

Checking older issues I saw that to remove an scheduled job doing it this way:
 ```
a = Sidekiq::ScheduledSet.new
    a.each do |job|
        if job.args[0] == id
            job.delete
        end
    end
```
Is not the best and the most efficient way to do it, and the best approach  is doing what it's described here instead:

[https://github.com/sidekiq/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job](https://github.com/sidekiq/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job)

For the situation that I'm facing I rather use the job.delete basically it's easy to code this on another scheduled job but I just want to make sure it's viable this way.

**Comment by mperham** [comment]
Correct, the Scheduled Set is not designed for lots of deletes so I recommend cancellation if you need a method which scales.

But that code snippet you pasted is particularly slow. The lookup can be done far faster with `scan`. See "Scanning and Filtering" here:

https://www.mikeperham.com/2021/04/20/a-tour-of-the-sidekiq-api/

**Comment by eddygarcas** [comment]
Thanks for you quick answer. I was trying the scan and definitely is way faster that other approaches.

```
sq = Sidekiq::ScheduledSet.new
pre_count = sq.scan("OrderScheduledJob").count { |j| j.display_class == "OrderScheduledJob" }

sq.scan("OrderScheduledJob").select do |job|
    job.item['class'] == 'OrderScheduledJob' && job.item['args'].first['id'] == order.id
end.map(&:delete)

post_count = sq.scan("OrderScheduledJob").count { |j| j.display_class == "OrderScheduledJob" }
pp "Pre count #{pre_count} and post count #{post_count}"
```
Printing the count is just to make sure the job was deleted. 
Anyway I will follow the cancel approach, as you said this way is not efficient on a production environment.

Thanks
