### ISSUE TITLE
Storing error data on Sidekiq job for next retry

### ISSUE THREAD

**Issue by AdirWe** [sidekiq/sidekiq#6344]
Hey everyone,

Is there a way to save data on a job so it will be available for the next retry?

For instance, I have a job that processes a list of instances. If an exception occurs, I want the job to remember the instance where it failed to avoid starting over from the beginning of the list.
Therefore, I was thinking of storing the current instance ID in the exception or job data so it can be accessed during the next retry.

Thanks :-)

**Comment by mperham** [comment]
See the new job iteration feature on main but still unreleased. See Iteration wiki page.
