### ISSUE TITLE
Running sidekiqswarm on docker container

### ISSUE THREAD

**Issue by yossiedri** [sidekiq/sidekiq#6346]
Hi Mike 
please advice on how to run sidekiqswarm on docker container
thanks
yossi

**Comment by mperham** [comment]
Could you be more specific? What's the problem?

**Comment by yossiedri** [comment]
We have sidekiq ent as a service (systemctl) and we moved our app to AWS k8s with docker and I want to know what the best practice in this configuration is.


From: Mike Perham ***@***.***>
Date: Wednesday, 26 June 2024 at 15:51
To: sidekiq/sidekiq ***@***.***>
Cc: yossi edri ***@***.***>, Author ***@***.***>
Subject: Re: [sidekiq/sidekiq] Running sidekiqswarm on docker container (Issue #6346)

Could you be more specific? What's the problem?

**Comment by mperham** [comment]
You replace sidekiq with sidekiqswarm in ExecStart as the wiki says. That’s it.

**Comment by mperham** [comment]
Oh, you are migrating from systemd to k8s. I don't have a good answer for you. I can't help with 3rd party tooling since I have no experience with it.

**Comment by mperham** [comment]
I don't think we have a Docker wiki page but we do have https://github.com/sidekiq/sidekiq/wiki/Kubernetes

**Comment by mperham** [comment]
And starting sidekiqswarm in Docker should be very similar to Sidekiq, just replace `bundle exec sidekiq` with `SIDEKIQ_COUNT=2 bundle exec sidekiqswarm`. Make sure you set SIDEKIQ_COUNT to reflect the CPU core count which the Docker container has access to.
