### ISSUE TITLE
ActiveJob `retry_on` Exceptions counting as successes and not joining retry queue immediately.

### ISSUE THREAD

**Issue by JGSweets** [sidekiq/sidekiq#6347]
Ruby version: `3.3`
Rails version: `7.1`
Sidekiq / Pro / Enterprise version(s): `7.2.4`

Exceptions caught by ActiveJob `retry_on` are counted as success and go directly to `scheduled` as opposed to the `retry` bucket for the number of `retry_on` attempts.

For example, if sidekiq uses the default of 25 and ActiveJob `retry_on` has 5 attempts and all jobs fail, it will conduct 30 attempts.
This will result in `4 success` and `26 failed`.

**Comment by mperham** [comment]
Correct. Active Job's retry subsystem is not visible to Sidekiq and vice versa. You have to use one or the other.
