### ISSUE TITLE
Retries sometimes go through client middleware

### ISSUE THREAD

**Issue by eileen-jiang** [sidekiq/sidekiq#6348]
Ruby version: 3.1.4
Rails version: 7.0.8.1
Sidekiq / Pro / Enterprise version(s): sidekiq-pro (5.5.0)

In the past from testing and looking through the Sidekiq gem, I've expected retries to only go through the server middleware.

I'm seeing now that retries will occasionally go through the client middleware. Is this a new change?

**Comment by mperham** [comment]
Retries go through client middleware if you are using the standard scheduler. They don't go through client middleware if using the reliable scheduler in Sidekiq Pro because the reliable logic uses Lua to keep the job entirely within Redis, we can't execute any Ruby.
