### ISSUE TITLE
API does not respect `dead_max_jobs`

### ISSUE THREAD

**Issue by krasnoukhov** [sidekiq/sidekiq#6349]
Ruby version: 3.2.2
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): 7.1.4 / 7.1.4 / 7.1.2

While it's possible to configure `dead_max_jobs` to a bigger number as specified in [this discussion](https://github.com/sidekiq/sidekiq/discussions/5011#discussioncomment-4998997), it does not take effect when `Sidekiq::DeadSet.new.kill` API is used:

https://github.com/sidekiq/sidekiq/blob/8885ce2f197f666e059c60bc7c37601f8d0b921c/lib/sidekiq/api.rb#L821-L822

Leading to inconsistent behavior - losing dead jobs due to the default limit.

**Comment by mperham** [comment]
The API is only used in client mode, not server, so `configure_server` won't affect the API. You want to set it in both modes, like so:
```ruby
Sidekiq.default_configuration[:dead_jobs_max] = 10_000
```
