### ISSUE TITLE
Really Complex Batches Ignore Callback Queue

### ISSUE THREAD

**Issue by robertwpaul** [sidekiq/sidekiq#6355]
Ruby version: 3.1.3
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): 7.2.0 / 7.2.1 / 7.2.4

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```ruby
# initializer

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
end
```

```yml
# sidekiq.yml

:queues:
  - customer
  - default
```

Hi,

I'm following the [Really Complex Workflow with Batches](https://github.com/sidekiq/sidekiq/wiki/Really-Complex-Workflows-with-Batches) guide and I'm seeing that the callback jobs for the parent batch are being added to the default queue rather than the queue the jobs in batch use.

In this example, if I pause the `default` queue and run this, the final `totally_done` callback never runs, but queues a pending job in the default queue. Unpausing runs the callback. 

```ruby
require 'sidekiq'

module ReallyComplex
  class StartWorkflow
    include Sidekiq::Job
    sidekiq_options retry: 3, queue: :customer

    def perform
      batch.jobs do
        step1 = Sidekiq::Batch.new
        step1.on(:success, 'ReallyComplex::Callbacks#step1_done')

        step1.jobs do
          ReallyComplex::TheJob.perform_async('A')
        end
      end
    end
  end

  class TheJob
    include Sidekiq::Job
    sidekiq_options retry: 3, queue: :customer

    def perform(name)
      puts "***** Inside TheJob #{name} *****"
    end
  end

  class Callbacks
    def totally_done(status, options)
      puts '***** TOTALLY DONE *****'
    end

    def step1_done(status, options)
      puts '***** step1 done *****'
    end
  end
end
```

```ruby
overall = Sidekiq::Batch.new
overall.callback_queue = 'customer'
overall.on(:success, 'ReallyComplex::Callbacks#totally_done')

overall.jobs do
  ReallyComplex::StartWorkflow.perform_async
end
```

If I also queue up a job directly in `StartWorkflow` like so, the final callback runs in the `customer` queue:

```ruby
class StartWorkflow
  include Sidekiq::Job
  sidekiq_options retry: 3, queue: :customer

  def perform
    batch.jobs do
      step1 = Sidekiq::Batch.new
      step1.on(:success, 'ReallyComplex::Callbacks#step1_done')

      step1.jobs do
        ReallyComplex::TheJob.perform_async('A')
      end

      ReallyComplex::TheJob.perform_async('B')
    end
  end
end
```

It seems like it's interpreting the `perform` in `StartWorkflow` as creating an empty batch (it adds a `Batch::Empty` job to `default`) but I'm adding to the parent batch that already had a job in it.

Is this expected?

Thanks!

**Comment by mperham** [comment]
The pseudocode isn’t really debuggable. Can you give me a gist which reproduces the issue?

**Comment by mmarinaccio** [comment]
@robertwpaul Did you ever figure this out? I'm running into the same issue.
