### ISSUE TITLE
DEPRECATION: Sidekiq exception handlers now take three arguments

### ISSUE THREAD

**Issue by kikikiblue** [sidekiq/sidekiq#6357]
Ruby version: 3.3.0
Rails version: 6.1.7.7
sidekiq (7.2.4)
exception_notification (4.5.0)

my sidekiq config 
```
url_hash = {url: "#{ENV["REDIS_TLS_URL"]}/0", ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }, timeout: 3}

  Sidekiq.configure_server do |config|
    config.redis = url_hash
  end

  Sidekiq.configure_client do |config|
    config.redis = url_hash
  end
```
my exception notifier gem config 
```
require 'exception_notification/rails'
require 'exception_notification/sidekiq'

ExceptionNotification.configure do |config|
  config.ignored_exceptions += %w{Net::SMTPSyntaxError}
  config.ignore_if do |exception, options|
    not Rails.env.production?
  end

  config.ignore_crawlers %w{Googlebot bingbot}
  config.error_grouping = true

  config.add_notifier :email, {
    email_prefix: "[Sidekiq Exception] ",
    sender_address: %{"no-reply" <no-reply@mydomain.com>},
    exception_recipients: %w{myemail@mydomain.com},
  }
end
```

My app is on heroku but when sidekiq exception is happening, I got this DEPRECATION message. 
```
DEPRECATION: Sidekiq exception handlers now take three arguments, see #<Proc:0x00007efde8a1f7b0 /app/vendor/bundle/ruby/3.3.0/gems/exception_notification-4.5.0/lib/exception_notification/sidekiq.rb:25
```

I searched and I guess that is from this line in Sidekiq 
https://github.com/sidekiq/sidekiq/blob/636b4fd36786f27969b1551737e8540eb78c1c4d/lib/sidekiq/config.rb#L278
          
I found also this issue and it is resolved but I have still this problem. 
https://github.com/sidekiq/sidekiq/issues/6065

I would greatly appreciate any information anyone can provide about this issue.

**Comment by mperham** [comment]
Upgrade the exception notifier gem.

**Comment by kikikiblue** [comment]
I specified exception notifier gem github like this and upgraded all.
```
gem 'exception_notification', git: 'https://github.com/smartinez87/exception_notification'
```
upgraded sidekiq to 7.3.0 

This is my Gemfile.lock
```
GIT
  remote: https://github.com/smartinez87/exception_notification
  revision: 8f04a8b12c019cae03a43c92d27c67dcfda27e17
  specs:
    exception_notification (4.5.0)
      actionmailer (>= 5.2, < 8)
      activesupport (>= 5.2, < 8)

sidekiq (7.3.0)
```
exception_notification's revision is shoing it is from 4 month ago latest commit. 

But the DEPRECATION message is still showing. 
Please let me know what else I can do.

**Comment by mperham** [comment]
Open an issue there and ask them to fix it. It’s an easy fix.
