### ISSUE TITLE
<jemalloc>: Error in munmap(): Invalid argument

### ISSUE THREAD

**Issue by damuz91** [sidekiq/sidekiq#6358]
Good day!

Description:

After upgrading from Rails 5 to Rails 7 and Sidekiq 6 to 7 started to get random Sidekiq crash. The process just stop running with the backtrace shown below. I manually restart the process by running `sudo service sidekiq restart` and it starts working for a couple of hours.

The error states:
```
<jemalloc>: Error in munmap(): Invalid argument
[BUG] Segmentation fault at 0x0000ffff69bfe000
ruby 3.3.2 (2024-05-30 revision e5a195edf6) [aarch64-linux]
```

My sidekiq program runs a background job that checks for an API every 10 minutes at all hours, so each cycle it runs the exact same code, that is why I can't understand what makes it crash at random hours of the day and not on every cycle call.

OS: Amazon Linux 2 aarch64
Ruby version: 3.3.2
Rails version: 7.1.3.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.2.4

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

Initializer:
```
Sidekiq.configure_server do |config|
  conf = {
    url: REDIS_FULL_URL,
    network_timeout: 15,
    size: 25
  }
  config.redis = conf
end

Sidekiq.configure_client do |config|
  conf = {
    url: REDIS_FULL_URL,
    network_timeout: 15,
    size: 25
  }
  config.redis = conf
end

Sidekiq::DelayExtensions.enable_delay! # gem 'sidekiq-delay_extensions', '~> 7.1'
```

sidekiq.yml
```
:sidekiq_pid: ./tmp/pids/sidekiq.pid
:sidekiq_log: ./log/sidekiq.log
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>
:batch_push_interval: 0
:queues:
  - default
```

The backtrace [gist](https://gist.github.com/damuz91/429bed215c7ff13ee33e3968d52a4729).

Extensions used (not sure if relevant):
```
- gem 'sidekiq-delay_extensions', '~> 7.1'
- gem 'sidekiq-batch', git: 'git@github.com:breamware/sidekiq-batch.git', ref: 'f2ef0289ea23e652797741de96506957535099ff'
- gem 'sidekiq-cron'
```

I have read the backtrace but I can't really seem to find a clue, the only would be it mentions this line from my source code:

```
Jul 05 05:00:01 subsystems-sync sidekiq[11766]: c:0048 p:0049 s:0277 e:000276 METHOD /home/ec2-user/production/sync-backend/releases/370/app/services/scheduler/partial_sync_scheduler_job.rb:6
```

which contains:
```
class Scheduler::PartialSyncSchedulerJob
  include Sidekiq::Job

  def perform(location_ids = [])
    locations = location_ids.any? ? Location.where(id: location_ids) : Location.enabled.should_sync.includes(:customer).where.not(customers: {service_object: ['xxx', 'yyy']})
    locations.each do |location| # <- Line 6
      if location.use_workflow
        PartialSync::Workflow.perform_async(location.id)
      else
        queue = location.customer.service_object.underscore.to_sym
        Sync::PartialSyncJob.set(queue: queue).perform_later(location.id)
      end
    end
  end

end
```

I would be thankful to any idea on how to troubleshoot this!

**Comment by mperham** [comment]
I don't believe that error has anything to do with Sidekiq, it's a low-level issue between Ruby and jemalloc. Possibly a bug in 3.3.2.
