### ISSUE TITLE
Rack dependency (standalone sidekiq-web)?

### ISSUE THREAD

**Issue by severin** [sidekiq/sidekiq#6360]
Hi there,

this is not really an issue but rather a question/idea.

Currently we are stuck with sidekiq v5 in a legacy rails app due to the rack2 dependency in sidekiq v6/7. I completely understand that keeping sidekiq-web compatible with all rack versions (1 through 3) is additional work and would benefit only a tiny fraction of your users.

But since rack is only used by the sidekiq-web bits of sidekiq and potentially not everyone is actually using sidekiq-web I wondered if it is possible to make rack either an optional dependency or break out sidekiq-web into a additional standalone gem?

**Comment by mperham** [comment]
Anything is possible but I don’t want to deal with versioning between different Sidekiq gems. Keeping everything all in one gem means that versioning is never a problem.

**Comment by fatkodima** [comment]
@mperham Wdyt about removing that `gem.add_dependency "rack", "~> 2.0"` line from gemspec file and add a requirement to the top of `lib/sidekiq/web.rb` file?

**Comment by mperham** [comment]
Given that Rack has no dependencies, I don’t think there’s much to gain. The code in sidekiq/web depends on Rack 3 and the gemspec makes that clear.

**Comment by fatkodima** [comment]
That is to make it work for the case described in this issue. Sidekiq will not automatically install rack and so people not using web ui will not be forced to install it.

**Comment by mperham** [comment]
If we do that, the natural next step is to run the Sidekiq 6 runtime with the Sidekiq 5 webui. Which is a gigantic hack and will break. And then people will file issues. The purpose of the dependency in the gemspec is to break early so people know: "you need to upgrade to use this version".

I don't think it's unreasonable to say that if you're stuck on an old version of Rack, you're also stuck on a lot of other old versions, including rails and sidekiq.
