### ISSUE TITLE
Enable passing cursor as an argument to a Sidekiq::IterableJob

### ISSUE THREAD

**Issue by sethherr** [sidekiq/sidekiq#6361]
Sidekiq v7.3.0

The new [Sidekiq Iteration](https://github.com/sidekiq/sidekiq/wiki/Iteration) functionality is an exciting addition!

However, the cursor functionality seems unnecessarily opaque to me, because it isn't a normal argument to the job. If it was passed to the job as a normal argument:

- You would be able to see it in the web interface
- You could manually enqueue a job with a cursor yourself

The only drawback I can think of to enabling passing it as an argument is that it needs to be overwritten by `Sidekiq::Job::Iterable#fetch_previous_iteration_state`, which might be confusing?

Maybe there are more disadvantages that I'm missing?

**Comment by mperham** [comment]
Jobs are immutable. Args can't change.

**Comment by sethherr** [comment]
Ahhh. That's what I was missing!

**Comment by sethherr** [comment]
Does it have to be the same job? Would it be reasonable to enqueue a new job?

**Comment by mperham** [comment]
Yes. No. For instance, batches would break.

**Comment by sethherr** [comment]
Ok, seems like this wouldn't work. 

Thanks for your considerate responses @mperham!
