### ISSUE TITLE
Periodic jobs stopped working 

### ISSUE THREAD

**Issue by stereosupersonic** [sidekiq/sidekiq#6363]
Ruby version: 3.1.4
Rails version: 7.0.8.4
Sidekiq 7.2.4 / Pro 7.2.0 / Enterprise version 7.2.2

the sidekiq jobs runs in a kubernetes cluster

without any deployment or updating the application, 3 of 41 periodic jobs stopped scheduling since yesterday 6am. 
These 3 jobs are the only one which uses the cron syntax for every x minutes  like "*/5 * * * 1,2,3,4,5" 

![Sidekiq_Enterprise](https://github.com/sidekiq/sidekiq/assets/62422/bebf80bc-2eb2-4428-8d8c-8da7dff0b8a9)

After a redeployment, the jobs start working again

any idea what causes this issue?

**Comment by mperham** [comment]
No, I've never heard of this issue. Let me know if it becomes chronic.

**Comment by caleb** [comment]
My jobs seem to be stopping as well. As soon as I restart sidekiq they start working again. I will investigate more deeply, but today users told me in the morning and in the afternoon that files they dropped in to be processed weren't being picked up.

I figured it was a different issue, but sure enough restarting Sidekiq was enough to get them going again.

**Comment by mperham** [comment]
@caleb use the “stuck” tips on the Probs and Troubleshooting wiki page. TTIN signal specifically.
