### ISSUE TITLE
[Wiki Issue] Sidekiq testing wiki page has outdated testing instructions for Batches

### ISSUE THREAD

**Issue by azrazalea-debtbook** [sidekiq/sidekiq#6365]
https://github.com/sidekiq/sidekiq/wiki/Testing#testing-batches

Compared to

https://github.com/sidekiq/sidekiq/wiki/Batches#testing

Might be just easier to link the former section to the latter? This had me writing tests in a much more difficult way until I found the latter link instead. If you don't want to just link, then this issue is to update the section to match.

**Comment by azrazalea-debtbook** [comment]
Github doesn't support wiki PRs or I'd have done that :(

**Comment by mperham** [comment]
I removed the section in Testing. All Batch documentation is on the Batch page.
