### ISSUE TITLE
Configuration to disable "start" & "done" logs

### ISSUE THREAD

**Issue by louiscb** [sidekiq/sidekiq#6368]
rails ~> 6.1.7.7
sidekiq-pro ~> 5.5.8
sidekiq ~> 6.0, 6.5.6

In the [logging docs page](https://github.com/sidekiq/sidekiq/wiki/Logging) you describe how Sidekiq jobs log additional information such as the start and end of each job. In the case of my application this results in a complete polluting of my logs, since we have large numbers of mundane & non-critical Sidekiq jobs running.

The only solutions I can think of are:
1. Change the log level to e.g `warn` - this isn't an option since there might be some messages we want to log that we choose ourselves in the specific jobs at an info level. 
2. Perhaps it's possible to set the log level for the non important jobs individually, this seems tedious and is something we need to maintain as we add jobs.

Am I missing a way to achieve this?

A great option would be to add a new configurable boolean such as:

```
Sidekiq.configure_server do |config|
    config.disable_default_logs = true
end
```

Example below of the messages that are polluting our logs:

```
UTC Timestamp----------- PID------ Thread----- JobType--------- JID------------------------- More...
2019-08-31T15:36:07.569Z pid=82859 tid=11cy9br class=HardWorker jid=528f1b0ddc4a9d0690464fe4 INFO: start
2019-08-31T15:36:07.573Z pid=82859 tid=119pz7z class=HardWorker jid=b7f805c545c78770d30dc1fd elapsed=0.089 INFO: done
```

**Comment by louiscb** [comment]
Could be as simple as wrapping these logs in conditionals based on the value of that config, which would default to true https://github.com/sidekiq/sidekiq/blob/fec787e68c81596c07dec4d944c8e964a1f558a9/lib/sidekiq/job_logger.rb#L28

**Comment by mperham** [comment]
https://github.com/sidekiq/sidekiq/blob/main/Changes.md#730

```ruby
Sidekiq.configure_server do |config|
  config[:skip_default_job_logging] = true
end
```

**Comment by louiscb** [comment]
Thank you @mperham!

Couldn't see the preferred way of contributing to the Wiki but I think adding the following to the doc page would be beneficial: https://github.com/sidekiq/sidekiq/wiki/Logging


## Skipping default job logging

You can skip Sidekiq's default start/finish job logging (from version [7.3.0](https://github.com/sidekiq/sidekiq/blob/main/Changes.md#730)).

```ruby
Sidekiq.configure_server do |config|
  config[:skip_default_job_logging] = true
end
```
