### ISSUE TITLE
Retry Now in the retries tab does not increase the retry count

### ISSUE THREAD

**Issue by maria-lau** [sidekiq/sidekiq#6375]
Ruby version: 2.7.6
Rails version: 6.1.7
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.1/Pro 5.3.1/Enterprise 2.3.1

In the Sidekiq Web UI, I can see when jobs are allowed to retry automatically, their retry count properly increments. However, if I select a job and click "retry now" and the job retries and fails again, it comes back into the retry queue with the same retry count.

**Comment by mperham** [comment]
This is As Designed. You shouldn't be penalized for manually retrying a job.

**Comment by mperham** [comment]
There is none. You can special case the exception or reduce the retry value but I can't think of any way to speed up the retries.

**Comment by maria-lau** [comment]
@mperham To clarify, am I able to reduce the retry value for a specific job that's in the retry queue? Or do you mean reduce the retry valye on that job class in general?

**Comment by mperham** [comment]
The latter.  Once created, jobs are meant to be immutable, the user is not meant to modify the payload.

**Comment by maria-lau** [comment]
Got it. Okay, thanks @mperham for clarifying. I'll close this issue then.
