### ISSUE TITLE
Job interruptions are confusing Sidekiq Web

### ISSUE THREAD

**Issue by franzliedke** [sidekiq/sidekiq#6383]
Ruby version: 3.3.4
Rails version: 7.1.3.4
Sidekiq / Pro / Enterprise version(s): 7.3.0

We're trying out the new iterable jobs feature. I really like it, it appeared at just the right time. 😊 

It seems that special exception classes are being used in the interruption mechanism. Those are handled in Sidekiq's processor so that they do not cause a retry. However, Sidekiq's own Web UI seems to get confused by them. On the "Metrics" tab, we are seeing 1 "Failure" per interruption - although I would expect these jobs to be counted as "Success".

![image](https://github.com/user-attachments/assets/124de4f7-b2b1-45e5-a12d-47c1a643d980)

Job durations seem to be missing as well.

**Comment by fatkodima** [comment]
The culprit is this line https://github.com/sidekiq/sidekiq/blob/f14749c99af163f89d1de66c46d25baac0ec8f31/lib/sidekiq/job/interrupt_handler.rb#L14 which I think should be just removed. Is it needed?

**Comment by mperham** [comment]
Without the raise, Sidekiq will consider it a success and things like the batch middleware could run callbacks. Maybe the Processor should bypass metrics when Skip is raised?

**Comment by fatkodima** [comment]
Good idea, to bypass metrics, except for duration, I think. I will provide a PR.
