### ISSUE TITLE
Massive number of Redis lmove operations after upgrading to Sidekiq 7.2

### ISSUE THREAD

**Issue by pyueli** [sidekiq/sidekiq#6394]
Ruby version: 3.2
Rails version: 7.1
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 7.2.0

We see massive number of Redis lmove operations after upgrading to Sidekiq 7.2. One of our services makes 30K lmove Redis requests per second while the sidekiq job_fetch is only 460 requests per second. The Redis DB is used by Sidekiq exclusively.

Understand some of lmove operations are valid since they are triggered by the retrieve_work method of super_fetch.
But it cannot explain the huge difference between the numbers of lmove and job_fetch. Any idea on what could be the root cause of the massive number of lmove operations?

Thx!

**Comment by mperham** [comment]
Can you give me a sampling of the actual commands.? Seeing the key names should tell us the root cause.

**Comment by pyueli** [comment]
Below is a sample of the lmove command. But they are triggered from job_fetch. 
LMOVE queue:xxxx...   queue:sq|xxxxx... RIGHT LEFT
It seems there are massive numbers of lmove commands triggered by some other sidekiq components. We are trying to find out the root cause.

**Comment by mperham** [comment]
Yep, that’s super fetch. Your LMOVE command count will scale linearly with the number of queues you have, which is why I recommend only using a handful of queues per process. How many named queues do you have?

**Comment by mperham** [comment]
I don’t know what “job_fetch” is.

Superfetch is the only code in Sidekiq and Pro which use lmove. Enterprise rate limiting uses it too but you aren’t on Ent. Do you have any other plugins?

**Comment by mperham** [comment]
Superfetch does use lmove when recovering jobs, not just for fetching. Do you suddenly see thousands of jobs appearing in your queues?

**Comment by pyueli** [comment]
job_fetch is super fetch.
We don't see thousands of jobs appearing suddenly. The high number of lmove started right after we upgraded to sidekiq 7.2
We are using both Pro and Enterprise. But the service doesn't use rate limiting.

**Comment by pyueli** [comment]
Just to confirm with you. We only have three places in Sidekiq, which calls LMOVE.
- in super fetch, which is called once for each job
- in orphan recovering, which is called once for each orphan job
- rate limiting
Is that correct?

**Comment by mperham** [comment]
Correct. Only Ent's concurrent limiter uses LMOVE.

**Comment by mperham** [comment]
I believe 7.2.0 is when I dropped support for earlier Redis versions and migrated from RPOPLPUSH to LMOVE. Why aren't you using 7.2.4, maybe this was already fixed?

**Comment by pyueli** [comment]
One question regarding one of your previous comment: 

> Your LMOVE command count will scale linearly with the number of queues you have, which is why I recommend only using a handful of queues per process. How many named queues do you have?

Let's say my process has [q1, q2, q3]. Will Sidekiq keep fetching jobs from queues without sleep even if the queues are empty? If that is the case, [q1, q2, q3, q4, q5] will have the same number of LMOVE as [q1, q2, q3] since the Sidekiq keeps running LMOVE to fetch jobs continuously. Why does the number of queues matter?

**Comment by pyueli** [comment]
Close this issue. It turns out to be a service issue.
