### ISSUE TITLE
The testing "jobs" obj is empty when adding jobs to at batch using push_bulk and requiring 'sidekiq/testing' in a helper file

### ISSUE THREAD

**Issue by hadaromash** [sidekiq/sidekiq#6398]
Ruby version: 2.6.8
Rails version: 5.2.6
Sidekiq / Pro / Enterprise version(s): 6.5.12 / 5.5.8 / 2.5.3

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

My spec file require the following file:
`require 'spec_helper'`

In `spec_helper` file I use:
`require 'sidekiq/testing'`

Now I'm running a test of a method that receives a batch object and adds jobs to this batch using `Sidekiq::Client.push_bulk`:
The test:
```
batch = Sidekiq::Batch.new
customer_ids = [*1..2005]

consumer.update_customers_in_sidekiq_batch(batch, customer_ids)

expect(AccountProcessing::EventConsumers::UpdateCustomersJob.jobs.size).to eq(3)
```

The method:
```
def update_customers_in_sidekiq_batch(batch, customer_ids)
    slice_size = ENV.fetch('EVENT_CONSUMERS_UPDATE_CUSTOMERS_SLICE_SIZE', 1000).to_i
    batch.jobs do
      Sidekiq::Client.push_bulk('class' => AccountProcessing::EventConsumers::UpdateCustomersJob,
                                'queue' => 'default',
                                'args' => customer_ids.each_slice(slice_size).map { |customer_ids_slice| [self.id, customer_ids_slice] })
    end
  end
```

The `AccountProcessing::EventConsumers::UpdateCustomersJob.jobs` equals 0 instead of 3.

However, when I require `sidekiq/testing` in the spec file and remove it from `spec_helper`, I have 3 element in the `jobs` array and test passes.

I noticed that only when I require `sidekiq/testing` in `spec_helper`, the `push_bulk` is going through `Sidekiq::BatchClient` that bypasses the `TestingClient`.

Am I missing something in my setup?

Thanks in advance.

**Comment by mperham** [comment]
It sounds like there's an issue when files are required in different orders. I don't have a specific fix for you but it sounds like you can adjust where the require is to solve the issue?

**Comment by nickgervasi** [comment]
Ran into this recently. In my case, ensuring that `sidekiq/testing` was required _after_ `config/environment` (which requires and initializes the application) did the trick.

Worth noting that I only ran into this issue on sidekiq 6.5.x. The same specs running on sidekiq 7.3.x did not exhibit this issue.
