### ISSUE TITLE
Overwriting RAILS_ENV?

### ISSUE THREAD

**Issue by J-Swift** [sidekiq/sidekiq#6399]
I'm not sure this is a bug as much as its a "am I holding this wrong?"... but we recently signed up for enterprise, and were really glad to see that you dont charge for non-prod environments. Our issue is that we use `RAILS_ENV=production` for _all_ our deployed environments (dev/staging/prod) and then use a custom `DEPLOYMENT_SITE=...` for the physical environment (dev/staging/prod). This is maybe not the 'rails way' to do it, but its a way for us to try and be as 'production like' as we can all things considered. It also doesn't seem like we are too strange, based on the straw poll in the RailsSpeed slack [1].

When I started to look at our options, I saw you provide a way to pass `-e`. So I started looking at if that would be an option and it looks like sidekiq actually uses this cli flag to _overwrite_ RAILS_ENV [2]. So it would break our current setup without refactoring the app code. So that leads to my question... are we holding it wrong? I did some git spelunking and it looks like thats just always been how sidekiq has worked, so I guess people have just not worried about reducing their cost, or maybe bit-the-bullet and refactored how configuration/environments are defined for them? Or are we just the first ones to bring it up, and its possibly not how it should work?

Curious to hear what you recommend.

[1] - Paid, but I know you are in there https://railsperf.slack.com/archives/C0RUUGY6R/p1724181937190279
[2] - https://github.com/sidekiq/sidekiq/blob/ed8b217d32f026acc1fae7221dca18d1baa86d11/lib/sidekiq/cli.rb#L297

**Comment by mperham** [comment]
Sidekiq enforces that RAILS_ENV=production is for production only. If you want a free staging/qa environment for Sidekiq Enterprise, you must do the work to create a separate environment for it in config/environments.

**Comment by J-Swift** [comment]
OK, so it sounds like we are holding it wrong then. Which is maybe a little surprising based on my straw poll, but totally fair : D

Glad it could be documented here, I was surprised I hadn't seen the answer in my research.

**Comment by mperham** [comment]
As mentioned elsewhere, it is simple enough to create `config/environments/staging.rb`:

```ruby
require_relative "./production"

# staging overrides
Rails.application.configure do
  config.x.foo.sftp_host = "staging.example.com"
end
```

I hope this works well for you.

**Comment by J-Swift** [comment]
@mperham Right, one part of the issue is our own code checking environment in various ways that we need to fix first. But the bigger (imagined?) issue is that we cant force various gems in our dependency tree to not rely on `RAILS_ENV` to alter their behavior and so we've generally avoided using anything other than `RAILS_ENV=production` for any of our pre-prod environments.

**Comment by mperham** [comment]
Can you give me examples? Because that’s a bug in their part.

**Comment by J-Swift** [comment]
I dont have any current examples, which is why I hedged with 'imagined' : D

But its definitely something weve seen in the perhaps distant past, and I agree its a bug.
