### ISSUE TITLE
Middleware to add stacktrace at the point of being enqued does not work in production

### ISSUE THREAD

**Issue by krisleech** [sidekiq/sidekiq#6400]
Ruby version: 3.2.2
Rails version: 7.0.8.1
sidekiq-ent (2.3.0) 
sidekiq-pro (5.3.0)
sentry-sidekiq (5.8.0)
sidekiq-failures (1.0.1)
sidekiq-scheduler (3.1.0)

We have a middleware, the purpose being to add the stacktrace at the point the worker is enqueued so we can see this in Sentry exception reports. 

The sentry-sidekiq gem adds a Sidekiq middleware which takes the job (Hash) and adds it to the Sentry context which then appears in the Sentry UI.

Therefore the idea is we add the stacktrace to the job Hash in our middleware and it then appears in the Sentry UI.

This works locally and when deployed to staging. But not in production. 

Sentry UI (staging env):

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/186018db-a0de-46e6-a7b0-2cf85fcd0f3d)

```ruby
module Sidekiq
  class PreEnqueuedStacktraceMiddleware
    def call(_, job, _, _)
      job['enqueued_stacktrace'] ||= Rails.backtrace_cleaner.clean(caller)
      yield
    end

    def self.setup
      Sidekiq.configure_client do |config|
        config.client_middleware do |chain|
          chain.insert_before(Sentry::Sidekiq::SentryContextClientMiddleware, self)
        end
      end
    end
  end
end
```

You can also see in the screenshot that the `cattr` which is added by `Sidekiq::CurrentAttributes` middleware is present. This middleware does work, in that it sets `Current` as expected in the worker. But for, I assume, the same reason it does not make it's way to Sentry for staging.

This could potentially be a Sentry issue, e.g. some kind of filtering which only happens in production. But I thought I'd open an issue to see if there is an obvious cause.

**Comment by mperham** [comment]
Are you calling setup in production?

**Comment by krisleech** [comment]
> Are you calling setup in production?

yes, I can see it's in the chain from the production console:

```
Sidekiq.client_middleware
=>
#<Sidekiq::Middleware::Chain:0x00007fbcf06117f0
 @entries=
  [#<Sidekiq::Middleware::Entry:0x00007fbce526f260 @args=[], @klass=Sidekiq::Enterprise::Unique::Client>,
   #<Sidekiq::Middleware::Entry:0x00007fbcf06115c0 @args=[], @klass=Sidekiq::Batch::Client>,
   #<Sidekiq::Middleware::Entry:0x00007fbce5181e70 @args=[], @klass=Sidekiq::PreEnqueuedStacktraceMiddleware>,
   #<Sidekiq::Middleware::Entry:0x00007fbcf220cce8 @args=[], @klass=Sentry::Sidekiq::SentryContextClientMiddleware>,
   #<Sidekiq::Middleware::Entry:0x00007fbcee2d6bf0 @args=[], @klass=NewRelic::Agent::Instrumentation::Sidekiq::Client>,
   #<Sidekiq::Middleware::Entry:0x00007fbce5189940 @args=[Current], @klass=Sidekiq::CurrentAttributes::Save>]>
```

**Comment by mperham** [comment]
I don’t know why it’s not working.

**Comment by krisleech** [comment]
I'm going to close this as I'm pretty sure it's not Sidekiq related. Thanks for looking 💜 

If I find anything of note out I'll update the issue.

**Comment by krisleech** [comment]
So... it works intermittently, some Sentry reports (from Sidekiq workers) have the data our middleware adds, some don't.

I've not sampled many reports yet but the ones which don't have the data seem to have additional newrelic data added to the sentry sidekiq context key.

I think is might be related to [newrelic sidekiq server middleware](https://github.com/newrelic/newrelic-ruby-agent/blob/9.2.2/lib/new_relic/agent/instrumentation/sidekiq/server.rb#L21) in newrelic_rpm v9.2.2, which may clobber additional data added, hard to tell without a deep dive.

I will try and upgrade to the latest new relic gem first given the [server middleware](https://github.com/newrelic/newrelic-ruby-agent/blob/9.12.0/lib/new_relic/agent/instrumentation/sidekiq/server.rb) has changed a lot.
