### ISSUE TITLE
Sidekiq Queue Limit Set in Redis leading to incomplete utilization of available threads

### ISSUE THREAD

**Issue by chirayu45** [sidekiq/sidekiq#6403]
Ruby version: 2.5.3
Rails version: 6.0.3.3
Sidekiq / Pro / Enterprise version(s): Free

I have multiple machines of Sidekiq and all of them have a single queue called "within_5_minutes"
Earlier I had put limit of 5 for this queue in my config/sidekiq.yml
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - within_5_minutes
 :limits:
  within_5_minutes: 5

After that, I had removed the limit line to fix this issue, but still this limit is cached in Redis 
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - within_5_minutes
  
 Now, I had 3 machines with 10 threads each so a total of 30 threads available for this queue but only 5 threads were being utilised by over 4 machines even when I had 200 jobs enqueued. Upon checking in Redis, I found
  irb(main):015:0> Sidekiq::Queue.new("within_5_minutes").limit
=> 5

Whenever, I restart Sidekiq in any one of the machines, this value is again been set to nil and now all the 30 threads are busy
irb(main):018:0> Sidekiq::Queue.new("within_5_minutes").limit
=> nil
![Screenshot 2024-08-22 at 7 31 00 PM](https://github.com/user-attachments/assets/4abe1002-8de0-4fdf-a97a-712c61a2c39c)

But the issue is, I have to restart everytime all the threads are not being utilized. Is there any way to set this value as nil with Rails Console?

Thanks !

**Comment by mperham** [comment]
Sidekiq doesn't support queue limits in OSS except thru Capsules.

**Comment by chirayu45** [comment]
Hi @mperham, Thanks for reaching out!
On every alternate restart of sidekiq, limit is being set to 5 and nil respectively. Even when I had not specified the limits in my config/sidekiq.yml file

:concurrency: 10
developement:
  :concurrency: 2
  :queues:
    - within_5_minutes
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - within_5_minutes
  
Earlier I had a put a limit of 5 for within_5_minutes queue but that had been removed 3 days ago and I am still facing that issue.
irb(main):005:0> Sidekiq::Queue.new("within_5_minutes").limit
=> 5
After restarting sidekiq.service, I get
irb(main):001:0> Sidekiq::Queue.new("within_5_minutes").limit
=> nil

When enqueued jobs were 86, even then only 5 threads were being used when the capacity was for 40
![Screenshot 2024-08-23 at 12 05 27 PM](https://github.com/user-attachments/assets/6b9b4a42-d478-4464-982e-08ead12842a1)
![Screenshot 2024-08-23 at 12 08 18 PM](https://github.com/user-attachments/assets/d916484d-9bfd-49ba-95a3-facb93259c12)

**Comment by mperham** [comment]
You're using a 3rd party extension? Sidekiq does not provide limits.

**Comment by chirayu45** [comment]
Nope, I am using Elasticache's Redis service.

**Comment by mperham** [comment]
I don’t think you understand. Sidekiq does not provide limits.
