### ISSUE TITLE
Namespace not being used

### ISSUE THREAD

**Issue by travisTheOrange** [sidekiq/sidekiq#6406]
Ruby version: 3.3.0
Rails version: 7.1.3.4
Sidekiq Pro version: 7.3.0

We're using Datadog and have configured both DD and Sidekiq Pro to send Sidekiq metrics to our Datadog agent. However, when in Datadog the only way we can view the various metrics from Sidekiq is with the prefix `jobs.*`, rather than `sidekiq.jobs.*`.

Our Sidekiq config file (located in `config/initializers/sidekiq.rb`) looks like this:

```ruby
require 'datadog/statsd' # gem 'dogstatsd-ruby'

Sidekiq.configure_server do |config|
  config.dogstatsd = ->{ Datadog::Statsd.new(socket_path: ENV['SOCKET_PATH'], namespace: 'sidekiq') }
  config.server_middleware do |chain|
    require 'sidekiq/middleware/server/statsd'
    chain.add Sidekiq::Middleware::Server::Statsd
  end
end
```

The first line within the `Sidekiq.configure_server` block was originally not there. Previously we had this line outside the config block, set as:

```ruby
Sidekiq::Pro.dogstatsd = ->{ Datadog::Statsd.new(socket_path: ENV['SOCKET_PATH'], namespace:'sidekiq') }
```

Which resulted in _no_ metrics being sent, maybe. We are seeing metrics in DD now, but we're unsure if it's because of the aforementioned code change or using the prefix `jobs.*` instead of `sidekiq.jobs.*`

**Comment by mperham** [comment]
It's possible I need to update the docs. I'll investigate Monday.

**Comment by mperham** [comment]
Inconsistent namespacing is a currently known issue, see #6337. The plan is the prefix all metrics with `sidekiq` for Sidekiq Pro 8.0. Likewise metrics coming from puma should start with `puma.`. Your namespace should reflect your app name, not the library name. If you have apps with internal names like `wolf`, `lion` and `zebra`, in 8.0 you'd see metrics like `wolf.sidekiq.jobs.expired`.

**Comment by mperham** [comment]
Yes.

**Comment by mperham** [comment]
Only metrics coming internally from Sidekiq. If you want it to have a sidekiq. prefix you'd need to add it.

**Comment by javierjulio** [comment]
I'm working on integrating dogstatsd metrics with Sidekiq 6.5.12 with Pro 5.5.8 and Enterprise 2.5.3 and been reviewing the docs and finding these related issues.

Coming across https://github.com/sidekiq/sidekiq/issues/4650 it was noted that the namespace has to be or at least start with "sidekiq" for Datadog to not consider it a custom metric but in this issue it was stated that the metrics would now be prefixed with the app name so "my-app.sidekiq.*" instead.

Considering the versions Sidekiq 6.5.12 with Pro 5.5.8 and Enterprise 2.5.3, what would the namespace be set as to get the right behavior then? Would it be something like the following?

```ruby
Sidekiq::Pro.dogstatsd = -> { Datadog::Statsd.new(ENV['DD_AGENT_HOST'], 8125, namespace: "my-app.sidekiq") }
```

Or perhaps flipped to be `namespace: "sidekiq.my-app"` instead?

This is also the second issue (the first is #6337) where I'm seeing someone configure the dogstatsd client in a different location than what Sidekiq and Datadog have in their documentation where it's being done here instead:

```
Sidekiq.configure_server do |config|
  config.dogstatsd = ->{ # ... }
end
```

Should that matter at all?

**Comment by weppos** [comment]
> Or perhaps flipped to be `namespace: "sidekiq.my-app"` instead?

Better the format `<app>.<service>` as most likely you care to aggregate by app first. This is best described in the point (3) in the following reply above https://github.com/sidekiq/sidekiq/issues/6406#issuecomment-2310873406

From https://github.com/sidekiq/sidekiq/issues/6337#issuecomment-2318696945, I understand you are using Datadog. Note that there is a better way to work with multiple apps.

Avoid to use one namespace per app, and simply tag the metric with some additional information that allows you to filter out the metrics. For instance you can tag the metrics with the `app` tag, where the value is the actual application name.

In our setup, we run multiple envs (production, sandbox, etc), we don't prefix our metrics by the env. We tag them by env, so we don't end up with a multitude of different metrics name. And we can filter them more effectively in Datadog dashboards.
