### ISSUE TITLE
sidekiq 7.3.0 bottom bar style bug

### ISSUE THREAD

**Issue by mailbaoer** [sidekiq/sidekiq#6409]
Ruby version: 3.2.4
Rails version: 7.1.2
Sidekiq / Pro / Enterprise version(s): 7.3.0

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

When I use Sidekiq version 7.3.0, the bottom bar is not at the bottom of the screen; it's positioned halfway down, and also, it does not span the full width of the screen, covering only a part. This issue does not exist in version 7.2.0.

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

![image](https://github.com/user-attachments/assets/4df044ee-7632-45b6-ba33-5c6044efec16)

**Comment by mperham** [comment]
What browser?

**Comment by mailbaoer** [comment]
latest chrome(128.0.6613.85 arm64)

**Comment by mperham** [comment]
Looks like this might have been broken by @MatWrz's changes in a9cab7d047230bdc53c35c9ead849783c758a3b1

**Comment by mperham** [comment]
@mailbaoer van you try the main branch and see if that fix solves your issue?

**Comment by mailbaoer** [comment]
Of course, I have tested that the mentioned browsers have already been fixed. Thank you very much.
