### ISSUE TITLE
Sidekiq-wrapped ActiveJob from an engine doesn't seem to retry automatically

### ISSUE THREAD

**Issue by timdiggins** [sidekiq/sidekiq#6410]
According to wiki vanilla ActiveJobs run via sidekiq should use Sidekiq's retry mechanism. However I have found that (at least some) jobs from engines aren't retrying, while a TestActiveJob I have created in my rails app is retrying as expected. I can see no configuration differences in the jobs. 

Any ideas why this is happening? I can see the retries for the TestActiveJob in sidekiq web ui, and also each failure in the logs, and I can see the engine's single failure in the log (and absence from the retries in the web ui).

<details><summary>Wiki: https://github.com/sidekiq/sidekiq/wiki/Active-Job#usage</summary>

> At this point, Sidekiq will run the job for us. If the job for some reason fails, Sidekiq will retry as normal.
> 
> Note: This can be confusing when comparing Sidekiq and ActiveJob documentation, as ActiveJob does not provide a retry mechanism on its own, but rest assured: failed ActiveJob jobs will retry.
https://github.com/sidekiq/sidekiq/wiki/Active-Job#usage
</details>

# Versions and other required info

- Ruby version: 3.0.6
- Rails version:  7.0.8.4 
- Sidekiq / Pro / Enterprise version(s): Sidekiq 7.3.1

<details>
<summary>initializer</summary>

```
# frozen_string_literal: true

if ENV["REDIS_PROVIDER"].present?
  # https://github.com/mperham/sidekiq/wiki/Heroku

  sidekiq_redis_configuration = {
    url: ENV[ENV["REDIS_PROVIDER"]], # if one assumes that REDIS_PROVIDER indirection is reliably present
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }, # we must trust Heroku and AWS here
  }
  Sidekiq.configure_server do |config|
    config.redis = sidekiq_redis_configuration
  end

  Sidekiq.configure_client do |config|
    config.redis = sidekiq_redis_configuration
  end
end

Sidekiq.strict_args!
```
</details>

<details>
<summary>sidekiq.yml</summary>

```
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10).to_i %>

# all queues, useful on staging/development/etc
# typically we don't want to run
:queues:
  - urgent
  - mailers
  - default
  - slow
```
</details>

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?
N/A

<details><summary>Also the job I'm using to test is something obvious like this:</summary>

```
class TestActiveJob < ApplicationJob
  queue_as :default
  ERROR = "error"

  def perform(email_or_error = nil)
    if email_or_error == ERROR
      raise "Some deliberate error"
    elsif email_or_error
      NotificationMailer.quick_message(email_or_error, subject: "TestActiveJob has performed", body: "that's it").deliver_now
      puts "TestActiveJob has emailed #{email_or_error}"
    else
      puts "TestActiveJob has performed"
    end
  end
end
```

and there's also an ApplicationJob (which doesn't do much extra)

```
class ApplicationJob < ActiveJob::Base
  around_perform :wrap_performance

  private

  def wrap_performance
    Refreshable::Refresh.required(later: false) do
      yield
    end
  end
end
```
</details>

<details><summary>Sample active job from engine which is not retrying (https://github.com/thredded/thredded/blob/main/app/jobs/thredded/auto_follow_and_notify_job.rb)</summary>

```
module Thredded
  class AutoFollowAndNotifyJob < ::ActiveJob::Base
    queue_as :default

    def perform(post_id)
      post = Thredded::Post.find_by(id: post_id)
      return if post.nil? || post.postable.nil?

      Thredded::AutofollowUsers.new(post).run
      Thredded::NotifyFollowingUsers.new(post).run
    end
  end
end
```
</details>

**Comment by mperham** [comment]
No idea. I would ask the engine maintainers.
