### ISSUE TITLE
Batch description mutability

### ISSUE THREAD

**Issue by jmccormick11** [sidekiq/sidekiq#6411]
Ruby version: 3.3.1
Rails version: 7.1.3.2
Sidekiq / Pro / Enterprise version(s): 7.3.1

This may be closer to a feature request but I noticed the `Sidekiq::Batch` `description` field is not mutable but because it is setup with an `attr_accessor` it seems like it can be changed but that hcange is never persisted. I think it should either raise an error if oyu try and mutate an already created batch, or even better actually let you modify the description of a given batch.

**Comment by mperham** [comment]
Batches are not mutable once created. I don't think I've ever heard of anyone else trying to mutate the description so I'm going to leave the code as is. It's not worth the trouble or risk to change.
