### ISSUE TITLE
Backoff not adding randomness?

### ISSUE THREAD

**Issue by key88sf** [sidekiq/sidekiq#6413]
Ruby version: 3.3.1
Rails version: 7.1
Sidekiq / Pro / Enterprise version(s): 7.3.1

Hi - I was looking at our Retry page in the web UI, where it had over 1,300 jobs in the retry queue. All these jobs were on their 9th retry attempt, and I noticed all of them were scheduled for retry in the same interval and time as when they were first queued. In other words, if 50 jobs were queued per minute originally, then on the 9th retry, those same 50 were scheduled to be retried at the same future timestamp again.

I took a screenshot of the web UI html which shows the timestamps for the next retry, so you can see it's the same down to the 100ths of a second.  I thought Sidekiq uses a backoff that includes a random jitter, in order to avoid this problem? I have not modified anything in the retry mechanism, etc here.  What do you think?

![Screenshot 2024-08-30 at 7 27 36 AM](https://github.com/user-attachments/assets/897d54d0-d9a8-41ee-bfff-5643780357ca)

These jobs end up calling a throttled web API, so when they all run again at the same time, it causes them to fail and get retried again, forever looping and failing. I was counting on the retry randomness to spread them out over time and avoid this.

**Comment by mperham** [comment]
Are these rate limited jobs or error retries? Those two categories use different retry scheduling math.

https://github.com/sidekiq/sidekiq/wiki/Ent-Rate-Limiting#back-off

**Comment by key88sf** [comment]
These are all error retries.

**Comment by mperham** [comment]
Yes, Sidekiq adds randomness. https://github.com/sidekiq/sidekiq/wiki/Error-Handling#automatic-job-retry

**Comment by key88sf** [comment]
Aha, so I think maybe this is because I'm going through ActiveJob here, and not directly using Sidekiq and `perform_async`, etc, yes?

**Comment by mperham** [comment]
I'm not sure how it works with AJ but sounds like it.
