### ISSUE TITLE
Feature Request: Allow Sidekiq::Batch::LINGER to be customized globally

### ISSUE THREAD

**Issue by marcelolx** [sidekiq/sidekiq#6421]
Similar to https://github.com/sidekiq/sidekiq/issues/4772, we would like to customize linger value globally so we don't have to remember to define the linger every time for each batch.

Would that be possible?

**Comment by mperham** [comment]
I'm ok with you redefining the Batch::LINGER constant but I can also add a configuration option in the next Pro release.

**Comment by marcelolx** [comment]
Sounds good; we will override the constant for now and wait for the next Pro release.

I appreciate it, Mike!

**Comment by mperham** [comment]
Ah, it's undocumented but already available:

```ruby
    # set this per batch to override LINGER, e.g.
    #   batch = Sidekiq::Batch.new
    #   batch.linger = 600 # 10 minutes
    #   batch.jobs { ... }
    attr_accessor :linger
```

**Comment by marcelolx** [comment]
Well, that is what we don't want to do: have to set the linger on every `Sidekiq::Batch.new`

We would rather like to be able to do the following

```ruby
# config/initializers/sidekiq.rb
Sidekiq::Batch.linger = 600 # 10 minutes

...
```

**Comment by mperham** [comment]
I think I'm ok with the current options. Redefine LINGER if you want a global change, set it on Batch.new if you want to customize an individual workflow.
