### ISSUE TITLE
How to Support Upgrades to Redis without Suffering Job Loss

### ISSUE THREAD

**Issue by kasra-sheik** [sidekiq/sidekiq#6423]
I'm exploring scenarios in which I'd have to perform upgrades to my Redis Server. Either to perform a routine software patch, upgrade capacity, or any other scenario where I'd need to reboot the host. 

Redis will need to take downtime. Any sidekiq client that tries to enqueue a job or update it's job state in this time will fail. Has anyone dealt with this problem in a production environment in which job loss cannot be tolerated? 

I've sketched out a few potential solutions. You could bring up a separate standby Redis (one with no jobs in it) and swap to it as your backing Redis - making sure you are still able to drain jobs in the old Redis. Another idea would be to set Redis to be in a "unhealthy" state while you upgrade it, and any jobs that try to enqueue at this time will instead push to some separate persistence store. This is essentially `reliable_push` but with guaranteed durability. 

Would love to hear some thoughts from others who have dealt with this problem. Thanks again!

**Comment by mperham** [comment]
The general idea is that you use replication to a newer version replica and promote the replica after shutting down the worker processes and the primary. I tend to avoid overly complex “100% uptime” solutions; most apps can handle a short bit of downtime and keep it simple.
