### ISSUE TITLE
Ent Rate Limiting wiki update

### ISSUE THREAD

**Issue by locofocos** [sidekiq/sidekiq#6433]
I'm using `Sidekiq::Limiter.concurrent`. The wiki states

> The same concurrent limiter (based on the name) may be used with different `lock_timeout` values which allows for different blocks of code to lock on the same resource with a different `lock_timeout`.
> https://github.com/sidekiq/sidekiq/wiki/Ent-Rate-Limiting#notes

It looks like this is also true for `wait_timeout` values, based on some experimentation. If that's true, could we update the wiki? Thanks!

**For context, if you're curious:**

We're using `Sidekiq::Limiter.concurrent` when hitting some external API. We usually hit this API from a sidekiq job, where it makes sense to keep `wait_timeout` at zero. `wait_timeout = 0` helps avoid tying up our sidekiq threads with jobs that are waiting and destined to fail. 

But we also hit this API from our rails controller. In this case, we like having `wait_timeout` set to ~5 seconds, b/c waiting for a loading spinner is better than failing and having to retry.

**Comment by mperham** [comment]
It's sort of an implementation detail and not really designed to be a documented feature. I'm glad it's useful to you; I'm not sure I want to guarantee that behavior forever but I have no plans to change it so I'm not sure what to do.

**Comment by locofocos** [comment]
That's helpful. We'll keep an eye out whenever we upgrade. Thanks!
