### ISSUE TITLE
Drop concurrent-ruby?

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#6442]
We only use it for the metrics. Is it reasonable to vendor or re-implement the necessary code?

https://github.com/sidekiq/sidekiq/blob/9a3b460bb6aa84618fc151e7c950b39e7a11b342/lib/sidekiq/metrics/shared.rb#L9

**Comment by fatkodima** [comment]
Very 👍 given how little it is used. Also found this https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md#210

> Remove concurrent-ruby gem dependency [#4586]

**Comment by mperham** [comment]
Yeah, neither sidekiq pro nor enterprise need concurrent Ruby. I didn’t think it was a big deal for sidekiq to depend on it because it’s already a dependency of rails anyways, and most people are using sidekiq with rails, but since it’s simple to remove…
