### ISSUE TITLE
Negative value on the dashboard chart

### ISSUE THREAD

**Issue by nyjt** [sidekiq/sidekiq#6444]
Ruby version: 3.0.4
Rails version: 6.1.5.1
Sidekiq version: v7.3.1
Redis Version: 7.0.15

On the dashboard chart, we should not see a negative value. 
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/5ec3b0a0-acbd-48d4-83d8-7f36536150ba">

**Comment by mperham** [comment]
I've never seen this before. We'll need more info.

**Comment by nyjt** [comment]
I know what happened here. The Sidekiq UI fetches the `stats` endpoint periodically. One of the requests responded slower than the polling interval, and the next `stats` request was faster than the previous one. Therefore, the negative value appeared because of the slower response, which means the UI processed the stats in the order of getting the response, which could be different from the order of sending the requests.

**Comment by mperham** [comment]
Thanks for the report. I don't think there's anything necessary to fix, maybe clamp negative values to zero?
