### ISSUE TITLE
doc: cancelling an iterable job

### ISSUE THREAD

**Issue by bf4** [sidekiq/sidekiq#6452]
since the job iteration feature changes the primary interface from `#perform` to `#each_iteration` via `#build_enumerator` via an internally defined `#perform` (which is forbidden to be defined in user-space)

I took a look at https://github.com/sidekiq/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job to see if there was recommended change but didn't see one.

I think perhaps the recommendation may be modified or extended to

```ruby
def build_enumerator(*args, cursor:)
  throw :abort if cancelled?
  _build_enumerator(*args, cursor:)
end
```

where `_build_enumerator(*args, cursor:)` is whatever you'd do without this override.

While here, this got me thinking-- it would be nice if there were some nice consistent interface for this sort of thing.  Perhaps there could be a common callback-like code such as suggested by methods like `on_start` and `around_iteration`.

**Comment by mperham** [comment]
I think it’s a great idea to offer an API to cancel a job by JID.

**Comment by bf4** [comment]
<Details>

<Summary>
For full reference, here's what we're doing in ApplicationWorker
</Summary>

```ruby
  def perform(*args)
    return if cancelled?
    return if cancelled_batch?
    _perform(*args) # method must be defined in subclass
```

and

```ruby
  # Jobs can be cancelled
  # https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job
  # @example
  #   ApplicationWorker.cancel!(jid)
  def self.cancel!(jid, delete: false)
    Sidekiq.redis { |c| c.call("SETEX", "cancelled-#{jid}", 86400, "1") }
  end

  def self.cancel_batch!(bid)
    batch = Sidekiq::Batch.new(bid)
    batch.invalidate_all
  end

  def self.cancelled?(jid)
    Sidekiq.redis { |c| c.call("EXISTS", "cancelled-#{jid}") { |c| c > 0 } }
  end

  def self.cancelled_batch?(bid, worker_instance)
    return false if bid.nil?
    !worker_instance.valid_within_batch?
  end

  def cancelled?
    self.class.cancelled?(jid)
  end

  def cancelled_batch?
    self.class.cancelled_batch?(bid, self)
  end
```

</Details>

**Comment by bf4** [comment]
Commits look good. I believe the wiki is locked down and I may not update it?
