### ISSUE TITLE
Bug: Current attributes are nil in callbacks

### ISSUE THREAD

**Issue by sirwolfgang** [sidekiq/sidekiq#6455]
Ruby version: 3.3.0
Rails version: 7.1.3.4
Sidekiq / Pro / Enterprise version(s): 7.3.1

In my application i've discovered an issue where inside of a callback, when I go to enqueue further jobs, my Current attributes are nil. 

My expectation based on how [Current attributes pass between jobs](https://www.mikeperham.com/2022/07/29/sidekiq-and-request-specific-context/) that this would be included.

This is how I ended up fixing the issue within my application, which did solve the issue.
```ruby
class Workflow
   # run during the perform
    def create_step_batch
      callback_params = Current.to_sidekiq_callback_params(**@params)

      step_batch = Sidekiq::Batch.new
      step_batch.on(:success, "#{self.class.name}#callback", **callback_params)
      step_batch
    end

    def callback(status, data)
      @params = Current.from_sidekiq_callback_params(data.symbolize_keys)

      finish
    end
end

class Current < ActiveSupport::CurrentAttributes
  def to_sidekiq_callback_params(**params)
    params.merge(current: { sidekiq_wid: })
  end

  def from_sidekiq_callback_params(data)
    data = data.symbolize_keys

    if (sidekiq = data[:current].symbolize_keys)
      self.sidekiq_wid   = sidekiq[:sidekiq_wid]
    end

    data.except(:current)
  end
end
```

When I get a min, I intend to isolate this bug better into code sample; but wanted share what I have available.

**Comment by mperham** [comment]
Can you show me your initializer?

**Comment by sirwolfgang** [comment]
```ruby
# frozen_string_literal: true

require 'sidekiq/middleware/current_attributes'

# This is in vendor to avoid breaking debugging on development with Better Errors.
require_relative '../../vendor/middlewares/sidekiq_analytics_middleware'

Rails.application.reloader.to_prepare do
  Sidekiq::CurrentAttributes.persist(Current)
end

unless Rails.env.test?
  Sidekiq::Client.reliable_push!
  Sidekiq::Enterprise.unique!
end

Sidekiq.configure_client do |config|
  config.redis = Redis.config_sidekiq
end

Sidekiq.configure_server do |config|
  config.redis = Redis.config_sidekiq

  # @see https://github.com/mperham/sidekiq/blob/main/docs/middleware.md
  config.server_middleware do |chain|
    chain.add SidekiqAnalyticsMiddleware
  end

  ...

  # @see https://github.com/mperham/sidekiq/wiki/Reliability
  config.super_fetch!
  config.reliable_scheduler!

  # @see https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs
  # @see https://crontab.guru/
  config.periodic do |mgr|
    ...
  end
end

Sidekiq.default_job_options = {
...
}
```

**Comment by mperham** [comment]
Ah, it's because the CurrentAttributes middleware comes "after" the Batch middleware so when unwinding, the CurrentAttributes are unset and then the batch middleware creates the callbacks. Use `-v` to see the server middleware ordering. Remove `to_prepare` here and use `Sidekiq::CurrentAttributes.persist("::Current")` instead.

```ruby
Rails.application.reloader.to_prepare do
  Sidekiq::CurrentAttributes.persist(Current)
end
```

Let me know if reordering the middlewares works.

**Comment by mperham** [comment]
It's possible the CurrentAttributes middleware needs to be adjusted to always insert itself at the head of the middleware chain, rather than just `add`ing itself.

**Comment by sirwolfgang** [comment]
Confirmed that pulling from main with the original `Rails.application.reloader.to_prepare` code fixes the issue
