### ISSUE TITLE
Version agnostic way to find leader process

### ISSUE THREAD

**Issue by sato-s** [sidekiq/sidekiq#6471]
According to wiki, we can find a leader with `leader` method.
https://github.com/sidekiq/sidekiq/wiki/Ent-Leader-Election

But,  there seems to be several ways to find a leader and it changes time by time.
https://github.com/sidekiq/sidekiq/issues/5425

I want to make a gem that work with various versions of sidekiq.
Is there good way to find a leader?

**Comment by mperham** [comment]
This should work for all versions.

Sidekiq::Enterprise::VERSION < "2.5.0":

```
Sidekiq::Senate.leader?
```

>= "2.5.0", < "7.0.0":

```
Sidekiq.service("ent:senate").leader?
```

>= "7.0.0":

```
Sidekiq.default_configuration.lookup("ent:senate").leader?
```

**Comment by sato-s** [comment]
@mperham Thanks!!
