### ISSUE TITLE
(docs) Wiki for preloading has incorrect code snippet

### ISSUE THREAD

**Issue by geoffharcourt** [sidekiq/sidekiq#6473]
I don't think I can do a PR against the wiki, but there's a code snippet in https://github.com/sidekiq/sidekiq/wiki/Ent-Multi-Process#application-preload that isn't correct and will cause an application crash.

The after fork callback is currently `ActiveRecord::Base.clear_active_connections!`, but it needs to call the connection handler:

```ruby
# current - breaks
Sidekiq.configure_server do |config|
  config.on(:fork) do
    ActiveRecord::Base.clear_active_connections!
  end
end

# should be
Sidekiq.configure_server do |config|
  config.on(:fork) do
    ActiveRecord::Base.connection_handler.clear_active_connections!
  end
end
```

**Comment by mperham** [comment]
Do you know which version of Rails introduced that change? The code did work in the past. I assume this was removed in 7.0?

Update: looks like it was removed in Rails 7.2?

**Comment by geoffharcourt** [comment]
That would explain it! It was deprecated in 7.1 and removed in 7.2.

**Comment by mperham** [comment]
I've removed the example because _matthewd confirmed that ActiveRecord is fork-safe as of Rails v5.2 and my connection_pool gem is fork-safe as of v2.4.
