### ISSUE TITLE
Question about production performance using delete_by_jid

### ISSUE THREAD

**Issue by bladerunnn** [sidekiq/sidekiq#6478]
I'm aware of the inefficiencies of searching and filtering the scheduled set, however I can't find if using the delete_by_jid directly with the job id and and timestamp of the job is not recommended as well.  

Taking from the https://github.com/sidekiq/sidekiq/wiki/API#scheduled - if you have the job id and the scheduled time is it ok, performance wise, to do the following if your scheduled set is tens of thousands?

```
time = scheduled_obj.scheduled_for.to_f
jid = scheduled_obj.job_id
Sidekiq::ScheduledSet.new.delete_by_jid(time, jid)
```

From the api.rb source:
```

    def delete_by_jid(score, jid)
      Sidekiq.redis do |conn|
        elements = conn.zrange(name, score, score, "BYSCORE")
        elements.each do |element|
          if element.index(jid)
            message = Sidekiq.load_json(element)
            if message["jid"] == jid
              ret = conn.zrem(name, element)
              @_size -= 1 if ret
              break ret
            end
          end
        end
      end
    end
```

I assume this is performant, however I'm not 100% on the zrange performance with large sets.  Please advise - thanks!

**Comment by mperham** [comment]
That should be fast most of the time. It iterates through each result because you can schedule many jobs at the exact same time; one score does not correspond to one job. But having multiple results should be uncommon since we add random jitter when scheduling most things.
