### ISSUE TITLE
/sidekiq/busy crashes with LocalJumpError and no block given (yield) error

### ISSUE THREAD

**Issue by joshdaloewen** [sidekiq/sidekiq#6486]
Ruby version: 3.2.0
Rails version: 7.1.5
Sidekiq / Pro / Enterprise version(s): 7.3.4

I just added Sidekiq to an app, and have been running Jobs without any issues.  The web interface has been mounted, and all the pages work EXCEPT the /busy page.  That always crashes with `no block given (yield)` error.

I was monkey-ing in the code at api.rb:932, and it seems to think no block has been passed.  It's the `each` method that is failing.  When I disable a few parts of the busy.erb template (eg. processes.size, processes.total_concurrency, processes.total_rss) I'm able to get the page to load.  But it seems odd to me that a fresh install of Sidekiq would give me basic errors like this.

LocalJumpError (no block given (yield)):
  
sidekiq (7.3.4) lib/sidekiq/api.rb:932:in `block in each'
sidekiq (7.3.4) lib/sidekiq/api.rb:925:in `each'
sidekiq (7.3.4) lib/sidekiq/api.rb:925:in `each'
descriptive_statistics (2.5.1) lib/descriptive_statistics/support/convert.rb:37:in `to_array'
descriptive_statistics (2.5.1) lib/descriptive_statistics/support/convert.rb:8:in `convert'
descriptive_statistics (2.5.1) lib/descriptive_statistics/sum.rb:3:in `sum'
sidekiq (7.3.4) lib/sidekiq/api.rb:954:in `total_concurrency'
sidekiq (7.3.4) web/views/busy.erb:12:in `_erb_busy'
sidekiq (7.3.4) lib/sidekiq/web/action.rb:99:in `_erb'
sidekiq (7.3.4) lib/sidekiq/web/action.rb:68:in `erb'
sidekiq (7.3.4) lib/sidekiq/web/application.rb:92:in `block in <class:WebApplication>'
sidekiq (7.3.4) lib/sidekiq/web/application.rb:390:in `instance_exec'
sidekiq (7.3.4) lib/sidekiq/web/application.rb:390:in `block in call'
sidekiq (7.3.4) lib/sidekiq/web/application.rb:388:in `catch'
sidekiq (7.3.4) lib/sidekiq/web/application.rb:388:in `call'
sidekiq (7.3.4) lib/sidekiq/web/csrf_protection.rb:51:in `admit'
sidekiq (7.3.4) lib/sidekiq/web/csrf_protection.rb:40:in `call'
rack (3.1.8) lib/rack/static.rb:161:in `call'
rack (3.1.8) lib/rack/builder.rb:277:in `call'
sidekiq (7.3.4) lib/sidekiq/web.rb:121:in `call'
sidekiq (7.3.4) lib/sidekiq/web.rb:126:in `call'
actionpack (7.1.5) lib/action_dispatch/routing/mapper.rb:31:in `block in <class:Constraints>'
actionpack (7.1.5) lib/action_dispatch/routing/mapper.rb:60:in `serve'
actionpack (7.1.5) lib/action_dispatch/journey/router.rb:51:in `block in serve'
actionpack (7.1.5) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
actionpack (7.1.5) lib/action_dispatch/journey/router.rb:124:in `each'
actionpack (7.1.5) lib/action_dispatch/journey/router.rb:124:in `find_routes'
actionpack (7.1.5) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.1.5) lib/action_dispatch/routing/route_set.rb:882:in `call'
rack (3.1.8) lib/rack/tempfile_reaper.rb:20:in `call'
rack (3.1.8) lib/rack/etag.rb:29:in `call'
rack (3.1.8) lib/rack/conditional_get.rb:31:in `call'
rack (3.1.8) lib/rack/head.rb:15:in `call'
actionpack (7.1.5) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
actionpack (7.1.5) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (7.1.5) lib/active_record/migration.rb:655:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (7.1.5) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.1.5) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (7.1.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (7.1.5) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (7.1.5) lib/active_support/tagged_logging.rb:139:in `block in tagged'
activesupport (7.1.5) lib/active_support/tagged_logging.rb:39:in `tagged'
activesupport (7.1.5) lib/active_support/tagged_logging.rb:139:in `tagged'
activesupport (7.1.5) lib/active_support/broadcast_logger.rb:241:in `method_missing'
railties (7.1.5) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.5.2) lib/sprockets/rails/quiet_assets.rb:17:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (3.1.8) lib/rack/method_override.rb:28:in `call'
rack (3.1.8) lib/rack/runtime.rb:24:in `call'
activesupport (7.1.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
actionpack (7.1.5) lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
actionpack (7.1.5) lib/action_dispatch/middleware/server_timing.rb:58:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/static.rb:25:in `call'
rack (3.1.8) lib/rack/sendfile.rb:114:in `call'
actionpack (7.1.5) lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
railties (7.1.5) lib/rails/engine.rb:536:in `call'
puma (6.4.3) lib/puma/configuration.rb:272:in `call'
puma (6.4.3) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.3) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.3) lib/puma/request.rb:99:in `handle_request'
puma (6.4.3) lib/puma/server.rb:464:in `process_client'
puma (6.4.3) lib/puma/server.rb:245:in `block in run'
puma (6.4.3) lib/puma/thread_pool.rb:155:in `block in spawn_thread'

**Comment by mperham** [comment]
Remove descriptive_statistics and try to reproduce it again.

**Comment by joshdaloewen** [comment]
Yup, that did it.  Sorry for the hassle (and thanks for your second eyes on that).  I thought descriptive_statistics was a sidekiq dependency...I guess I previously added it to this app.
