### ISSUE TITLE
Batch callback_queue does not persist

### ISSUE THREAD

**Issue by bschrag620** [sidekiq/sidekiq#6489]
Ruby version: 3.2.5
Rails version: 7.1.5
Sidekiq / Pro / Enterprise version(s): sidekiq-pro 7.2.2

I have a workflow that specifies a `callback_queue` when starting a batch. In some of the jobs, some of the jobs may open the batch and add more jobs. However, when doing so the original `callback_queue` is not passed along. I should note here that this was discovered because an `EmptyBatch` job was being created in the `default` queue rather than the originally specified `callback_queue`. To work around this, we are having to specify the `callback_queue` every time a batch has its `jobs` opened, even when previously specified.

My understanding is that batches are generally considered immutable so it feels like once a `callback_queue` is specified it should persist for the entirety of the batch. I noticed in the `initilialize` for `sidekiq/batch.rb`, there currently doesn't seem to be an effort to initialize the `callback_queue` from `props`. Setting `@callback_queue = props["cbq"]` seems to resolve this issue.

**Comment by mperham** [comment]
Can you show me the misbehaving code, even if you have to elide parts? I want to make sure I understand your usage so I can build a test for this.

**Comment by bschrag620** [comment]
@mperham I did a bit more testing and I do think this issue is scoped specifically to the situation where a batch is re-opened but then no jobs are passed in. 
```
if @added.size == 0
  cbq = callback_queue || Sidekiq.default_job_options["queue"] || "default"
  Sidekiq::Client.push("class" => Sidekiq::Batch::Empty, "queue" => cbq, "args" => [])
end
```
When a batch is re-opened, `callback_queue` is not set in the initializer. This causes the line above to set `cbq` to `default` (or whatever the configured default value is) rather than the value originally specified in the batch creation. So really, maybe the misbehaving code is just in the initializer, and not the code above. In the initialize method, I added the following to test the fix:
```
if bid
  ...
  @callback_queue = props['cbq']
  ...
end
```

This causes `callback_queue` to be set and the `Batch::Empty` to be pushed into the same queue.

**Comment by mperham** [comment]
Are you possibly creating an empty child batch when reopening a parent batch? I'm not sure the child batch inherits the parent's callback_queue today. It probably should.

I'm not sure it's possible to "reopen" a batch and have it create a Batch::Empty job; by definition the job reopening the batch is in the batch already. Again, please show the actual code if possible; I want to make sure I capture the broken edge case in a test.

**Comment by bschrag620** [comment]
```
class BatchTest
  include Sidekiq::Job
  queue_as :foo

  def perform
    batch.jobs do
      # do nothing here
    end
  end

  def self.start
    batch = Sidekiq::Batch.new
    batch.callback_queue = :foo
    batch.jobs { BatchTest.perform_async }
  end
end

BatchTest.start
```
I apologize for the terminology I'm using here, "reopen" seems like the incorrect term. In the job, I'm opening the batch (this is what I was referring to as re-opening) and adding more jobs. Because the jobs being added inside of the job is an empty set, sidekiq is pushing a `Batch::Empty` job into it with a callback queue of `default`. To avoid this, I can specify the callback queue inside the job as follows:

```
def perform
  batch.callback_queue = :foo  # <---- re-specify the callback queue
  batch.jobs do
    # do nothing here
  end
end
```
The change here ensures the Empty::Batch utilizes the correct callback queue when complete.

**Comment by mperham** [comment]
I think the actual fix is this:

```diff
--- a/lib/sidekiq/batch.rb
+++ b/lib/sidekiq/batch.rb
@@ -251,7 +251,7 @@ module Sidekiq
           parent, Thread.current[:sidekiq_batch] = Thread.current[:sidekiq_batch], self
           block.call
 
-          if @added.size == 0
+          if @new && @added.size == 0
             cbq = callback_queue || Sidekiq.default_job_options["queue"] || "default"
             Sidekiq::Client.push("class" => Sidekiq::Batch::Empty, "queue" => cbq, "args" => [])
           end
```

Since you're reopening, the `jobs` block shouldn't issue Batch::Empty. By definition reopening means we're running in a batch job already so adding no jobs should be a no-op.

**Comment by mperham** [comment]
(That said, I still agree that this is a good fix too:

```
@callback_queue = props['cbq']
```

**Comment by mperham** [comment]
I found two places in the test suite where I had bad assertions that glossed over extraneous Batch::Empty jobs. I don't think there could be any way that people would rely on this behavior so I'll fix it in the next Pro patch release.

**Comment by bschrag620** [comment]
Thanks Mike!
