### ISSUE TITLE
Job callbacks, high level function

### ISSUE THREAD

**Issue by null0vector** [sidekiq/sidekiq#6490]
Hey there! I want to add `on_success` callback to my job. So I suppose it is possible just simply to put method inside perform at the end and have private method. But I want more flexible way like this:

```ruby
class FirstJob
# ...
end

class SecondJob
# ...
end

FirstJob.perform_async("abc") do |job|
  job.on_success do |data|
    SecondJob.perform_async(data)
  end
end
```

Does anybody else want this feature? I can implement it

**Comment by mperham** [comment]
What use case are you trying to solve? Are you trying to build a workflow without coupling the two jobs together?

**Comment by null0vector** [comment]
> What use case are you trying to solve? Are you trying to build a workflow without coupling the two jobs together?

@mperham Yes! In my case `JobC` depend on `JobB`, `JobB` depend on `JobA`. I don't want to have implementation details inside one of these jobs

**Comment by mperham** [comment]
There are third party extensions which add workflows on top of Sidekiq and of course, Sidekiq Pro offers a broader workflow system with Batches. I'm not a fan of Rails's callback pattern so you don't find it in Sidekiq but you can use Active Job callbacks, e.g. `after_perform`.
