### ISSUE TITLE
Metrics filter applies inconsistently

### ISSUE THREAD

**Issue by J-Swift** [sidekiq/sidekiq#6498]
Ruby version: 3.3.5
Rails version: 6.1.7.9
Sidekiq / Pro / Enterprise version(s): 7.3.5 / 7.3.2

It appears the time filter on the Metrics tab only applies if you also supply a name. Otherwise it just resets to '1h'. Ive captured a screen-recording demonstrating.

https://github.com/user-attachments/assets/0574640b-15bf-45fb-8ebc-9f800f3f7af9

**Comment by mperham** [comment]
I think it might be useful to capture this setting in a cookie so it persists. PRs welcome if anyone wants a relatively easy task.

**Comment by J-Swift** [comment]
I'm not sure its a cookie issue (at least not entirely). It appears the server redirects when not submitting `substr` param. In this screenshot, the first arrow is a network request with `substr` being set. Notice no redirect. The 2nd arrow is without it set.
<img width="1523" alt="Screenshot 2024-11-12 at 1 32 02 PM" src="https://github.com/user-attachments/assets/8f021ff2-6484-4c8e-bab9-a7bda17b0a64">

**Comment by mperham** [comment]
That literally just changed this morning, someone refactored the metric filtering to use GET. See latest pulls.

**Comment by mperham** [comment]
In other words, see how main behaves.

**Comment by J-Swift** [comment]
Thanks for confirming, it was going to take me a bit to get things updated to check on my end.
