### ISSUE TITLE
feature request: possible to have unique job running + enqueued?

### ISSUE THREAD

**Issue by modosc** [sidekiq/sidekiq#6499]
Ruby version: 3.3.5 
Rails version: 7.2.2 
Sidekiq / Pro / Enterprise version(s): 7.3.2

is it possible to configure unique jobs so that a single job is unique both in the queue and while running (eg, [this](https://github.com/mhenrixon/sidekiq-unique-jobs/issues/748) functionality from `sidekiq-unique-jobs`)? we have a similar issue to https://github.com/sidekiq/sidekiq/issues/3471#issuecomment-300866335 but we'd like to dedupe at enqueue time _and_ run time.

**Comment by mperham** [comment]
Isn’t that the default? https://github.com/sidekiq/sidekiq/wiki/Ent-Unique-Jobs#unlock-policy

**Comment by modosc** [comment]
if i'm understanding correctly then with `unique_until: :success` my job is unique from the moment it's enqueued until it finishes executing successfully. this means that any attempt to enqueue the job during this time is rejected. 


apologies if i'm not making this clear enough. 

if i use `unique_until: :start` then my job is unique from the moment it's enqueued until it starts. this means i'll only ever have a single job in the queue but potentially i could have multiple jobs running.

what we want is separate uniqueness for enqueuing _and_ running. only one copy will ever exist in the queue, but also only one copy will ever run simultaneously. basically `unique_until: :start` but if our job is reenqueued while it's running the enqueued job won't be picked up by a worker until the running job finishes.

**Comment by mperham** [comment]
Sidekiq cannot guarantee unique execution as that’s a hard problem when distributed across many machines. What I do provide is a concurrency limiter which can be used as a distributed Mutex. See the rate limiting wiki page.
