### ISSUE TITLE
[Sidekiq Enterprise] Unregistering periodic jobs

### ISSUE THREAD

**Issue by tdegrunt** [sidekiq/sidekiq#6500]
Hello, spent a few hours now trying to unregister periodic jobs from our setup, but not sure how this is supposed to work.
I've read https://stackoverflow.com/questions/36876565/how-to-delete-sidekiq-enterprise-periodic-jobs - but that's inconclusive.

Shutting down the whole Sidekiq cluster doesn't remove these periodic jobs. There doesn't seem to be anything in the wiki about it either. Can you please explain me how to remove a periodic entry (not the jobs itself, but the cron entries) from Sidekiq?

**Comment by mperham** [comment]
You delete the line and redeploy.

**Comment by tdegrunt** [comment]
Our Sidekiq.rb used to have this block, but that's been removed and we've redeployed several times:
```ruby
  config.periodic do |mgr|
    cron = YAML.load_file('config/cronjobs.yml')
    cron.each do |_name, options|
      mgr.register(options["cron"], options["class"], args: options["args"], retry: options["retry"]|| 2, queue: options["queue"])
    end
  end
```

I would've thought this would remove all entries.

**Comment by mperham** [comment]
If the block is gone, where are you still seeing the entries? The Web UI? It can’t clear the data if you don’t start the periodic subsystem at all. The data might still be in Redis for the Web UI to display but no jobs should be created.

**Comment by tdegrunt** [comment]
We were indeed seeing the entries in the web UI. So in conclusion the solution is to keep having this block in Sidekiq.rb:
```ruby
config.periodic do |mgr|
end
```

Maybe not having this block should clear the jobs as well? 
Thanks!
