### ISSUE TITLE
redis-client throwing "unknown keyword: :region"

### ISSUE THREAD

**Issue by eileen-jiang** [sidekiq/sidekiq#6504]
Ruby version: 3.2.5
Rails version: 7.1.4.1
Sidekiq / Pro / Enterprise version(s): sidekiq-pro 7.3.5
Redis-client version: redis-client-0.22.2

While upgrading to Sidekiq 7, I'm trying to understand the changes made to `Sidekiq::RedisConnection`. We're using `Sidekiq::RedisConnection.create` to create a separate connection pool to Redis instead of `Sidekiq.redis` because we need an extra connection for a "cron" that we're running.

We're now getting this error originating from `redis-client`'s `config.rb` at startup: `unknown keyword: :region` with logs:
```
Sidekiq 7.3.5 connecting to Redis with options {:size=>15, :pool_name=>"internal", :db=>5, :host=>..., :port=>6379, :timeout=>5.0, :password=>"REDACTED", :region=>"us-west-2", :ssl=>true, :username=>"app", :url=>nil}
```
Is `region` no longer an offered option?

I've read through the [Connection Pools changes section](https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-API-Migration.md#connection-pools) but doesn't seem relevant to my issue.

**Comment by mperham** [comment]
This is a redis-client issue, nothing Sidekiq knows about or controls.
