### ISSUE TITLE
Permission error trying to push to wiki

### ISSUE THREAD

**Issue by eileen-jiang** [sidekiq/sidekiq#6506]
I'm trying to open a PR to update the wiki. Followed instructions [here](https://github.com/sidekiq/sidekiq/blob/main/.github/contributing.md) and used HTTPS to clone the `sidekiq.wiki` repo, which worked, but I'm getting this error when trying to push my changes:
```
remote: Permission to sidekiq/sidekiq.wiki.git denied to eileen-jiang.
fatal: unable to access 'https://github.com/sidekiq/sidekiq.wiki.git/': The requested URL returned error: 403
```

Here's the change I'd like to make:
![Screenshot 2024-11-20 at 11 06 02 AM](https://github.com/user-attachments/assets/d893a6a5-5483-4a37-864e-5f969822357b)

We previously were accessing the payload via `work['payload']`, which now returns a String instead of a Hash in Sidekiq 7. I think `work.job` is the more idiomatic way to access now?

**Comment by eileen-jiang** [comment]
Sorry is that warning you pasted already in the wiki?

Thanks for confirming! This was silently having different behavior for us because Ruby apparently allows lookups into String hashes, so `{ 'foo' => 1 }['foo']` returned `'foo'` instead of '1'.

**Comment by mperham** [comment]
I guess you meant:

```ruby
> "{ 'foo' => 1 }"['foo']
=> "foo"
```

**Comment by eileen-jiang** [comment]
Sorry. That is totally what I meant :)
