### ISSUE TITLE
Filter on Sidekiq Morgue Page Not Working After Update to Sidekiq 7.3.6

### ISSUE THREAD

**Issue by durcak** [sidekiq/sidekiq#6508]
### Environment

- **Sidekiq Version:** 7.3.6
- **Rails Version:** 7.2.2
- **Ruby Version:** 3.3.5

### Summary

After updating to **Sidekiq version 7.3.6**, which includes the following change:  
*Filtering in the Web UI now works via GET so you can bookmark a filtered view ([#6497](https://github.com/mperham/sidekiq/pull/6497))*  

the **filter functionality on the Morgue page** (`https://WEBSITE/sidekiq/morgue`) has stopped working.

### Steps to Reproduce

1. Update Sidekiq to version 7.3.6.
2. Navigate to `https://WEBSITE/sidekiq/morgue`.
3. Use the filter with any substring (e.g., `test`).

### Expected Behavior

The request should be sent to:  
`https://WEBSITE/sidekiq/morgue?substr=test`

### Actual Behavior

The request fails with the following error:  
`No route matches [GET] "/admin/sidekiq/dead"`  

The URL generated is incorrect:  
`https://WEBSITE/sidekiq/morgue/sidekiq/dead?substr=test`  

Instead, it should be:  
`https://WEBSITE/sidekiq/morgue?substr=test`

**Comment by mperham** [comment]
Thanks for pointing this out!

**Comment by franzliedke** [comment]
Soooorry, and thanks for the fix!
