### ISSUE TITLE
Disallow block argument for limiters

### ISSUE THREAD

**Issue by aliismayilov** [sidekiq/sidekiq#6512]
Ruby version: ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin24]
Sidekiq Enterprise version: 7.3.2

In ruby, every method can receive a block:
```ruby
def foo; end
foo { garble }
=> nil
```

And that block won't be executed if no `yield` was defined in the method. I've found myself way too many times shipping the following code to production:
```ruby
Sidekiq::Limiter.concurrent('erp', 50, wait_timeout: 5, lock_timeout: 30) do
  # work
end
```

I'd like to suggest to add the following lines to every `Sidekiq::Limiter.(concurrent|bucket|etc.)` methods:
```ruby
raise ArgumentError, "block given" if block_given?
# or
raise ArgumentError, "block given, did you mean to use `within_limit`?" if block_given?
```

**Comment by mperham** [comment]
The wiki specifically says to memoize limiters and treat it as a class constant if possible:

```ruby
ERP = Sidekiq::Limiter.concurrent('erp', 50, wait_timeout: 5, lock_timeout: 30)
```

If you did that, it seems like you wouldn't have problems adding a block -- the limited action is separated from the limiter definition in the code.

If we disallow blocks now, would that make it harder to support blocks in the future, if we wanted to add something like a configuration block?

```ruby
c = Sidekiq::Limiter.concurrent(...) do |lmtr|
  lmtr.more_config...
end
c.within_limit ...
```

**Comment by aliismayilov** [comment]
> The wiki specifically says to memoize limiters and treat it as a class constant if possible:
> 
> ```ruby
> ERP = Sidekiq::Limiter.concurrent('erp', 50, wait_timeout: 5, lock_timeout: 30)
> ```
> 
> If you did that, it seems like you wouldn't have problems adding a block -- the limited action is separated from the limiter definition in the code.

We have more complex examples that also require dynamic arguments:
```ruby
def perform(user_id)
  Sidekiq::Limiter.bucket("stripe-#{user_id}", 30, :second, wait_timeout: 5).within_limit do
    # call stripe with user's account creds
  end
end
```

It's not so easy to always enforce or keep in mind to assign to a variable. In that case, one might as well keep in mind to not forget `.within_limit` 😄 

> If we disallow blocks now, would that make it harder to support blocks in the future, if we wanted to add something like a configuration block?
> 
> ```ruby
> c = Sidekiq::Limiter.concurrent(...) do |lmtr|
>   lmtr.more_config...
> end
> c.within_limit ...
> ```

If such ergonomics would be introduced, then the number of arguments of the block could be enforced.

**Comment by mperham** [comment]
This is fixed but it just missed the deadline for 7.x, you'll see it in 8.0.
