### ISSUE TITLE
Pro version "Dead" Filter broken

### ISSUE THREAD

**Issue by troex** [sidekiq/sidekiq#6514]
Ruby version: 3.2.6
Rails version: -
Sidekiq / Pro / Enterprise version(s): 7.3.6 / Pro 7.3.3 / Ent 7.3.3

In `Sidekiq::Pro::Web` version filtering is not working in "Dead" tab, because of `<form action="/dead">` it renders 404 when trying to search.

It should be `<form action="/morgue">` instead.

**Comment by mperham** [comment]
Dupe, fixed on main.
