### ISSUE TITLE
Add CI for Valkey

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#6527]
As Redis Inc squeezes their ecosystem harder, we need to support alternatives to ensure the ecosystem doesn’t go into a capitalist death spiral. Add CI for Valkey as I think it’s time to add official support in 8.0.

**Comment by skunkworker** [comment]
I'm excited there is official support for Valkey. A few projects I am on are looking to move off of redis and onto valkey in the upcoming year.

**Comment by kapso** [comment]
@mperham this is great, thanks for your work.

Will Sidekiq Pro have support for Valkey as well. And also what is the timeline?

**Comment by mperham** [comment]
Yes. Today. Valkey is just a fork of Redis and should be 100% compatible.
