### ISSUE TITLE
Unable to get error/death handlers to operate in rspec

### ISSUE THREAD

**Issue by KieranP** [sidekiq/sidekiq#6538]
Ruby version: 3.3.4
Rails version: 8.0.0
Sidekiq / Pro / Enterprise version(s): Pro 7.3.3

I'm trying to get our error and death handlers to run in Rspec but I cannot seem to get them to execute.

```ruby
  Sidekiq.configure_server do |config|
    config.redis = { url: redis_url }
    config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new

    config.super_fetch! do |jobstr, _pill|
      Sidekiq.logger.error("Sidekiq Recovered Job: #{jobstr}")
    end

    config.error_handlers << ->(error, context, _config) do
      puts "calling error_handlers"
    end

    config.death_handlers << ->(job_payload, error) do
      puts "calling death_handlers"
    end
  end
```

Any suggestions? I don't see anything about this on https://github.com/sidekiq/sidekiq/wiki/Testing

**Comment by mperham** [comment]
RSpec is not a Sidekiq process, the error/death handlers do not run in a test process. You'd have to test them manually or extract a set of sample arguments manually and write a test which calls the Proc with those arguments.

**Comment by KieranP** [comment]
Hmm, my expectation with `Sidekiq::Testing.inline!` is that it would test the whole middleware stack and error handlers. Similar to the support you've added for `Sidekiq::Testing.server_middleware`, would you consider adding something like this within Sidekiq::Testing?

```ruby
Sidekiq::Testing.configure_server do |config|
  config.error_handlers << ->(error, context, _config) do
    puts "calling error_handlers"
  end

  config.death_handlers << ->(job_payload, error) do
    puts "calling death_handlers"
  end
end
```

or more simply:

```ruby
Sidekiq::Testing.error_handlers << ->(error, context, _config) do
  puts "calling error_handlers"
end

Sidekiq::Testing.death_handlers << ->(job_payload, error) do
  puts "calling death_handlers"
end
```

Is there any harm is allowing this?

**Comment by mperham** [comment]
You're asking for one step closer to a full blown Sidekiq mock to verify the entire job execution path. This is diminishing returns and gets you into an uncanny valley of relying on something which can never actually replicate the thing 100%. Where do we stop?

If you want to test Sidekiq, start Sidekiq, enqueue a job and verify the standard output. At some point your system test has to test the actual system.

Another way of looking at it: how often are your handlers changing? Automated tests are a great investment for code which changes frequently. If your handlers are simple, test them once manually and move on.
