### ISSUE TITLE
Dealing with perform_bulk and dynamic queues set from a client middleware.

### ISSUE THREAD

**Issue by ericproulx** [sidekiq/sidekiq#6546]
By design, `perform_bulk` will push all the jobs in a single queue since its based on a single worker. In my case, I've a `client_middleware` that will update a job's queue dynamically based on its args. This works perfectly when calling `perform_async` but when using `perform_bulk` the queue is [set](https://github.com/sidekiq/sidekiq/blob/7239276d85089e9a19c2642584bf6fa5a53224dc/lib/sidekiq/client.rb#L272) like this `payload['queue'].first`.

I wonder if it could be possible to partition queues from the payload and push jobs on different queues instead of relying on the first one.

**Comment by mperham** [comment]
PRs welcome but this seems like not much value for the increase in code complexity.
