### ISSUE TITLE
Filter in dead jobs not working in Sidekiq 7.3.6 / Pro 7.3.3 / Ent 7.3.3

### ISSUE THREAD

**Issue by TheWudu** [sidekiq/sidekiq#6550]
Ruby version: 3.3.6
Rails version: -
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.3.6 / Pro 7.3.3 / Ent 7.3.3

When trying to filter for dead jobs in the latest version, it only opens a page with "Not Found" as plain text. 
Downgrading to Sidekiq 7.3.5 / Pro 7.3.2 / Ent 7.3.2 make it work again. 

So something happend in the last update.

Best regards,
TheWudu

**Comment by mperham** [comment]
Fixed on main, waiting on the 7.3.7 release.

**Comment by mperham** [comment]
(you just need to change "dead" to "morgue" in the URL)
