### ISSUE TITLE
Sidekiq::Periodic::Manager#inspect can consume GBs of memory

### ISSUE THREAD

**Issue by jdelStrother** [sidekiq/sidekiq#6553]
Ruby version: 3.2.4
Rails version: 7.2
Sidekiq / Pro / Enterprise version(s): 7.3.3

I have sentry installed to catch errors. When an error occurs, sentry [ends up calling inspect](https://github.com/getsentry/sentry-ruby/blob/d21c5000d5d9e9fa5a8ba93403c2ed65a8173808/sentry-ruby/lib/sentry/interfaces/single_exception.rb#L51) on the job that failed.

When this happened on our sidekiq leader process, I sometimes saw it consuming ever-increasing amounts of memory, eventually getting killed at around the 7GB mark. The job has a @_context ivar that, on the leader process, eventually leads to a large Containers::Heap structure which seems to get exponentially larger based on the number of registered cronjobs.

I believe I've more-or-less reproduced the problem here:

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require "sidekiq"
require "sidekiq/cli"
require "sidekiq-ent"
require "sidekiq-ent/periodic"
require "sidekiq-ent/periodic/config"
require "sidekiq-ent/periodic/manager"
require "sidekiq-ent/senate"
require "active_support"
require "active_support/core_ext"
require "logger"

def rss_size
  pid = $$
  ["/proc/#{pid}/status", "/system/lxproc/#{pid}/status"].each do |proc_path|
    next unless File.exist?(proc_path)
    if File.read(proc_path) =~ /VmRSS:\s*(\d+) kB/
      return $1.to_i
    end
  end
  IO.popen(%W[ps -o rss= -p #{pid}]) { _1.read.to_i }
end

class SomeJob
  include Sidekiq::Job
  def perform(number)
  end
end

# Potential fixes:
# require "sidekiq-ent/heap"
# class Containers::Heap
#   def inspect
#     "<#{self.class.name} size=#{size}>"
#   end
# end
# class Sidekiq::Periodic::Manager
#   def inspect
#     "#<#{self.class.name}>"
#   end
# end

config = Sidekiq.default_configuration
config.logger = Logger.new($stdout).tap { _1.level = 1 }
senate = config.lookup("ent:senate", Sidekiq::Senate)
loop do
  senate.stage_coup!
  break if senate.leader?
  puts "trying to stage a coup..."
  sleep 1
end

cfg = config.lookup("ent:croncfg", Sidekiq::Periodic::Config)
NUMBER_OF_CRONJOBS = 40
NUMBER_OF_CRONJOBS.times do |i|
  cfg.register "* * * * *", "SomeJob", args: [i]
end


act = config.lookup("ent:periodic", Sidekiq::Periodic::Manager)
act.persist(cfg)

puts "RSS=#{rss_size}"
act.process(Time.now)
act.process(Time.now + 1.minute)
act.process(Time.now + 1.day)

puts "done! Inspecting...."
puts "Inspection is #{config.inspect.length / 1024 / 1024}MB long"
# puts config.inspect

puts "RSS=#{rss_size}"
```

This script doesn't show the boundless memory growth we were seeing in production, I think maybe that's triggered by having 1 thread trying to inspect a job while another thread is running Sidekiq::Periodic::Manager#process. But you can increase NUMBER_OF_CRONJOBS to, say, 50 to see that the inspect-size seems to get exponentially worse.

It might be worth overriding `inspect` on Containers::Heap and/or Sidekiq::Periodic::Manager to avoid this. I've patched it locally in our own app for now.

(Our own cronjobs aren't all "* * * * *", nor do they all use a single job class. But we do have 50-or-so of them, not sure if that's an unprecedented amount..?)

**Comment by mperham** [comment]
So I think this is, in part, due to `Sidekiq::Config` having a large `inspect` output because it holds references to closures and Procs which themselves have state. I'm not super familiar with best practices for how to trim or customize the output of `to_s` or `inspect`. Anyone have more info or good reference material on the subject? Should I allowlist only known good instance_variables to log? Should I log everything except Procs, etc? Opinions welcome.

**Comment by mperham** [comment]
Current plan: override `to_s` and `inspect` on `Sidekiq::Component`. That should get us sane output for a large amount of the internal Sidekiq state. I might need to do spot fixes here and there but that should help immensely.
